//
// Generated by dtk
// Translation Unit: JASBasicWaveBank.cpp
//

#include "JASBasicWaveBank.h"
#include "dolphin/types.h"

/* 80285968-802859C8       .text __ct__Q28JASystem14TBasicWaveBankFv */
JASystem::TBasicWaveBank::TBasicWaveBank() {
    /* Nonmatching */
}

/* 802859C8-80285A74       .text __dt__Q28JASystem14TBasicWaveBankFv */
JASystem::TBasicWaveBank::~TBasicWaveBank() {
    /* Nonmatching */
}

/* 80285A74-80285AFC       .text getWaveGroup__Q28JASystem14TBasicWaveBankFi */
void JASystem::TBasicWaveBank::getWaveGroup(int) {
    /* Nonmatching */
}

/* 80285AFC-80285C10       .text setGroupCount__Q28JASystem14TBasicWaveBankFUl */
void JASystem::TBasicWaveBank::setGroupCount(unsigned long) {
    /* Nonmatching */
}

/* 80285C10-80285CB0       .text setWaveTableSize__Q28JASystem14TBasicWaveBankFUl */
void JASystem::TBasicWaveBank::setWaveTableSize(unsigned long) {
    /* Nonmatching */
}

/* 80285CB0-80285D54       .text incWaveTable__Q28JASystem14TBasicWaveBankFPCQ38JASystem14TBasicWaveBank10TWaveGroup */
void JASystem::TBasicWaveBank::incWaveTable(const JASystem::TBasicWaveBank::TWaveGroup*) {
    /* Nonmatching */
}

/* 80285D54-80285E28       .text decWaveTable__Q28JASystem14TBasicWaveBankFPCQ38JASystem14TBasicWaveBank10TWaveGroup */
void JASystem::TBasicWaveBank::decWaveTable(const JASystem::TBasicWaveBank::TWaveGroup*) {
    /* Nonmatching */
}

/* 80285E28-80285E58       .text getWaveHandle__Q28JASystem14TBasicWaveBankCFUl */
void JASystem::TBasicWaveBank::getWaveHandle(unsigned long) const {
    /* Nonmatching */
}

/* 80285E58-80285EB0       .text __ct__Q38JASystem14TBasicWaveBank10TWaveGroupFPQ28JASystem14TBasicWaveBank */
JASystem::TBasicWaveBank::TWaveGroup::TWaveGroup(JASystem::TBasicWaveBank*) {
    /* Nonmatching */
}

/* 80285EB0-80285F64       .text __dt__Q38JASystem14TBasicWaveBank10TWaveGroupFv */
JASystem::TBasicWaveBank::TWaveGroup::~TWaveGroup() {
    /* Nonmatching */
}

/* 80285F64-80285FC4       .text __dt__Q38JASystem14TBasicWaveBank9TWaveInfoFv */
JASystem::TBasicWaveBank::TWaveInfo::~TWaveInfo() {
    /* Nonmatching */
}

/* 80285FC4-802860B8       .text setWaveCount__Q38JASystem14TBasicWaveBank10TWaveGroupFUl */
void JASystem::TBasicWaveBank::TWaveGroup::setWaveCount(unsigned long) {
    /* Nonmatching */
}

/* 802860B8-80286204       .text setWaveInfo__Q38JASystem14TBasicWaveBank10TWaveGroupFiUlRCQ28JASystem9TWaveInfo */
void JASystem::TBasicWaveBank::TWaveGroup::setWaveInfo(int, unsigned long, const JASystem::TWaveInfo&) {
    /* Nonmatching */
}

/* 80286204-80286274       .text onLoadDone__Q38JASystem14TBasicWaveBank10TWaveGroupFv */
void JASystem::TBasicWaveBank::TWaveGroup::onLoadDone() {
    /* Nonmatching */
}

/* 80286274-802862E4       .text onEraseDone__Q38JASystem14TBasicWaveBank10TWaveGroupFv */
void JASystem::TBasicWaveBank::TWaveGroup::onEraseDone() {
    /* Nonmatching */
}

/* 802862E4-802862F8       .text getWaveID__Q38JASystem14TBasicWaveBank10TWaveGroupCFi */
void JASystem::TBasicWaveBank::TWaveGroup::getWaveID(int) const {
    /* Nonmatching */
}

/* 802862F8-80286340       .text __dt__Q28JASystem9TWaveBankFv */
JASystem::TWaveBank::~TWaveBank() {
    /* Nonmatching */
}

/* 80286340-80286388       .text __dt__Q28JASystem11TWaveHandleFv */
JASystem::TWaveHandle::~TWaveHandle() {
    /* Nonmatching */
}

/* 80286388-802863B8       .text __ct__Q38JASystem14TBasicWaveBank9TWaveInfoFv */
JASystem::TBasicWaveBank::TWaveInfo::TWaveInfo() {
    /* Nonmatching */
}

/* 802863B8-80286414       .text __dt__Q38JASystem14TBasicWaveBank11TWaveHandleFv */
JASystem::TBasicWaveBank::TWaveHandle::~TWaveHandle() {
    /* Nonmatching */
}

/* 80286414-8028641C       .text getWaveInfo__Q38JASystem14TBasicWaveBank11TWaveHandleCFv */
void JASystem::TBasicWaveBank::TWaveHandle::getWaveInfo() const {
    /* Nonmatching */
}

/* 8028641C-802864A8       .text getWavePtr__Q38JASystem14TBasicWaveBank11TWaveHandleCFv */
void JASystem::TBasicWaveBank::TWaveHandle::getWavePtr() const {
    /* Nonmatching */
}

/* 802864A8-802864C8       .text getWaveArc__Q28JASystem14TBasicWaveBankFi */
void JASystem::TBasicWaveBank::getWaveArc(int) {
    /* Nonmatching */
}

