#ifndef RES_ADNNO_H
#define RES_ADNNO_H

enum dRes_INDEX_ADNNO {
    /* BDL  */
    dRes_INDEX_ADNNO_BDL_ADNNO_e=0x4,
    /* BMT  */
    dRes_INDEX_ADNNO_BMT_ADNNO_00_e=0x7,
    dRes_INDEX_ADNNO_BMT_ADNNO_01_e=0x8,
    dRes_INDEX_ADNNO_BMT_ADNNO_02_e=0x9,
    dRes_INDEX_ADNNO_BMT_ADNNO_03_e=0xA,
    dRes_INDEX_ADNNO_BMT_ADNNO_04_e=0xB,
    dRes_INDEX_ADNNO_BMT_ADNNO_05_e=0xC,
    dRes_INDEX_ADNNO_BMT_ADNNO_06_e=0xD,
    dRes_INDEX_ADNNO_BMT_ADNNO_07_e=0xE,
    dRes_INDEX_ADNNO_BMT_ADNNO_08_e=0xF,
    dRes_INDEX_ADNNO_BMT_ADNNO_09_e=0x10,
    dRes_INDEX_ADNNO_BMT_ADNNO_10_e=0x11,
    dRes_INDEX_ADNNO_BMT_ADNNO_11_e=0x12,
    dRes_INDEX_ADNNO_BMT_ADNNO_12_e=0x13,
    dRes_INDEX_ADNNO_BMT_ADNNO_13_e=0x14,
    dRes_INDEX_ADNNO_BMT_ADNNO_14_e=0x15,
    dRes_INDEX_ADNNO_BMT_ADNNO_15_e=0x16,
};

enum dRes_ID_ADNNO {
    /* BDL  */
    dRes_ID_ADNNO_BDL_ADNNO_e=0x4,
    /* BMT  */
    dRes_ID_ADNNO_BMT_ADNNO_00_e=0x7,
    dRes_ID_ADNNO_BMT_ADNNO_01_e=0x8,
    dRes_ID_ADNNO_BMT_ADNNO_02_e=0x9,
    dRes_ID_ADNNO_BMT_ADNNO_03_e=0xA,
    dRes_ID_ADNNO_BMT_ADNNO_04_e=0xB,
    dRes_ID_ADNNO_BMT_ADNNO_05_e=0xC,
    dRes_ID_ADNNO_BMT_ADNNO_06_e=0xD,
    dRes_ID_ADNNO_BMT_ADNNO_07_e=0xE,
    dRes_ID_ADNNO_BMT_ADNNO_08_e=0xF,
    dRes_ID_ADNNO_BMT_ADNNO_09_e=0x10,
    dRes_ID_ADNNO_BMT_ADNNO_10_e=0x11,
    dRes_ID_ADNNO_BMT_ADNNO_11_e=0x12,
    dRes_ID_ADNNO_BMT_ADNNO_12_e=0x13,
    dRes_ID_ADNNO_BMT_ADNNO_13_e=0x14,
    dRes_ID_ADNNO_BMT_ADNNO_14_e=0x15,
    dRes_ID_ADNNO_BMT_ADNNO_15_e=0x16,
};

enum ADNNO_JNT {
    ADNNO_JNT_ADNNO_e=0x0,
};

#endif /* !RES_ADNNO_H */