#ifndef RES_BDK_H
#define RES_BDK_H

enum dRes_INDEX_BDK {
    /* BAS  */
    dRes_INDEX_BDK_BAS_ATTACK1_e=0x7,
    dRes_INDEX_BDK_BAS_BACK1_e=0x8,
    dRes_INDEX_BDK_BAS_DAMAGE2_e=0x9,
    dRes_INDEX_BDK_BAS_DEATH1_e=0xA,
    dRes_INDEX_BDK_BAS_FLY1_e=0xB,
    dRes_INDEX_BDK_BAS_FLY2_e=0xC,
    dRes_INDEX_BDK_BAS_FLY3_e=0xD,
    dRes_INDEX_BDK_BAS_JIDANDA1_e=0xE,
    dRes_INDEX_BDK_BAS_JUMP1_e=0xF,
    dRes_INDEX_BDK_BAS_LAST_DAMAGE1_e=0x10,
    dRes_INDEX_BDK_BAS_LAST_DAMAGE2_e=0x11,
    dRes_INDEX_BDK_BAS_LAST_DAMAGE3_e=0x12,
    dRes_INDEX_BDK_BAS_SENKAI_L1_e=0x13,
    dRes_INDEX_BDK_BAS_SENKAI_R1_e=0x14,
    dRes_INDEX_BDK_BAS_S_DEMO2_e=0x15,
    dRes_INDEX_BDK_BAS_TOBITATU1_e=0x16,
    dRes_INDEX_BDK_BAS_TYAKUTI1_e=0x17,
    dRes_INDEX_BDK_BAS_TYAKUTI_T1_e=0x18,
    dRes_INDEX_BDK_BAS_WALK1_e=0x19,
    /* BCK  */
    dRes_INDEX_BDK_BCK_ATTACK1_e=0x1C,
    dRes_INDEX_BDK_BCK_ATTACK_T1_e=0x1D,
    dRes_INDEX_BDK_BCK_ATTACK_T2_e=0x1E,
    dRes_INDEX_BDK_BCK_ATTACK_T3_e=0x1F,
    dRes_INDEX_BDK_BCK_BACK1_e=0x20,
    dRes_INDEX_BDK_BCK_DAMAGE1_e=0x21,
    dRes_INDEX_BDK_BCK_DAMAGE2_e=0x22,
    dRes_INDEX_BDK_BCK_DAMAGE3_e=0x23,
    dRes_INDEX_BDK_BCK_DAMAGE4_e=0x24,
    dRes_INDEX_BDK_BCK_DAMAGE_T1_e=0x25,
    dRes_INDEX_BDK_BCK_DEATH1_e=0x26,
    dRes_INDEX_BDK_BCK_DEATH2_e=0x27,
    dRes_INDEX_BDK_BCK_DK_L_AKUBI1_e=0x28,
    dRes_INDEX_BDK_BCK_DK_L_WAIT1_e=0x29,
    dRes_INDEX_BDK_BCK_FLY1_e=0x2A,
    dRes_INDEX_BDK_BCK_FLY2_e=0x2B,
    dRes_INDEX_BDK_BCK_FLY3_e=0x2C,
    dRes_INDEX_BDK_BCK_JIDANDA1_e=0x2D,
    dRes_INDEX_BDK_BCK_JUMP1_e=0x2E,
    dRes_INDEX_BDK_BCK_KAKKU1_e=0x2F,
    dRes_INDEX_BDK_BCK_LAST_DAMAGE1_e=0x30,
    dRes_INDEX_BDK_BCK_LAST_DAMAGE2_e=0x31,
    dRes_INDEX_BDK_BCK_LAST_DAMAGE3_e=0x32,
    dRes_INDEX_BDK_BCK_NUKENAI1_e=0x33,
    dRes_INDEX_BDK_BCK_NUKU1_e=0x34,
    dRes_INDEX_BDK_BCK_PIKUPIKU1_e=0x35,
    dRes_INDEX_BDK_BCK_RAKKA_T1_e=0x36,
    dRes_INDEX_BDK_BCK_SENKAI_L1_e=0x37,
    dRes_INDEX_BDK_BCK_SENKAI_R1_e=0x38,
    dRes_INDEX_BDK_BCK_S_DEMO1_e=0x39,
    dRes_INDEX_BDK_BCK_S_DEMO2_e=0x3A,
    dRes_INDEX_BDK_BCK_TOBITATU1_e=0x3B,
    dRes_INDEX_BDK_BCK_TOBITATU_T1_e=0x3C,
    dRes_INDEX_BDK_BCK_TO_DAMAGE_T1_e=0x3D,
    dRes_INDEX_BDK_BCK_TYAKUTI1_e=0x3E,
    dRes_INDEX_BDK_BCK_TYAKUTI_T1_e=0x3F,
    dRes_INDEX_BDK_BCK_WAIT1_e=0x40,
    dRes_INDEX_BDK_BCK_WAIT_T1_e=0x41,
    dRes_INDEX_BDK_BCK_WALK1_e=0x42,
    /* BDL  */
    dRes_INDEX_BDK_BDL_BDK_HANE_e=0x45,
    dRes_INDEX_BDK_BDL_BUHINA_e=0x46,
    dRes_INDEX_BDK_BDL_BUHINB_e=0x47,
    dRes_INDEX_BDK_BDL_BUHINC_e=0x48,
    dRes_INDEX_BDK_BDL_BUHIND_e=0x49,
    dRes_INDEX_BDK_BDL_DK_e=0x4A,
    dRes_INDEX_BDK_BDL_DK_KAMEN4_e=0x4B,
    dRes_INDEX_BDK_BDL_DK_TAIL_e=0x4C,
    dRes_INDEX_BDK_BDL_GHANE00_e=0x4D,
    dRes_INDEX_BDK_BDL_GROCK00_e=0x4E,
    dRes_INDEX_BDK_BDL_SHAHENL_e=0x4F,
    dRes_INDEX_BDK_BDL_SHAHENS_e=0x50,
    dRes_INDEX_BDK_BDL_S_TSHUTTER_e=0x51,
    dRes_INDEX_BDK_BDL_S_TTOGE_e=0x52,
    /* BVA  */
    dRes_INDEX_BDK_BVA_HIBIWARE1_e=0x55,
    /* DZB  */
    dRes_INDEX_BDK_DZB_S_TSHUTTER_e=0x58,
    dRes_INDEX_BDK_DZB_S_TTOGE_e=0x59,
};

enum dRes_ID_BDK {
    /* BAS  */
    dRes_ID_BDK_BAS_ATTACK1_e=0x7,
    dRes_ID_BDK_BAS_BACK1_e=0x8,
    dRes_ID_BDK_BAS_DAMAGE2_e=0x9,
    dRes_ID_BDK_BAS_DEATH1_e=0xA,
    dRes_ID_BDK_BAS_FLY1_e=0xB,
    dRes_ID_BDK_BAS_FLY2_e=0xC,
    dRes_ID_BDK_BAS_FLY3_e=0xD,
    dRes_ID_BDK_BAS_JIDANDA1_e=0xE,
    dRes_ID_BDK_BAS_JUMP1_e=0xF,
    dRes_ID_BDK_BAS_LAST_DAMAGE1_e=0x10,
    dRes_ID_BDK_BAS_LAST_DAMAGE2_e=0x11,
    dRes_ID_BDK_BAS_LAST_DAMAGE3_e=0x12,
    dRes_ID_BDK_BAS_SENKAI_L1_e=0x13,
    dRes_ID_BDK_BAS_SENKAI_R1_e=0x14,
    dRes_ID_BDK_BAS_S_DEMO2_e=0x15,
    dRes_ID_BDK_BAS_TOBITATU1_e=0x16,
    dRes_ID_BDK_BAS_TYAKUTI1_e=0x17,
    dRes_ID_BDK_BAS_TYAKUTI_T1_e=0x18,
    dRes_ID_BDK_BAS_WALK1_e=0x19,
    /* BCK  */
    dRes_ID_BDK_BCK_ATTACK1_e=0x1C,
    dRes_ID_BDK_BCK_ATTACK_T1_e=0x1D,
    dRes_ID_BDK_BCK_ATTACK_T2_e=0x1E,
    dRes_ID_BDK_BCK_ATTACK_T3_e=0x1F,
    dRes_ID_BDK_BCK_BACK1_e=0x20,
    dRes_ID_BDK_BCK_DAMAGE1_e=0x21,
    dRes_ID_BDK_BCK_DAMAGE2_e=0x22,
    dRes_ID_BDK_BCK_DAMAGE3_e=0x23,
    dRes_ID_BDK_BCK_DAMAGE4_e=0x24,
    dRes_ID_BDK_BCK_DAMAGE_T1_e=0x25,
    dRes_ID_BDK_BCK_DEATH1_e=0x26,
    dRes_ID_BDK_BCK_DEATH2_e=0x27,
    dRes_ID_BDK_BCK_DK_L_AKUBI1_e=0x28,
    dRes_ID_BDK_BCK_DK_L_WAIT1_e=0x29,
    dRes_ID_BDK_BCK_FLY1_e=0x2A,
    dRes_ID_BDK_BCK_FLY2_e=0x2B,
    dRes_ID_BDK_BCK_FLY3_e=0x2C,
    dRes_ID_BDK_BCK_JIDANDA1_e=0x2D,
    dRes_ID_BDK_BCK_JUMP1_e=0x2E,
    dRes_ID_BDK_BCK_KAKKU1_e=0x2F,
    dRes_ID_BDK_BCK_LAST_DAMAGE1_e=0x30,
    dRes_ID_BDK_BCK_LAST_DAMAGE2_e=0x31,
    dRes_ID_BDK_BCK_LAST_DAMAGE3_e=0x32,
    dRes_ID_BDK_BCK_NUKENAI1_e=0x33,
    dRes_ID_BDK_BCK_NUKU1_e=0x34,
    dRes_ID_BDK_BCK_PIKUPIKU1_e=0x35,
    dRes_ID_BDK_BCK_RAKKA_T1_e=0x36,
    dRes_ID_BDK_BCK_SENKAI_L1_e=0x37,
    dRes_ID_BDK_BCK_SENKAI_R1_e=0x38,
    dRes_ID_BDK_BCK_S_DEMO1_e=0x39,
    dRes_ID_BDK_BCK_S_DEMO2_e=0x3A,
    dRes_ID_BDK_BCK_TOBITATU1_e=0x3B,
    dRes_ID_BDK_BCK_TOBITATU_T1_e=0x3C,
    dRes_ID_BDK_BCK_TO_DAMAGE_T1_e=0x3D,
    dRes_ID_BDK_BCK_TYAKUTI1_e=0x3E,
    dRes_ID_BDK_BCK_TYAKUTI_T1_e=0x3F,
    dRes_ID_BDK_BCK_WAIT1_e=0x40,
    dRes_ID_BDK_BCK_WAIT_T1_e=0x41,
    dRes_ID_BDK_BCK_WALK1_e=0x42,
    /* BDL  */
    dRes_ID_BDK_BDL_BDK_HANE_e=0x45,
    dRes_ID_BDK_BDL_BUHINA_e=0x46,
    dRes_ID_BDK_BDL_BUHINB_e=0x47,
    dRes_ID_BDK_BDL_BUHINC_e=0x48,
    dRes_ID_BDK_BDL_BUHIND_e=0x49,
    dRes_ID_BDK_BDL_DK_e=0x4A,
    dRes_ID_BDK_BDL_DK_KAMEN4_e=0x4B,
    dRes_ID_BDK_BDL_DK_TAIL_e=0x4C,
    dRes_ID_BDK_BDL_GHANE00_e=0x4D,
    dRes_ID_BDK_BDL_GROCK00_e=0x4E,
    dRes_ID_BDK_BDL_SHAHENL_e=0x4F,
    dRes_ID_BDK_BDL_SHAHENS_e=0x50,
    dRes_ID_BDK_BDL_S_TSHUTTER_e=0x51,
    dRes_ID_BDK_BDL_S_TTOGE_e=0x52,
    /* BVA  */
    dRes_ID_BDK_BVA_HIBIWARE1_e=0x55,
    /* DZB  */
    dRes_ID_BDK_DZB_S_TSHUTTER_e=0x58,
    dRes_ID_BDK_DZB_S_TTOGE_e=0x59,
};

enum BDK_HANE_JNT {
    BDK_HANE_JNT_BODY_e=0x0,
};

enum BUHINA_JNT {
    BUHINA_JNT_BUHINA_e=0x0,
};

enum BUHINB_JNT {
    BUHINB_JNT_BUHINB_e=0x0,
};

enum BUHINC_JNT {
    BUHINC_JNT_BUHINC_e=0x0,
};

enum BUHIND_JNT {
    BUHIND_JNT_BUHIND_e=0x0,
};

enum DK_JNT {
    DK_JNT_DK_ALLROOT_e=0x0,
    DK_JNT_DK_SKLROOT_e=0x1,
    DK_JNT_J_DK_KOSI_e=0x2,
    DK_JNT_J_DK_ASHI_L1_e=0x3,
    DK_JNT_J_DK_ASHI_L2_e=0x4,
    DK_JNT_J_DK_ASHI_L3_e=0x5,
    DK_JNT_J_DK_YUBI_LA1_e=0x6,
    DK_JNT_J_DK_YUBI_LA2_e=0x7,
    DK_JNT_J_DK_YUBI_LB1_e=0x8,
    DK_JNT_J_DK_YUBI_LB2_e=0x9,
    DK_JNT_J_DK_YUBI_LC1_e=0xA,
    DK_JNT_J_DK_YUBI_LC2_e=0xB,
    DK_JNT_J_DK_ASHI_R1_e=0xC,
    DK_JNT_J_DK_ASHI_R2_e=0xD,
    DK_JNT_J_DK_ASHI_R3_e=0xE,
    DK_JNT_J_DK_YUBI_RA1_e=0xF,
    DK_JNT_J_DK_YUBI_RA2_e=0x10,
    DK_JNT_J_DK_YUBI_RB1_e=0x11,
    DK_JNT_J_DK_YUBI_RB2_e=0x12,
    DK_JNT_J_DK_YUBI_RC1_e=0x13,
    DK_JNT_J_DK_YUBI_RC2_e=0x14,
    DK_JNT_J_DK_MUNE1_e=0x15,
    DK_JNT_J_DK_MUNE2_e=0x16,
    DK_JNT_J_DK_KUBI1_e=0x17,
    DK_JNT_J_DK_ATAMA1_e=0x18,
    DK_JNT_J_DK_AGO_e=0x19,
    DK_JNT_J_DK_KAMINOKE_e=0x1A,
    DK_JNT_J_DK_KUTIBASI_e=0x1B,
    DK_JNT_J_DK_MABUTA_e=0x1C,
    DK_JNT_J_DK_ODEKO_e=0x1D,
    DK_JNT_J_DK_SITA_e=0x1E,
    DK_JNT_J_DK_TOSAKA_A1_e=0x1F,
    DK_JNT_J_DK_TOSAKA_A2_e=0x20,
    DK_JNT_J_DK_TOSAKA_A3_e=0x21,
    DK_JNT_J_DK_TOSAKA_A4_e=0x22,
    DK_JNT_J_DK_TOSAKA_B1_e=0x23,
    DK_JNT_J_DK_TOSAKA_B2_e=0x24,
    DK_JNT_J_DK_TUBASA_L1_e=0x25,
    DK_JNT_J_DK_TUBASA_L2_e=0x26,
    DK_JNT_J_DK_HANE_L1_e=0x27,
    DK_JNT_J_DK_HANE_L2_e=0x28,
    DK_JNT_J_DK_HANE_L3_e=0x29,
    DK_JNT_J_DK_HANE_L4_e=0x2A,
    DK_JNT_J_DK_HANE_L5_e=0x2B,
    DK_JNT_J_DK_HANE_L6_e=0x2C,
    DK_JNT_J_DK_PIKO_LA_e=0x2D,
    DK_JNT_J_DK_PIKO_LB_e=0x2E,
    DK_JNT_J_DK_TUBASA_R1_e=0x2F,
    DK_JNT_J_DK_TUBASA_R2_e=0x30,
    DK_JNT_J_DK_HANE_R1_e=0x31,
    DK_JNT_J_DK_HANE_R2_e=0x32,
    DK_JNT_J_DK_HANE_R3_e=0x33,
    DK_JNT_J_DK_HANE_R4_e=0x34,
    DK_JNT_J_DK_HANE_R5_e=0x35,
    DK_JNT_J_DK_HANE_R6_e=0x36,
    DK_JNT_J_DK_PIKO_RA_e=0x37,
    DK_JNT_J_DK_PIKO_RB_e=0x38,
    DK_JNT_J_DK_O_LA1_e=0x39,
    DK_JNT_J_DK_O_LA2_e=0x3A,
    DK_JNT_J_DK_O_LB1_e=0x3B,
    DK_JNT_J_DK_O_LB2_e=0x3C,
    DK_JNT_J_DK_O_RA1_e=0x3D,
    DK_JNT_J_DK_O_RA2_e=0x3E,
    DK_JNT_J_DK_O_RB1_e=0x3F,
    DK_JNT_J_DK_O_RB2_e=0x40,
};

enum DK_KAMEN4_JNT {
    DK_KAMEN4_JNT_WORLD_ROOT_e=0x0,
    DK_KAMEN4_JNT_TEKKAMENA_e=0x1,
    DK_KAMEN4_JNT_TEKKAMENB_e=0x2,
    DK_KAMEN4_JNT_TEKKAMENC_e=0x3,
    DK_KAMEN4_JNT_TEKKAMEND_e=0x4,
};

enum DK_TAIL_JNT {
    DK_TAIL_JNT_DK_TAIL_e=0x0,
};

enum GHANE00_JNT {
    GHANE00_JNT_GHANE00_e=0x0,
};

enum GROCK00_JNT {
    GROCK00_JNT_GROCK00_e=0x0,
};

enum SHAHENL_JNT {
    SHAHENL_JNT_KAKERA_L_e=0x0,
    SHAHENL_JNT_LOCATOR3_e=0x1,
    SHAHENL_JNT_POLYSURFACE810_e=0x2,
};

enum SHAHENS_JNT {
    SHAHENS_JNT_KAKERA_S_e=0x0,
    SHAHENS_JNT_LOCATOR5_e=0x1,
    SHAHENS_JNT_POLYSURFACE811_e=0x2,
};

enum S_TSHUTTER_JNT {
    S_TSHUTTER_JNT_S_TSHUTTER_e=0x0,
    S_TSHUTTER_JNT_S_SHUTTER_e=0x1,
    S_TSHUTTER_JNT_POLYSURFACE808_e=0x2,
};

enum S_TTOGE_JNT {
    S_TTOGE_JNT_S_TTOGE_e=0x0,
    S_TTOGE_JNT_S_TOGE_e=0x1,
    S_TTOGE_JNT_TOGE_02_e=0x2,
};

#endif /* !RES_BDK_H */