#ifndef RES_BMDHAND_H
#define RES_BMDHAND_H

enum dRes_INDEX_BMDHAND {
    /* BCK  */
    dRes_INDEX_BMDHAND_BCK_FOOK_HIRAKU_e=0x5,
    dRes_INDEX_BMDHAND_BCK_FOOK_TOJIRU_e=0x6,
    /* BMD  */
    dRes_INDEX_BMDHAND_BMD_BKM_FOOK_e=0x9,
    /* TEX  */
    dRes_INDEX_BMDHAND_BTI_SYOKUSYU_UE_e=0xC,
};

enum dRes_ID_BMDHAND {
    /* BCK  */
    dRes_ID_BMDHAND_BCK_FOOK_HIRAKU_e=0x5,
    dRes_ID_BMDHAND_BCK_FOOK_TOJIRU_e=0x6,
    /* BMD  */
    dRes_ID_BMDHAND_BMD_BKM_FOOK_e=0x9,
    /* TEX  */
    dRes_ID_BMDHAND_BTI_SYOKUSYU_UE_e=0xC,
};

enum BKM_FOOK_JNT {
    BKM_FOOK_JNT_UDE_e=0x0,
    BKM_FOOK_JNT_NAKAYUBI_e=0x1,
    BKM_FOOK_JNT_YUBI1_e=0x2,
    BKM_FOOK_JNT_YUBI2_e=0x3,
};

#endif /* !RES_BMDHAND_H */