#ifndef RES_BOMBER_H
#define RES_BOMBER_H

enum dRes_INDEX_BOMBER {
    /* BMDC */
    dRes_INDEX_BOMBER_BMD_AISI_e=0x5,
    /* BDL  */
    dRes_INDEX_BOMBER_BDL_VCANK_e=0x8,
    /* TEX  */
    dRes_INDEX_BOMBER_BTI_GAME_BATTERY_e=0xB,
    dRes_INDEX_BOMBER_BTI_GAME_BATTERY_BASE_e=0xC,
    dRes_INDEX_BOMBER_BTI_GAME_BOMB_01_e=0xD,
    dRes_INDEX_BOMBER_BTI_GAME_BOMB_02_e=0xE,
    dRes_INDEX_BOMBER_BTI_GAME_HUNE_DAMAGE_e=0xF,
    dRes_INDEX_BOMBER_BTI_GAME_RULE_e=0x10,
    dRes_INDEX_BOMBER_BTI_GAME_SHIP_NODAMAGE_e=0x11,
    dRes_INDEX_BOMBER_BTI_RUPY_NUM_DEGREE_e=0x12,
};

enum dRes_ID_BOMBER {
    /* BMDC */
    dRes_ID_BOMBER_BMD_AISI_e=0x1,
    /* BDL  */
    dRes_ID_BOMBER_BDL_VCANK_e=0x6,
    /* TEX  */
    dRes_ID_BOMBER_BTI_GAME_BATTERY_e=0x7,
    dRes_ID_BOMBER_BTI_GAME_BATTERY_BASE_e=0x8,
    dRes_ID_BOMBER_BTI_GAME_BOMB_01_e=0x9,
    dRes_ID_BOMBER_BTI_GAME_BOMB_02_e=0xA,
    dRes_ID_BOMBER_BTI_GAME_HUNE_DAMAGE_e=0xB,
    dRes_ID_BOMBER_BTI_GAME_RULE_e=0xC,
    dRes_ID_BOMBER_BTI_GAME_SHIP_NODAMAGE_e=0xD,
    dRes_ID_BOMBER_BTI_RUPY_NUM_DEGREE_e=0xE,
};

enum AISI_JNT {
    AISI_JNT_POLYSURFACE3967_e=0x0,
};

enum VCANK_JNT {
    VCANK_JNT_CANON_ROOT_e=0x0,
    VCANK_JNT_CANON_e=0x1,
};

#endif /* !RES_BOMBER_H */