#ifndef RES_IKARI_H
#define RES_IKARI_H

enum dRes_INDEX_IKARI {
    /* BMD  */
    dRes_INDEX_IKARI_BMD_S_IKARI2_e=0x3,
    dRes_INDEX_IKARI_BMD_S_IKARI3_e=0x4,
    dRes_INDEX_IKARI_BMD_S_IKARI4_e=0x5,
};

enum dRes_ID_IKARI {
    /* BMD  */
    dRes_ID_IKARI_BMD_S_IKARI2_e=0x3,
    dRes_ID_IKARI_BMD_S_IKARI3_e=0x4,
    dRes_ID_IKARI_BMD_S_IKARI4_e=0x5,
};

enum S_IKARI2_JNT {
    S_IKARI2_JNT_S_IKARI2_e=0x0,
    S_IKARI2_JNT_IKARI2_OBJ_e=0x1,
    S_IKARI2_JNT_IKARI2_e=0x2,
    S_IKARI2_JNT_KUI2_e=0x3,
};

enum S_IKARI3_JNT {
    S_IKARI3_JNT_S_IKARI3_e=0x0,
    S_IKARI3_JNT_IKARI3_OBJ_e=0x1,
    S_IKARI3_JNT_IKARI3_e=0x2,
    S_IKARI3_JNT_KUI3_e=0x3,
};

enum S_IKARI4_JNT {
    S_IKARI4_JNT_S_IKARI4_e=0x0,
    S_IKARI4_JNT_IKARI4_OBJ_e=0x1,
    S_IKARI4_JNT_IKARI4_e=0x2,
    S_IKARI4_JNT_KUI4_e=0x3,
};

#endif /* !RES_IKARI_H */