#ifndef RES_KAISEN_H
#define RES_KAISEN_H

enum dRes_INDEX_KAISEN {
    /* BDL  */
    dRes_INDEX_KAISEN_BDL_AK2SH_e=0x4,
    dRes_INDEX_KAISEN_BDL_AK3SH_e=0x5,
    dRes_INDEX_KAISEN_BDL_AK4SH_e=0x6,
    dRes_INDEX_KAISEN_BDL_AKATR_e=0x7,
    dRes_INDEX_KAISEN_BDL_AKBOD_e=0x8,
    dRes_INDEX_KAISEN_BDL_AKCSR_e=0x9,
    dRes_INDEX_KAISEN_BDL_AKHZR_e=0xA,
    dRes_INDEX_KAISEN_BDL_AKKSL_e=0xB,
    /* TEX  */
    dRes_INDEX_KAISEN_BTI_GAME_BEST_RECORD_e=0xE,
    dRes_INDEX_KAISEN_BTI_GAME_BOMB_01_e=0xF,
    dRes_INDEX_KAISEN_BTI_GAME_BOMB_02_e=0x10,
    dRes_INDEX_KAISEN_BTI_GAME_HUNE_DAMAGE_e=0x11,
    dRes_INDEX_KAISEN_BTI_GAME_PAPER_e=0x12,
    dRes_INDEX_KAISEN_BTI_GAME_SHIP_NODAMAGE_e=0x13,
};

enum dRes_ID_KAISEN {
    /* BDL  */
    dRes_ID_KAISEN_BDL_AK2SH_e=0x4,
    dRes_ID_KAISEN_BDL_AK3SH_e=0x5,
    dRes_ID_KAISEN_BDL_AK4SH_e=0x6,
    dRes_ID_KAISEN_BDL_AKATR_e=0x7,
    dRes_ID_KAISEN_BDL_AKBOD_e=0x8,
    dRes_ID_KAISEN_BDL_AKCSR_e=0x9,
    dRes_ID_KAISEN_BDL_AKHZR_e=0xA,
    dRes_ID_KAISEN_BDL_AKKSL_e=0xB,
    /* TEX  */
    dRes_ID_KAISEN_BTI_GAME_BEST_RECORD_e=0xE,
    dRes_ID_KAISEN_BTI_GAME_BOMB_01_e=0xF,
    dRes_ID_KAISEN_BTI_GAME_BOMB_02_e=0x10,
    dRes_ID_KAISEN_BTI_GAME_HUNE_DAMAGE_e=0x11,
    dRes_ID_KAISEN_BTI_GAME_PAPER_e=0x12,
    dRes_ID_KAISEN_BTI_GAME_SHIP_NODAMAGE_e=0x13,
};

enum AK2SH_JNT {
    AK2SH_JNT_AK2SH_e=0x0,
};

enum AK3SH_JNT {
    AK3SH_JNT_AK3SH_e=0x0,
};

enum AK4SH_JNT {
    AK4SH_JNT_AK4SH_e=0x0,
};

enum AKATR_JNT {
    AKATR_JNT_AKATR_e=0x0,
};

enum AKBOD_JNT {
    AKBOD_JNT_AKBOD_e=0x0,
};

enum AKCSR_JNT {
    AKCSR_JNT_AKCSR_e=0x0,
};

enum AKHZR_JNT {
    AKHZR_JNT_AKHZR_e=0x0,
};

enum AKKSL_JNT {
    AKKSL_JNT_AKCSR_e=0x0,
};

#endif /* !RES_KAISEN_H */