#ifndef RES_MGTEM_H
#define RES_MGTEM_H

enum dRes_INDEX_MGTEM {
    /* ROOT */
    dRes_INDEX_MGTEM_ARC_MGTEM_e=0x0,
    /* SCRN */
    dRes_INDEX_MGTEM_BLO_SHIP_RACE2_e=0x5,
    /* TIMG */
    dRes_INDEX_MGTEM_BTI_SHIPFONT_A_e=0x8,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_C_BIG_e=0x9,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_D_e=0xA,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_E_e=0xB,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_EX_e=0xC,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_E_BIG_e=0xD,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_F_BIG_e=0xE,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_G_e=0xF,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_G_BIG_e=0x10,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_I_e=0x11,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_L_e=0x12,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_M_e=0x13,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_N_e=0x14,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_O_e=0x15,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_P_BIG_e=0x16,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_R_BIG_e=0x17,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_T_e=0x18,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_T_BIG_e=0x19,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_U_e=0x1A,
    dRes_INDEX_MGTEM_BTI_SHIPFONT_Y_BIG_e=0x1B,
};

enum dRes_ID_MGTEM {
    /* ROOT */
    dRes_ID_MGTEM_ARC_MGTEM_e=0x0,
    /* SCRN */
    dRes_ID_MGTEM_BLO_SHIP_RACE2_e=0x5,
    /* TIMG */
    dRes_ID_MGTEM_BTI_SHIPFONT_A_e=0x8,
    dRes_ID_MGTEM_BTI_SHIPFONT_C_BIG_e=0x9,
    dRes_ID_MGTEM_BTI_SHIPFONT_D_e=0xA,
    dRes_ID_MGTEM_BTI_SHIPFONT_E_e=0xB,
    dRes_ID_MGTEM_BTI_SHIPFONT_EX_e=0xC,
    dRes_ID_MGTEM_BTI_SHIPFONT_E_BIG_e=0xD,
    dRes_ID_MGTEM_BTI_SHIPFONT_F_BIG_e=0xE,
    dRes_ID_MGTEM_BTI_SHIPFONT_G_e=0xF,
    dRes_ID_MGTEM_BTI_SHIPFONT_G_BIG_e=0x10,
    dRes_ID_MGTEM_BTI_SHIPFONT_I_e=0x11,
    dRes_ID_MGTEM_BTI_SHIPFONT_L_e=0x12,
    dRes_ID_MGTEM_BTI_SHIPFONT_M_e=0x13,
    dRes_ID_MGTEM_BTI_SHIPFONT_N_e=0x14,
    dRes_ID_MGTEM_BTI_SHIPFONT_O_e=0x15,
    dRes_ID_MGTEM_BTI_SHIPFONT_P_BIG_e=0x16,
    dRes_ID_MGTEM_BTI_SHIPFONT_R_BIG_e=0x17,
    dRes_ID_MGTEM_BTI_SHIPFONT_T_e=0x18,
    dRes_ID_MGTEM_BTI_SHIPFONT_T_BIG_e=0x19,
    dRes_ID_MGTEM_BTI_SHIPFONT_U_e=0x1A,
    dRes_ID_MGTEM_BTI_SHIPFONT_Y_BIG_e=0x1B,
};

#endif /* !RES_MGTEM_H */