#ifndef RES_MTORISU_H
#define RES_MTORISU_H

//
// Generated by res_arc.py from archive: MtoriSU.arc
// Do not manually modify this file or your changes will be overwritten.
//

enum dRes_INDEX_MTORISU {
    /* BDL  */
    dRes_INDEX_MTORISU_BDL_MTORISU_e=0x4,
    /* DZB  */
    dRes_INDEX_MTORISU_DZB_MTORISU_e=0x7,
};

enum dRes_ID_MTORISU {
    /* BDL  */
    dRes_ID_MTORISU_BDL_MTORISU_e=0x4,
    /* DZB  */
    dRes_ID_MTORISU_DZB_MTORISU_e=0x7,
};

enum MTORISU_JNT {
    MTORISU_JNT_MTORISU_e=0x0,
};

#endif /* RES_MTORISU_H */
