#ifndef RES_PH_H
#define RES_PH_H

enum dRes_INDEX_PH {
    /* BAS  */
    dRes_INDEX_PH_BAS_BCHAKUCHI_e=0x5,
    dRes_INDEX_PH_BAS_BDAMAGE_e=0x6,
    dRes_INDEX_PH_BAS_BFLY_e=0x7,
    dRes_INDEX_PH_BAS_BHUKKI_e=0x8,
    dRes_INDEX_PH_BAS_BJUMP_e=0x9,
    dRes_INDEX_PH_BAS_BUCHIWA_e=0xA,
    dRes_INDEX_PH_BAS_BUCHI_CHAKU_e=0xB,
    dRes_INDEX_PH_BAS_PAWAY_e=0xC,
    dRes_INDEX_PH_BAS_PFLY_e=0xD,
    dRes_INDEX_PH_BAS_PHUKKI_e=0xE,
    dRes_INDEX_PH_BAS_PUCHIWA_e=0xF,
    dRes_INDEX_PH_BAS_PUCHI_CHAKU_e=0x10,
    /* BCK  */
    dRes_INDEX_PH_BCK_BCHAKUCHI_e=0x13,
    dRes_INDEX_PH_BCK_BDAMAGE_e=0x14,
    dRes_INDEX_PH_BCK_BFLY_e=0x15,
    dRes_INDEX_PH_BCK_BHUKKI_e=0x16,
    dRes_INDEX_PH_BCK_BJAWS_e=0x17,
    dRes_INDEX_PH_BCK_BJUMP_e=0x18,
    dRes_INDEX_PH_BCK_BUCHIWA_e=0x19,
    dRes_INDEX_PH_BCK_BUCHI_CHAKU_e=0x1A,
    dRes_INDEX_PH_BCK_PAWAY_e=0x1B,
    dRes_INDEX_PH_BCK_PFLY_e=0x1C,
    dRes_INDEX_PH_BCK_PHUKKI_e=0x1D,
    dRes_INDEX_PH_BCK_PUCHIWA_e=0x1E,
    dRes_INDEX_PH_BCK_PUCHI_CHAKU_e=0x1F,
    /* BDLM */
    dRes_INDEX_PH_BDL_PHB_e=0x22,
    dRes_INDEX_PH_BDL_PHP_e=0x23,
};

enum dRes_ID_PH {
    /* BAS  */
    dRes_ID_PH_BAS_BCHAKUCHI_e=0x5,
    dRes_ID_PH_BAS_BDAMAGE_e=0x6,
    dRes_ID_PH_BAS_BFLY_e=0x7,
    dRes_ID_PH_BAS_BHUKKI_e=0x8,
    dRes_ID_PH_BAS_BJUMP_e=0x9,
    dRes_ID_PH_BAS_BUCHIWA_e=0xA,
    dRes_ID_PH_BAS_BUCHI_CHAKU_e=0xB,
    dRes_ID_PH_BAS_PAWAY_e=0xC,
    dRes_ID_PH_BAS_PFLY_e=0xD,
    dRes_ID_PH_BAS_PHUKKI_e=0xE,
    dRes_ID_PH_BAS_PUCHIWA_e=0xF,
    dRes_ID_PH_BAS_PUCHI_CHAKU_e=0x10,
    /* BCK  */
    dRes_ID_PH_BCK_BCHAKUCHI_e=0x13,
    dRes_ID_PH_BCK_BDAMAGE_e=0x14,
    dRes_ID_PH_BCK_BFLY_e=0x15,
    dRes_ID_PH_BCK_BHUKKI_e=0x16,
    dRes_ID_PH_BCK_BJAWS_e=0x17,
    dRes_ID_PH_BCK_BJUMP_e=0x18,
    dRes_ID_PH_BCK_BUCHIWA_e=0x19,
    dRes_ID_PH_BCK_BUCHI_CHAKU_e=0x1A,
    dRes_ID_PH_BCK_PAWAY_e=0x1B,
    dRes_ID_PH_BCK_PFLY_e=0x1C,
    dRes_ID_PH_BCK_PHUKKI_e=0x1D,
    dRes_ID_PH_BCK_PUCHIWA_e=0x1E,
    dRes_ID_PH_BCK_PUCHI_CHAKU_e=0x1F,
    /* BDLM */
    dRes_ID_PH_BDL_PHB_e=0x22,
    dRes_ID_PH_BDL_PHP_e=0x23,
};

enum PHB_JNT {
    PHB_JNT_HARA_e=0x0,
    PHB_JNT_CONNECTA_e=0x1,
    PHB_JNT_HIGEA_e=0x2,
    PHB_JNT_HIGEB_e=0x3,
};

enum PHP_JNT {
    PHP_JNT_HANE_CENT_e=0x0,
    PHP_JNT_HANEA01_e=0x1,
    PHP_JNT_HANEA02_e=0x2,
    PHP_JNT_HANEA03_e=0x3,
    PHP_JNT_HANEA04_e=0x4,
    PHP_JNT_HANEB01_e=0x5,
    PHP_JNT_HANEB02_e=0x6,
    PHP_JNT_HANEB03_e=0x7,
    PHP_JNT_HANEB04_e=0x8,
    PHP_JNT_HANEC01_e=0x9,
    PHP_JNT_HANEC02_e=0xA,
    PHP_JNT_HANEC03_e=0xB,
    PHP_JNT_HANEC04_e=0xC,
};

#endif /* !RES_PH_H */