#ifndef RES_RSH_H
#define RES_RSH_H

enum dRes_INDEX_RSH {
    /* BAS  */
    dRes_INDEX_RSH_BAS_RS_WAIT01_e=0x8,
    dRes_INDEX_RSH_BAS_RS_WAIT02_e=0x9,
    dRes_INDEX_RSH_BAS_RS_PUSH_e=0xA,
    dRes_INDEX_RSH_BAS_RS_TALK01_e=0xB,
    dRes_INDEX_RSH_BAS_RS_TALK02_e=0xC,
    dRes_INDEX_RSH_BAS_RS_WALK_e=0xD,
    dRes_INDEX_RSH_BAS_RS_JAMP_e=0xE,
    dRes_INDEX_RSH_BAS_RS_SWING_e=0xF,
    dRes_INDEX_RSH_BAS_RS_TALK03_e=0x10,
    dRes_INDEX_RSH_BAS_RS_TAME_e=0x11,
    /* BCK  */
    dRes_INDEX_RSH_BCK_RS_WAIT01_e=0x14,
    dRes_INDEX_RSH_BCK_RS_WAIT02_e=0x15,
    dRes_INDEX_RSH_BCK_RS_PUSH_e=0x16,
    dRes_INDEX_RSH_BCK_RS_TALK01_e=0x17,
    dRes_INDEX_RSH_BCK_RS_TALK02_e=0x18,
    dRes_INDEX_RSH_BCK_RS_WALK_e=0x19,
    dRes_INDEX_RSH_BCK_RS_JAMP_e=0x1A,
    dRes_INDEX_RSH_BCK_RS_SWING_e=0x1B,
    dRes_INDEX_RSH_BCK_RS_TALK03_e=0x1C,
    dRes_INDEX_RSH_BCK_RS_TAME_e=0x1D,
    /* BMDM */
    dRes_INDEX_RSH_BMD_SHOP_CURSOR01_e=0x20,
    /* BRK  */
    dRes_INDEX_RSH_BRK_SHOP_CURSOR01_e=0x23,
    /* BTP  */
    dRes_INDEX_RSH_BTP_RS_MABA01_e=0x26,
    /* BDLM */
    dRes_INDEX_RSH_BDL_RS_e=0x29,
};

enum dRes_ID_RSH {
    /* BAS  */
    dRes_ID_RSH_BAS_RS_WAIT01_e=0xD,
    dRes_ID_RSH_BAS_RS_WAIT02_e=0xE,
    dRes_ID_RSH_BAS_RS_PUSH_e=0x13,
    dRes_ID_RSH_BAS_RS_TALK01_e=0x14,
    dRes_ID_RSH_BAS_RS_TALK02_e=0x15,
    dRes_ID_RSH_BAS_RS_WALK_e=0x16,
    dRes_ID_RSH_BAS_RS_JAMP_e=0x1B,
    dRes_ID_RSH_BAS_RS_SWING_e=0x1C,
    dRes_ID_RSH_BAS_RS_TALK03_e=0x1D,
    dRes_ID_RSH_BAS_RS_TAME_e=0x1E,
    /* BCK  */
    dRes_ID_RSH_BCK_RS_WAIT01_e=0xF,
    dRes_ID_RSH_BCK_RS_WAIT02_e=0x10,
    dRes_ID_RSH_BCK_RS_PUSH_e=0x17,
    dRes_ID_RSH_BCK_RS_TALK01_e=0x18,
    dRes_ID_RSH_BCK_RS_TALK02_e=0x19,
    dRes_ID_RSH_BCK_RS_WALK_e=0x1A,
    dRes_ID_RSH_BCK_RS_JAMP_e=0x1F,
    dRes_ID_RSH_BCK_RS_SWING_e=0x20,
    dRes_ID_RSH_BCK_RS_TALK03_e=0x21,
    dRes_ID_RSH_BCK_RS_TAME_e=0x22,
    /* BMDM */
    dRes_ID_RSH_BMD_SHOP_CURSOR01_e=0x4,
    /* BRK  */
    dRes_ID_RSH_BRK_SHOP_CURSOR01_e=0x5,
    /* BTP  */
    dRes_ID_RSH_BTP_RS_MABA01_e=0x11,
    /* BDLM */
    dRes_ID_RSH_BDL_RS_e=0x12,
};

enum SHOP_CURSOR01_JNT {
    SHOP_CURSOR01_JNT_CURSOR01_e=0x0,
};

enum RS_JNT {
    RS_JNT_WORLD_ROOT_e=0x0,
    RS_JNT_BACKBONE_e=0x1,
    RS_JNT_HEAD_e=0x2,
    RS_JNT_RIDDON_e=0x3,
    RS_JNT_HOOD1_e=0x4,
    RS_JNT_HOOD2_e=0x5,
    RS_JNT_SHOULDERL_e=0x6,
    RS_JNT_ARML1_e=0x7,
    RS_JNT_ARML2_e=0x8,
    RS_JNT_ARML3_e=0x9,
    RS_JNT_HANDL_e=0xA,
    RS_JNT_SHOULDERR_e=0xB,
    RS_JNT_ARMR1_e=0xC,
    RS_JNT_ARMR2_e=0xD,
    RS_JNT_ARMR3_e=0xE,
    RS_JNT_HANDR_e=0xF,
    RS_JNT_WAIST_e=0x10,
    RS_JNT_LEGL1_e=0x11,
    RS_JNT_LEGL2_e=0x12,
    RS_JNT_FOOTL_e=0x13,
    RS_JNT_LEGR1_e=0x14,
    RS_JNT_LEGR2_e=0x15,
    RS_JNT_FOOTR_e=0x16,
};

#endif /* !RES_RSH_H */