#ifndef RES_SPEAR_H
#define RES_SPEAR_H

//
// Generated by res_arc.py from archive: Spear.arc
// Do not manually modify this file or your changes will be overwritten.
//

enum dRes_INDEX_SPEAR {
    /* BDLC */
    dRes_INDEX_SPEAR_BDL_MO_YARI_e=0x3,
};

enum dRes_ID_SPEAR {
    /* BDLC */
    dRes_ID_SPEAR_BDL_MO_YARI_e=0x3,
};

enum MO_YARI_JNT {
    MO_YARI_JNT_MO_YARI_e=0x0,
};

#endif /* RES_SPEAR_H */
