#ifndef RES_VDORA_H
#define RES_VDORA_H

enum dRes_INDEX_VDORA {
    /* BDL  */
    dRes_INDEX_VDORA_BDL_VDORA_e=0x4,
    /* BCKS */
    dRes_INDEX_VDORA_BCK_05_VDORA_CUT02_HIT_e=0x7,
    dRes_INDEX_VDORA_BCK_05_VDORA_CUT02_WAIT_e=0x8,
};

enum dRes_ID_VDORA {
    /* BDL  */
    dRes_ID_VDORA_BDL_VDORA_e=0x3,
    /* BCKS */
    dRes_ID_VDORA_BCK_05_VDORA_CUT02_HIT_e=0x6,
    dRes_ID_VDORA_BCK_05_VDORA_CUT02_WAIT_e=0x7,
};

enum VDORA_JNT {
    VDORA_JNT_DORA_ALL_e=0x0,
    VDORA_JNT_CENTER_e=0x1,
    VDORA_JNT_DORAROT_e=0x2,
    VDORA_JNT_DORASCALE_e=0x3,
    VDORA_JNT_POLEL_e=0x4,
    VDORA_JNT_POLER_e=0x5,
};

#endif /* !RES_VDORA_H */