#ifndef RES_VGNFD_H
#define RES_VGNFD_H

enum dRes_INDEX_VGNFD {
    /* BDLM */
    dRes_INDEX_VGNFD_BDL_VGNFD0_e=0x6,
    dRes_INDEX_VGNFD_BDL_VGNFD1_e=0x7,
    dRes_INDEX_VGNFD_BDL_VGNFD2_e=0x8,
    dRes_INDEX_VGNFD_BDL_VGNFD3_e=0x9,
    dRes_INDEX_VGNFD_BDL_VGNFD4_e=0xA,
    dRes_INDEX_VGNFD_BDL_VGNFD5_e=0xB,
    dRes_INDEX_VGNFD_BDL_YGCBD00_e=0xC,
    /* BRK  */
    dRes_INDEX_VGNFD_BRK_VGNFD0_e=0xF,
    dRes_INDEX_VGNFD_BRK_VGNFD1_e=0x10,
    dRes_INDEX_VGNFD_BRK_VGNFD2_e=0x11,
    dRes_INDEX_VGNFD_BRK_VGNFD3_e=0x12,
    dRes_INDEX_VGNFD_BRK_VGNFD4_e=0x13,
    /* BTK  */
    dRes_INDEX_VGNFD_BTK_YGCBD00_e=0x16,
    /* DZB  */
    dRes_INDEX_VGNFD_DZB_VGNFD_e=0x19,
};

enum dRes_ID_VGNFD {
    /* BDLM */
    dRes_ID_VGNFD_BDL_VGNFD0_e=0x6,
    dRes_ID_VGNFD_BDL_VGNFD1_e=0x7,
    dRes_ID_VGNFD_BDL_VGNFD2_e=0x8,
    dRes_ID_VGNFD_BDL_VGNFD3_e=0x9,
    dRes_ID_VGNFD_BDL_VGNFD4_e=0xA,
    dRes_ID_VGNFD_BDL_VGNFD5_e=0xB,
    dRes_ID_VGNFD_BDL_YGCBD00_e=0xC,
    /* BRK  */
    dRes_ID_VGNFD_BRK_VGNFD0_e=0xF,
    dRes_ID_VGNFD_BRK_VGNFD1_e=0x10,
    dRes_ID_VGNFD_BRK_VGNFD2_e=0x11,
    dRes_ID_VGNFD_BRK_VGNFD3_e=0x12,
    dRes_ID_VGNFD_BRK_VGNFD4_e=0x13,
    /* BTK  */
    dRes_ID_VGNFD_BTK_YGCBD00_e=0x16,
    /* DZB  */
    dRes_ID_VGNFD_DZB_VGNFD_e=0x19,
};

enum VGNFD0_JNT {
    VGNFD0_JNT_V0_GANON_e=0x0,
};

enum VGNFD1_JNT {
    VGNFD1_JNT_V1_GOMA_e=0x0,
};

enum VGNFD2_JNT {
    VGNFD2_JNT_V2_BABARESIA_e=0x0,
};

enum VGNFD3_JNT {
    VGNFD3_JNT_V3_BIG_POW_e=0x0,
};

enum VGNFD4_JNT {
    VGNFD4_JNT_V4_RANENEMORA_e=0x0,
};

enum VGNFD5_JNT {
    VGNFD5_JNT_V5_DOOR_FOUR_e=0x0,
};

enum YGCBD00_JNT {
    YGCBD00_JNT_V5_DOOR_FOUR_e=0x0,
};

#endif /* !RES_VGNFD_H */