#ifndef RES_ITEMRES_H
#define RES_ITEMRES_H

enum dRes_INDEX_ITEMRES {
    /* SCRN */
    dRes_INDEX_ITEMRES_BLO_MENU_ITEM_02_e=0x4,
    /* TIMG */
    dRes_INDEX_ITEMRES_BTI_CHECK_00_e=0x7,
    dRes_INDEX_ITEMRES_BTI_ITEM_NAMEPLATE2_e=0x8,
    dRes_INDEX_ITEMRES_BTI_SUB_WINDOW_012_e=0x9,
    dRes_INDEX_ITEMRES_BTI_SUB_WINDOW_022_e=0xA,
    dRes_INDEX_ITEMRES_BTI_SUB_WINDOW_032_e=0xB,
    dRes_INDEX_ITEMRES_BTI_TITLE_ITEM_e=0xC,
    dRes_INDEX_ITEMRES_BTI_WORD_SAVE2_e=0xD,
};

enum dRes_ID_ITEMRES {
    /* SCRN */
    dRes_ID_ITEMRES_BLO_MENU_ITEM_02_e=0x4,
    /* TIMG */
    dRes_ID_ITEMRES_BTI_CHECK_00_e=0x7,
    dRes_ID_ITEMRES_BTI_ITEM_NAMEPLATE2_e=0x8,
    dRes_ID_ITEMRES_BTI_SUB_WINDOW_012_e=0x9,
    dRes_ID_ITEMRES_BTI_SUB_WINDOW_022_e=0xA,
    dRes_ID_ITEMRES_BTI_SUB_WINDOW_032_e=0xB,
    dRes_ID_ITEMRES_BTI_TITLE_ITEM_e=0xC,
    dRes_ID_ITEMRES_BTI_WORD_SAVE2_e=0xD,
};

#endif /* !RES_ITEMRES_H */