#ifndef RES_MOONMAPRES_H
#define RES_MOONMAPRES_H

enum dRes_INDEX_MOONMAPRES {
    /* SCRN */
    dRes_INDEX_MOONMAPRES_BLO_MN_MAP_1_e=0x4,
    /* TIMG */
    dRes_INDEX_MOONMAPRES_BTI_MN_BLACK_e=0x7,
    dRes_INDEX_MOONMAPRES_BTI_MN_CLOTH_PIECE01_e=0x8,
    dRes_INDEX_MOONMAPRES_BTI_MN_FULMN_e=0x9,
    dRes_INDEX_MOONMAPRES_BTI_MN_HMN_e=0xA,
    dRes_INDEX_MOONMAPRES_BTI_MN_KIRA_e=0xB,
    dRes_INDEX_MOONMAPRES_BTI_MN_LINE392_e=0xC,
    dRes_INDEX_MOONMAPRES_BTI_MN_LINK_e=0xD,
    dRes_INDEX_MOONMAPRES_BTI_MN_MENU_NOTE_00_e=0xE,
    dRes_INDEX_MOONMAPRES_BTI_MN_MENU_NOTE_02_e=0xF,
    dRes_INDEX_MOONMAPRES_BTI_MN_MENU_NOTE_03_e=0x10,
    dRes_INDEX_MOONMAPRES_BTI_MN_NMN_e=0x11,
    dRes_INDEX_MOONMAPRES_BTI_MN_NOTE_03_1_e=0x12,
    dRes_INDEX_MOONMAPRES_BTI_MN_POINT_e=0x13,
    dRes_INDEX_MOONMAPRES_BTI_MN_TITLE_MJ_e=0x14,
    dRes_INDEX_MOONMAPRES_BTI_MN_TITLE_WAKU_e=0x15,
    dRes_INDEX_MOONMAPRES_BTI_MN_YOGORE_01_e=0x16,
};

enum dRes_ID_MOONMAPRES {
    /* SCRN */
    dRes_ID_MOONMAPRES_BLO_MN_MAP_1_e=0x4,
    /* TIMG */
    dRes_ID_MOONMAPRES_BTI_MN_BLACK_e=0x7,
    dRes_ID_MOONMAPRES_BTI_MN_CLOTH_PIECE01_e=0x8,
    dRes_ID_MOONMAPRES_BTI_MN_FULMN_e=0x9,
    dRes_ID_MOONMAPRES_BTI_MN_HMN_e=0xA,
    dRes_ID_MOONMAPRES_BTI_MN_KIRA_e=0xB,
    dRes_ID_MOONMAPRES_BTI_MN_LINE392_e=0xC,
    dRes_ID_MOONMAPRES_BTI_MN_LINK_e=0xD,
    dRes_ID_MOONMAPRES_BTI_MN_MENU_NOTE_00_e=0xE,
    dRes_ID_MOONMAPRES_BTI_MN_MENU_NOTE_02_e=0xF,
    dRes_ID_MOONMAPRES_BTI_MN_MENU_NOTE_03_e=0x10,
    dRes_ID_MOONMAPRES_BTI_MN_NMN_e=0x11,
    dRes_ID_MOONMAPRES_BTI_MN_NOTE_03_1_e=0x12,
    dRes_ID_MOONMAPRES_BTI_MN_POINT_e=0x13,
    dRes_ID_MOONMAPRES_BTI_MN_TITLE_MJ_e=0x14,
    dRes_ID_MOONMAPRES_BTI_MN_TITLE_WAKU_e=0x15,
    dRes_ID_MOONMAPRES_BTI_MN_YOGORE_01_e=0x16,
};

#endif /* !RES_MOONMAPRES_H */