#ifndef RES_MSGRES_H
#define RES_MSGRES_H

enum dRes_INDEX_MSGRES {
    /* BCK  */
    dRes_INDEX_MSGRES_BCK_HUKIDASHI_07_e=0x7,
    /* BDLM */
    dRes_INDEX_MSGRES_BDL_HUKIDASHI_07_e=0xA,
    /* BMT  */
    dRes_INDEX_MSGRES_BMT_HUKIDASHI_07_e=0xD,
    /* SCRN */
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_00_e=0x10,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_02_e=0x11,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_05_e=0x12,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_07_e=0x13,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_08_e=0x14,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_09_e=0x15,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_e=0x16,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_0_1_e=0x17,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_0_2_e=0x18,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_1_e=0x19,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_3_e=0x1A,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_5_e=0x1B,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_6_e=0x1C,
    /* TIMG */
    dRes_INDEX_MSGRES_BTI_BACK_LIGHT_e=0x1F,
    dRes_INDEX_MSGRES_BTI_BATON_ARROW_e=0x20,
    dRes_INDEX_MSGRES_BTI_BATON_ARROW0_e=0x21,
    dRes_INDEX_MSGRES_BTI_BATON_INPUT_FRAME_e=0x22,
    dRes_INDEX_MSGRES_BTI_BATON_LINE_e=0x23,
    dRes_INDEX_MSGRES_BTI_BATON_LINE2_e=0x24,
    dRes_INDEX_MSGRES_BTI_DOT_02_e=0x25,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_e=0x26,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_C12_e=0x27,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_C22_e=0x28,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_02_e=0x29,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_0212_e=0x2A,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_06_e=0x2B,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_07_e=0x2C,
    dRes_INDEX_MSGRES_BTI_RING_LOGHT_e=0x2D,
    dRes_INDEX_MSGRES_BTI_WHITE_BLACK_e=0x2E,
    dRes_INDEX_MSGRES_BTI_YAZIRUSHI_00_e=0x2F,
};

enum dRes_ID_MSGRES {
    /* BCK  */
    dRes_ID_MSGRES_BCK_HUKIDASHI_07_e=0x7,
    /* BDLM */
    dRes_ID_MSGRES_BDL_HUKIDASHI_07_e=0xA,
    /* BMT  */
    dRes_ID_MSGRES_BMT_HUKIDASHI_07_e=0xD,
    /* SCRN */
    dRes_ID_MSGRES_BLO_HUKIDASHI_00_e=0x10,
    dRes_ID_MSGRES_BLO_HUKIDASHI_02_e=0x11,
    dRes_ID_MSGRES_BLO_HUKIDASHI_05_e=0x12,
    dRes_ID_MSGRES_BLO_HUKIDASHI_07_e=0x13,
    dRes_ID_MSGRES_BLO_HUKIDASHI_08_e=0x14,
    dRes_ID_MSGRES_BLO_HUKIDASHI_09_e=0x15,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_e=0x16,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_0_1_e=0x17,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_0_2_e=0x18,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_1_e=0x19,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_3_e=0x1A,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_5_e=0x1B,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_6_e=0x1C,
    /* TIMG */
    dRes_ID_MSGRES_BTI_BACK_LIGHT_e=0x1F,
    dRes_ID_MSGRES_BTI_BATON_ARROW_e=0x20,
    dRes_ID_MSGRES_BTI_BATON_ARROW0_e=0x21,
    dRes_ID_MSGRES_BTI_BATON_INPUT_FRAME_e=0x22,
    dRes_ID_MSGRES_BTI_BATON_LINE_e=0x23,
    dRes_ID_MSGRES_BTI_BATON_LINE2_e=0x24,
    dRes_ID_MSGRES_BTI_DOT_02_e=0x25,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_e=0x26,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_C12_e=0x27,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_C22_e=0x28,
    dRes_ID_MSGRES_BTI_HUKIDASHI_02_e=0x29,
    dRes_ID_MSGRES_BTI_HUKIDASHI_0212_e=0x2A,
    dRes_ID_MSGRES_BTI_HUKIDASHI_06_e=0x2B,
    dRes_ID_MSGRES_BTI_HUKIDASHI_07_e=0x2C,
    dRes_ID_MSGRES_BTI_RING_LOGHT_e=0x2D,
    dRes_ID_MSGRES_BTI_WHITE_BLACK_e=0x2E,
    dRes_ID_MSGRES_BTI_YAZIRUSHI_00_e=0x2F,
};

#endif /* !RES_MSGRES_H */