#ifndef RES_TNMAPRES_H
#define RES_TNMAPRES_H

enum dRes_INDEX_TNMAPRES {
    /* SCRN */
    dRes_INDEX_TNMAPRES_BLO_T_MAP_01_e=0x4,
    /* TIMG */
    dRes_INDEX_TNMAPRES_BTI_F_KOBOSHI_01_e=0x7,
    dRes_INDEX_TNMAPRES_BTI_F_TIN_MOJI_e=0x8,
    dRes_INDEX_TNMAPRES_BTI_F_TIN_NAME_e=0x9,
    dRes_INDEX_TNMAPRES_BTI_F_TIN_NOTE_01_e=0xA,
    dRes_INDEX_TNMAPRES_BTI_F_TIN_NOTE_02_e=0xB,
    dRes_INDEX_TNMAPRES_BTI_F_TIN_YOGORE_02_e=0xC,
    dRes_INDEX_TNMAPRES_BTI_TIN_TOWER_TEST_e=0xD,
    dRes_INDEX_TNMAPRES_BTI_TIN_TOWN_TEST_e=0xE,
    dRes_INDEX_TNMAPRES_BTI_TIN_YAJI_TEST_e=0xF,
    dRes_INDEX_TNMAPRES_BTI_T_BLACK_e=0x10,
    dRes_INDEX_TNMAPRES_BTI_T_CLOTH_PIECE01_e=0x11,
    dRes_INDEX_TNMAPRES_BTI_T_MENU_NOTE_00_e=0x12,
    dRes_INDEX_TNMAPRES_BTI_T_MENU_NOTE_01_e=0x13,
    dRes_INDEX_TNMAPRES_BTI_T_MENU_NOTE_02_e=0x14,
    dRes_INDEX_TNMAPRES_BTI_T_YOGORE_01_e=0x15,
};

enum dRes_ID_TNMAPRES {
    /* SCRN */
    dRes_ID_TNMAPRES_BLO_T_MAP_01_e=0x4,
    /* TIMG */
    dRes_ID_TNMAPRES_BTI_F_KOBOSHI_01_e=0x7,
    dRes_ID_TNMAPRES_BTI_F_TIN_MOJI_e=0x8,
    dRes_ID_TNMAPRES_BTI_F_TIN_NAME_e=0x9,
    dRes_ID_TNMAPRES_BTI_F_TIN_NOTE_01_e=0xA,
    dRes_ID_TNMAPRES_BTI_F_TIN_NOTE_02_e=0xB,
    dRes_ID_TNMAPRES_BTI_F_TIN_YOGORE_02_e=0xC,
    dRes_ID_TNMAPRES_BTI_TIN_TOWER_TEST_e=0xD,
    dRes_ID_TNMAPRES_BTI_TIN_TOWN_TEST_e=0xE,
    dRes_ID_TNMAPRES_BTI_TIN_YAJI_TEST_e=0xF,
    dRes_ID_TNMAPRES_BTI_T_BLACK_e=0x10,
    dRes_ID_TNMAPRES_BTI_T_CLOTH_PIECE01_e=0x11,
    dRes_ID_TNMAPRES_BTI_T_MENU_NOTE_00_e=0x12,
    dRes_ID_TNMAPRES_BTI_T_MENU_NOTE_01_e=0x13,
    dRes_ID_TNMAPRES_BTI_T_MENU_NOTE_02_e=0x14,
    dRes_ID_TNMAPRES_BTI_T_YOGORE_01_e=0x15,
};

#endif /* !RES_TNMAPRES_H */