// All names in this file are fake.

class dSv_evtBit_c {
public:
    enum {
        ENDLESS_NIGHT = 0x0A02,
        MET_KORL = 0x0F80,
        RODE_KORL = 0x2A08,
        BARRIER_BREAK = 0x2C02,
        LITHOGRAPH_1 = 0x3508,
        LITHOGRAPH_2 = 0x3504,
        LITHOGRAPH_3 = 0x3502,
        LITHOGRAPH_4 = 0x3501,
        LITHOGRAPH_5 = 0x3680,
        LITHOGRAPH_6 = 0x3640,
        LITHOGRAPH_7 = 0x3620,
        LITHOGRAPH_8 = 0x3610,
        LITHOGRAPH_9 = 0x3608,
        LITHOGRAPH_10 = 0x3604,
        COLORS_IN_HYRULE = 0x3802,
        NOTE_TO_MOM = 0xAC03,
    };
};
