//
// Generated by dtk
// Translation Unit: JUTDirectFile.cpp
//

#include "JSystem/JUtility/JUTDirectFile.h"
#include "dolphin/types.h"

/* 802CBAD8-802CBBA0       .text fetch32byte__13JUTDirectFileFv */
void JUTDirectFile::fetch32byte() {
    /* Nonmatching */
}

/* 802CBBA0-802CBBC4       .text __ct__13JUTDirectFileFv */
JUTDirectFile::JUTDirectFile() {
    /* Nonmatching */
}

/* 802CBBC4-802CBC08       .text __dt__13JUTDirectFileFv */
JUTDirectFile::~JUTDirectFile() {
    /* Nonmatching */
}

/* 802CBC08-802CBCA4       .text fopen__13JUTDirectFileFPCc */
void JUTDirectFile::fopen(const char*) {
    /* Nonmatching */
}

/* 802CBCA4-802CBD00       .text fclose__13JUTDirectFileFv */
void JUTDirectFile::fclose() {
    /* Nonmatching */
}

/* 802CBD00-802CBEB0       .text fgets__13JUTDirectFileFPvi */
void JUTDirectFile::fgets(void*, int) {
    /* Nonmatching */
}
