#ifndef RES_DMAPRES_H
#define RES_DMAPRES_H

enum dRes_INDEX_DMAPRES {
    /* SCRN */
    dRes_INDEX_DMAPRES_BLO_MENU_EXPLANATION_e=0x4,
    dRes_INDEX_DMAPRES_BLO_MENU_MAP_D_e=0x5,
    /* TIMG */
    dRes_INDEX_DMAPRES_BTI_BLACK_GAUSS_01_e=0x8,
    dRes_INDEX_DMAPRES_BTI_BLACK_WHITE_3_e=0x9,
    dRes_INDEX_DMAPRES_BTI_BOSS_SMALL_e=0xA,
    dRes_INDEX_DMAPRES_BTI_CIRCLE_e=0xB,
    dRes_INDEX_DMAPRES_BTI_CROSS_BUTTON_e=0xC,
    dRes_INDEX_DMAPRES_BTI_DTMAP_MASK_e=0xD,
    dRes_INDEX_DMAPRES_BTI_F_OTMICON_e=0xE,
    dRes_INDEX_DMAPRES_BTI_GRID_32_e=0xF,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_1_e=0x10,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_2_e=0x11,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_3_e=0x12,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_4_e=0x13,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_B1_e=0x14,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_B2_e=0x15,
    dRes_INDEX_DMAPRES_BTI_HIERARCHY_NUM_B3_e=0x16,
    dRes_INDEX_DMAPRES_BTI_LINK_EYE1_e=0x17,
    dRes_INDEX_DMAPRES_BTI_LINK_EYE2_e=0x18,
    dRes_INDEX_DMAPRES_BTI_LINK_HEAD_e=0x19,
    dRes_INDEX_DMAPRES_BTI_LINK_MOUTH1_e=0x1A,
    dRes_INDEX_DMAPRES_BTI_LINK_MOUTH2_e=0x1B,
    dRes_INDEX_DMAPRES_BTI_MENU_NOTE_02_2_e=0x1C,
    dRes_INDEX_DMAPRES_BTI_TREASUREBOX_e=0x1D,
};

enum dRes_ID_DMAPRES {
    /* SCRN */
    dRes_ID_DMAPRES_BLO_MENU_EXPLANATION_e=0x4,
    dRes_ID_DMAPRES_BLO_MENU_MAP_D_e=0x5,
    /* TIMG */
    dRes_ID_DMAPRES_BTI_BLACK_GAUSS_01_e=0x8,
    dRes_ID_DMAPRES_BTI_BLACK_WHITE_3_e=0x9,
    dRes_ID_DMAPRES_BTI_BOSS_SMALL_e=0xA,
    dRes_ID_DMAPRES_BTI_CIRCLE_e=0xB,
    dRes_ID_DMAPRES_BTI_CROSS_BUTTON_e=0xC,
    dRes_ID_DMAPRES_BTI_DTMAP_MASK_e=0xD,
    dRes_ID_DMAPRES_BTI_F_OTMICON_e=0xE,
    dRes_ID_DMAPRES_BTI_GRID_32_e=0xF,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_1_e=0x10,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_2_e=0x11,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_3_e=0x12,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_4_e=0x13,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_B1_e=0x14,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_B2_e=0x15,
    dRes_ID_DMAPRES_BTI_HIERARCHY_NUM_B3_e=0x16,
    dRes_ID_DMAPRES_BTI_LINK_EYE1_e=0x17,
    dRes_ID_DMAPRES_BTI_LINK_EYE2_e=0x18,
    dRes_ID_DMAPRES_BTI_LINK_HEAD_e=0x19,
    dRes_ID_DMAPRES_BTI_LINK_MOUTH1_e=0x1A,
    dRes_ID_DMAPRES_BTI_LINK_MOUTH2_e=0x1B,
    dRes_ID_DMAPRES_BTI_MENU_NOTE_02_2_e=0x1C,
    dRes_ID_DMAPRES_BTI_TREASUREBOX_e=0x1D,
};

#endif /* !RES_DMAPRES_H */