#ifndef RES_IRMAPRES_H
#define RES_IRMAPRES_H

enum dRes_INDEX_IRMAPRES {
    /* SCRN */
    dRes_INDEX_IRMAPRES_BLO_IR_MAP_1_e=0x4,
    /* TIMG */
    dRes_INDEX_IRMAPRES_BTI_IR_BLACK_e=0x7,
    dRes_INDEX_IRMAPRES_BTI_IR_CLOTH_PIECE01_e=0x8,
    dRes_INDEX_IRMAPRES_BTI_IR_KAZARI_1_e=0x9,
    dRes_INDEX_IRMAPRES_BTI_IR_LINE392_e=0xA,
    dRes_INDEX_IRMAPRES_BTI_IR_LINK_e=0xB,
    dRes_INDEX_IRMAPRES_BTI_IR_MENU_NOTE_00_e=0xC,
    dRes_INDEX_IRMAPRES_BTI_IR_MENU_NOTE_02_e=0xD,
    dRes_INDEX_IRMAPRES_BTI_IR_MENU_NOTE_03_e=0xE,
    dRes_INDEX_IRMAPRES_BTI_IR_NOTE_03_1_e=0xF,
    dRes_INDEX_IRMAPRES_BTI_IR_NUM_02_e=0x10,
    dRes_INDEX_IRMAPRES_BTI_IR_NUM_CROSS_e=0x11,
    dRes_INDEX_IRMAPRES_BTI_IR_POINT_e=0x12,
    dRes_INDEX_IRMAPRES_BTI_IR_QUE_e=0x13,
    dRes_INDEX_IRMAPRES_BTI_IR_TITLE_e=0x14,
    dRes_INDEX_IRMAPRES_BTI_IR_YOGORE_01_e=0x15,
};

enum dRes_ID_IRMAPRES {
    /* SCRN */
    dRes_ID_IRMAPRES_BLO_IR_MAP_1_e=0x4,
    /* TIMG */
    dRes_ID_IRMAPRES_BTI_IR_BLACK_e=0x7,
    dRes_ID_IRMAPRES_BTI_IR_CLOTH_PIECE01_e=0x8,
    dRes_ID_IRMAPRES_BTI_IR_KAZARI_1_e=0x9,
    dRes_ID_IRMAPRES_BTI_IR_LINE392_e=0xA,
    dRes_ID_IRMAPRES_BTI_IR_LINK_e=0xB,
    dRes_ID_IRMAPRES_BTI_IR_MENU_NOTE_00_e=0xC,
    dRes_ID_IRMAPRES_BTI_IR_MENU_NOTE_02_e=0xD,
    dRes_ID_IRMAPRES_BTI_IR_MENU_NOTE_03_e=0xE,
    dRes_ID_IRMAPRES_BTI_IR_NOTE_03_1_e=0xF,
    dRes_ID_IRMAPRES_BTI_IR_NUM_02_e=0x10,
    dRes_ID_IRMAPRES_BTI_IR_NUM_CROSS_e=0x11,
    dRes_ID_IRMAPRES_BTI_IR_POINT_e=0x12,
    dRes_ID_IRMAPRES_BTI_IR_QUE_e=0x13,
    dRes_ID_IRMAPRES_BTI_IR_TITLE_e=0x14,
    dRes_ID_IRMAPRES_BTI_IR_YOGORE_01_e=0x15,
};

#endif /* !RES_IRMAPRES_H */