#ifndef RES_MSGRES_H
#define RES_MSGRES_H

enum dRes_INDEX_MSGRES {
    /* SCRN */
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_00_e=0x4,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_02_e=0x5,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_05_e=0x6,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_07_e=0x7,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_08_e=0x8,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_09_e=0x9,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_e=0xA,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_0_1_e=0xB,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_0_2_e=0xC,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_1_e=0xD,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_3_e=0xE,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_5_e=0xF,
    dRes_INDEX_MSGRES_BLO_HUKIDASHI_14_6_e=0x10,
    /* TIMG */
    dRes_INDEX_MSGRES_BTI_BACK_LIGHT_e=0x13,
    dRes_INDEX_MSGRES_BTI_BATON_ARROW_e=0x14,
    dRes_INDEX_MSGRES_BTI_BATON_ARROW0_e=0x15,
    dRes_INDEX_MSGRES_BTI_BATON_INPUT_FRAME_e=0x16,
    dRes_INDEX_MSGRES_BTI_BATON_LINE_e=0x17,
    dRes_INDEX_MSGRES_BTI_BATON_LINE2_e=0x18,
    dRes_INDEX_MSGRES_BTI_DOT_02_e=0x19,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_e=0x1A,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_C12_e=0x1B,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_00_C22_e=0x1C,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_02_e=0x1D,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_0212_e=0x1E,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_06_e=0x1F,
    dRes_INDEX_MSGRES_BTI_HUKIDASHI_07_e=0x20,
    dRes_INDEX_MSGRES_BTI_RING_LOGHT_e=0x21,
    dRes_INDEX_MSGRES_BTI_WHITE_BLACK_e=0x22,
    dRes_INDEX_MSGRES_BTI_YAZIRUSHI_00_e=0x23,
};

enum dRes_ID_MSGRES {
    /* SCRN */
    dRes_ID_MSGRES_BLO_HUKIDASHI_00_e=0x4,
    dRes_ID_MSGRES_BLO_HUKIDASHI_02_e=0x5,
    dRes_ID_MSGRES_BLO_HUKIDASHI_05_e=0x6,
    dRes_ID_MSGRES_BLO_HUKIDASHI_07_e=0x7,
    dRes_ID_MSGRES_BLO_HUKIDASHI_08_e=0x8,
    dRes_ID_MSGRES_BLO_HUKIDASHI_09_e=0x9,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_e=0xA,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_0_1_e=0xB,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_0_2_e=0xC,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_1_e=0xD,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_3_e=0xE,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_5_e=0xF,
    dRes_ID_MSGRES_BLO_HUKIDASHI_14_6_e=0x10,
    /* TIMG */
    dRes_ID_MSGRES_BTI_BACK_LIGHT_e=0x13,
    dRes_ID_MSGRES_BTI_BATON_ARROW_e=0x14,
    dRes_ID_MSGRES_BTI_BATON_ARROW0_e=0x15,
    dRes_ID_MSGRES_BTI_BATON_INPUT_FRAME_e=0x16,
    dRes_ID_MSGRES_BTI_BATON_LINE_e=0x17,
    dRes_ID_MSGRES_BTI_BATON_LINE2_e=0x18,
    dRes_ID_MSGRES_BTI_DOT_02_e=0x19,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_e=0x1A,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_C12_e=0x1B,
    dRes_ID_MSGRES_BTI_HUKIDASHI_00_C22_e=0x1C,
    dRes_ID_MSGRES_BTI_HUKIDASHI_02_e=0x1D,
    dRes_ID_MSGRES_BTI_HUKIDASHI_0212_e=0x1E,
    dRes_ID_MSGRES_BTI_HUKIDASHI_06_e=0x1F,
    dRes_ID_MSGRES_BTI_HUKIDASHI_07_e=0x20,
    dRes_ID_MSGRES_BTI_RING_LOGHT_e=0x21,
    dRes_ID_MSGRES_BTI_WHITE_BLACK_e=0x22,
    dRes_ID_MSGRES_BTI_YAZIRUSHI_00_e=0x23,
};

#endif /* !RES_MSGRES_H */