#ifndef RES_SUBMAMAPRES_H
#define RES_SUBMAMAPRES_H

enum dRes_INDEX_SUBMAMAPRES {
    /* SCRN */
    dRes_INDEX_SUBMAMAPRES_BLO_SENSUI_MAP_1_e=0x4,
    /* TIMG */
    dRes_INDEX_SUBMAMAPRES_BTI_SENBLACK_e=0x7,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_HUK_e=0x8,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_KANBAN_e=0x9,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_KANBAN2_e=0xA,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_KOKO_e=0xB,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_NERAI_e=0xC,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_SHIP_e=0xD,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_SHIP2_e=0xE,
    dRes_INDEX_SUBMAMAPRES_BTI_SENSUI_SHIP3_e=0xF,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_CLOTH_PIECE01_e=0x10,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_HIKI_e=0x11,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_LINE392_e=0x12,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_LINK_e=0x13,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_MENU_NOTE_00_e=0x14,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_MENU_NOTE_01_e=0x15,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_MENU_NOTE_02_e=0x16,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_MENU_NOTE_03_e=0x17,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_NOTE_03_1_e=0x18,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_YOGORE_01_e=0x19,
    dRes_INDEX_SUBMAMAPRES_BTI_SEN_YOGORE_02_e=0x1A,
};

enum dRes_ID_SUBMAMAPRES {
    /* SCRN */
    dRes_ID_SUBMAMAPRES_BLO_SENSUI_MAP_1_e=0x4,
    /* TIMG */
    dRes_ID_SUBMAMAPRES_BTI_SENBLACK_e=0x7,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_HUK_e=0x8,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_KANBAN_e=0x9,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_KANBAN2_e=0xA,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_KOKO_e=0xB,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_NERAI_e=0xC,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_SHIP_e=0xD,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_SHIP2_e=0xE,
    dRes_ID_SUBMAMAPRES_BTI_SENSUI_SHIP3_e=0xF,
    dRes_ID_SUBMAMAPRES_BTI_SEN_CLOTH_PIECE01_e=0x10,
    dRes_ID_SUBMAMAPRES_BTI_SEN_HIKI_e=0x11,
    dRes_ID_SUBMAMAPRES_BTI_SEN_LINE392_e=0x12,
    dRes_ID_SUBMAMAPRES_BTI_SEN_LINK_e=0x13,
    dRes_ID_SUBMAMAPRES_BTI_SEN_MENU_NOTE_00_e=0x14,
    dRes_ID_SUBMAMAPRES_BTI_SEN_MENU_NOTE_01_e=0x15,
    dRes_ID_SUBMAMAPRES_BTI_SEN_MENU_NOTE_02_e=0x16,
    dRes_ID_SUBMAMAPRES_BTI_SEN_MENU_NOTE_03_e=0x17,
    dRes_ID_SUBMAMAPRES_BTI_SEN_NOTE_03_1_e=0x18,
    dRes_ID_SUBMAMAPRES_BTI_SEN_YOGORE_01_e=0x19,
    dRes_ID_SUBMAMAPRES_BTI_SEN_YOGORE_02_e=0x1A,
};

#endif /* !RES_SUBMAMAPRES_H */