//
// Generated by dtk
// Translation Unit: J3DShape.cpp
//

#include "JSystem/J3DGraphBase/J3DShape.h"
#include "dolphin/types.h"

/* 802DD18C-802DD1FC       .text initialize__8J3DShapeFv */
void J3DShape::initialize() {
    /* Nonmatching */
}

/* 802DD1FC-802DD27C       .text calcNBTScale__8J3DShapeFRC3VecPA3_A3_fPA3_A3_f */
void J3DShape::calcNBTScale(const Vec&, float(*)[3][3], float(*)[3][3]) {
    /* Nonmatching */
}

/* 802DD27C-802DD2F0       .text countBumpMtxNum__8J3DShapeCFv */
void J3DShape::countBumpMtxNum() const {
    /* Nonmatching */
}

/* 802DD2F0-802DD308       .text J3DLoadCPCmd__FUcUl */
void J3DLoadCPCmd(unsigned char, unsigned long) {
    /* Nonmatching */
}

/* 802DD308-802DD344       .text J3DLoadArrayBasePtr__F7_GXAttrPv */
void J3DLoadArrayBasePtr(_GXAttr, void*) {
    /* Nonmatching */
}

/* 802DD344-802DD3B4       .text loadVtxArray__8J3DShapeCFv */
void J3DShape::loadVtxArray() const {
    /* Nonmatching */
}

/* 802DD3B4-802DD3F0       .text isSameVcdVatCmd__8J3DShapeFP8J3DShape */
void J3DShape::isSameVcdVatCmd(J3DShape*) {
    /* Nonmatching */
}

/* 802DD3F0-802DD6B8       .text makeVtxArrayCmd__8J3DShapeFv */
void J3DShape::makeVtxArrayCmd() {
    /* Nonmatching */
}

/* 802DD6B8-802DD72C       .text makeVcdVatCmd__8J3DShapeFv */
void J3DShape::makeVcdVatCmd() {
    /* Nonmatching */
}

/* 802DD72C-802DD7CC       .text loadPreDrawSetting__8J3DShapeCFv */
void J3DShape::loadPreDrawSetting() const {
    /* Nonmatching */
}

/* 802DD7CC-802DD874       .text setArrayAndBindPipeline__8J3DShapeCFv */
void J3DShape::setArrayAndBindPipeline() const {
    /* Nonmatching */
}

/* 802DD874-802DD9FC       .text drawFast__8J3DShapeCFv */
void J3DShape::drawFast() const {
    /* Nonmatching */
}

/* 802DD9FC-802DDA44       .text draw__8J3DShapeCFv */
void J3DShape::draw() const {
    /* Nonmatching */
}

/* 802DDA44-802DDAC8       .text simpleDraw__8J3DShapeCFv */
void J3DShape::simpleDraw() const {
    /* Nonmatching */
}

/* 802DDAC8-802DDBC4       .text simpleDrawCache__8J3DShapeCFv */
void J3DShape::simpleDrawCache() const {
    /* Nonmatching */
}
