#ifndef RES_BMDFOOT_H
#define RES_BMDFOOT_H

enum dRes_INDEX_BMDFOOT {
    /* BCK  */
    dRes_INDEX_BMDFOOT_BCK_ASI_ATTACK1_e=0x5,
    dRes_INDEX_BMDFOOT_BCK_ASI_ATTACK2_e=0x6,
    dRes_INDEX_BMDFOOT_BCK_ASI_ATTACK_LOOP_e=0x7,
    dRes_INDEX_BMDFOOT_BCK_ASI_DATTACK1_e=0x8,
    dRes_INDEX_BMDFOOT_BCK_ASI_DATTACK2_e=0x9,
    dRes_INDEX_BMDFOOT_BCK_ASI_DATTACK3_e=0xA,
    dRes_INDEX_BMDFOOT_BCK_ASI_DEAD_e=0xB,
    dRes_INDEX_BMDFOOT_BCK_ASI_DEAD_LOOP_e=0xC,
    dRes_INDEX_BMDFOOT_BCK_ASI_NOBIKIRU_e=0xD,
    dRes_INDEX_BMDFOOT_BCK_ASI_NUKU_e=0xE,
    dRes_INDEX_BMDFOOT_BCK_ASI_START1_e=0xF,
    dRes_INDEX_BMDFOOT_BCK_ASI_START2_e=0x10,
    dRes_INDEX_BMDFOOT_BCK_ASI_UMARU_e=0x11,
    dRes_INDEX_BMDFOOT_BCK_ASI_UMARU_WAIT_e=0x12,
    dRes_INDEX_BMDFOOT_BCK_ASI_WAIT_e=0x13,
    /* BMDM */
    dRes_INDEX_BMDFOOT_BMD_ASI_e=0x16,
    /* BTK  */
    dRes_INDEX_BMDFOOT_BTK_ASI_e=0x19,
};

enum dRes_ID_BMDFOOT {
    /* BCK  */
    dRes_ID_BMDFOOT_BCK_ASI_ATTACK1_e=0x5,
    dRes_ID_BMDFOOT_BCK_ASI_ATTACK2_e=0x6,
    dRes_ID_BMDFOOT_BCK_ASI_ATTACK_LOOP_e=0x7,
    dRes_ID_BMDFOOT_BCK_ASI_DATTACK1_e=0x8,
    dRes_ID_BMDFOOT_BCK_ASI_DATTACK2_e=0x9,
    dRes_ID_BMDFOOT_BCK_ASI_DATTACK3_e=0xA,
    dRes_ID_BMDFOOT_BCK_ASI_DEAD_e=0xB,
    dRes_ID_BMDFOOT_BCK_ASI_DEAD_LOOP_e=0xC,
    dRes_ID_BMDFOOT_BCK_ASI_NOBIKIRU_e=0xD,
    dRes_ID_BMDFOOT_BCK_ASI_NUKU_e=0xE,
    dRes_ID_BMDFOOT_BCK_ASI_START1_e=0xF,
    dRes_ID_BMDFOOT_BCK_ASI_START2_e=0x10,
    dRes_ID_BMDFOOT_BCK_ASI_UMARU_e=0x11,
    dRes_ID_BMDFOOT_BCK_ASI_UMARU_WAIT_e=0x12,
    dRes_ID_BMDFOOT_BCK_ASI_WAIT_e=0x13,
    /* BMDM */
    dRes_ID_BMDFOOT_BMD_ASI_e=0x16,
    /* BTK  */
    dRes_ID_BMDFOOT_BTK_ASI_e=0x19,
};

enum ASI_JNT {
    ASI_JNT_ASI1_e=0x0,
    ASI_JNT_ASI2_e=0x1,
    ASI_JNT_ASI3_e=0x2,
    ASI_JNT_ASI4_e=0x3,
    ASI_JNT_ASI5_e=0x4,
    ASI_JNT_ASI6_e=0x5,
    ASI_JNT_ASI7_e=0x6,
    ASI_JNT_ASI8_e=0x7,
    ASI_JNT_ASI9_e=0x8,
    ASI_JNT_ASI10_e=0x9,
    ASI_JNT_ASI11_e=0xA,
    ASI_JNT_ASI12_e=0xB,
    ASI_JNT_ASI13_e=0xC,
    ASI_JNT_ASI14_e=0xD,
    ASI_JNT_ASI15_e=0xE,
    ASI_JNT_ASI16_e=0xF,
    ASI_JNT_ASI17_e=0x10,
    ASI_JNT_ASI18_e=0x11,
};

#endif /* !RES_BMDFOOT_H */