#ifndef RES_BWDS_H
#define RES_BWDS_H

enum dRes_INDEX_BWDS {
    /* BCK  */
    dRes_INDEX_BWDS_BCK_KOBOSS_CLOSE_e=0x4,
    dRes_INDEX_BWDS_BCK_KOBOSS_PAKUPAKU_e=0x5,
    /* BDLM */
    dRes_INDEX_BWDS_BDL_KOBOSS_BODY_e=0x8,
    dRes_INDEX_BWDS_BDL_KOBOSS_HEAD_e=0x9,
    dRes_INDEX_BWDS_BDL_KOBOSS_SHIPPO_e=0xA,
};

enum dRes_ID_BWDS {
    /* BCK  */
    dRes_ID_BWDS_BCK_KOBOSS_CLOSE_e=0x4,
    dRes_ID_BWDS_BCK_KOBOSS_PAKUPAKU_e=0x5,
    /* BDLM */
    dRes_ID_BWDS_BDL_KOBOSS_BODY_e=0x8,
    dRes_ID_BWDS_BDL_KOBOSS_HEAD_e=0x9,
    dRes_ID_BWDS_BDL_KOBOSS_SHIPPO_e=0xA,
};

enum KOBOSS_BODY_JNT {
    KOBOSS_BODY_JNT_POLYSURFACE1_e=0x0,
};

enum KOBOSS_HEAD_JNT {
    KOBOSS_HEAD_JNT_KUBI_e=0x0,
    KOBOSS_HEAD_JNT_AGO_e=0x1,
    KOBOSS_HEAD_JNT_HEAD_e=0x2,
};

enum KOBOSS_SHIPPO_JNT {
    KOBOSS_SHIPPO_JNT_POLYSURFACE1_e=0x0,
};

#endif /* !RES_BWDS_H */