#ifndef RES_KO_H
#define RES_KO_H

enum dRes_INDEX_KO {
    /* BCKS */
    dRes_INDEX_KO_BCK_BALLOON_BANG_e=0x7,
    dRes_INDEX_KO_BCK_BALLOON_SLEEP04_e=0x8,
    dRes_INDEX_KO_BCK_KOHEAD01_BANG_e=0x9,
    dRes_INDEX_KO_BCK_KOHEAD01_BUTUKARI_e=0xA,
    dRes_INDEX_KO_BCK_KOHEAD01_OISI_e=0xB,
    dRes_INDEX_KO_BCK_KOHEAD01_RUN01_e=0xC,
    dRes_INDEX_KO_BCK_KOHEAD01_SLEEP03_e=0xD,
    dRes_INDEX_KO_BCK_KOHEAD01_SLEEP04_e=0xE,
    dRes_INDEX_KO_BCK_KOHEAD01_SUSURI_e=0xF,
    dRes_INDEX_KO_BCK_KOHEAD01_TALK01_e=0x10,
    dRes_INDEX_KO_BCK_KOHEAD01_WAIT01_e=0x11,
    dRes_INDEX_KO_BCK_KOHEAD01_WALK01_e=0x12,
    dRes_INDEX_KO_BCK_KO_BANG_e=0x13,
    dRes_INDEX_KO_BCK_KO_BUTUKARI_e=0x14,
    dRes_INDEX_KO_BCK_KO_OISI_e=0x15,
    dRes_INDEX_KO_BCK_KO_RUN01_e=0x16,
    dRes_INDEX_KO_BCK_KO_SLEEP01_e=0x17,
    dRes_INDEX_KO_BCK_KO_SLEEP02_e=0x18,
    dRes_INDEX_KO_BCK_KO_SLEEP03_e=0x19,
    dRes_INDEX_KO_BCK_KO_SLEEP04_e=0x1A,
    dRes_INDEX_KO_BCK_KO_SUSURI_e=0x1B,
    dRes_INDEX_KO_BCK_KO_TALK01_e=0x1C,
    dRes_INDEX_KO_BCK_KO_WAIT01_e=0x1D,
    dRes_INDEX_KO_BCK_KO_WAIT02_e=0x1E,
    dRes_INDEX_KO_BCK_KO_WALK01_e=0x1F,
    dRes_INDEX_KO_BCK_KOHEAD02_WAIT01_e=0x20,
    dRes_INDEX_KO_BCK_KO_OHOHO_e=0x21,
    /* BDL  */
    dRes_INDEX_KO_BDL_KOEDA_e=0x24,
    dRes_INDEX_KO_BDL_KO_BALLOON_e=0x25,
    /* BDLM */
    dRes_INDEX_KO_BDL_KO_e=0x28,
    dRes_INDEX_KO_BDL_KOHEAD01_e=0x29,
    dRes_INDEX_KO_BDL_KOHEAD02_e=0x2A,
    /* BMT  */
    dRes_INDEX_KO_BMT_KO02_e=0x2D,
    /* BTP  */
    dRes_INDEX_KO_BTP_KOHEAD01_e=0x30,
    dRes_INDEX_KO_BTP_KOHEAD01_SLEEP_e=0x31,
    dRes_INDEX_KO_BTP_KOHEAD01_SLEEP04_e=0x32,
    dRes_INDEX_KO_BTP_KOHEAD01_SUSURI_e=0x33,
    dRes_INDEX_KO_BTP_KOHEAD02_e=0x34,
    dRes_INDEX_KO_BTP_KOHEAD02_SLEEP_e=0x35,
};

enum dRes_ID_KO {
    /* BCKS */
    dRes_ID_KO_BCK_BALLOON_BANG_e=0x0,
    dRes_ID_KO_BCK_BALLOON_SLEEP04_e=0x1,
    dRes_ID_KO_BCK_KOHEAD01_BANG_e=0x2,
    dRes_ID_KO_BCK_KOHEAD01_BUTUKARI_e=0x3,
    dRes_ID_KO_BCK_KOHEAD01_OISI_e=0x4,
    dRes_ID_KO_BCK_KOHEAD01_RUN01_e=0x5,
    dRes_ID_KO_BCK_KOHEAD01_SLEEP03_e=0x6,
    dRes_ID_KO_BCK_KOHEAD01_SLEEP04_e=0x7,
    dRes_ID_KO_BCK_KOHEAD01_SUSURI_e=0x8,
    dRes_ID_KO_BCK_KOHEAD01_TALK01_e=0x9,
    dRes_ID_KO_BCK_KOHEAD01_WAIT01_e=0xA,
    dRes_ID_KO_BCK_KOHEAD01_WALK01_e=0xB,
    dRes_ID_KO_BCK_KO_BANG_e=0xC,
    dRes_ID_KO_BCK_KO_BUTUKARI_e=0xD,
    dRes_ID_KO_BCK_KO_OISI_e=0xE,
    dRes_ID_KO_BCK_KO_RUN01_e=0xF,
    dRes_ID_KO_BCK_KO_SLEEP01_e=0x10,
    dRes_ID_KO_BCK_KO_SLEEP02_e=0x11,
    dRes_ID_KO_BCK_KO_SLEEP03_e=0x12,
    dRes_ID_KO_BCK_KO_SLEEP04_e=0x13,
    dRes_ID_KO_BCK_KO_SUSURI_e=0x14,
    dRes_ID_KO_BCK_KO_TALK01_e=0x15,
    dRes_ID_KO_BCK_KO_WAIT01_e=0x16,
    dRes_ID_KO_BCK_KO_WAIT02_e=0x17,
    dRes_ID_KO_BCK_KO_WALK01_e=0x18,
    dRes_ID_KO_BCK_KOHEAD02_WAIT01_e=0x25,
    dRes_ID_KO_BCK_KO_OHOHO_e=0x26,
    /* BDL  */
    dRes_ID_KO_BDL_KOEDA_e=0x19,
    dRes_ID_KO_BDL_KO_BALLOON_e=0x1A,
    /* BDLM */
    dRes_ID_KO_BDL_KO_e=0x1B,
    dRes_ID_KO_BDL_KOHEAD01_e=0x1C,
    dRes_ID_KO_BDL_KOHEAD02_e=0x1D,
    /* BMT  */
    dRes_ID_KO_BMT_KO02_e=0x1E,
    /* BTP  */
    dRes_ID_KO_BTP_KOHEAD01_e=0x1F,
    dRes_ID_KO_BTP_KOHEAD01_SLEEP_e=0x20,
    dRes_ID_KO_BTP_KOHEAD01_SLEEP04_e=0x21,
    dRes_ID_KO_BTP_KOHEAD01_SUSURI_e=0x22,
    dRes_ID_KO_BTP_KOHEAD02_e=0x23,
    dRes_ID_KO_BTP_KOHEAD02_SLEEP_e=0x24,
};

enum KOEDA_JNT {
    KOEDA_JNT_KO_EDA_e=0x0,
};

enum KO_BALLOON_JNT {
    KO_BALLOON_JNT_BALLOON_LOC_e=0x0,
    KO_BALLOON_JNT_KO_BALLOON_e=0x1,
};

enum KO_JNT {
    KO_JNT_CENTER_e=0x0,
    KO_JNT_BACKBONE_e=0x1,
    KO_JNT_HEAD_e=0x2,
    KO_JNT_HEADEND_e=0x3,
    KO_JNT_SHOULDERL_e=0x4,
    KO_JNT_ARML1_e=0x5,
    KO_JNT_ARML2_e=0x6,
    KO_JNT_SHOULDERR_e=0x7,
    KO_JNT_ARMR1_e=0x8,
    KO_JNT_ARMR2_e=0x9,
    KO_JNT_WAIST_e=0xA,
    KO_JNT_LEGL1_e=0xB,
    KO_JNT_LEGL2_e=0xC,
    KO_JNT_LEGR1_e=0xD,
    KO_JNT_LEGR2_e=0xE,
};

enum KOHEAD01_JNT {
    KOHEAD01_JNT_HEAD2_e=0x0,
    KOHEAD01_JNT_HANAMIZU1_e=0x1,
    KOHEAD01_JNT_HANAMIZU2_e=0x2,
    KOHEAD01_JNT_HANAMIZU3_e=0x3,
};

enum KOHEAD02_JNT {
    KOHEAD02_JNT_KOHEAD02_e=0x0,
};

#endif /* !RES_KO_H */