#ifndef RES_LINK_H
#define RES_LINK_H

enum dRes_INDEX_LINK {
    /* BCK  */
    dRes_INDEX_LINK_BCK_ATNGSHA_e=0xA,
    dRes_INDEX_LINK_BCK_BOMB_e=0xB,
    dRes_INDEX_LINK_BCK_COMBO_TATE_e=0xC,
    dRes_INDEX_LINK_BCK_GICER01_e=0xD,
    dRes_INDEX_LINK_BCK_GWP00_e=0xE,
    dRes_INDEX_LINK_BCK_SWGRIPMSAB_e=0xF,
    dRes_INDEX_LINK_BCK_YUCHW00_e=0x10,
    /* BDL  */
    dRes_INDEX_LINK_BDL_BINFAIRY_e=0x13,
    dRes_INDEX_LINK_BDL_BOOMERANG_e=0x14,
    dRes_INDEX_LINK_BDL_BOTTLECAP_e=0x15,
    dRes_INDEX_LINK_BDL_BOW_e=0x16,
    dRes_INDEX_LINK_BDL_CAMERA_e=0x17,
    dRes_INDEX_LINK_BDL_CL_e=0x18,
    dRes_INDEX_LINK_BDL_FAN_e=0x19,
    dRes_INDEX_LINK_BDL_FANB_e=0x1A,
    dRes_INDEX_LINK_BDL_FANSMALL_e=0x1B,
    dRes_INDEX_LINK_BDL_HAMMER_e=0x1C,
    dRes_INDEX_LINK_BDL_HANDS_e=0x1D,
    dRes_INDEX_LINK_BDL_HOOKSHOT_e=0x1E,
    dRes_INDEX_LINK_BDL_HYOINOMI_e=0x1F,
    dRes_INDEX_LINK_BDL_KATSURA_e=0x20,
    dRes_INDEX_LINK_BDL_LETTER_e=0x21,
    dRes_INDEX_LINK_BDL_PODMS_e=0x22,
    dRes_INDEX_LINK_BDL_PRING_e=0x23,
    dRes_INDEX_LINK_BDL_SHA_e=0x24,
    dRes_INDEX_LINK_BDL_SWA_e=0x25,
    dRes_INDEX_LINK_BDL_SWGRIPA_e=0x26,
    dRes_INDEX_LINK_BDL_TCEIVER_e=0x27,
    dRes_INDEX_LINK_BDL_TETOLACH_e=0x28,
    dRes_INDEX_LINK_BDL_YAMU_e=0x29,
    /* BDLC */
    dRes_INDEX_LINK_BDL_ESA_e=0x2C,
    dRes_INDEX_LINK_BDL_HBOOTS_e=0x2D,
    dRes_INDEX_LINK_BDL_ROPEEND_e=0x2E,
    dRes_INDEX_LINK_BDL_TELESCOPE_e=0x2F,
    /* BDLI */
    dRes_INDEX_LINK_BDL_GARWFI00_e=0x32,
    dRes_INDEX_LINK_BDL_GARWFI01_e=0x33,
    dRes_INDEX_LINK_BDL_GARWG00_e=0x34,
    /* BDLM */
    dRes_INDEX_LINK_BDL_ARROW_e=0x37,
    dRes_INDEX_LINK_BDL_ARROWGLITTER_e=0x38,
    dRes_INDEX_LINK_BDL_BINHO_e=0x39,
    dRes_INDEX_LINK_BDL_BINLIQUID_e=0x3A,
    dRes_INDEX_LINK_BDL_BINLIQUIDH_e=0x3B,
    dRes_INDEX_LINK_BDL_BOMB_e=0x3C,
    dRes_INDEX_LINK_BDL_BOTTLEEMP_e=0x3D,
    dRes_INDEX_LINK_BDL_CUTFH_e=0x3E,
    dRes_INDEX_LINK_BDL_CUTFM_e=0x3F,
    dRes_INDEX_LINK_BDL_GICER00_e=0x40,
    dRes_INDEX_LINK_BDL_GICER01_e=0x41,
    dRes_INDEX_LINK_BDL_GWP00_e=0x42,
    dRes_INDEX_LINK_BDL_SHMS_e=0x43,
    dRes_INDEX_LINK_BDL_SUIMEN_MUNYA_e=0x44,
    dRes_INDEX_LINK_BDL_SWGRIPMS_e=0x45,
    dRes_INDEX_LINK_BDL_SWMS_e=0x46,
    dRes_INDEX_LINK_BDL_TAKT_e=0x47,
    dRes_INDEX_LINK_BDL_YAURA00_e=0x48,
    dRes_INDEX_LINK_BDL_YBAFO00_e=0x49,
    dRes_INDEX_LINK_BDL_YHSLS00_e=0x4A,
    dRes_INDEX_LINK_BDL_YMGCS00_e=0x4B,
    dRes_INDEX_LINK_BDL_YMSLI00_e=0x4C,
    dRes_INDEX_LINK_BDL_YMSLS00_e=0x4D,
    dRes_INDEX_LINK_BDL_YUCHW00_e=0x4E,
    /* BRK  */
    dRes_INDEX_LINK_BRK_BOMB_e=0x51,
    dRes_INDEX_LINK_BRK_GARWFI00_e=0x52,
    dRes_INDEX_LINK_BRK_GARWFI01_e=0x53,
    dRes_INDEX_LINK_BRK_GARWG00_e=0x54,
    dRes_INDEX_LINK_BRK_GWP00_e=0x55,
    dRes_INDEX_LINK_BRK_TSWGRIPMSAB_e=0x56,
    dRes_INDEX_LINK_BRK_YAURA00_G_e=0x57,
    dRes_INDEX_LINK_BRK_YAURA00_R_e=0x58,
    dRes_INDEX_LINK_BRK_YMGCS00_MS_e=0x59,
    dRes_INDEX_LINK_BRK_YMGCS00_TS_e=0x5A,
    dRes_INDEX_LINK_BRK_YUCHW00_e=0x5B,
    /* BTK  */
    dRes_INDEX_LINK_BTK_GARWFI00_e=0x5E,
    dRes_INDEX_LINK_BTK_GARWFI01_e=0x5F,
    dRes_INDEX_LINK_BTK_GARWG00_e=0x60,
    dRes_INDEX_LINK_BTK_GICER00_e=0x61,
    dRes_INDEX_LINK_BTK_GICER01_e=0x62,
    dRes_INDEX_LINK_BTK_GWP00_e=0x63,
    dRes_INDEX_LINK_BTK_SUIMEN_MUNYA_e=0x64,
    dRes_INDEX_LINK_BTK_TARROWGLITTER_e=0x65,
    dRes_INDEX_LINK_BTK_TSHMS_e=0x66,
    dRes_INDEX_LINK_BTK_TSWGRIPMS_e=0x67,
    dRes_INDEX_LINK_BTK_TTIPICE_e=0x68,
    dRes_INDEX_LINK_BTK_YAURA00_e=0x69,
    dRes_INDEX_LINK_BTK_YBAFO00_e=0x6A,
    dRes_INDEX_LINK_BTK_YMGCS00_e=0x6B,
    dRes_INDEX_LINK_BTK_YMSLS00_e=0x6C,
    dRes_INDEX_LINK_BTK_YUCHW00_e=0x6D,
    /* TEX  */
    dRes_INDEX_LINK_BTI_BLUR_e=0x70,
    dRes_INDEX_LINK_BTI_LINKTEXBCI4_e=0x71,
    dRes_INDEX_LINK_BTI_ROCK_MARK_e=0x72,
};

enum dRes_ID_LINK {
    /* BCK  */
    dRes_ID_LINK_BCK_ATNGSHA_e=0xA,
    dRes_ID_LINK_BCK_BOMB_e=0xB,
    dRes_ID_LINK_BCK_COMBO_TATE_e=0xC,
    dRes_ID_LINK_BCK_GICER01_e=0xD,
    dRes_ID_LINK_BCK_GWP00_e=0xE,
    dRes_ID_LINK_BCK_SWGRIPMSAB_e=0xF,
    dRes_ID_LINK_BCK_YUCHW00_e=0x10,
    /* BDL  */
    dRes_ID_LINK_BDL_BINFAIRY_e=0x13,
    dRes_ID_LINK_BDL_BOOMERANG_e=0x14,
    dRes_ID_LINK_BDL_BOTTLECAP_e=0x15,
    dRes_ID_LINK_BDL_BOW_e=0x16,
    dRes_ID_LINK_BDL_CAMERA_e=0x17,
    dRes_ID_LINK_BDL_CL_e=0x18,
    dRes_ID_LINK_BDL_FAN_e=0x19,
    dRes_ID_LINK_BDL_FANB_e=0x1A,
    dRes_ID_LINK_BDL_FANSMALL_e=0x1B,
    dRes_ID_LINK_BDL_HAMMER_e=0x1C,
    dRes_ID_LINK_BDL_HANDS_e=0x1D,
    dRes_ID_LINK_BDL_HOOKSHOT_e=0x1E,
    dRes_ID_LINK_BDL_HYOINOMI_e=0x1F,
    dRes_ID_LINK_BDL_KATSURA_e=0x20,
    dRes_ID_LINK_BDL_LETTER_e=0x21,
    dRes_ID_LINK_BDL_PODMS_e=0x22,
    dRes_ID_LINK_BDL_PRING_e=0x23,
    dRes_ID_LINK_BDL_SHA_e=0x24,
    dRes_ID_LINK_BDL_SWA_e=0x25,
    dRes_ID_LINK_BDL_SWGRIPA_e=0x26,
    dRes_ID_LINK_BDL_TCEIVER_e=0x27,
    dRes_ID_LINK_BDL_TETOLACH_e=0x28,
    dRes_ID_LINK_BDL_YAMU_e=0x29,
    /* BDLC */
    dRes_ID_LINK_BDL_ESA_e=0x2C,
    dRes_ID_LINK_BDL_HBOOTS_e=0x2D,
    dRes_ID_LINK_BDL_ROPEEND_e=0x2E,
    dRes_ID_LINK_BDL_TELESCOPE_e=0x2F,
    /* BDLI */
    dRes_ID_LINK_BDL_GARWFI00_e=0x32,
    dRes_ID_LINK_BDL_GARWFI01_e=0x33,
    dRes_ID_LINK_BDL_GARWG00_e=0x34,
    /* BDLM */
    dRes_ID_LINK_BDL_ARROW_e=0x37,
    dRes_ID_LINK_BDL_ARROWGLITTER_e=0x38,
    dRes_ID_LINK_BDL_BINHO_e=0x39,
    dRes_ID_LINK_BDL_BINLIQUID_e=0x3A,
    dRes_ID_LINK_BDL_BINLIQUIDH_e=0x3B,
    dRes_ID_LINK_BDL_BOMB_e=0x3C,
    dRes_ID_LINK_BDL_BOTTLEEMP_e=0x3D,
    dRes_ID_LINK_BDL_CUTFH_e=0x3E,
    dRes_ID_LINK_BDL_CUTFM_e=0x3F,
    dRes_ID_LINK_BDL_GICER00_e=0x40,
    dRes_ID_LINK_BDL_GICER01_e=0x41,
    dRes_ID_LINK_BDL_GWP00_e=0x42,
    dRes_ID_LINK_BDL_SHMS_e=0x43,
    dRes_ID_LINK_BDL_SUIMEN_MUNYA_e=0x44,
    dRes_ID_LINK_BDL_SWGRIPMS_e=0x45,
    dRes_ID_LINK_BDL_SWMS_e=0x46,
    dRes_ID_LINK_BDL_TAKT_e=0x47,
    dRes_ID_LINK_BDL_YAURA00_e=0x48,
    dRes_ID_LINK_BDL_YBAFO00_e=0x49,
    dRes_ID_LINK_BDL_YHSLS00_e=0x4A,
    dRes_ID_LINK_BDL_YMGCS00_e=0x4B,
    dRes_ID_LINK_BDL_YMSLI00_e=0x4C,
    dRes_ID_LINK_BDL_YMSLS00_e=0x4D,
    dRes_ID_LINK_BDL_YUCHW00_e=0x4E,
    /* BRK  */
    dRes_ID_LINK_BRK_BOMB_e=0x51,
    dRes_ID_LINK_BRK_GARWFI00_e=0x52,
    dRes_ID_LINK_BRK_GARWFI01_e=0x53,
    dRes_ID_LINK_BRK_GARWG00_e=0x54,
    dRes_ID_LINK_BRK_GWP00_e=0x55,
    dRes_ID_LINK_BRK_TSWGRIPMSAB_e=0x56,
    dRes_ID_LINK_BRK_YAURA00_G_e=0x57,
    dRes_ID_LINK_BRK_YAURA00_R_e=0x58,
    dRes_ID_LINK_BRK_YMGCS00_MS_e=0x59,
    dRes_ID_LINK_BRK_YMGCS00_TS_e=0x5A,
    dRes_ID_LINK_BRK_YUCHW00_e=0x5B,
    /* BTK  */
    dRes_ID_LINK_BTK_GARWFI00_e=0x5E,
    dRes_ID_LINK_BTK_GARWFI01_e=0x5F,
    dRes_ID_LINK_BTK_GARWG00_e=0x60,
    dRes_ID_LINK_BTK_GICER00_e=0x61,
    dRes_ID_LINK_BTK_GICER01_e=0x62,
    dRes_ID_LINK_BTK_GWP00_e=0x63,
    dRes_ID_LINK_BTK_SUIMEN_MUNYA_e=0x64,
    dRes_ID_LINK_BTK_TARROWGLITTER_e=0x65,
    dRes_ID_LINK_BTK_TSHMS_e=0x66,
    dRes_ID_LINK_BTK_TSWGRIPMS_e=0x67,
    dRes_ID_LINK_BTK_TTIPICE_e=0x68,
    dRes_ID_LINK_BTK_YAURA00_e=0x69,
    dRes_ID_LINK_BTK_YBAFO00_e=0x6A,
    dRes_ID_LINK_BTK_YMGCS00_e=0x6B,
    dRes_ID_LINK_BTK_YMSLS00_e=0x6C,
    dRes_ID_LINK_BTK_YUCHW00_e=0x6D,
    /* TEX  */
    dRes_ID_LINK_BTI_BLUR_e=0x70,
    dRes_ID_LINK_BTI_LINKTEXBCI4_e=0x71,
    dRes_ID_LINK_BTI_ROCK_MARK_e=0x72,
};

enum BINFAIRY_JNT {
    BINFAIRY_JNT_BINFAIRY_e=0x0,
};

enum BOOMERANG_JNT {
    BOOMERANG_JNT_BOOMERANG_e=0x0,
};

enum BOTTLECAP_JNT {
    BOTTLECAP_JNT_BOTTLECAP_e=0x0,
};

enum BOW_JNT {
    BOW_JNT_CL_BOW_e=0x0,
    BOW_JNT_BOW_JNT_e=0x1,
    BOW_JNT_AA_JNT_e=0x2,
    BOW_JNT_AB_JNT_e=0x3,
    BOW_JNT_ACJNT_e=0x4,
    BOW_JNT_LINEAA_JNT_e=0x5,
    BOW_JNT_LINEAB_JNT_e=0x6,
    BOW_JNT_BA_JNT_e=0x7,
    BOW_JNT_BB_JNT_e=0x8,
    BOW_JNT_BC_JNT_e=0x9,
    BOW_JNT_LINEBA_JNT_e=0xA,
    BOW_JNT_LINEBB_JNT_e=0xB,
};

enum CAMERA_JNT {
    CAMERA_JNT_WORLD_ROOT_e=0x0,
    CAMERA_JNT_CAMERA_e=0x1,
    CAMERA_JNT_FRASH_e=0x2,
};

enum CL_JNT {
    CL_JNT_LINK_ROOT_e=0x0,
    CL_JNT_CENTER_e=0x1,
    CL_JNT_BODY_CHN_e=0x2,
    CL_JNT_STOMACH_JNT_e=0x3,
    CL_JNT_CHEST_JNT_e=0x4,
    CL_JNT_LSHOULDER_JNT_e=0x5,
    CL_JNT_LARMA_JNT_e=0x6,
    CL_JNT_LARMB_JNT_e=0x7,
    CL_JNT_CL_LHANDA_e=0x8,
    CL_JNT_RSHOULDER_JNT_e=0x9,
    CL_JNT_RARMA_JNT_e=0xA,
    CL_JNT_RARMB_JNT_e=0xB,
    CL_JNT_CL_RHANDA_e=0xC,
    CL_JNT_CL_PODA_e=0xD,
    CL_JNT_NECK_JNT_e=0xE,
    CL_JNT_HEAD_JNT_e=0xF,
    CL_JNT_LMOMI_JNT_e=0x10,
    CL_JNT_RMOMI_JNT_e=0x11,
    CL_JNT_CHIN_JNT_e=0x12,
    CL_JNT_CL_EYE_e=0x13,
    CL_JNT_CL_HANA_e=0x14,
    CL_JNT_CL_MAYU_e=0x15,
    CL_JNT_HAIR1A_JNT_e=0x16,
    CL_JNT_HAIR1B_JNT_e=0x17,
    CL_JNT_HAIR2A_JNT_e=0x18,
    CL_JNT_HAIR2B_JNT_e=0x19,
    CL_JNT_HATA_JNT_e=0x1A,
    CL_JNT_HATB_JNT_e=0x1B,
    CL_JNT_HATC_JNT_e=0x1C,
    CL_JNT_WAIST_CHN_e=0x1D,
    CL_JNT_WAIST_JNT_e=0x1E,
    CL_JNT_LCLOTCH_JNT_e=0x1F,
    CL_JNT_LLEGA_JNT_e=0x20,
    CL_JNT_LLEGB_JNT_e=0x21,
    CL_JNT_LFOOT_JNT_e=0x22,
    CL_JNT_LTOE_JNT_e=0x23,
    CL_JNT_RCLOTCH_JNT_e=0x24,
    CL_JNT_RLEGA_JNT_e=0x25,
    CL_JNT_RLEGB_JNT_e=0x26,
    CL_JNT_RFOOT_JNT_e=0x27,
    CL_JNT_RTOE_JNT_e=0x28,
    CL_JNT_CL_BACK_e=0x29,
};

enum FAN_JNT {
    FAN_JNT_CL_FAN_e=0x0,
    FAN_JNT_FANROOT_JNT_e=0x1,
    FAN_JNT_FANA_JNT_e=0x2,
    FAN_JNT_FANB_JNT_e=0x3,
    FAN_JNT_FANC_JNT_e=0x4,
    FAN_JNT_FAND_JNT_e=0x5,
    FAN_JNT_FANE_JNT_e=0x6,
};

enum FANB_JNT {
    FANB_JNT_FANB_ROOT_e=0x0,
    FANB_JNT_LROOT_e=0x1,
    FANB_JNT_LARMA_e=0x2,
    FANB_JNT_LARMB_e=0x3,
    FANB_JNT_LARMC_e=0x4,
    FANB_JNT_LARMD_e=0x5,
    FANB_JNT_LARMTOP_e=0x6,
    FANB_JNT_RROOT_e=0x7,
    FANB_JNT_RARMA_e=0x8,
    FANB_JNT_RARMB_e=0x9,
    FANB_JNT_RARMC_e=0xA,
    FANB_JNT_RARMD_e=0xB,
    FANB_JNT_RARMTOP_e=0xC,
};

enum FANSMALL_JNT {
    FANSMALL_JNT_CL_FANSM_e=0x0,
    FANSMALL_JNT_FANSMROOT_JNT_e=0x1,
    FANSMALL_JNT_FANSMA_JNT_e=0x2,
    FANSMALL_JNT_FANSMB_JNT_e=0x3,
};

enum HAMMER_JNT {
    HAMMER_JNT_HAMMER_e=0x0,
    HAMMER_JNT_HAMMER_ROOT_e=0x1,
    HAMMER_JNT_ST_JNTA_e=0x2,
    HAMMER_JNT_ST_JNTB_e=0x3,
    HAMMER_JNT_ST_JNTC_e=0x4,
    HAMMER_JNT_HEAD_JNT_e=0x5,
    HAMMER_JNT_BOTTOM_JNT_e=0x6,
};

enum HANDS_JNT {
    HANDS_JNT_WORLD_ROOT_e=0x0,
    HANDS_JNT_CL_LHANDB_e=0x1,
    HANDS_JNT_CL_LHANDC_e=0x2,
    HANDS_JNT_CL_LHANDD_e=0x3,
    HANDS_JNT_CL_LHANDE_e=0x4,
    HANDS_JNT_CL_LHANDF_e=0x5,
    HANDS_JNT_CL_LHANDG_e=0x6,
    HANDS_JNT_CL_RHANDB_e=0x7,
    HANDS_JNT_CL_RHANDC_e=0x8,
    HANDS_JNT_CL_RHANDD_e=0x9,
    HANDS_JNT_CL_RHANDE_e=0xA,
};

enum HOOKSHOT_JNT {
    HOOKSHOT_JNT_WORLD_ROOT_e=0x0,
    HOOKSHOT_JNT_HOOKSHOT_e=0x1,
    HOOKSHOT_JNT_BODY_JNT_e=0x2,
    HOOKSHOT_JNT_BARREL_JMT_e=0x3,
    HOOKSHOT_JNT_HSHOTTIP_e=0x4,
};

enum HYOINOMI_JNT {
    HYOINOMI_JNT_HYOINOMI_e=0x0,
};

enum KATSURA_JNT {
    KATSURA_JNT_CL_KATSURA_e=0x0,
};

enum LETTER_JNT {
    LETTER_JNT_LETTER_e=0x0,
};

enum PODMS_JNT {
    PODMS_JNT_CL_PODMS_e=0x0,
};

enum PRING_JNT {
    PRING_JNT_WORLD_ROOT_e=0x0,
    PRING_JNT_PRINGL_e=0x1,
    PRING_JNT_PRINGR_e=0x2,
};

enum SHA_JNT {
    SHA_JNT_CL_SHA_e=0x0,
    SHA_JNT_SHAROOT_JNT_e=0x1,
    SHA_JNT_SHA1_JNT_e=0x2,
    SHA_JNT_SHA2_JNT_e=0x3,
    SHA_JNT_SHA3_JNT_e=0x4,
    SHA_JNT_SHA4_JNT_e=0x5,
};

enum SWA_JNT {
    SWA_JNT_CL_SWA_e=0x0,
    SWA_JNT_SWAROOT_JNT_e=0x1,
    SWA_JNT_SWAA_JNT_e=0x2,
    SWA_JNT_SWAB_JNT_e=0x3,
};

enum SWGRIPA_JNT {
    SWGRIPA_JNT_CL_SWGRIPA_e=0x0,
};

enum TCEIVER_JNT {
    TCEIVER_JNT_TCEIVER_e=0x0,
};

enum TETOLACH_JNT {
    TETOLACH_JNT_TETOLACHLOOT_e=0x0,
    TETOLACH_JNT_CH_JNTA_e=0x1,
    TETOLACH_JNT_CH_JNTB_e=0x2,
};

enum YAMU_JNT {
    YAMU_JNT_YAMU_e=0x0,
};

enum ESA_JNT {
    ESA_JNT_ESA_e=0x0,
};

enum HBOOTS_JNT {
    HBOOTS_JNT_WORLD_ROOT_e=0x0,
    HBOOTS_JNT_CL_HBOOTSA_e=0x1,
    HBOOTS_JNT_CL_HBOOTSB_e=0x2,
    HBOOTS_JNT_CL_HBOOTSC_e=0x3,
};

enum ROPEEND_JNT {
    ROPEEND_JNT_ROPEEND_e=0x0,
};

enum TELESCOPE_JNT {
    TELESCOPE_JNT_TELESCOPE_e=0x0,
};

enum GARWFI00_JNT {
    GARWFI00_JNT_ROOT_FI_e=0x0,
    GARWFI00_JNT_OMOTE1_e=0x1,
    GARWFI00_JNT_OMOTE2_e=0x2,
    GARWFI00_JNT_URA1_e=0x3,
    GARWFI00_JNT_URA2_e=0x4,
};

enum GARWFI01_JNT {
    GARWFI01_JNT_ROOT_FI_e=0x0,
    GARWFI01_JNT_OMOTE1_e=0x1,
    GARWFI01_JNT_OMOTE2_e=0x2,
    GARWFI01_JNT_URA1_e=0x3,
    GARWFI01_JNT_URA2_e=0x4,
};

enum GARWG00_JNT {
    GARWG00_JNT_ROOT_G_e=0x0,
    GARWG00_JNT_OMOTE1_e=0x1,
    GARWG00_JNT_OMOTE2_e=0x2,
    GARWG00_JNT_URA1_e=0x3,
    GARWG00_JNT_URA2_e=0x4,
};

enum ARROW_JNT {
    ARROW_JNT_WORLD_ROOT_e=0x0,
    ARROW_JNT_ARROW_e=0x1,
    ARROW_JNT_TIPFIRE_e=0x2,
    ARROW_JNT_TIPICE_e=0x3,
    ARROW_JNT_TIPNOMAL_e=0x4,
};

enum ARROWGLITTER_JNT {
    ARROWGLITTER_JNT_ARROWGLITTER_e=0x0,
};

enum BINHO_JNT {
    BINHO_JNT_NANAHO_e=0x0,
};

enum BINLIQUID_JNT {
    BINLIQUID_JNT_BINLIQUID_e=0x0,
};

enum BINLIQUIDH_JNT {
    BINLIQUIDH_JNT_BINLIQUIDH_e=0x0,
};

enum BOMB_JNT {
    BOMB_JNT_VBOMB_MODEL_e=0x0,
    BOMB_JNT_VBOMB_UP_e=0x1,
};

enum BOTTLEEMP_JNT {
    BOTTLEEMP_JNT_BOTTLE_e=0x0,
};

enum CUTFH_JNT {
    CUTFH_JNT_CUTF_HSWORD_e=0x0,
};

enum CUTFM_JNT {
    CUTFM_JNT_CUTF_MSWORD_e=0x0,
};

enum GICER00_JNT {
    GICER00_JNT_ROOT_e=0x0,
    GICER00_JNT_GICER00_e=0x1,
};

enum GICER01_JNT {
    GICER01_JNT_ROOT_e=0x0,
    GICER01_JNT_A_e=0x1,
    GICER01_JNT_LOCATOR2_e=0x2,
    GICER01_JNT_L_e=0x3,
    GICER01_JNT_M_e=0x4,
    GICER01_JNT_S_e=0x5,
    GICER01_JNT_LOCATOR3_e=0x6,
    GICER01_JNT_L_1_e=0x7,
    GICER01_JNT_M_1_e=0x8,
    GICER01_JNT_S_1_e=0x9,
    GICER01_JNT_LOCATOR4_e=0xA,
    GICER01_JNT_L_2_e=0xB,
    GICER01_JNT_M_2_e=0xC,
    GICER01_JNT_S_2_e=0xD,
    GICER01_JNT_B_e=0xE,
    GICER01_JNT_LOCATOR2_1_e=0xF,
    GICER01_JNT_L_3_e=0x10,
    GICER01_JNT_M_3_e=0x11,
    GICER01_JNT_S_3_e=0x12,
    GICER01_JNT_LOCATOR3_1_e=0x13,
    GICER01_JNT_L_4_e=0x14,
    GICER01_JNT_M_4_e=0x15,
    GICER01_JNT_S_4_e=0x16,
    GICER01_JNT_LOCATOR4_1_e=0x17,
    GICER01_JNT_L_5_e=0x18,
    GICER01_JNT_M_5_e=0x19,
    GICER01_JNT_S_5_e=0x1A,
};

enum GWP00_JNT {
    GWP00_JNT_ROOT_e=0x0,
    GWP00_JNT_SOTOGAWA_e=0x1,
    GWP00_JNT_UCHIGAWA_e=0x2,
};

enum SHMS_JNT {
    SHMS_JNT_CL_SHA_e=0x0,
    SHMS_JNT_SHAROOT_JNT_e=0x1,
    SHMS_JNT_SHA1_JNT_e=0x2,
    SHMS_JNT_SHA2_JNT_e=0x3,
    SHMS_JNT_SHA3_JNT_e=0x4,
    SHMS_JNT_SHA4_JNT_e=0x5,
};

enum SUIMEN_MUNYA_JNT {
    SUIMEN_MUNYA_JNT_PPLANE2_e=0x0,
};

enum SWGRIPMS_JNT {
    SWGRIPMS_JNT_CL_SWGRIPMS_e=0x0,
    SWGRIPMS_JNT_SWGRIPMS_e=0x1,
    SWGRIPMS_JNT_LWING_JNT_e=0x2,
    SWGRIPMS_JNT_RWING_JNT_e=0x3,
};

enum SWMS_JNT {
    SWMS_JNT_CL_SWMS_e=0x0,
    SWMS_JNT_SWMSROOT_JNT_e=0x1,
    SWMS_JNT_SWMSA_JNT_e=0x2,
    SWMS_JNT_SWMSB_JNT_e=0x3,
    SWMS_JNT_SWMSC_JNT_e=0x4,
};

enum TAKT_JNT {
    TAKT_JNT_TAKT_e=0x0,
};

enum YAURA00_JNT {
    YAURA00_JNT_AURA_e=0x0,
};

enum YBAFO00_JNT {
    YBAFO00_JNT_YBAFO00_e=0x0,
    YBAFO00_JNT_A00_e=0x1,
    YBAFO00_JNT_INNER_e=0x2,
    YBAFO00_JNT_OUTER_e=0x3,
};

enum YHSLS00_JNT {
    YHSLS00_JNT_CL_SWA_e=0x0,
    YHSLS00_JNT_SWAROOT_JNT_e=0x1,
    YHSLS00_JNT_SWAA_JNT_e=0x2,
    YHSLS00_JNT_SWAB_JNT_e=0x3,
};

enum YMGCS00_JNT {
    YMGCS00_JNT_LINK_ROOT_e=0x0,
    YMGCS00_JNT_CENTER_e=0x1,
    YMGCS00_JNT_BODY_CHN_e=0x2,
    YMGCS00_JNT_STOMACH_JNT_e=0x3,
    YMGCS00_JNT_CHEST_JNT_e=0x4,
    YMGCS00_JNT_LSHOULDER_JNT_e=0x5,
    YMGCS00_JNT_LARMA_JNT_e=0x6,
    YMGCS00_JNT_LARMB_JNT_e=0x7,
    YMGCS00_JNT_CL_LHANDA_e=0x8,
    YMGCS00_JNT_RSHOULDER_JNT_e=0x9,
    YMGCS00_JNT_RARMA_JNT_e=0xA,
    YMGCS00_JNT_RARMB_JNT_e=0xB,
    YMGCS00_JNT_CL_RHANDA_e=0xC,
    YMGCS00_JNT_CL_PODA_e=0xD,
    YMGCS00_JNT_NECK_JNT_e=0xE,
    YMGCS00_JNT_HEAD_JNT_e=0xF,
    YMGCS00_JNT_LMOMI_JNT_e=0x10,
    YMGCS00_JNT_RMOMI_JNT_e=0x11,
    YMGCS00_JNT_CHIN_JNT_e=0x12,
    YMGCS00_JNT_CL_EYE_e=0x13,
    YMGCS00_JNT_CL_HANA_e=0x14,
    YMGCS00_JNT_CL_MAYU_e=0x15,
    YMGCS00_JNT_HAIR1A_JNT_e=0x16,
    YMGCS00_JNT_HAIR1B_JNT_e=0x17,
    YMGCS00_JNT_HAIR2A_JNT_e=0x18,
    YMGCS00_JNT_HAIR2B_JNT_e=0x19,
    YMGCS00_JNT_HATA_JNT_e=0x1A,
    YMGCS00_JNT_HATB_JNT_e=0x1B,
    YMGCS00_JNT_HATC_JNT_e=0x1C,
    YMGCS00_JNT_WAIST_CHN_e=0x1D,
    YMGCS00_JNT_WAIST_JNT_e=0x1E,
    YMGCS00_JNT_LCLOTCH_JNT_e=0x1F,
    YMGCS00_JNT_LLEGA_JNT_e=0x20,
    YMGCS00_JNT_LLEGB_JNT_e=0x21,
    YMGCS00_JNT_LFOOT_JNT_e=0x22,
    YMGCS00_JNT_LTOE_JNT_e=0x23,
    YMGCS00_JNT_RCLOTCH_JNT_e=0x24,
    YMGCS00_JNT_RLEGA_JNT_e=0x25,
    YMGCS00_JNT_RLEGB_JNT_e=0x26,
    YMGCS00_JNT_RFOOT_JNT_e=0x27,
    YMGCS00_JNT_RTOE_JNT_e=0x28,
    YMGCS00_JNT_CL_BACK_e=0x29,
};

enum YMSLI00_JNT {
    YMSLI00_JNT_CL_SWMS_e=0x0,
    YMSLI00_JNT_SWMSROOT_JNT_e=0x1,
    YMSLI00_JNT_SWMSA_JNT_e=0x2,
    YMSLI00_JNT_SWMSB_JNT_e=0x3,
    YMSLI00_JNT_SWMSC_JNT_e=0x4,
};

enum YMSLS00_JNT {
    YMSLS00_JNT_SHMSPILLAR_e=0x0,
};

enum YUCHW00_JNT {
    YUCHW00_JNT_YSTRM00_e=0x0,
    YUCHW00_JNT_A00_e=0x1,
    YUCHW00_JNT_LWIND_e=0x2,
    YUCHW00_JNT_SWIND_e=0x3,
};

#endif /* !RES_LINK_H */