#ifndef RES_MT_H
#define RES_MT_H

enum dRes_INDEX_MT {
    /* BCK  */
    dRes_INDEX_MT_BCK_ATTACK_e=0x7,
    dRes_INDEX_MT_BCK_SUKI_e=0x8,
    dRes_INDEX_MT_BCK_TUKKOMI_e=0x9,
    dRes_INDEX_MT_BCK_WAIT1_e=0xA,
    /* BDLM */
    dRes_INDEX_MT_BDL_KBA_e=0xD,
    dRes_INDEX_MT_BDL_KBB_e=0xE,
    dRes_INDEX_MT_BDL_KBC_e=0xF,
    dRes_INDEX_MT_BDL_KBD_e=0x10,
    dRes_INDEX_MT_BDL_KBE_e=0x11,
    dRes_INDEX_MT_BDL_MAGT_F_e=0x12,
    dRes_INDEX_MT_BDL_MG_BODY_e=0x13,
    dRes_INDEX_MT_BDL_MG_HEAD_e=0x14,
    dRes_INDEX_MT_BDL_MG_TAIL_e=0x15,
    /* BRK  */
    dRes_INDEX_MT_BRK_FUKKATU_B_e=0x18,
    dRes_INDEX_MT_BTK_FUKKATU_B_e=0x19,
    dRes_INDEX_MT_BRK_FUKKATU_H_e=0x1A,
    dRes_INDEX_MT_BTK_FUKKATU_H_e=0x1B,
    dRes_INDEX_MT_BRK_FUKKATU_T_e=0x1C,
    dRes_INDEX_MT_BTK_FUKKATU_T_e=0x1D,
    dRes_INDEX_MT_BRK_MAGT_F_e=0x1E,
    dRes_INDEX_MT_BRK_MG_BODY_e=0x1F,
    dRes_INDEX_MT_BRK_MG_BODY1_e=0x20,
    dRes_INDEX_MT_BRK_MG_HEAD_e=0x21,
    dRes_INDEX_MT_BRK_MG_HEAD1_e=0x22,
    dRes_INDEX_MT_BRK_MG_TAIL_e=0x23,
    dRes_INDEX_MT_BRK_MG_TAIL1_e=0x24,
    dRes_INDEX_MT_BRK_SYOUKA_B_e=0x25,
    dRes_INDEX_MT_BRK_SYOUKA_H_e=0x26,
    dRes_INDEX_MT_BRK_SYOUKA_T_e=0x27,
    /* BTK  */
    dRes_INDEX_MT_BTK_MAGT_F_e=0x2A,
    dRes_INDEX_MT_BTK_MG_BODY_e=0x2B,
    dRes_INDEX_MT_BTK_MG_BODY1_e=0x2C,
    dRes_INDEX_MT_BTK_MG_HEAD_e=0x2D,
    dRes_INDEX_MT_BTK_MG_HEAD1_e=0x2E,
    dRes_INDEX_MT_BTK_MG_TAIL_e=0x2F,
    dRes_INDEX_MT_BTK_MG_TAIL1_e=0x30,
    dRes_INDEX_MT_BTK_SYOUKA_B_e=0x31,
    dRes_INDEX_MT_BTK_SYOUKA_H_e=0x32,
    dRes_INDEX_MT_BTK_SYOUKA_T_e=0x33,
    /* BTP  */
    dRes_INDEX_MT_BTP_MG_MABA_e=0x36,
    dRes_INDEX_MT_BTP_MG_TOJI_e=0x37,
};

enum dRes_ID_MT {
    /* BCK  */
    dRes_ID_MT_BCK_ATTACK_e=0x7,
    dRes_ID_MT_BCK_SUKI_e=0x8,
    dRes_ID_MT_BCK_TUKKOMI_e=0x9,
    dRes_ID_MT_BCK_WAIT1_e=0xA,
    /* BDLM */
    dRes_ID_MT_BDL_KBA_e=0xD,
    dRes_ID_MT_BDL_KBB_e=0xE,
    dRes_ID_MT_BDL_KBC_e=0xF,
    dRes_ID_MT_BDL_KBD_e=0x10,
    dRes_ID_MT_BDL_KBE_e=0x11,
    dRes_ID_MT_BDL_MAGT_F_e=0x12,
    dRes_ID_MT_BDL_MG_BODY_e=0x13,
    dRes_ID_MT_BDL_MG_HEAD_e=0x14,
    dRes_ID_MT_BDL_MG_TAIL_e=0x15,
    /* BRK  */
    dRes_ID_MT_BRK_FUKKATU_B_e=0x18,
    dRes_ID_MT_BTK_FUKKATU_B_e=0x19,
    dRes_ID_MT_BRK_FUKKATU_H_e=0x1A,
    dRes_ID_MT_BTK_FUKKATU_H_e=0x1B,
    dRes_ID_MT_BRK_FUKKATU_T_e=0x1C,
    dRes_ID_MT_BTK_FUKKATU_T_e=0x1D,
    dRes_ID_MT_BRK_MAGT_F_e=0x1E,
    dRes_ID_MT_BRK_MG_BODY_e=0x1F,
    dRes_ID_MT_BRK_MG_BODY1_e=0x20,
    dRes_ID_MT_BRK_MG_HEAD_e=0x21,
    dRes_ID_MT_BRK_MG_HEAD1_e=0x22,
    dRes_ID_MT_BRK_MG_TAIL_e=0x23,
    dRes_ID_MT_BRK_MG_TAIL1_e=0x24,
    dRes_ID_MT_BRK_SYOUKA_B_e=0x25,
    dRes_ID_MT_BRK_SYOUKA_H_e=0x26,
    dRes_ID_MT_BRK_SYOUKA_T_e=0x27,
    /* BTK  */
    dRes_ID_MT_BTK_MAGT_F_e=0x2A,
    dRes_ID_MT_BTK_MG_BODY_e=0x2B,
    dRes_ID_MT_BTK_MG_BODY1_e=0x2C,
    dRes_ID_MT_BTK_MG_HEAD_e=0x2D,
    dRes_ID_MT_BTK_MG_HEAD1_e=0x2E,
    dRes_ID_MT_BTK_MG_TAIL_e=0x2F,
    dRes_ID_MT_BTK_MG_TAIL1_e=0x30,
    dRes_ID_MT_BTK_SYOUKA_B_e=0x31,
    dRes_ID_MT_BTK_SYOUKA_H_e=0x32,
    dRes_ID_MT_BTK_SYOUKA_T_e=0x33,
    /* BTP  */
    dRes_ID_MT_BTP_MG_MABA_e=0x36,
    dRes_ID_MT_BTP_MG_TOJI_e=0x37,
};

enum KBA_JNT {
    KBA_JNT_BLURA_e=0x0,
};

enum KBB_JNT {
    KBB_JNT_BLURB_e=0x0,
};

enum KBC_JNT {
    KBC_JNT_BLURC_e=0x0,
};

enum KBD_JNT {
    KBD_JNT_BLURD_e=0x0,
};

enum KBE_JNT {
    KBE_JNT_BLURE_e=0x0,
};

enum MAGT_F_JNT {
    MAGT_F_JNT_PPLANE1_e=0x0,
};

enum MG_BODY_JNT {
    MG_BODY_JNT_MG_BODY_ALLROOT_e=0x0,
    MG_BODY_JNT_J_MG_BODY_MAIN1_e=0x1,
    MG_BODY_JNT_J_MG_BODY_ASHI_LA1_e=0x2,
    MG_BODY_JNT_J_MG_BODY_ASHI_LB1_e=0x3,
    MG_BODY_JNT_J_MG_BODY_ASHI_RA1_e=0x4,
    MG_BODY_JNT_J_MG_BODY_ASHI_RB1_e=0x5,
};

enum MG_HEAD_JNT {
    MG_HEAD_JNT_MG_HEAD_ALLROOT_e=0x0,
    MG_HEAD_JNT_J_MG_HEAD_MAIN1_e=0x1,
    MG_HEAD_JNT_J_MG_HEAD_ASHI_L1_e=0x2,
    MG_HEAD_JNT_J_MG_HEAD_ASHI_R1_e=0x3,
    MG_HEAD_JNT_J_MG_HEAD_HASAMI_L1_e=0x4,
    MG_HEAD_JNT_J_MG_HEAD_HASAMI_R1_e=0x5,
};

enum MG_TAIL_JNT {
    MG_TAIL_JNT_MG_TAIL_ALLROOT_e=0x0,
    MG_TAIL_JNT_J_MG_TAIL_MAIN1_e=0x1,
    MG_TAIL_JNT_J_MG_TAIL_ASHI_LA1_e=0x2,
    MG_TAIL_JNT_J_MG_TAIL_ASHI_LB1_e=0x3,
    MG_TAIL_JNT_J_MG_TAIL_ASHI_RA1_e=0x4,
    MG_TAIL_JNT_J_MG_TAIL_ASHI_RB1_e=0x5,
};

#endif /* !RES_MT_H */