#ifndef RES_TOUSEKI_H
#define RES_TOUSEKI_H

enum dRes_INDEX_TOUSEKI {
    /* BCK  */
    dRes_INDEX_TOUSEKI_BCK_ATOSK_MAKI_e=0x4,
    dRes_INDEX_TOUSEKI_BCK_ATOSK_NAGE_e=0x5,
    /* BDL  */
    dRes_INDEX_TOUSEKI_BDL_ATOSK_A_e=0x8,
};

enum dRes_ID_TOUSEKI {
    /* BCK  */
    dRes_ID_TOUSEKI_BCK_ATOSK_MAKI_e=0x0,
    dRes_ID_TOUSEKI_BCK_ATOSK_NAGE_e=0x1,
    /* BDL  */
    dRes_ID_TOUSEKI_BDL_ATOSK_A_e=0x3,
};

enum ATOSK_A_JNT {
    ATOSK_A_JNT_ATOSK_e=0x0,
    ATOSK_A_JNT_ATOSK_1_e=0x1,
    ATOSK_A_JNT_J1_HONTAI_e=0x2,
    ATOSK_A_JNT_J2_UDE_e=0x3,
    ATOSK_A_JNT_JOINT4_e=0x4,
    ATOSK_A_JNT_J3_HANDLE_e=0x5,
    ATOSK_A_JNT_JOINT6_e=0x6,
    ATOSK_A_JNT_JOINT2_e=0x7,
};

#endif /* !RES_TOUSEKI_H */