#ifndef RES_YAKEROM_H
#define RES_YAKEROM_H

enum dRes_INDEX_YAKEROM {
    /* BDL  */
    dRes_INDEX_YAKEROM_BDL_YAKEROM_e=0x4,
    /* DZB  */
    dRes_INDEX_YAKEROM_DZB_YAKEROM_e=0x7,
};

enum dRes_ID_YAKEROM {
    /* BDL  */
    dRes_ID_YAKEROM_BDL_YAKEROM_e=0x4,
    /* DZB  */
    dRes_ID_YAKEROM_DZB_YAKEROM_e=0x7,
};

enum YAKEROM_JNT {
    YAKEROM_JNT_YAKEROM_e=0x0,
    YAKEROM_JNT_YAKE_ROOM_e=0x1,
    YAKEROM_JNT_POLYSURFACE865_e=0x2,
    YAKEROM_JNT_POLYSURFACE866_e=0x3,
};

#endif /* !RES_YAKEROM_H */