#ifndef RES_ALWAYS_H
#define RES_ALWAYS_H

enum dRes_INDEX_ALWAYS {
    /* BCK  */
    dRes_INDEX_ALWAYS_BCK_FA_e=0xC,
    dRes_INDEX_ALWAYS_BCK_OBM_SYOUGEKISW_e=0xD,
    dRes_INDEX_ALWAYS_BCK_START_e=0xE,
    dRes_INDEX_ALWAYS_BCK_VBELL_e=0xF,
    dRes_INDEX_ALWAYS_BCK_VBOKL_e=0x10,
    dRes_INDEX_ALWAYS_BCK_VCHUL_e=0x11,
    dRes_INDEX_ALWAYS_BCK_VDOKL_e=0x12,
    dRes_INDEX_ALWAYS_BCK_VESAL_e=0x13,
    dRes_INDEX_ALWAYS_BCK_VHANL_e=0x14,
    dRes_INDEX_ALWAYS_BCK_VHAPL_e=0x15,
    dRes_INDEX_ALWAYS_BCK_W_PILLAR_A_e=0x16,
    dRes_INDEX_ALWAYS_BCK_YJ_DELETE_e=0x17,
    dRes_INDEX_ALWAYS_BCK_YJ_IN_e=0x18,
    dRes_INDEX_ALWAYS_BCK_YJ_LOOP_e=0x19,
    dRes_INDEX_ALWAYS_BCK_YJ_OUT_e=0x1A,
    dRes_INDEX_ALWAYS_BCK_YJ_SCALE_e=0x1B,
    /* BDL  */
    dRes_INDEX_ALWAYS_BDL_ARROWITEM_e=0x1E,
    dRes_INDEX_ALWAYS_BDL_FA_e=0x1F,
    dRes_INDEX_ALWAYS_BDL_KROCK_00_e=0x20,
    dRes_INDEX_ALWAYS_BDL_OBM_KOISI1_e=0x21,
    dRes_INDEX_ALWAYS_BDL_OBM_KOISI2_e=0x22,
    dRes_INDEX_ALWAYS_BDL_OBM_KOTUBO1_e=0x23,
    dRes_INDEX_ALWAYS_BDL_OBM_OOTUBO1_e=0x24,
    dRes_INDEX_ALWAYS_BDL_VBELL_e=0x25,
    dRes_INDEX_ALWAYS_BDL_VBOKL_e=0x26,
    dRes_INDEX_ALWAYS_BDL_VDOKL_e=0x27,
    dRes_INDEX_ALWAYS_BDL_VESAL_e=0x28,
    dRes_INDEX_ALWAYS_BDL_VHAPL_e=0x29,
    dRes_INDEX_ALWAYS_BDL_VHRTL_e=0x2A,
    dRes_INDEX_ALWAYS_BDL_VKEYL_e=0x2B,
    /* BDLM */
    dRes_INDEX_ALWAYS_BDL_IB_e=0x2E,
    dRes_INDEX_ALWAYS_BDL_MPA_SIMI_e=0x2F,
    dRes_INDEX_ALWAYS_BDL_MPI_KOISHI_e=0x30,
    dRes_INDEX_ALWAYS_BDL_MPM_TUBO_e=0x31,
    dRes_INDEX_ALWAYS_BDL_MPODA_e=0x32,
    dRes_INDEX_ALWAYS_BDL_MPODB_e=0x33,
    dRes_INDEX_ALWAYS_BDL_NH_e=0x34,
    dRes_INDEX_ALWAYS_BDL_OBM_SYOUGEKISW_e=0x35,
    dRes_INDEX_ALWAYS_BDL_VCHUL_e=0x36,
    dRes_INDEX_ALWAYS_BDL_VHANL_e=0x37,
    dRes_INDEX_ALWAYS_BDL_VHKAL_e=0x38,
    dRes_INDEX_ALWAYS_BDL_VHUTL_e=0x39,
    dRes_INDEX_ALWAYS_BDL_VLUPL_e=0x3A,
    dRes_INDEX_ALWAYS_BDL_W_PILLAR_A_e=0x3B,
    dRes_INDEX_ALWAYS_BDL_YA_e=0x3C,
    dRes_INDEX_ALWAYS_BDL_YAZIRUSHI_01_e=0x3D,
    dRes_INDEX_ALWAYS_BDL_YTHDR00_e=0x3E,
    /* BMTM */
    dRes_INDEX_ALWAYS_BMT_ICE_e=0x41,
    /* BPK  */
    dRes_INDEX_ALWAYS_BPK_YJ_DELETE_e=0x44,
    dRes_INDEX_ALWAYS_BPK_YJ_IN_e=0x45,
    dRes_INDEX_ALWAYS_BPK_YJ_LOOP_e=0x46,
    dRes_INDEX_ALWAYS_BPK_YJ_OUT_e=0x47,
    dRes_INDEX_ALWAYS_BPK_YJ_SCALE_e=0x48,
    /* BRK  */
    dRes_INDEX_ALWAYS_BRK_IB_01_e=0x4B,
    dRes_INDEX_ALWAYS_BRK_IB_02_e=0x4C,
    dRes_INDEX_ALWAYS_BRK_MPA_SIMI_e=0x4D,
    dRes_INDEX_ALWAYS_BRK_TNH_e=0x4E,
    dRes_INDEX_ALWAYS_BRK_VCHUL_e=0x4F,
    dRes_INDEX_ALWAYS_BRK_VHANL_e=0x50,
    dRes_INDEX_ALWAYS_BRK_VLUPL_e=0x51,
    dRes_INDEX_ALWAYS_BRK_YTHDR00_e=0x52,
    /* BTK  */
    dRes_INDEX_ALWAYS_BTK_EFA_USONAMI_01_e=0x55,
    dRes_INDEX_ALWAYS_BTK_IB_e=0x56,
    dRes_INDEX_ALWAYS_BTK_ICE_e=0x57,
    dRes_INDEX_ALWAYS_BTK_OBM_SYOUGEKISW_e=0x58,
    dRes_INDEX_ALWAYS_BTK_VBELL_e=0x59,
    dRes_INDEX_ALWAYS_BTK_VHANL_e=0x5A,
    dRes_INDEX_ALWAYS_BTK_VHKAL_e=0x5B,
    dRes_INDEX_ALWAYS_BTK_VHUTL_e=0x5C,
    dRes_INDEX_ALWAYS_BTK_VLUPL_e=0x5D,
    dRes_INDEX_ALWAYS_BTK_W_PILLAR_A_e=0x5E,
    dRes_INDEX_ALWAYS_BTK_YA_e=0x5F,
    dRes_INDEX_ALWAYS_BTK_YTHDR00_e=0x60,
    /* BTP  */
    dRes_INDEX_ALWAYS_BTP_MPA_SIMI_e=0x63,
    dRes_INDEX_ALWAYS_BTP_MPI_KIBAKO_TARU_e=0x64,
    dRes_INDEX_ALWAYS_BTP_MPI_KINOHAHEN_e=0x65,
    dRes_INDEX_ALWAYS_BTP_MPI_KOISHI_e=0x66,
    dRes_INDEX_ALWAYS_BTP_MPM_TUBO_e=0x67,
    /* DAT  */
    dRes_INDEX_ALWAYS_BIN_ITEM_TABLE_e=0x6A,
    /* TEX  */
    dRes_INDEX_ALWAYS_BTI_AK_HOUSHI00_e=0x6D,
    dRes_INDEX_ALWAYS_BTI_AK_SMOKE01_e=0x6E,
    dRes_INDEX_ALWAYS_BTI_B_SEA_TEX0AND2_e=0x6F,
    dRes_INDEX_ALWAYS_BTI_B_WYURAYURA_TEX1_e=0x70,
    dRes_INDEX_ALWAYS_I4_BALL128B_e=0x71,
    dRes_INDEX_ALWAYS_BTI_BLACK_WHITE_2_e=0x72,
    dRes_INDEX_ALWAYS_BTI_CAMERA_FREE_e=0x73,
    dRes_INDEX_ALWAYS_BTI_CAMERA_SELF_e=0x74,
    dRes_INDEX_ALWAYS_BTI_F_SHIPICON_e=0x75,
    dRes_INDEX_ALWAYS_CI4_MAP08G_e=0x76,
    dRes_INDEX_ALWAYS_CI4_MAP16G_e=0x77,
    dRes_INDEX_ALWAYS_BTI_MAP_BLACK_CI8_e=0x78,
    dRes_INDEX_ALWAYS_BTI_MAP_CHECK16_CI4_e=0x79,
    dRes_INDEX_ALWAYS_BTI_MAP_FRAME1_e=0x7A,
    dRes_INDEX_ALWAYS_BTI_MAP_FRAME2_e=0x7B,
    dRes_INDEX_ALWAYS_BTI_MAP_FRAME3_e=0x7C,
    dRes_INDEX_ALWAYS_BTI_MAP_FRAME4_e=0x7D,
    dRes_INDEX_ALWAYS_BTI_ROPE_e=0x7E,
    dRes_INDEX_ALWAYS_BTI_SHMREF_e=0x7F,
    dRes_INDEX_ALWAYS_BTI_TREASUREBOX_e=0x80,
    dRes_INDEX_ALWAYS_I8_TX_SNOW01_e=0x81,
    dRes_INDEX_ALWAYS_BTI_TXA_LENS_32HALF_e=0x82,
    dRes_INDEX_ALWAYS_BTI_TXA_MOYA_A_64_e=0x83,
    dRes_INDEX_ALWAYS_BTI_TXA_MOYA_B_64_e=0x84,
    dRes_INDEX_ALWAYS_BTI_TXA_RING_A_32HAFE_e=0x85,
    dRes_INDEX_ALWAYS_BTI_TXA_TAIYO_e=0x86,
    dRes_INDEX_ALWAYS_BTI_TXA_TUKI_AS_e=0x87,
    dRes_INDEX_ALWAYS_BTI_TXA_TUKI_BS_e=0x88,
    dRes_INDEX_ALWAYS_BTI_TXA_TUKI_CS_e=0x89,
    dRes_INDEX_ALWAYS_BTI_TXA_TUKI_DS_e=0x8A,
    dRes_INDEX_ALWAYS_BTI_TXA_USONAMI_256_64MIP_e=0x8B,
    dRes_INDEX_ALWAYS_BTI_TXA_USONAMI_M_256_64MIP_e=0x8C,
    dRes_INDEX_ALWAYS_BTI_TXM_ROPE1_e=0x8D,
    dRes_INDEX_ALWAYS_BTI_UMIPT_e=0x8E,
};

enum dRes_ID_ALWAYS {
    /* BCK  */
    dRes_ID_ALWAYS_BCK_FA_e=0xC,
    dRes_ID_ALWAYS_BCK_OBM_SYOUGEKISW_e=0xD,
    dRes_ID_ALWAYS_BCK_START_e=0xE,
    dRes_ID_ALWAYS_BCK_VBELL_e=0xF,
    dRes_ID_ALWAYS_BCK_VBOKL_e=0x10,
    dRes_ID_ALWAYS_BCK_VCHUL_e=0x11,
    dRes_ID_ALWAYS_BCK_VDOKL_e=0x12,
    dRes_ID_ALWAYS_BCK_VESAL_e=0x13,
    dRes_ID_ALWAYS_BCK_VHANL_e=0x14,
    dRes_ID_ALWAYS_BCK_VHAPL_e=0x15,
    dRes_ID_ALWAYS_BCK_W_PILLAR_A_e=0x16,
    dRes_ID_ALWAYS_BCK_YJ_DELETE_e=0x17,
    dRes_ID_ALWAYS_BCK_YJ_IN_e=0x18,
    dRes_ID_ALWAYS_BCK_YJ_LOOP_e=0x19,
    dRes_ID_ALWAYS_BCK_YJ_OUT_e=0x1A,
    dRes_ID_ALWAYS_BCK_YJ_SCALE_e=0x1B,
    /* BDL  */
    dRes_ID_ALWAYS_BDL_ARROWITEM_e=0x1E,
    dRes_ID_ALWAYS_BDL_FA_e=0x1F,
    dRes_ID_ALWAYS_BDL_KROCK_00_e=0x20,
    dRes_ID_ALWAYS_BDL_OBM_KOISI1_e=0x21,
    dRes_ID_ALWAYS_BDL_OBM_KOISI2_e=0x22,
    dRes_ID_ALWAYS_BDL_OBM_KOTUBO1_e=0x23,
    dRes_ID_ALWAYS_BDL_OBM_OOTUBO1_e=0x24,
    dRes_ID_ALWAYS_BDL_VBELL_e=0x25,
    dRes_ID_ALWAYS_BDL_VBOKL_e=0x26,
    dRes_ID_ALWAYS_BDL_VDOKL_e=0x27,
    dRes_ID_ALWAYS_BDL_VESAL_e=0x28,
    dRes_ID_ALWAYS_BDL_VHAPL_e=0x29,
    dRes_ID_ALWAYS_BDL_VHRTL_e=0x2A,
    dRes_ID_ALWAYS_BDL_VKEYL_e=0x2B,
    /* BDLM */
    dRes_ID_ALWAYS_BDL_IB_e=0x2E,
    dRes_ID_ALWAYS_BDL_MPA_SIMI_e=0x2F,
    dRes_ID_ALWAYS_BDL_MPI_KOISHI_e=0x30,
    dRes_ID_ALWAYS_BDL_MPM_TUBO_e=0x31,
    dRes_ID_ALWAYS_BDL_MPODA_e=0x32,
    dRes_ID_ALWAYS_BDL_MPODB_e=0x33,
    dRes_ID_ALWAYS_BDL_NH_e=0x34,
    dRes_ID_ALWAYS_BDL_OBM_SYOUGEKISW_e=0x35,
    dRes_ID_ALWAYS_BDL_VCHUL_e=0x36,
    dRes_ID_ALWAYS_BDL_VHANL_e=0x37,
    dRes_ID_ALWAYS_BDL_VHKAL_e=0x38,
    dRes_ID_ALWAYS_BDL_VHUTL_e=0x39,
    dRes_ID_ALWAYS_BDL_VLUPL_e=0x3A,
    dRes_ID_ALWAYS_BDL_W_PILLAR_A_e=0x3B,
    dRes_ID_ALWAYS_BDL_YA_e=0x3C,
    dRes_ID_ALWAYS_BDL_YAZIRUSHI_01_e=0x3D,
    dRes_ID_ALWAYS_BDL_YTHDR00_e=0x3E,
    /* BMTM */
    dRes_ID_ALWAYS_BMT_ICE_e=0x41,
    /* BPK  */
    dRes_ID_ALWAYS_BPK_YJ_DELETE_e=0x44,
    dRes_ID_ALWAYS_BPK_YJ_IN_e=0x45,
    dRes_ID_ALWAYS_BPK_YJ_LOOP_e=0x46,
    dRes_ID_ALWAYS_BPK_YJ_OUT_e=0x47,
    dRes_ID_ALWAYS_BPK_YJ_SCALE_e=0x48,
    /* BRK  */
    dRes_ID_ALWAYS_BRK_IB_01_e=0x4B,
    dRes_ID_ALWAYS_BRK_IB_02_e=0x4C,
    dRes_ID_ALWAYS_BRK_MPA_SIMI_e=0x4D,
    dRes_ID_ALWAYS_BRK_TNH_e=0x4E,
    dRes_ID_ALWAYS_BRK_VCHUL_e=0x4F,
    dRes_ID_ALWAYS_BRK_VHANL_e=0x50,
    dRes_ID_ALWAYS_BRK_VLUPL_e=0x51,
    dRes_ID_ALWAYS_BRK_YTHDR00_e=0x52,
    /* BTK  */
    dRes_ID_ALWAYS_BTK_EFA_USONAMI_01_e=0x55,
    dRes_ID_ALWAYS_BTK_IB_e=0x56,
    dRes_ID_ALWAYS_BTK_ICE_e=0x57,
    dRes_ID_ALWAYS_BTK_OBM_SYOUGEKISW_e=0x58,
    dRes_ID_ALWAYS_BTK_VBELL_e=0x59,
    dRes_ID_ALWAYS_BTK_VHANL_e=0x5A,
    dRes_ID_ALWAYS_BTK_VHKAL_e=0x5B,
    dRes_ID_ALWAYS_BTK_VHUTL_e=0x5C,
    dRes_ID_ALWAYS_BTK_VLUPL_e=0x5D,
    dRes_ID_ALWAYS_BTK_W_PILLAR_A_e=0x5E,
    dRes_ID_ALWAYS_BTK_YA_e=0x5F,
    dRes_ID_ALWAYS_BTK_YTHDR00_e=0x60,
    /* BTP  */
    dRes_ID_ALWAYS_BTP_MPA_SIMI_e=0x63,
    dRes_ID_ALWAYS_BTP_MPI_KIBAKO_TARU_e=0x64,
    dRes_ID_ALWAYS_BTP_MPI_KINOHAHEN_e=0x65,
    dRes_ID_ALWAYS_BTP_MPI_KOISHI_e=0x66,
    dRes_ID_ALWAYS_BTP_MPM_TUBO_e=0x67,
    /* DAT  */
    dRes_ID_ALWAYS_BIN_ITEM_TABLE_e=0x6A,
    /* TEX  */
    dRes_ID_ALWAYS_BTI_AK_HOUSHI00_e=0x6D,
    dRes_ID_ALWAYS_BTI_AK_SMOKE01_e=0x6E,
    dRes_ID_ALWAYS_BTI_B_SEA_TEX0AND2_e=0x6F,
    dRes_ID_ALWAYS_BTI_B_WYURAYURA_TEX1_e=0x70,
    dRes_ID_ALWAYS_I4_BALL128B_e=0x71,
    dRes_ID_ALWAYS_BTI_BLACK_WHITE_2_e=0x72,
    dRes_ID_ALWAYS_BTI_CAMERA_FREE_e=0x73,
    dRes_ID_ALWAYS_BTI_CAMERA_SELF_e=0x74,
    dRes_ID_ALWAYS_BTI_F_SHIPICON_e=0x75,
    dRes_ID_ALWAYS_CI4_MAP08G_e=0x76,
    dRes_ID_ALWAYS_CI4_MAP16G_e=0x77,
    dRes_ID_ALWAYS_BTI_MAP_BLACK_CI8_e=0x78,
    dRes_ID_ALWAYS_BTI_MAP_CHECK16_CI4_e=0x79,
    dRes_ID_ALWAYS_BTI_MAP_FRAME1_e=0x7A,
    dRes_ID_ALWAYS_BTI_MAP_FRAME2_e=0x7B,
    dRes_ID_ALWAYS_BTI_MAP_FRAME3_e=0x7C,
    dRes_ID_ALWAYS_BTI_MAP_FRAME4_e=0x7D,
    dRes_ID_ALWAYS_BTI_ROPE_e=0x7E,
    dRes_ID_ALWAYS_BTI_SHMREF_e=0x7F,
    dRes_ID_ALWAYS_BTI_TREASUREBOX_e=0x80,
    dRes_ID_ALWAYS_I8_TX_SNOW01_e=0x81,
    dRes_ID_ALWAYS_BTI_TXA_LENS_32HALF_e=0x82,
    dRes_ID_ALWAYS_BTI_TXA_MOYA_A_64_e=0x83,
    dRes_ID_ALWAYS_BTI_TXA_MOYA_B_64_e=0x84,
    dRes_ID_ALWAYS_BTI_TXA_RING_A_32HAFE_e=0x85,
    dRes_ID_ALWAYS_BTI_TXA_TAIYO_e=0x86,
    dRes_ID_ALWAYS_BTI_TXA_TUKI_AS_e=0x87,
    dRes_ID_ALWAYS_BTI_TXA_TUKI_BS_e=0x88,
    dRes_ID_ALWAYS_BTI_TXA_TUKI_CS_e=0x89,
    dRes_ID_ALWAYS_BTI_TXA_TUKI_DS_e=0x8A,
    dRes_ID_ALWAYS_BTI_TXA_USONAMI_256_64MIP_e=0x8B,
    dRes_ID_ALWAYS_BTI_TXA_USONAMI_M_256_64MIP_e=0x8C,
    dRes_ID_ALWAYS_BTI_TXM_ROPE1_e=0x8D,
    dRes_ID_ALWAYS_BTI_UMIPT_e=0x8E,
};

enum ARROWITEM_JNT {
    ARROWITEM_JNT_ARROWITEM_e=0x0,
};

enum FA_JNT {
    FA_JNT_CENTER_e=0x0,
    FA_JNT_NECK_e=0x1,
    FA_JNT_WINGL1_e=0x2,
    FA_JNT_WINGR_e=0x3,
};

enum KROCK_00_JNT {
    KROCK_00_JNT_PCYLINDER2_e=0x0,
};

enum OBM_KOISI1_JNT {
    OBM_KOISI1_JNT_PCYLINDER1_e=0x0,
};

enum OBM_KOISI2_JNT {
    OBM_KOISI2_JNT_KOISI2_e=0x0,
};

enum OBM_KOTUBO1_JNT {
    OBM_KOTUBO1_JNT_OBM_KOTUBO1_e=0x0,
};

enum OBM_OOTUBO1_JNT {
    OBM_OOTUBO1_JNT_OBM_OOTUBO1_e=0x0,
};

enum VBELL_JNT {
    VBELL_JNT_VBELL_MODEL_e=0x0,
};

enum VBOKL_JNT {
    VBOKL_JNT_VBOKL_e=0x0,
};

enum VDOKL_JNT {
    VDOKL_JNT_DOKURO_e=0x0,
    VDOKL_JNT_NKLS01_e=0x1,
    VDOKL_JNT_NKLS02_e=0x2,
};

enum VESAL_JNT {
    VESAL_JNT_VESAL_MODEL_e=0x0,
};

enum VHAPL_JNT {
    VHAPL_JNT_ROOT_e=0x0,
    VHAPL_JNT_NKLS_e=0x1,
    VHAPL_JNT_NKLSEND_e=0x2,
    VHAPL_JNT_WINGL_e=0x3,
    VHAPL_JNT_WINGR_e=0x4,
};

enum VHRTL_JNT {
    VHRTL_JNT_VHRTL_MODEL_e=0x0,
};

enum VKEYL_JNT {
    VKEYL_JNT_VKEYL_e=0x0,
};

enum IB_JNT {
    IB_JNT_IB_e=0x0,
};

enum MPA_SIMI_JNT {
    MPA_SIMI_JNT_MPA_SIMI_e=0x0,
};

enum MPI_KOISHI_JNT {
    MPI_KOISHI_JNT_KOISI1_e=0x0,
};

enum MPM_TUBO_JNT {
    MPM_TUBO_JNT_MPM_TUBO_e=0x0,
};

enum MPODA_JNT {
    MPODA_JNT_MAGICPODA_e=0x0,
};

enum MPODB_JNT {
    MPODB_JNT_MAGICPODB_e=0x0,
};

enum NH_JNT {
    NH_JNT_NANAHO_e=0x0,
};

enum OBM_SYOUGEKISW_JNT {
    OBM_SYOUGEKISW_JNT_SHOGEKISW_e=0x0,
    OBM_SYOUGEKISW_JNT_SWCORE_e=0x1,
    OBM_SYOUGEKISW_JNT_SWDAI_e=0x2,
    OBM_SYOUGEKISW_JNT_SWPOINT_e=0x3,
};

enum VCHUL_JNT {
    VCHUL_JNT_VCHUL_e=0x0,
};

enum VHANL_JNT {
    VHANL_JNT_ROOT_VHANL_e=0x0,
    VHANL_JNT_HANEA_e=0x1,
    VHANL_JNT_HANEB_e=0x2,
    VHANL_JNT_HANEC_e=0x3,
};

enum VHKAL_JNT {
    VHKAL_JNT_ROOT_VHKAL_e=0x0,
    VHKAL_JNT_KAKERA_0_e=0x1,
    VHKAL_JNT_KAKERA_1_e=0x2,
};

enum VHUTL_JNT {
    VHUTL_JNT_ROOT_VHUTL_e=0x0,
    VHUTL_JNT_UTUWA_LOW_0_e=0x1,
    VHUTL_JNT_UTUWA_LOW_1_e=0x2,
};

enum VLUPL_JNT {
    VLUPL_JNT_ROOT_VLUPL_e=0x0,
    VLUPL_JNT_VLUPL1_OUTSIDE_e=0x1,
    VLUPL_JNT_VLUPL2_INSIDE_e=0x2,
};

enum W_PILLAR_A_JNT {
    W_PILLAR_A_JNT_WORLD_ROOT_e=0x0,
    W_PILLAR_A_JNT_HASHIRA1_e=0x1,
    W_PILLAR_A_JNT_HASHIRA2_e=0x2,
    W_PILLAR_A_JNT_SHIBUKI_OUT_e=0x3,
};

enum YA_JNT {
    YA_JNT_POLYSURFACE3_e=0x0,
};

enum YAZIRUSHI_01_JNT {
    YAZIRUSHI_01_JNT_NULL_YJ_e=0x0,
    YAZIRUSHI_01_JNT_JNT_YJ_01_e=0x1,
    YAZIRUSHI_01_JNT_JNT_YJ_02_e=0x2,
    YAZIRUSHI_01_JNT_JNT_YJ_03_e=0x3,
};

enum YTHDR00_JNT {
    YTHDR00_JNT_THNDER_e=0x0,
};

#endif /* !RES_ALWAYS_H */