#ifndef RES_BM2_H
#define RES_BM2_H

enum dRes_INDEX_BM2 {
    /* BCKS */
    dRes_INDEX_BM2_BCK_BMARM_WAIT01_e=0x6,
    dRes_INDEX_BM2_BCK_BMHEAD01_DWAIT_e=0x7,
    dRes_INDEX_BM2_BCK_BMHEAD01_LOOKUP_e=0x8,
    dRes_INDEX_BM2_BCK_BMHEAD01_OROORO_e=0x9,
    dRes_INDEX_BM2_BCK_BMWING_DWAIT_e=0xA,
    dRes_INDEX_BM2_BCK_BMWING_LOOKUP_e=0xB,
    dRes_INDEX_BM2_BCK_BMWING_OROORO_e=0xC,
    dRes_INDEX_BM2_BCK_BM_DWAIT_e=0xD,
    dRes_INDEX_BM2_BCK_BM_LOOKUP_e=0xE,
    dRes_INDEX_BM2_BCK_BM_OROORO_e=0xF,
    /* BDL  */
    dRes_INDEX_BM2_BDL_BMWING_e=0x12,
    dRes_INDEX_BM2_BDL_BM_BAG_e=0x13,
    /* BDLM */
    dRes_INDEX_BM2_BDL_BM_e=0x16,
    dRes_INDEX_BM2_BDL_BMARM_e=0x17,
    dRes_INDEX_BM2_BDL_BMHEAD01_e=0x18,
    /* BTP  */
    dRes_INDEX_BM2_BTP_BMHEAD01_e=0x1B,
};

enum dRes_ID_BM2 {
    /* BCKS */
    dRes_ID_BM2_BCK_BMARM_WAIT01_e=0x0,
    dRes_ID_BM2_BCK_BMHEAD01_DWAIT_e=0x1,
    dRes_ID_BM2_BCK_BMHEAD01_LOOKUP_e=0x2,
    dRes_ID_BM2_BCK_BMHEAD01_OROORO_e=0x3,
    dRes_ID_BM2_BCK_BMWING_DWAIT_e=0x4,
    dRes_ID_BM2_BCK_BMWING_LOOKUP_e=0x5,
    dRes_ID_BM2_BCK_BMWING_OROORO_e=0x6,
    dRes_ID_BM2_BCK_BM_DWAIT_e=0x7,
    dRes_ID_BM2_BCK_BM_LOOKUP_e=0x8,
    dRes_ID_BM2_BCK_BM_OROORO_e=0x9,
    /* BDL  */
    dRes_ID_BM2_BDL_BMWING_e=0xA,
    dRes_ID_BM2_BDL_BM_BAG_e=0xB,
    /* BDLM */
    dRes_ID_BM2_BDL_BM_e=0xC,
    dRes_ID_BM2_BDL_BMARM_e=0xD,
    dRes_ID_BM2_BDL_BMHEAD01_e=0xE,
    /* BTP  */
    dRes_ID_BM2_BTP_BMHEAD01_e=0xF,
};

enum BMWING_JNT {
    BMWING_JNT_WORLD_ROOT_e=0x0,
    BMWING_JNT_WINGLLOC_e=0x1,
    BMWING_JNT_WINGL1_e=0x2,
    BMWING_JNT_WINGL2_e=0x3,
    BMWING_JNT_WINGL3_e=0x4,
    BMWING_JNT_WINGLEND_e=0x5,
    BMWING_JNT_WINGRLOC_e=0x6,
    BMWING_JNT_WINGR1_e=0x7,
    BMWING_JNT_WINGR2_e=0x8,
    BMWING_JNT_WINGR3_e=0x9,
    BMWING_JNT_WINGREND_e=0xA,
};

enum BM_BAG_JNT {
    BM_BAG_JNT_BAG_e=0x0,
};

enum BM_JNT {
    BM_JNT_CENTER_e=0x0,
    BM_JNT_BACKBONE_e=0x1,
    BM_JNT_ARML_e=0x2,
    BM_JNT_ARMR_e=0x3,
    BM_JNT_NECK_e=0x4,
    BM_JNT_HEAD_e=0x5,
    BM_JNT_WAIST_e=0x6,
    BM_JNT_LEGL1_e=0x7,
    BM_JNT_LEGL2_e=0x8,
    BM_JNT_FOOTL_e=0x9,
    BM_JNT_FOOTLEND_e=0xA,
    BM_JNT_LEGR1_e=0xB,
    BM_JNT_LEGR2_e=0xC,
    BM_JNT_FOOTR_e=0xD,
    BM_JNT_FOOTREND_e=0xE,
};

enum BMARM_JNT {
    BMARM_JNT_WORLD_ROOT_e=0x0,
    BMARM_JNT_ARMLLOC_e=0x1,
    BMARM_JNT_ARML1_e=0x2,
    BMARM_JNT_ARML2_e=0x3,
    BMARM_JNT_HANDL_e=0x4,
    BMARM_JNT_SLEEVEL1_e=0x5,
    BMARM_JNT_SLEEVEL2_e=0x6,
    BMARM_JNT_ARMRLOC_e=0x7,
    BMARM_JNT_ARMR1_e=0x8,
    BMARM_JNT_ARMR2_e=0x9,
    BMARM_JNT_HANDR_e=0xA,
    BMARM_JNT_SLEEVER1_e=0xB,
    BMARM_JNT_SLEEVER2_e=0xC,
};

enum BMHEAD01_JNT {
    BMHEAD01_JNT_HEAD02_e=0x0,
    BMHEAD01_JNT_SIDEHAIRL_e=0x1,
    BMHEAD01_JNT_SIDEHAIRR_e=0x2,
};

#endif /* !RES_BM2_H */