#ifndef RES_BMSW_H
#define RES_BMSW_H

enum dRes_INDEX_BMSW {
    /* BCKS */
    dRes_INDEX_BMSW_BCK_BMARM_TALK01_e=0x9,
    dRes_INDEX_BMSW_BCK_BMARM_SHIWAKE01_e=0xA,
    dRes_INDEX_BMSW_BCK_BMARM_SHIWAKE02_e=0xB,
    dRes_INDEX_BMSW_BCK_BMARM_TALK02_e=0xC,
    dRes_INDEX_BMSW_BCK_BM_SHIWAKE01_e=0xD,
    dRes_INDEX_BMSW_BCK_BM_SHIWAKE02_e=0xE,
    dRes_INDEX_BMSW_BCK_BM_TALK01_e=0xF,
    dRes_INDEX_BMSW_BCK_BM_TALK02_e=0x10,
    dRes_INDEX_BMSW_BCK_BMARM_WAIT01_e=0x11,
    dRes_INDEX_BMSW_BCK_BM_WAIT01_e=0x12,
    dRes_INDEX_BMSW_BCK_BMARM_TALK03_e=0x13,
    dRes_INDEX_BMSW_BCK_BMARM_WAIT02_e=0x14,
    dRes_INDEX_BMSW_BCK_BM_TALK03_e=0x15,
    dRes_INDEX_BMSW_BCK_BM_WAIT02_e=0x16,
    /* BDL  */
    dRes_INDEX_BMSW_BDL_BM_BAG_e=0x19,
    dRes_INDEX_BMSW_BDL_BM_LETTER_e=0x1A,
    /* BDLM */
    dRes_INDEX_BMSW_BDL_BM_e=0x1D,
    dRes_INDEX_BMSW_BDL_BMARM_e=0x1E,
    dRes_INDEX_BMSW_BDL_QMAIL_e=0x1F,
    dRes_INDEX_BMSW_BDL_BMHEAD11_e=0x20,
    /* BMT  */
    dRes_INDEX_BMSW_BMT_BM02_e=0x23,
    dRes_INDEX_BMSW_BMT_BMARM02_e=0x24,
    /* BTP  */
    dRes_INDEX_BMSW_BTP_QMAIL_e=0x27,
    dRes_INDEX_BMSW_BTP_BMHEAD11_e=0x28,
    /* BMDM */
    dRes_INDEX_BMSW_BMD_SHOP_CURSOR01_e=0x2B,
    /* BRK  */
    dRes_INDEX_BMSW_BRK_SHOP_CURSOR01_e=0x2E,
};

enum dRes_ID_BMSW {
    /* BCKS */
    dRes_ID_BMSW_BCK_BMARM_TALK01_e=0x0,
    dRes_ID_BMSW_BCK_BMARM_SHIWAKE01_e=0x11,
    dRes_ID_BMSW_BCK_BMARM_SHIWAKE02_e=0x12,
    dRes_ID_BMSW_BCK_BMARM_TALK02_e=0x13,
    dRes_ID_BMSW_BCK_BM_SHIWAKE01_e=0x14,
    dRes_ID_BMSW_BCK_BM_SHIWAKE02_e=0x15,
    dRes_ID_BMSW_BCK_BM_TALK01_e=0x16,
    dRes_ID_BMSW_BCK_BM_TALK02_e=0x17,
    dRes_ID_BMSW_BCK_BMARM_WAIT01_e=0x1A,
    dRes_ID_BMSW_BCK_BM_WAIT01_e=0x1B,
    dRes_ID_BMSW_BCK_BMARM_TALK03_e=0x1D,
    dRes_ID_BMSW_BCK_BMARM_WAIT02_e=0x1E,
    dRes_ID_BMSW_BCK_BM_TALK03_e=0x1F,
    dRes_ID_BMSW_BCK_BM_WAIT02_e=0x20,
    /* BDL  */
    dRes_ID_BMSW_BDL_BM_BAG_e=0x2,
    dRes_ID_BMSW_BDL_BM_LETTER_e=0x1C,
    /* BDLM */
    dRes_ID_BMSW_BDL_BM_e=0x3,
    dRes_ID_BMSW_BDL_BMARM_e=0x4,
    dRes_ID_BMSW_BDL_QMAIL_e=0xF,
    dRes_ID_BMSW_BDL_BMHEAD11_e=0x21,
    /* BMT  */
    dRes_ID_BMSW_BMT_BM02_e=0x9,
    dRes_ID_BMSW_BMT_BMARM02_e=0xA,
    /* BTP  */
    dRes_ID_BMSW_BTP_QMAIL_e=0x10,
    dRes_ID_BMSW_BTP_BMHEAD11_e=0x22,
    /* BMDM */
    dRes_ID_BMSW_BMD_SHOP_CURSOR01_e=0x18,
    /* BRK  */
    dRes_ID_BMSW_BRK_SHOP_CURSOR01_e=0x19,
};

enum BM_BAG_JNT {
    BM_BAG_JNT_BAG_e=0x0,
};

enum BM_LETTER_JNT {
    BM_LETTER_JNT_BM_LETTER_e=0x0,
};

enum BM_JNT {
    BM_JNT_CENTER_e=0x0,
    BM_JNT_BACKBONE_e=0x1,
    BM_JNT_ARML_e=0x2,
    BM_JNT_ARMR_e=0x3,
    BM_JNT_NECK_e=0x4,
    BM_JNT_HEAD_e=0x5,
    BM_JNT_WAIST_e=0x6,
    BM_JNT_LEGL1_e=0x7,
    BM_JNT_LEGL2_e=0x8,
    BM_JNT_FOOTL_e=0x9,
    BM_JNT_FOOTLEND_e=0xA,
    BM_JNT_LEGR1_e=0xB,
    BM_JNT_LEGR2_e=0xC,
    BM_JNT_FOOTR_e=0xD,
    BM_JNT_FOOTREND_e=0xE,
};

enum BMARM_JNT {
    BMARM_JNT_WORLD_ROOT_e=0x0,
    BMARM_JNT_ARMLLOC_e=0x1,
    BMARM_JNT_ARML1_e=0x2,
    BMARM_JNT_ARML2_e=0x3,
    BMARM_JNT_HANDL_e=0x4,
    BMARM_JNT_SLEEVEL1_e=0x5,
    BMARM_JNT_SLEEVEL2_e=0x6,
    BMARM_JNT_ARMRLOC_e=0x7,
    BMARM_JNT_ARMR1_e=0x8,
    BMARM_JNT_ARMR2_e=0x9,
    BMARM_JNT_HANDR_e=0xA,
    BMARM_JNT_SLEEVER1_e=0xB,
    BMARM_JNT_SLEEVER2_e=0xC,
};

enum QMAIL_JNT {
    QMAIL_JNT_MAIL_e=0x0,
};

enum BMHEAD11_JNT {
    BMHEAD11_JNT_BMHEAD11_e=0x0,
};

enum SHOP_CURSOR01_JNT {
    SHOP_CURSOR01_JNT_CURSOR01_e=0x0,
};

#endif /* !RES_BMSW_H */