#ifndef RES_CO_H
#define RES_CO_H

enum dRes_INDEX_CO {
    /* BCKS */
    dRes_INDEX_CO_BCK_COPEAL_MIGAMAE_e=0x7,
    dRes_INDEX_CO_BCK_COPEAL_OKIRU_e=0x8,
    dRes_INDEX_CO_BCK_COPEAL_READ_e=0x9,
    dRes_INDEX_CO_BCK_COPEAL_SWAIT01_e=0xA,
    dRes_INDEX_CO_BCK_COPEAL_TALK01_e=0xB,
    dRes_INDEX_CO_BCK_COPEAL_TALK02_e=0xC,
    dRes_INDEX_CO_BCK_COPEAL_UKETORI_e=0xD,
    dRes_INDEX_CO_BCK_COPEAL_WAIT01_e=0xE,
    dRes_INDEX_CO_BCK_COPEAL_WAIT02_e=0xF,
    dRes_INDEX_CO_BCK_CO_MIGAMAE_e=0x10,
    dRes_INDEX_CO_BCK_CO_OKIRU_e=0x11,
    dRes_INDEX_CO_BCK_CO_READ_e=0x12,
    dRes_INDEX_CO_BCK_CO_SWAIT01_e=0x13,
    dRes_INDEX_CO_BCK_CO_TALK01_e=0x14,
    dRes_INDEX_CO_BCK_CO_TALK02_e=0x15,
    dRes_INDEX_CO_BCK_CO_UKETORI_e=0x16,
    dRes_INDEX_CO_BCK_CO_WAIT01_e=0x17,
    dRes_INDEX_CO_BCK_CO_WAIT02_e=0x18,
    dRes_INDEX_CO_BCK_CO_WAIT00_e=0x19,
    /* BDL  */
    dRes_INDEX_CO_BDL_CO_LETTER_e=0x1C,
    /* BDLM */
    dRes_INDEX_CO_BDL_CO_e=0x1F,
    dRes_INDEX_CO_BDL_CO_PEAL_e=0x20,
    /* BTK  */
    dRes_INDEX_CO_BTK_CO_PEAL_e=0x23,
    /* BTP  */
    dRes_INDEX_CO_BTP_FUAN_e=0x26,
    dRes_INDEX_CO_BTP_KIRI_e=0x27,
    dRes_INDEX_CO_BTP_MIGAMAE_e=0x28,
    dRes_INDEX_CO_BTP_NAGAME_e=0x29,
    dRes_INDEX_CO_BTP_NIKO_e=0x2A,
    dRes_INDEX_CO_BTP_OKIRU_e=0x2B,
    dRes_INDEX_CO_BTP_OKORI_e=0x2C,
};

enum dRes_ID_CO {
    /* BCKS */
    dRes_ID_CO_BCK_COPEAL_MIGAMAE_e=0x0,
    dRes_ID_CO_BCK_COPEAL_OKIRU_e=0x1,
    dRes_ID_CO_BCK_COPEAL_READ_e=0x2,
    dRes_ID_CO_BCK_COPEAL_SWAIT01_e=0x3,
    dRes_ID_CO_BCK_COPEAL_TALK01_e=0x4,
    dRes_ID_CO_BCK_COPEAL_TALK02_e=0x5,
    dRes_ID_CO_BCK_COPEAL_UKETORI_e=0x6,
    dRes_ID_CO_BCK_COPEAL_WAIT01_e=0x7,
    dRes_ID_CO_BCK_COPEAL_WAIT02_e=0x8,
    dRes_ID_CO_BCK_CO_MIGAMAE_e=0x9,
    dRes_ID_CO_BCK_CO_OKIRU_e=0xA,
    dRes_ID_CO_BCK_CO_READ_e=0xB,
    dRes_ID_CO_BCK_CO_SWAIT01_e=0xC,
    dRes_ID_CO_BCK_CO_TALK01_e=0xD,
    dRes_ID_CO_BCK_CO_TALK02_e=0xE,
    dRes_ID_CO_BCK_CO_UKETORI_e=0xF,
    dRes_ID_CO_BCK_CO_WAIT01_e=0x10,
    dRes_ID_CO_BCK_CO_WAIT02_e=0x11,
    dRes_ID_CO_BCK_CO_WAIT00_e=0x1D,
    /* BDL  */
    dRes_ID_CO_BDL_CO_LETTER_e=0x12,
    /* BDLM */
    dRes_ID_CO_BDL_CO_e=0x13,
    dRes_ID_CO_BDL_CO_PEAL_e=0x14,
    /* BTK  */
    dRes_ID_CO_BTK_CO_PEAL_e=0x15,
    /* BTP  */
    dRes_ID_CO_BTP_FUAN_e=0x16,
    dRes_ID_CO_BTP_KIRI_e=0x17,
    dRes_ID_CO_BTP_MIGAMAE_e=0x18,
    dRes_ID_CO_BTP_NAGAME_e=0x19,
    dRes_ID_CO_BTP_NIKO_e=0x1A,
    dRes_ID_CO_BTP_OKIRU_e=0x1B,
    dRes_ID_CO_BTP_OKORI_e=0x1C,
};

enum CO_LETTER_JNT {
    CO_LETTER_JNT_CO_LETTER_e=0x0,
};

enum CO_JNT {
    CO_JNT_CENTER_e=0x0,
    CO_JNT_BACKBONE_e=0x1,
    CO_JNT_NECK_e=0x2,
    CO_JNT_HEAD_e=0x3,
    CO_JNT_HAIR1_e=0x4,
    CO_JNT_HAIR2_e=0x5,
    CO_JNT_SHOULDERL_e=0x6,
    CO_JNT_ARML1_e=0x7,
    CO_JNT_ARML2_e=0x8,
    CO_JNT_HANDL_e=0x9,
    CO_JNT_SHOULDERR_e=0xA,
    CO_JNT_ARMR1_e=0xB,
    CO_JNT_ARMR2_e=0xC,
    CO_JNT_HANDR_e=0xD,
    CO_JNT_WAIST_e=0xE,
    CO_JNT_LEGL1_e=0xF,
    CO_JNT_LEGL2_e=0x10,
    CO_JNT_FOOTL_e=0x11,
    CO_JNT_LEGR1_e=0x12,
    CO_JNT_LEGR2_e=0x13,
    CO_JNT_FOOTR_e=0x14,
    CO_JNT_SKIRTF_e=0x15,
};

enum CO_PEAL_JNT {
    CO_PEAL_JNT_PEAL_LOC_e=0x0,
    CO_PEAL_JNT_CO_PEARL_e=0x1,
    CO_PEAL_JNT_CO_P_MARK_e=0x2,
};

#endif /* !RES_CO_H */