#ifndef RES_DAIOCTA_H
#define RES_DAIOCTA_H

enum dRes_INDEX_DAIOCTA {
    /* BCK  */
    dRes_INDEX_DAIOCTA_BCK_DAMAGE1_e=0x6,
    dRes_INDEX_DAIOCTA_BCK_DAMAGE2_e=0x7,
    dRes_INDEX_DAIOCTA_BCK_DEATH1_e=0x8,
    dRes_INDEX_DAIOCTA_BCK_DEATH2_e=0x9,
    dRes_INDEX_DAIOCTA_BCK_GAWA00_e=0xA,
    dRes_INDEX_DAIOCTA_BCK_HAKIDASU1_e=0xB,
    dRes_INDEX_DAIOCTA_BCK_SUIKOMU1_e=0xC,
    dRes_INDEX_DAIOCTA_BCK_WAIT1_e=0xD,
    /* BDLM */
    dRes_INDEX_DAIOCTA_BDL_DO_EYE1_e=0x10,
    dRes_INDEX_DAIOCTA_BDL_DO_MAIN1_e=0x11,
    dRes_INDEX_DAIOCTA_BDL_GAWA00_e=0x12,
    dRes_INDEX_DAIOCTA_BDL_GDO_SUI00_e=0x13,
    /* BRK  */
    dRes_INDEX_DAIOCTA_BRK_DAMAGE1_e=0x16,
    dRes_INDEX_DAIOCTA_BRK_DAMAGE2_e=0x17,
    dRes_INDEX_DAIOCTA_BRK_DAMAGE_EYE_A1_e=0x18,
    dRes_INDEX_DAIOCTA_BRK_DAMAGE_EYE_B1_e=0x19,
    dRes_INDEX_DAIOCTA_BRK_DEATH1_e=0x1A,
    dRes_INDEX_DAIOCTA_BRK_DEATH2_e=0x1B,
    dRes_INDEX_DAIOCTA_BRK_GAWA00_e=0x1C,
    dRes_INDEX_DAIOCTA_BRK_GDO_SUI00_e=0x1D,
    dRes_INDEX_DAIOCTA_BRK_HAKIDASU1_e=0x1E,
    dRes_INDEX_DAIOCTA_BRK_SUIKOMU1_e=0x1F,
    dRes_INDEX_DAIOCTA_BRK_WAIT1_e=0x20,
    /* BTK  */
    dRes_INDEX_DAIOCTA_BTK_DAMAGE_EYE_A1_e=0x23,
    dRes_INDEX_DAIOCTA_BTK_DAMAGE_EYE_B1_e=0x24,
    dRes_INDEX_DAIOCTA_BTK_GAWA00_e=0x25,
    dRes_INDEX_DAIOCTA_BTK_GDO_SUI00_e=0x26,
};

enum dRes_ID_DAIOCTA {
    /* BCK  */
    dRes_ID_DAIOCTA_BCK_DAMAGE1_e=0x6,
    dRes_ID_DAIOCTA_BCK_DAMAGE2_e=0x7,
    dRes_ID_DAIOCTA_BCK_DEATH1_e=0x8,
    dRes_ID_DAIOCTA_BCK_DEATH2_e=0x9,
    dRes_ID_DAIOCTA_BCK_GAWA00_e=0xA,
    dRes_ID_DAIOCTA_BCK_HAKIDASU1_e=0xB,
    dRes_ID_DAIOCTA_BCK_SUIKOMU1_e=0xC,
    dRes_ID_DAIOCTA_BCK_WAIT1_e=0xD,
    /* BDLM */
    dRes_ID_DAIOCTA_BDL_DO_EYE1_e=0x10,
    dRes_ID_DAIOCTA_BDL_DO_MAIN1_e=0x11,
    dRes_ID_DAIOCTA_BDL_GAWA00_e=0x12,
    dRes_ID_DAIOCTA_BDL_GDO_SUI00_e=0x13,
    /* BRK  */
    dRes_ID_DAIOCTA_BRK_DAMAGE1_e=0x16,
    dRes_ID_DAIOCTA_BRK_DAMAGE2_e=0x17,
    dRes_ID_DAIOCTA_BRK_DAMAGE_EYE_A1_e=0x18,
    dRes_ID_DAIOCTA_BRK_DAMAGE_EYE_B1_e=0x19,
    dRes_ID_DAIOCTA_BRK_DEATH1_e=0x1A,
    dRes_ID_DAIOCTA_BRK_DEATH2_e=0x1B,
    dRes_ID_DAIOCTA_BRK_GAWA00_e=0x1C,
    dRes_ID_DAIOCTA_BRK_GDO_SUI00_e=0x1D,
    dRes_ID_DAIOCTA_BRK_HAKIDASU1_e=0x1E,
    dRes_ID_DAIOCTA_BRK_SUIKOMU1_e=0x1F,
    dRes_ID_DAIOCTA_BRK_WAIT1_e=0x20,
    /* BTK  */
    dRes_ID_DAIOCTA_BTK_DAMAGE_EYE_A1_e=0x23,
    dRes_ID_DAIOCTA_BTK_DAMAGE_EYE_B1_e=0x24,
    dRes_ID_DAIOCTA_BTK_GAWA00_e=0x25,
    dRes_ID_DAIOCTA_BTK_GDO_SUI00_e=0x26,
};

enum DO_EYE1_JNT {
    DO_EYE1_JNT_J_DO_EYE_ALLROOT_e=0x0,
    DO_EYE1_JNT_J_DO_EYE1_e=0x1,
    DO_EYE1_JNT_J_DO_EYE2_e=0x2,
};

enum DO_MAIN1_JNT {
    DO_MAIN1_JNT_DO_SKL_ROOT_e=0x0,
    DO_MAIN1_JNT_J_DO_ASHI1_e=0x1,
    DO_MAIN1_JNT_J_DO_BODY1_e=0x2,
    DO_MAIN1_JNT_J_DO_BODY2_e=0x3,
    DO_MAIN1_JNT_J_DO_BODY3_e=0x4,
    DO_MAIN1_JNT_J_DO_BODY4_e=0x5,
    DO_MAIN1_JNT_J_DO_BODY5_e=0x6,
    DO_MAIN1_JNT_J_DO_HIRE_L2_e=0x7,
    DO_MAIN1_JNT_J_DO_HIRE_R2_e=0x8,
    DO_MAIN1_JNT_J_DO_HIRE_L1_e=0x9,
    DO_MAIN1_JNT_J_DO_HIRE_R1_e=0xA,
    DO_MAIN1_JNT_J_DO_ME10_e=0xB,
    DO_MAIN1_JNT_J_DO_ME11_e=0xC,
    DO_MAIN1_JNT_J_DO_ME12_e=0xD,
    DO_MAIN1_JNT_J_DO_ME9_e=0xE,
    DO_MAIN1_JNT_J_DO_ME3_e=0xF,
    DO_MAIN1_JNT_J_DO_ME6_e=0x10,
    DO_MAIN1_JNT_J_DO_ME7_e=0x11,
    DO_MAIN1_JNT_J_DO_ME8_e=0x12,
    DO_MAIN1_JNT_J_DO_KUTI1_e=0x13,
    DO_MAIN1_JNT_J_DO_KUTI2_e=0x14,
    DO_MAIN1_JNT_J_DO_ME1_e=0x15,
    DO_MAIN1_JNT_J_DO_ME2_e=0x16,
    DO_MAIN1_JNT_J_DO_ME4_e=0x17,
    DO_MAIN1_JNT_J_DO_ME5_e=0x18,
    DO_MAIN1_JNT_J_DO_TE_L1_e=0x19,
    DO_MAIN1_JNT_J_DO_TE_L2_e=0x1A,
    DO_MAIN1_JNT_J_DO_TE_L3_e=0x1B,
    DO_MAIN1_JNT_J_DO_TE_L4_e=0x1C,
    DO_MAIN1_JNT_J_DO_TE_L5_e=0x1D,
    DO_MAIN1_JNT_J_DO_TE_L6_e=0x1E,
    DO_MAIN1_JNT_J_DO_TE_R1_e=0x1F,
    DO_MAIN1_JNT_J_DO_TE_R2_e=0x20,
    DO_MAIN1_JNT_J_DO_TE_R3_e=0x21,
    DO_MAIN1_JNT_J_DO_TE_R4_e=0x22,
    DO_MAIN1_JNT_J_DO_TE_R5_e=0x23,
    DO_MAIN1_JNT_J_DO_TE_R6_e=0x24,
};

enum GAWA00_JNT {
    GAWA00_JNT_GAWA00_e=0x0,
    GAWA00_JNT_A00_e=0x1,
    GAWA00_JNT_AWA_e=0x2,
};

enum GDO_SUI00_JNT {
    GDO_SUI00_JNT_ROOT_e=0x0,
    GDO_SUI00_JNT_GDO_SUI00_e=0x1,
};

#endif /* !RES_DAIOCTA_H */