#ifndef RES_DALWAYS_H
#define RES_DALWAYS_H

enum dRes_INDEX_DALWAYS {
    /* BCK  */
    dRes_INDEX_DALWAYS_BCK_BOXOPENBOX_e=0x8,
    dRes_INDEX_DALWAYS_BCK_BOXOPENSHORTBOX_e=0x9,
    dRes_INDEX_DALWAYS_BCK_IT_TAKARA_FLASH_e=0xA,
    dRes_INDEX_DALWAYS_BCK_IT_TAKARA_FLASH2_e=0xB,
    /* BDLI */
    dRes_INDEX_DALWAYS_BDL_BOXA_e=0xE,
    dRes_INDEX_DALWAYS_BDL_BOXB_e=0xF,
    dRes_INDEX_DALWAYS_BDL_BOXC_e=0x10,
    /* BDLM */
    dRes_INDEX_DALWAYS_BDL_BOX_SHADOW_e=0x13,
    dRes_INDEX_DALWAYS_BDL_BOXD_e=0x14,
    dRes_INDEX_DALWAYS_BDL_BOXSEA_e=0x15,
    dRes_INDEX_DALWAYS_BDL_IT_TAKARA_FLASH_e=0x16,
    dRes_INDEX_DALWAYS_BDL_YTRIF00_e=0x17,
    /* BRK  */
    dRes_INDEX_DALWAYS_BRK_BOX_SHADOW_e=0x1A,
    dRes_INDEX_DALWAYS_BRK_BOXA_e=0x1B,
    dRes_INDEX_DALWAYS_BRK_BOXB_e=0x1C,
    dRes_INDEX_DALWAYS_BRK_BOXC_e=0x1D,
    dRes_INDEX_DALWAYS_BRK_IT_TAKARA_FLASH_e=0x1E,
    dRes_INDEX_DALWAYS_BRK_YTRIF00_e=0x1F,
    /* BTK  */
    dRes_INDEX_DALWAYS_BTK_BOXA_e=0x22,
    dRes_INDEX_DALWAYS_BTK_BOXB_e=0x23,
    dRes_INDEX_DALWAYS_BTK_BOXC_e=0x24,
    dRes_INDEX_DALWAYS_BTK_IT_TAKARA_FLASH_e=0x25,
    /* DZB  */
    dRes_INDEX_DALWAYS_DZB_BOXA_00_e=0x28,
    dRes_INDEX_DALWAYS_DZB_BOXA_01_e=0x29,
    dRes_INDEX_DALWAYS_DZB_BOXB_00_e=0x2A,
    dRes_INDEX_DALWAYS_DZB_BOXB_01_e=0x2B,
    dRes_INDEX_DALWAYS_DZB_BOXD_00_e=0x2C,
    dRes_INDEX_DALWAYS_DZB_BOXD_01_e=0x2D,
    dRes_INDEX_DALWAYS_DZB_KINB_00_e=0x2E,
};

enum dRes_ID_DALWAYS {
    /* BCK  */
    dRes_ID_DALWAYS_BCK_BOXOPENBOX_e=0x8,
    dRes_ID_DALWAYS_BCK_BOXOPENSHORTBOX_e=0x9,
    dRes_ID_DALWAYS_BCK_IT_TAKARA_FLASH_e=0xA,
    dRes_ID_DALWAYS_BCK_IT_TAKARA_FLASH2_e=0xB,
    /* BDLI */
    dRes_ID_DALWAYS_BDL_BOXA_e=0xE,
    dRes_ID_DALWAYS_BDL_BOXB_e=0xF,
    dRes_ID_DALWAYS_BDL_BOXC_e=0x10,
    /* BDLM */
    dRes_ID_DALWAYS_BDL_BOX_SHADOW_e=0x13,
    dRes_ID_DALWAYS_BDL_BOXD_e=0x14,
    dRes_ID_DALWAYS_BDL_BOXSEA_e=0x15,
    dRes_ID_DALWAYS_BDL_IT_TAKARA_FLASH_e=0x16,
    dRes_ID_DALWAYS_BDL_YTRIF00_e=0x17,
    /* BRK  */
    dRes_ID_DALWAYS_BRK_BOX_SHADOW_e=0x1A,
    dRes_ID_DALWAYS_BRK_BOXA_e=0x1B,
    dRes_ID_DALWAYS_BRK_BOXB_e=0x1C,
    dRes_ID_DALWAYS_BRK_BOXC_e=0x1D,
    dRes_ID_DALWAYS_BRK_IT_TAKARA_FLASH_e=0x1E,
    dRes_ID_DALWAYS_BRK_YTRIF00_e=0x1F,
    /* BTK  */
    dRes_ID_DALWAYS_BTK_BOXA_e=0x22,
    dRes_ID_DALWAYS_BTK_BOXB_e=0x23,
    dRes_ID_DALWAYS_BTK_BOXC_e=0x24,
    dRes_ID_DALWAYS_BTK_IT_TAKARA_FLASH_e=0x25,
    /* DZB  */
    dRes_ID_DALWAYS_DZB_BOXA_00_e=0x28,
    dRes_ID_DALWAYS_DZB_BOXA_01_e=0x29,
    dRes_ID_DALWAYS_DZB_BOXB_00_e=0x2A,
    dRes_ID_DALWAYS_DZB_BOXB_01_e=0x2B,
    dRes_ID_DALWAYS_DZB_BOXD_00_e=0x2C,
    dRes_ID_DALWAYS_DZB_BOXD_01_e=0x2D,
    dRes_ID_DALWAYS_DZB_KINB_00_e=0x2E,
};

enum BOXA_JNT {
    BOXA_JNT_BOXA_e=0x0,
    BOXA_JNT_COVER_JNT_e=0x1,
    BOXA_JNT_COVERA_e=0x2,
};

enum BOXB_JNT {
    BOXB_JNT_BOXB_e=0x0,
    BOXB_JNT_COVER_JNT_e=0x1,
    BOXB_JNT_COVERB_e=0x2,
};

enum BOXC_JNT {
    BOXC_JNT_BOXC_e=0x0,
    BOXC_JNT_COVER_JNT_e=0x1,
    BOXC_JNT_COVERC_e=0x2,
};

enum BOX_SHADOW_JNT {
    BOX_SHADOW_JNT_WORLD_ROOT_e=0x0,
    BOX_SHADOW_JNT_KAGE_SHITA_e=0x1,
    BOX_SHADOW_JNT_KAGE_UE_e=0x2,
};

enum BOXD_JNT {
    BOXD_JNT_BOXD_e=0x0,
    BOXD_JNT_COVER_JNT_e=0x1,
    BOXD_JNT_COVERD_e=0x2,
};

enum BOXSEA_JNT {
    BOXSEA_JNT_BOXSEA_e=0x0,
    BOXSEA_JNT_COVER_JNT_e=0x1,
    BOXSEA_JNT_COVERSEA_e=0x2,
};

enum IT_TAKARA_FLASH_JNT {
    IT_TAKARA_FLASH_JNT_CENTER_e=0x0,
    IT_TAKARA_FLASH_JNT_FRONT1_e=0x1,
    IT_TAKARA_FLASH_JNT_REAR1_e=0x2,
};

enum YTRIF00_JNT {
    YTRIF00_JNT_YTRIF00_e=0x0,
    YTRIF00_JNT_A00_e=0x1,
    YTRIF00_JNT_TRIFORCE_e=0x2,
};

#endif /* !RES_DALWAYS_H */