#ifndef RES_GHRWP_H
#define RES_GHRWP_H

enum dRes_INDEX_GHRWP {
    /* BDLM */
    dRes_INDEX_GHRWP_BDL_GHRWPA00_e=0x5,
    dRes_INDEX_GHRWP_BDL_GHRWPB00_e=0x6,
    /* BRK  */
    dRes_INDEX_GHRWP_BRK_GHRWPB00_e=0x9,
    /* BTK  */
    dRes_INDEX_GHRWP_BTK_GHRWPA00_e=0xC,
    dRes_INDEX_GHRWP_BTK_GHRWPB00_e=0xD,
};

enum dRes_ID_GHRWP {
    /* BDLM */
    dRes_ID_GHRWP_BDL_GHRWPA00_e=0x5,
    dRes_ID_GHRWP_BDL_GHRWPB00_e=0x6,
    /* BRK  */
    dRes_ID_GHRWP_BRK_GHRWPB00_e=0x9,
    /* BTK  */
    dRes_ID_GHRWP_BTK_GHRWPA00_e=0xC,
    dRes_ID_GHRWP_BTK_GHRWPB00_e=0xD,
};

enum GHRWPA00_JNT {
    GHRWPA00_JNT_ROOTA_e=0x0,
    GHRWPA00_JNT_GHRWPA00_e=0x1,
    GHRWPA00_JNT_A_e=0x2,
    GHRWPA00_JNT_AOMOTE_e=0x3,
    GHRWPA00_JNT_AURA_e=0x4,
    GHRWPA00_JNT_B_e=0x5,
    GHRWPA00_JNT_BOMOTE_e=0x6,
    GHRWPA00_JNT_BURA_e=0x7,
    GHRWPA00_JNT_C_e=0x8,
    GHRWPA00_JNT_CURA_e=0x9,
};

enum GHRWPB00_JNT {
    GHRWPB00_JNT_ROOTB_e=0x0,
    GHRWPB00_JNT_GHRWPB00_e=0x1,
    GHRWPB00_JNT_OMOTE_e=0x2,
    GHRWPB00_JNT_URA_e=0x3,
};

#endif /* !RES_GHRWP_H */