#ifndef RES_GNNBTLTAKI_H
#define RES_GNNBTLTAKI_H

enum dRes_INDEX_GNNBTLTAKI {
    /* BDLM */
    dRes_INDEX_GNNBTLTAKI_BDL_GNN_BTL_TAKI_e=0x4,
    /* BTK  */
    dRes_INDEX_GNNBTLTAKI_BTK_GNN_BTL_TAKI_e=0x7,
};

enum dRes_ID_GNNBTLTAKI {
    /* BDLM */
    dRes_ID_GNNBTLTAKI_BDL_GNN_BTL_TAKI_e=0x4,
    /* BTK  */
    dRes_ID_GNNBTLTAKI_BTK_GNN_BTL_TAKI_e=0x7,
};

enum GNN_BTL_TAKI_JNT {
    GNN_BTL_TAKI_JNT_WATER_e=0x0,
    GNN_BTL_TAKI_JNT_TAKI_L_e=0x1,
    GNN_BTL_TAKI_JNT_X_NURE_e=0x2,
    GNN_BTL_TAKI_JNT_Z0_TAKI_LL_e=0x3,
    GNN_BTL_TAKI_JNT_Z1_TAKI_LLL_e=0x4,
    GNN_BTL_TAKI_JNT_SEA_e=0x5,
    GNN_BTL_TAKI_JNT_WAREMA_e=0x6,
    GNN_BTL_TAKI_JNT_WAREMA1_e=0x7,
};

#endif /* !RES_GNNBTLTAKI_H */