#ifndef RES_HIMO2_H
#define RES_HIMO2_H

//
// Generated by res_arc.py from archive: Himo2.arc
// Do not manually modify this file or your changes will be overwritten.
//

enum dRes_INDEX_HIMO2 {
    /* BMD  */
    dRes_INDEX_HIMO2_BMD_SEARCHITA_e=0x3,
};

enum dRes_ID_HIMO2 {
    /* BMD  */
    dRes_ID_HIMO2_BMD_SEARCHITA_e=0x3,
};

enum SEARCHITA_JNT {
    SEARCHITA_JNT_EREAITA_e=0x0,
};

#endif /* RES_HIMO2_H */
