#ifndef RES_SHIP_H
#define RES_SHIP_H

enum dRes_INDEX_SHIP {
    /* BCK  */
    dRes_INDEX_SHIP_BCK_AKIBI1_e=0x5,
    dRes_INDEX_SHIP_BCK_DAMAGE1_e=0x6,
    dRes_INDEX_SHIP_BCK_FN_LOOK_L_e=0x7,
    dRes_INDEX_SHIP_BCK_FN_LOOK_R_e=0x8,
    dRes_INDEX_SHIP_BCK_FN_LOSE1_e=0x9,
    dRes_INDEX_SHIP_BCK_FN_MAST_OFF2_e=0xA,
    dRes_INDEX_SHIP_BCK_FN_MAST_ON2_e=0xB,
    dRes_INDEX_SHIP_BCK_FN_TALK_A_e=0xC,
    dRes_INDEX_SHIP_BCK_FN_TALK_B_e=0xD,
    dRes_INDEX_SHIP_BCK_KYAKKAN1_e=0xE,
    /* BDL  */
    dRes_INDEX_SHIP_BDL_FN_BODY_e=0x11,
    dRes_INDEX_SHIP_BDL_FN_HEAD_H_e=0x12,
    dRes_INDEX_SHIP_BDL_VFNCN_e=0x13,
    dRes_INDEX_SHIP_BDL_VFNCR_e=0x14,
    /* TEX  */
    dRes_INDEX_SHIP_BTI_NEW_HO1_e=0x17,
};

enum dRes_ID_SHIP {
    /* BCK  */
    dRes_ID_SHIP_BCK_AKIBI1_e=0x5,
    dRes_ID_SHIP_BCK_DAMAGE1_e=0x6,
    dRes_ID_SHIP_BCK_FN_LOOK_L_e=0x7,
    dRes_ID_SHIP_BCK_FN_LOOK_R_e=0x8,
    dRes_ID_SHIP_BCK_FN_LOSE1_e=0x9,
    dRes_ID_SHIP_BCK_FN_MAST_OFF2_e=0xA,
    dRes_ID_SHIP_BCK_FN_MAST_ON2_e=0xB,
    dRes_ID_SHIP_BCK_FN_TALK_A_e=0xC,
    dRes_ID_SHIP_BCK_FN_TALK_B_e=0xD,
    dRes_ID_SHIP_BCK_KYAKKAN1_e=0xE,
    /* BDL  */
    dRes_ID_SHIP_BDL_FN_BODY_e=0x11,
    dRes_ID_SHIP_BDL_FN_HEAD_H_e=0x12,
    dRes_ID_SHIP_BDL_VFNCN_e=0x13,
    dRes_ID_SHIP_BDL_VFNCR_e=0x14,
    /* TEX  */
    dRes_ID_SHIP_BTI_NEW_HO1_e=0x17,
};

enum FN_BODY_JNT {
    FN_BODY_JNT_FN_BODY_ALLROOT_e=0x0,
    FN_BODY_JNT_FN_BODY_SKELROOT_e=0x1,
    FN_BODY_JNT_J_FN_MAIN1_e=0x2,
    FN_BODY_JNT_J_FN_FUTA_e=0x3,
    FN_BODY_JNT_J_FN_GATTAI_e=0x4,
    FN_BODY_JNT_J_FN_KAJI_e=0x5,
    FN_BODY_JNT_J_FN_MAST_e=0x6,
    FN_BODY_JNT_J_FN_SAIL1_e=0x7,
    FN_BODY_JNT_J_FN_SAIL2_e=0x8,
    FN_BODY_JNT_J_FN_SAIL_E_e=0x9,
    FN_BODY_JNT_J_FN_STEER1_e=0xA,
};

enum FN_HEAD_H_JNT {
    FN_HEAD_H_JNT_FN_HEAD_H_ALLROOT_e=0x0,
    FN_HEAD_H_JNT_FN_HEAD_H_SKLROOT_e=0x1,
    FN_HEAD_H_JNT_J_FN_KUBI1_e=0x2,
    FN_HEAD_H_JNT_J_FN_KUBI2_e=0x3,
    FN_HEAD_H_JNT_J_FN_KUBI3_e=0x4,
    FN_HEAD_H_JNT_J_FN_KUBI4_e=0x5,
    FN_HEAD_H_JNT_J_FN_KUBI5_e=0x6,
    FN_HEAD_H_JNT_J_FN_KUBI6_e=0x7,
    FN_HEAD_H_JNT_J_FN_ATAMA_e=0x8,
    FN_HEAD_H_JNT_J_FN_AGO1_e=0x9,
    FN_HEAD_H_JNT_J_FN_AGO2_e=0xA,
    FN_HEAD_H_JNT_J_FN_HOHO_e=0xB,
    FN_HEAD_H_JNT_J_FN_MAYU_L1_e=0xC,
    FN_HEAD_H_JNT_J_FN_MAYU_L2_e=0xD,
    FN_HEAD_H_JNT_J_FN_MAYU_R1_e=0xE,
    FN_HEAD_H_JNT_J_FN_MAYU_R2_e=0xF,
    FN_HEAD_H_JNT_J_FN_ME_L_e=0x10,
    FN_HEAD_H_JNT_J_FN_ME_R_e=0x11,
};

enum VFNCN_JNT {
    VFNCN_JNT_CANON_ROOT_e=0x0,
    VFNCN_JNT_CANON1_e=0x1,
    VFNCN_JNT_CANON2_e=0x2,
};

enum VFNCR_JNT {
    VFNCR_JNT_V_CRANE_ROOT_e=0x0,
    VFNCR_JNT_V_CRANE_ROTATION_e=0x1,
};

#endif /* !RES_SHIP_H */