#ifndef RES_SWTDOOR_H
#define RES_SWTDOOR_H

enum dRes_INDEX_SWTDOOR {
    /* BMD  */
    dRes_INDEX_SWTDOOR_BMD_SWTDOOR_e=0x3,
};

enum dRes_ID_SWTDOOR {
    /* BMD  */
    dRes_ID_SWTDOOR_BMD_SWTDOOR_e=0x3,
};

enum SWTDOOR_JNT {
    SWTDOOR_JNT_SWTDOOR_e=0x0,
    SWTDOOR_JNT_LOCATOR1_e=0x1,
    SWTDOOR_JNT_POLYSURFACE816_e=0x2,
};

#endif /* !RES_SWTDOOR_H */