#ifndef RES_BGN_H
#define RES_BGN_H

enum dRes_INDEX_BGN {
    /* BCK  */
    dRes_INDEX_BGN_BCK_BGN_HEAD1_e=0x6,
    dRes_INDEX_BGN_BCK_BGN_HEAD2_e=0x7,
    dRes_INDEX_BGN_BCK_DAMAGE1_e=0x8,
    dRes_INDEX_BGN_BCK_DERU1_e=0x9,
    dRes_INDEX_BGN_BCK_JUMP1_e=0xA,
    dRes_INDEX_BGN_BCK_MODORU1_e=0xB,
    dRes_INDEX_BGN_BCK_RAKKA1_e=0xC,
    dRes_INDEX_BGN_BCK_RAKKA2_e=0xD,
    dRes_INDEX_BGN_BCK_SETTI1_e=0xE,
    dRes_INDEX_BGN_BCK_WAIT1_e=0xF,
    dRes_INDEX_BGN_BCK_WAIT2_e=0x10,
    /* BDLM */
    dRes_INDEX_BGN_BDL_BGN_BODY1_e=0x13,
    dRes_INDEX_BGN_BDL_BGN_DEKU1_e=0x14,
    dRes_INDEX_BGN_BDL_BGN_HEAD1_e=0x15,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENA_e=0x16,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENA2_e=0x17,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENA3_e=0x18,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENB_e=0x19,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENB2_e=0x1A,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENB3_e=0x1B,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENC_e=0x1C,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENC2_e=0x1D,
    dRes_INDEX_BGN_BDL_BGN_JYAKUTENC3_e=0x1E,
    dRes_INDEX_BGN_BDL_BGN_KUMO1_e=0x1F,
    dRes_INDEX_BGN_BDL_BGN_MAIN1_e=0x20,
    dRes_INDEX_BGN_BDL_R00_e=0x21,
    dRes_INDEX_BGN_BDL_R0E_A_e=0x22,
    /* BRK  */
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENB_e=0x25,
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENB2_e=0x26,
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENB3_e=0x27,
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENC_e=0x28,
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENC2_e=0x29,
    dRes_INDEX_BGN_BRK_BGN_JYAKUTENC3_e=0x2A,
    /* TEX  */
    dRes_INDEX_BGN_BTI_HIMO_e=0x2D,
    dRes_INDEX_BGN_BTI_NOT_CUT1_e=0x2E,
};

enum dRes_ID_BGN {
    /* BCK  */
    dRes_ID_BGN_BCK_BGN_HEAD1_e=0x6,
    dRes_ID_BGN_BCK_BGN_HEAD2_e=0x7,
    dRes_ID_BGN_BCK_DAMAGE1_e=0x8,
    dRes_ID_BGN_BCK_DERU1_e=0x9,
    dRes_ID_BGN_BCK_JUMP1_e=0xA,
    dRes_ID_BGN_BCK_MODORU1_e=0xB,
    dRes_ID_BGN_BCK_RAKKA1_e=0xC,
    dRes_ID_BGN_BCK_RAKKA2_e=0xD,
    dRes_ID_BGN_BCK_SETTI1_e=0xE,
    dRes_ID_BGN_BCK_WAIT1_e=0xF,
    dRes_ID_BGN_BCK_WAIT2_e=0x10,
    /* BDLM */
    dRes_ID_BGN_BDL_BGN_BODY1_e=0x13,
    dRes_ID_BGN_BDL_BGN_DEKU1_e=0x14,
    dRes_ID_BGN_BDL_BGN_HEAD1_e=0x15,
    dRes_ID_BGN_BDL_BGN_JYAKUTENA_e=0x16,
    dRes_ID_BGN_BDL_BGN_JYAKUTENA2_e=0x17,
    dRes_ID_BGN_BDL_BGN_JYAKUTENA3_e=0x18,
    dRes_ID_BGN_BDL_BGN_JYAKUTENB_e=0x19,
    dRes_ID_BGN_BDL_BGN_JYAKUTENB2_e=0x1A,
    dRes_ID_BGN_BDL_BGN_JYAKUTENB3_e=0x1B,
    dRes_ID_BGN_BDL_BGN_JYAKUTENC_e=0x1C,
    dRes_ID_BGN_BDL_BGN_JYAKUTENC2_e=0x1D,
    dRes_ID_BGN_BDL_BGN_JYAKUTENC3_e=0x1E,
    dRes_ID_BGN_BDL_BGN_KUMO1_e=0x1F,
    dRes_ID_BGN_BDL_BGN_MAIN1_e=0x20,
    dRes_ID_BGN_BDL_R00_e=0x21,
    dRes_ID_BGN_BDL_R0E_A_e=0x22,
    /* BRK  */
    dRes_ID_BGN_BRK_BGN_JYAKUTENB_e=0x25,
    dRes_ID_BGN_BRK_BGN_JYAKUTENB2_e=0x26,
    dRes_ID_BGN_BRK_BGN_JYAKUTENB3_e=0x27,
    dRes_ID_BGN_BRK_BGN_JYAKUTENC_e=0x28,
    dRes_ID_BGN_BRK_BGN_JYAKUTENC2_e=0x29,
    dRes_ID_BGN_BRK_BGN_JYAKUTENC3_e=0x2A,
    /* TEX  */
    dRes_ID_BGN_BTI_HIMO_e=0x2D,
    dRes_ID_BGN_BTI_NOT_CUT1_e=0x2E,
};

enum BGN_BODY1_JNT {
    BGN_BODY1_JNT_BGN_BODY1_e=0x0,
};

enum BGN_DEKU1_JNT {
    BGN_DEKU1_JNT_PSPHERE1_e=0x0,
};

enum BGN_HEAD1_JNT {
    BGN_HEAD1_JNT_J_BGN_ATAMA1_e=0x0,
    BGN_HEAD1_JNT_J_BGN_AGO1_e=0x1,
    BGN_HEAD1_JNT_J_BGN_HANA1_e=0x2,
    BGN_HEAD1_JNT_J_BGN_ME_L1_e=0x3,
    BGN_HEAD1_JNT_J_BGN_ME_R1_e=0x4,
    BGN_HEAD1_JNT_J_BGN_MIMI_L1_e=0x5,
    BGN_HEAD1_JNT_J_BGN_MIMI_R1_e=0x6,
};

enum BGN_JYAKUTENA_JNT {
    BGN_JYAKUTENA_JNT_BGN_JYAKUTENA_e=0x0,
};

enum BGN_JYAKUTENA2_JNT {
    BGN_JYAKUTENA2_JNT_BGN_JYAKUTENA_e=0x0,
};

enum BGN_JYAKUTENA3_JNT {
    BGN_JYAKUTENA3_JNT_BGN_JYAKUTENA_e=0x0,
};

enum BGN_JYAKUTENB_JNT {
    BGN_JYAKUTENB_JNT_BGN_JYAKUTENB_e=0x0,
};

enum BGN_JYAKUTENB2_JNT {
    BGN_JYAKUTENB2_JNT_BGN_JYAKUTENB_e=0x0,
};

enum BGN_JYAKUTENB3_JNT {
    BGN_JYAKUTENB3_JNT_BGN_JYAKUTENB_e=0x0,
};

enum BGN_JYAKUTENC_JNT {
    BGN_JYAKUTENC_JNT_BGN_JYAKUTENB1_e=0x0,
};

enum BGN_JYAKUTENC2_JNT {
    BGN_JYAKUTENC2_JNT_BGN_JYAKUTENB1_e=0x0,
};

enum BGN_JYAKUTENC3_JNT {
    BGN_JYAKUTENC3_JNT_BGN_JYAKUTENB1_e=0x0,
};

enum BGN_KUMO1_JNT {
    BGN_KUMO1_JNT_BGN2_ALLROOT_e=0x0,
    BGN_KUMO1_JNT_BGN2_SKLROOT_e=0x1,
    BGN_KUMO1_JNT_J_BGN2_KARADA1_e=0x2,
    BGN_KUMO1_JNT_ATAMA_e=0x3,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LB1_e=0x4,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LB2_e=0x5,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LB3_e=0x6,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LB4_e=0x7,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LB5_e=0x8,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LF1_e=0x9,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LF2_e=0xA,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LF3_e=0xB,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LF4_e=0xC,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LF5_e=0xD,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LM1_e=0xE,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LM2_e=0xF,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LM3_e=0x10,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LM4_e=0x11,
    BGN_KUMO1_JNT_J_BGN2_ASHI_LM5_e=0x12,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RB1_e=0x13,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RB2_e=0x14,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RB3_e=0x15,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RB4_e=0x16,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RB5_e=0x17,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RF1_e=0x18,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RF2_e=0x19,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RF3_e=0x1A,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RF4_e=0x1B,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RF5_e=0x1C,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RM1_e=0x1D,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RM2_e=0x1E,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RM3_e=0x1F,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RM4_e=0x20,
    BGN_KUMO1_JNT_J_BGN2_ASHI_RM5_e=0x21,
    BGN_KUMO1_JNT_J_BGN2_KARADA2_e=0x22,
    BGN_KUMO1_JNT_JYAKUTEN_e=0x23,
};

enum BGN_MAIN1_JNT {
    BGN_MAIN1_JNT_EXP1_GN_MAIN1_e=0x0,
};

enum R00_JNT {
    R00_JNT_WORLD_ROOT_e=0x0,
};

enum R0E_A_JNT {
    R0E_A_JNT_UMI80_UMI1_e=0x0,
};

#endif /* !RES_BGN_H */