#ifndef RES_DOGUU_H
#define RES_DOGUU_H

enum dRes_INDEX_DOGUU {
    /* BCK  */
    dRes_INDEX_DOGUU_BCK_VGSBA_e=0x6,
    dRes_INDEX_DOGUU_BCK_VGSHD_e=0x7,
    dRes_INDEX_DOGUU_BCK_VGSHF_e=0x8,
    dRes_INDEX_DOGUU_BCK_VGSHN_e=0x9,
    dRes_INDEX_DOGUU_BCK_VGSPA_e=0xA,
    /* BDLM */
    dRes_INDEX_DOGUU_BDL_VGSBA_e=0xD,
    dRes_INDEX_DOGUU_BDL_VGSHD_e=0xE,
    dRes_INDEX_DOGUU_BDL_VGSHF_e=0xF,
    dRes_INDEX_DOGUU_BDL_VGSHN_e=0x10,
    dRes_INDEX_DOGUU_BDL_VGSMA_e=0x11,
    dRes_INDEX_DOGUU_BDL_VGSPD_e=0x12,
    dRes_INDEX_DOGUU_BDL_VGSPF_e=0x13,
    dRes_INDEX_DOGUU_BDL_VGSPN_e=0x14,
    /* BMT  */
    dRes_INDEX_DOGUU_BMT_VGSBD_e=0x17,
    dRes_INDEX_DOGUU_BMT_VGSBF_e=0x18,
    dRes_INDEX_DOGUU_BMT_VGSBN_e=0x19,
    dRes_INDEX_DOGUU_BMT_VGSMD_e=0x1A,
    dRes_INDEX_DOGUU_BMT_VGSMF_e=0x1B,
    dRes_INDEX_DOGUU_BMT_VGSMN_e=0x1C,
    /* BRK  */
    dRes_INDEX_DOGUU_BRK_VGSMD_e=0x1F,
    dRes_INDEX_DOGUU_BRK_VGSMF_e=0x20,
    dRes_INDEX_DOGUU_BRK_VGSMN_e=0x21,
    dRes_INDEX_DOGUU_BTK_VGSPA_e=0x22,
};

enum dRes_ID_DOGUU {
    /* BCK  */
    dRes_ID_DOGUU_BCK_VGSBA_e=0x6,
    dRes_ID_DOGUU_BCK_VGSHD_e=0x7,
    dRes_ID_DOGUU_BCK_VGSHF_e=0x8,
    dRes_ID_DOGUU_BCK_VGSHN_e=0x9,
    dRes_ID_DOGUU_BCK_VGSPA_e=0xA,
    /* BDLM */
    dRes_ID_DOGUU_BDL_VGSBA_e=0xD,
    dRes_ID_DOGUU_BDL_VGSHD_e=0xE,
    dRes_ID_DOGUU_BDL_VGSHF_e=0xF,
    dRes_ID_DOGUU_BDL_VGSHN_e=0x10,
    dRes_ID_DOGUU_BDL_VGSMA_e=0x11,
    dRes_ID_DOGUU_BDL_VGSPD_e=0x12,
    dRes_ID_DOGUU_BDL_VGSPF_e=0x13,
    dRes_ID_DOGUU_BDL_VGSPN_e=0x14,
    /* BMT  */
    dRes_ID_DOGUU_BMT_VGSBD_e=0x17,
    dRes_ID_DOGUU_BMT_VGSBF_e=0x18,
    dRes_ID_DOGUU_BMT_VGSBN_e=0x19,
    dRes_ID_DOGUU_BMT_VGSMD_e=0x1A,
    dRes_ID_DOGUU_BMT_VGSMF_e=0x1B,
    dRes_ID_DOGUU_BMT_VGSMN_e=0x1C,
    /* BRK  */
    dRes_ID_DOGUU_BRK_VGSMD_e=0x1F,
    dRes_ID_DOGUU_BRK_VGSMF_e=0x20,
    dRes_ID_DOGUU_BRK_VGSMN_e=0x21,
    dRes_ID_DOGUU_BTK_VGSPA_e=0x22,
};

enum VGSBA_JNT {
    VGSBA_JNT_CENTER_e=0x0,
    VGSBA_JNT_BACKBONE_e=0x1,
    VGSBA_JNT_NECK_e=0x2,
    VGSBA_JNT_HEAD1_e=0x3,
    VGSBA_JNT_SHOULDERL_e=0x4,
    VGSBA_JNT_ARML1_e=0x5,
    VGSBA_JNT_ARML2_e=0x6,
    VGSBA_JNT_HANDL_e=0x7,
    VGSBA_JNT_SHOULDERR_e=0x8,
    VGSBA_JNT_ARMR1_e=0x9,
    VGSBA_JNT_ARNR2_e=0xA,
    VGSBA_JNT_HANDR_e=0xB,
    VGSBA_JNT_WAIST_e=0xC,
};

enum VGSHD_JNT {
    VGSHD_JNT_HEAD2_e=0x0,
    VGSHD_JNT_BACKHAIR1_e=0x1,
    VGSHD_JNT_BACKHAIR2_e=0x2,
    VGSHD_JNT_SIDEHAIRL_e=0x3,
    VGSHD_JNT_SIDEHAIRR_e=0x4,
};

enum VGSHF_JNT {
    VGSHF_JNT_HEAD2_e=0x0,
    VGSHF_JNT_SIDEHAIRL_e=0x1,
    VGSHF_JNT_SIDEHAIRR_e=0x2,
};

enum VGSHN_JNT {
    VGSHN_JNT_HEAD2_e=0x0,
    VGSHN_JNT_BACKHAIR1_e=0x1,
    VGSHN_JNT_BACKHAIR2_e=0x2,
    VGSHN_JNT_SIDEHAIRL_e=0x3,
    VGSHN_JNT_SIDEHAIRR_e=0x4,
};

enum VGSMA_JNT {
    VGSMA_JNT_MUDDOLL_e=0x0,
    VGSMA_JNT_MUD_EYE_e=0x1,
};

enum VGSPD_JNT {
    VGSPD_JNT_GS_PEARL_e=0x0,
    VGSPD_JNT_GS_P_MARK_e=0x1,
};

enum VGSPF_JNT {
    VGSPF_JNT_GS_PEARL_e=0x0,
    VGSPF_JNT_GS_P_MARK_e=0x1,
};

enum VGSPN_JNT {
    VGSPN_JNT_GS_PEARL_e=0x0,
    VGSPN_JNT_GS_P_MARK_e=0x1,
};

#endif /* !RES_DOGUU_H */