#ifndef RES_DR_H
#define RES_DR_H

//
// Generated by res_arc.py from archive: Dr.arc
// Do not manually modify this file or your changes will be overwritten.
//

enum dRes_INDEX_DR {
    /* BAS  */
    dRes_INDEX_DR_BAS_ABARE1_e=0x5,
    dRes_INDEX_DR_BAS_ABARE2_e=0x6,
    dRes_INDEX_DR_BAS_AKUBI1_e=0x7,
    dRes_INDEX_DR_BAS_BIKU1_e=0x8,
    /* BCK  */
    dRes_INDEX_DR_BCK_DR_ABARE1_e=0xB,
    dRes_INDEX_DR_BCK_DR_ABARE2_e=0xC,
    dRes_INDEX_DR_BCK_DR_AKUBI1_e=0xD,
    dRes_INDEX_DR_BCK_DR_BIKU1_e=0xE,
    dRes_INDEX_DR_BCK_DR_HO1_e=0xF,
    dRes_INDEX_DR_BCK_DR_WAIT1_e=0x10,
    /* BMD  */
    dRes_INDEX_DR_BMD_DR1_e=0x13,
};

enum dRes_ID_DR {
    /* BAS  */
    dRes_ID_DR_BAS_ABARE1_e=0x5,
    dRes_ID_DR_BAS_ABARE2_e=0x6,
    dRes_ID_DR_BAS_AKUBI1_e=0x7,
    dRes_ID_DR_BAS_BIKU1_e=0x8,
    /* BCK  */
    dRes_ID_DR_BCK_DR_ABARE1_e=0xB,
    dRes_ID_DR_BCK_DR_ABARE2_e=0xC,
    dRes_ID_DR_BCK_DR_AKUBI1_e=0xD,
    dRes_ID_DR_BCK_DR_BIKU1_e=0xE,
    dRes_ID_DR_BCK_DR_HO1_e=0xF,
    dRes_ID_DR_BCK_DR_WAIT1_e=0x10,
    /* BMD  */
    dRes_ID_DR_BMD_DR1_e=0x13,
};

enum DR1_JNT {
    DR1_JNT_DR_ALL_ROOT_e=0x0,
    DR1_JNT_DR_SKL_ROOT_e=0x1,
    DR1_JNT_J_DR_KOSHI_e=0x2,
    DR1_JNT_J_DR_ASHI_L1_e=0x3,
    DR1_JNT_J_DR_ASHI_L2_e=0x4,
    DR1_JNT_J_DR_ASHI_L3_e=0x5,
    DR1_JNT_J_DR_ASHI_R1_e=0x6,
    DR1_JNT_J_DR_ASHI_R2_e=0x7,
    DR1_JNT_J_DR_ASI_R3_e=0x8,
    DR1_JNT_J_DR_MUNE_e=0x9,
    DR1_JNT_J_DR_HANE_L1_e=0xA,
    DR1_JNT_J_DR_HANE_L2_e=0xB,
    DR1_JNT_J_DR_HANE_L3_e=0xC,
    DR1_JNT_J_DR_HANE_R1_e=0xD,
    DR1_JNT_J_DR_HANE_R2_e=0xE,
    DR1_JNT_J_DR_HANE_R3_e=0xF,
    DR1_JNT_J_DR_KUBI1_e=0x10,
    DR1_JNT_J_DR_KUBI2_e=0x11,
    DR1_JNT_J_DR_KUBI3_e=0x12,
    DR1_JNT_J_DR_KUBI4_e=0x13,
    DR1_JNT_J_DR_KUBI5_e=0x14,
    DR1_JNT_J_DR_KUBI6_e=0x15,
    DR1_JNT_J_DR_KUBI7_e=0x16,
    DR1_JNT_J_DR_KUBI8_e=0x17,
    DR1_JNT_J_DR_KUBI9_e=0x18,
    DR1_JNT_J_DR_ATAMA_e=0x19,
    DR1_JNT_J_DR_AGO_e=0x1A,
    DR1_JNT_J_DR_HIGE1_e=0x1B,
    DR1_JNT_J_DR_HIGE2_e=0x1C,
    DR1_JNT_J_DR_HIGE3_e=0x1D,
    DR1_JNT_J_DR_HIGE4_e=0x1E,
    DR1_JNT_J_DR_SITA1_e=0x1F,
    DR1_JNT_J_DR_SITA2_e=0x20,
    DR1_JNT_J_DR_HOHO_L_e=0x21,
    DR1_JNT_J_DR_HOHO_R_e=0x22,
    DR1_JNT_J_DR_MABUTA_LS_e=0x23,
    DR1_JNT_J_DR_MABUTA_LU_e=0x24,
    DR1_JNT_J_DR_MABUTA_RS_e=0x25,
    DR1_JNT_J_DR_MABUTA_RU_e=0x26,
    DR1_JNT_J_DR_MAYU_L1_e=0x27,
    DR1_JNT_J_DR_MAYU_L2_e=0x28,
    DR1_JNT_J_DR_MAYU_R1_e=0x29,
    DR1_JNT_J_DR_MAYU_R2_e=0x2A,
    DR1_JNT_J_DR_ME_L_e=0x2B,
    DR1_JNT_J_DR_ME_R_e=0x2C,
    DR1_JNT_J_DR_UDE_L1_e=0x2D,
    DR1_JNT_J_DR_UDE_L2_e=0x2E,
    DR1_JNT_J_DR_UDE_L3_e=0x2F,
    DR1_JNT_J_DR_YUBI_LA_e=0x30,
    DR1_JNT_J_DR_YUBI_LB_e=0x31,
    DR1_JNT_J_DR_YUBI_LC_e=0x32,
    DR1_JNT_J_DR_YUBI_LO_e=0x33,
    DR1_JNT_J_DR_UDE_R1_e=0x34,
    DR1_JNT_J_DR_UDE_R2_e=0x35,
    DR1_JNT_J_DR_UDE_R3_e=0x36,
    DR1_JNT_J_DR_YUBI_RA_e=0x37,
    DR1_JNT_J_DR_YUBI_RB_e=0x38,
    DR1_JNT_J_DR_YUBI_RC_e=0x39,
    DR1_JNT_J_DR_YUBI_RO_e=0x3A,
    DR1_JNT_J_DR_SIPPO1_e=0x3B,
    DR1_JNT_J_DR_SIPPO2_e=0x3C,
    DR1_JNT_J_DR_SIPPO3_e=0x3D,
    DR1_JNT_J_DR_SIPPO4_e=0x3E,
};

#endif /* RES_DR_H */
