#ifndef RES_GNNDEMOTAKIS_H
#define RES_GNNDEMOTAKIS_H

enum dRes_INDEX_GNNDEMOTAKIS {
    /* BDLM */
    dRes_INDEX_GNNDEMOTAKIS_BDL_GNN_DEMO_TAKI_S_e=0x4,
    /* BTK  */
    dRes_INDEX_GNNDEMOTAKIS_BTK_GNN_DEMO_TAKI_S_e=0x7,
};

enum dRes_ID_GNNDEMOTAKIS {
    /* BDLM */
    dRes_ID_GNNDEMOTAKIS_BDL_GNN_DEMO_TAKI_S_e=0x4,
    /* BTK  */
    dRes_ID_GNNDEMOTAKIS_BTK_GNN_DEMO_TAKI_S_e=0x7,
};

enum GNN_DEMO_TAKI_S_JNT {
    GNN_DEMO_TAKI_S_JNT_LOCATOR2_e=0x0,
    GNN_DEMO_TAKI_S_JNT_TAKI_e=0x1,
    GNN_DEMO_TAKI_S_JNT_WAREME1_e=0x2,
};

#endif /* !RES_GNNDEMOTAKIS_H */