#ifndef RES_GOVER_H
#define RES_GOVER_H

enum dRes_INDEX_GOVER {
    /* SCRN */
    dRes_INDEX_GOVER_BLO_GAMEOVER_e=0x4,
    dRes_INDEX_GOVER_BLO_GAMEOVER_SP_e=0x5,
    /* TIMG */
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_A_BIG_e=0x8,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_D_BIG_e=0x9,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_E_BIG_e=0xA,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_F_BIG_e=0xB,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_G_BIG_e=0xC,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_I_BIG_e=0xD,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_L_BIG_e=0xE,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_M_BIG_e=0xF,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_N_BIG_e=0x10,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_O_BIG_e=0x11,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_P_BIG_e=0x12,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_R_BIG_e=0x13,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_T_BIG_e=0x14,
    dRes_INDEX_GOVER_BTI_G_SHIPFONT_V_BIG_e=0x15,
    dRes_INDEX_GOVER_BTI_G_SMOKE_e=0x16,
};

enum dRes_ID_GOVER {
    /* SCRN */
    dRes_ID_GOVER_BLO_GAMEOVER_e=0x4,
    dRes_ID_GOVER_BLO_GAMEOVER_SP_e=0x5,
    /* TIMG */
    dRes_ID_GOVER_BTI_G_SHIPFONT_A_BIG_e=0x8,
    dRes_ID_GOVER_BTI_G_SHIPFONT_D_BIG_e=0x9,
    dRes_ID_GOVER_BTI_G_SHIPFONT_E_BIG_e=0xA,
    dRes_ID_GOVER_BTI_G_SHIPFONT_F_BIG_e=0xB,
    dRes_ID_GOVER_BTI_G_SHIPFONT_G_BIG_e=0xC,
    dRes_ID_GOVER_BTI_G_SHIPFONT_I_BIG_e=0xD,
    dRes_ID_GOVER_BTI_G_SHIPFONT_L_BIG_e=0xE,
    dRes_ID_GOVER_BTI_G_SHIPFONT_M_BIG_e=0xF,
    dRes_ID_GOVER_BTI_G_SHIPFONT_N_BIG_e=0x10,
    dRes_ID_GOVER_BTI_G_SHIPFONT_O_BIG_e=0x11,
    dRes_ID_GOVER_BTI_G_SHIPFONT_P_BIG_e=0x12,
    dRes_ID_GOVER_BTI_G_SHIPFONT_R_BIG_e=0x13,
    dRes_ID_GOVER_BTI_G_SHIPFONT_T_BIG_e=0x14,
    dRes_ID_GOVER_BTI_G_SHIPFONT_V_BIG_e=0x15,
    dRes_ID_GOVER_BTI_G_SMOKE_e=0x16,
};

#endif /* !RES_GOVER_H */