#ifndef RES_TORIPOST_H
#define RES_TORIPOST_H

enum dRes_INDEX_TORIPOST {
    /* BCKS */
    dRes_INDEX_TORIPOST_BCK_POST_GET_e=0x4,
    dRes_INDEX_TORIPOST_BCK_POST_PUTOUT_e=0x5,
    dRes_INDEX_TORIPOST_BCK_POST_WAIT_e=0x6,
    /* BDL  */
    dRes_INDEX_TORIPOST_BDL_VPOST_e=0x9,
};

enum dRes_ID_TORIPOST {
    /* BCKS */
    dRes_ID_TORIPOST_BCK_POST_GET_e=0x4,
    dRes_ID_TORIPOST_BCK_POST_PUTOUT_e=0x5,
    dRes_ID_TORIPOST_BCK_POST_WAIT_e=0x6,
    /* BDL  */
    dRes_ID_TORIPOST_BDL_VPOST_e=0x9,
};

enum VPOST_JNT {
    VPOST_JNT_ROOT_APOST_e=0x0,
    VPOST_JNT_BODY_e=0x1,
    VPOST_JNT_MOUTH_e=0x2,
};

#endif /* !RES_TORIPOST_H */