#ifndef RES_VTIN2_H
#define RES_VTIN2_H

//
// Generated by res_arc.py from archive: Vtin2.arc
// Do not manually modify this file or your changes will be overwritten.
//

enum dRes_INDEX_VTIN2 {
    /* BDL  */
    dRes_INDEX_VTIN2_BDL_VTIN2_e=0x3,
};

enum dRes_ID_VTIN2 {
    /* BDL  */
    dRes_ID_VTIN2_BDL_VTIN2_e=0x3,
};

enum VTIN2_JNT {
    VTIN2_JNT_VTIN2_MODEL_e=0x0,
};

#endif /* RES_VTIN2_H */
