//
// Generated by dtk
// Translation Unit: d_bg_s_movebg_actor.cpp
//

#include "d_bg_s_movebg_actor.h"
#include "dolphin/types.h"

/* 800A56B8-800A56FC       .text __ct__16dBgS_MoveBgActorFv */
dBgS_MoveBgActor::dBgS_MoveBgActor() {
    /* Nonmatching */
}

/* 800A56FC-800A571C       .text CheckCreateHeap__FP10fopAc_ac_c */
void CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 800A571C-800A57F4       .text MoveBGCreateHeap__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::MoveBGCreateHeap() {
    /* Nonmatching */
}

/* 800A57F4-800A58F4       .text MoveBGCreate__16dBgS_MoveBgActorFPCciPFP4dBgWPvR13cBgS_PolyInfobP4cXyzP5csXyzP5csXyz_vUl */
void dBgS_MoveBgActor::MoveBGCreate(const char*, int, void (*)(dBgW*, void*, cBgS_PolyInfo&, bool, cXyz*, csXyz*, csXyz*), unsigned long) {
    /* Nonmatching */
}

/* 800A58F4-800A5980       .text MoveBGDelete__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::MoveBGDelete() {
    /* Nonmatching */
}

/* 800A5980-800A5A3C       .text MoveBGExecute__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::MoveBGExecute() {
    /* Nonmatching */
}

/* 800A5A3C-800A5A44       .text CreateHeap__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::CreateHeap() {
    /* Nonmatching */
}

/* 800A5A44-800A5A4C       .text Create__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::Create() {
    /* Nonmatching */
}

/* 800A5A4C-800A5A54       .text Delete__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::Delete() {
    /* Nonmatching */
}

/* 800A5A54-800A5A5C       .text Execute__16dBgS_MoveBgActorFPPA3_A4_f */
void dBgS_MoveBgActor::Execute(float(**)[3][4]) {
    /* Nonmatching */
}

/* 800A5A5C-800A5A64       .text Draw__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::Draw() {
    /* Nonmatching */
}

/* 800A5A64-800A5A6C       .text IsDelete__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::IsDelete() {
    /* Nonmatching */
}

/* 800A5A6C-800A5A74       .text ToFore__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::ToFore() {
    /* Nonmatching */
}

/* 800A5A74-800A5A7C       .text ToBack__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::ToBack() {
    /* Nonmatching */
}

