//
// Generated by dtk
// Translation Unit: d_menu_fmap.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_menu_fmap.h"
#include "dolphin/types.h"
#include "f_op/f_op_msg_mng.h"
#include "m_Do/m_Do_controller_pad.h"
#include "m_Do/m_Do_hostIO.h"
#include "printf.h"
#include "res/Object/X_futa.h"
#include "res/Object/X_tower.h"

dMf_HIO_c g_mfHIO;

/* 801AF4F0-801AF848       .text __ct__9dMf_HIO_cFv */
dMf_HIO_c::dMf_HIO_c() {
    /* Nonmatching */
}

/* 801AF848-801AFB64       .text _create__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::_create() {
    /* Nonmatching */
    mFmapMode = FMAP_MODE_NORMAL;
}

/* 801AFB64-801AFBDC       .text phantomShipCheck__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::phantomShipCheck() {
    /* Nonmatching */
}

/* 801AFBDC-801B06D4       .text screenSet__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::screenSet() {
    /* Nonmatching */
}

/* 801B06D4-801B0FB4       .text initialize__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::initialize() {
    /* Nonmatching */
}

/* 801B0FB4-801B1200       .text displayinit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::displayinit() {
    /* Nonmatching */
}

/* 801B1200-801B1210       .text backClothDispInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::backClothDispInit() {
    mClPane.pane->hide();
}

/* 801B1210-801B1374       .text calcGetMapCount__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::calcGetMapCount() {
    /* Nonmatching */
}

/* 801B1374-801B14C4       .text dispEndSalvageMark__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::dispEndSalvageMark() {
    /* Nonmatching */
}

/* 801B14C4-801B1684       .text checkMarkCheck1__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkMarkCheck1() {
    /* Nonmatching */
}

/* 801B1684-801B1714       .text checkMarkCheck2__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkMarkCheck2() {
    /* Nonmatching */
}

/* 801B1714-801B190C       .text checkMarkCheck3__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkMarkCheck3() {
    /* Nonmatching */
}

/* 801B190C-801B1914       .text isFmapClose__12dMenu_Fmap_cFv */
bool dMenu_Fmap_c::isFmapClose() {
    return mMapClose;
}

/* 801B1914-801B1978       .text setPaneOnOff__12dMenu_Fmap_cFP9J2DScreenUlb */
void dMenu_Fmap_c::setPaneOnOff(J2DScreen*, unsigned long, bool) {
    /* Nonmatching */
}

/* 801B1978-801B19F0       .text childPaneMoveSp__12dMenu_Fmap_cFP18fopMsgM_pane_classP18fopMsgM_pane_classfff */
void dMenu_Fmap_c::childPaneMoveSp(fopMsgM_pane_class*, fopMsgM_pane_class*, float, float, float) {
    /* Nonmatching */
}

/* 801B19F0-801B1A80       .text selGridMaskAlphaCtrl__12dMenu_Fmap_cFsUcUci */
void dMenu_Fmap_c::selGridMaskAlphaCtrl(short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801B1A80-801B1B10       .text fmapMaskAlphaCtrl__12dMenu_Fmap_cFsUcUci */
void dMenu_Fmap_c::fmapMaskAlphaCtrl(short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801B1B10-801B1B58       .text selCursorInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::selCursorInit() {
    mSelCursorBufIdx = 0;
    for (int i = 0; i < 4; i++) {
        mKk1xPanes[i].pane->show();
        mKk2xPanes[i].pane->hide();
    }
    mKk1xPanes->mUserArea = g_mfHIO.field_0x3A;
}

/* 801B1B58-801B1B80       .text selCursorHide__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::selCursorHide() {
    for (int i = 0; i < 8; i++) {
        mKk1xPanes[i].pane->hide();
    }
}

/* 801B1B80-801B1CF0       .text selCursorMove__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::selCursorMove() {
    /* Nonmatching */
}

/* 801B1CF0-801B1D48       .text islandNameChange__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::islandNameChange() {
    if (mAreaTxtChanging == TRUE) {
        AreaTxtChgFast();
    } else {
        mAreaTxtChanging = TRUE;
    }
    changeIslandName(mAreaTxtBufIdx ^ 1);
}

/* 801B1D48-801B1FCC       .text changeIslandName__12dMenu_Fmap_cFUc */
void dMenu_Fmap_c::changeIslandName(unsigned char) {
    /* Nonmatching */
}

/* 801B1FCC-801B2044       .text AreaTxtChg__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::AreaTxtChg() {
    /* Nonmatching */
}

/* 801B2044-801B20E0       .text AreaTxtChgFast__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::AreaTxtChgFast() {
    mAreaTxtTimer = false;
    fopMsgM_setNowAlpha(&mAreaTxtPanes[mAreaTxtBufIdx ^ 1], 1.0f);
    fopMsgM_setAlpha(&mAreaTxtPanes[mAreaTxtBufIdx ^ 1]);
    fopMsgM_setNowAlpha(&mAreaTxtPanes[mAreaTxtBufIdx], 0.0f);
    fopMsgM_setAlpha(&mAreaTxtPanes[mAreaTxtBufIdx]);
    mAreaTxtBufIdx ^= 1;
}

/* 801B20E0-801B2154       .text salvageGetItemChg__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::salvageGetItemChg() {
    /* Nonmatching */
}

/* 801B2154-801B21AC       .text salvageGetItemChange__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::salvageGetItemChange() {
    if (mSalvItmChanging == TRUE) {
        SalvItmDispChgFast();
    } else {
        mSalvItmChanging = TRUE;
    }
    changeSalvageGetItem(mSalvItmBufIdx ^ 1);
}

/* 801B21AC-801B2274       .text SalvItmDispChgFast__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::SalvItmDispChgFast() {
    mSalvItmTimer = 0;
    if (mFullMapMode == TRUE) {
        fopMsgM_setNowAlpha(&mKk1xPanes[mSalvItmBufIdx ^ 1], 1.0f);
    } else {
        fopMsgM_setNowAlpha(&mKk1xPanes[mSalvItmBufIdx ^ 1], 0.0f);
    }
    fopMsgM_setAlpha(&mKk1xPanes[mSalvItmBufIdx ^ 1]);
    fopMsgM_setNowAlpha(&mKk1xPanes[mSalvItmBufIdx], 0.0f);
    fopMsgM_setAlpha(&mKk1xPanes[mSalvItmBufIdx]);
    mSalvItmBufIdx ^= 1;
}

/* 801B2274-801B23EC       .text changeSalvageGetItem__12dMenu_Fmap_cFUc */
void dMenu_Fmap_c::changeSalvageGetItem(unsigned char) {
    /* Nonmatching */
}

/* 801B23EC-801B247C       .text selCursorAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::selCursorAnime() {
    /* Nonmatching */
}

/* 801B247C-801B24C4       .text zoomCursorInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::zoomCursorInit() {
    mCursorBufIdx = 0;
    for (int i = 0; i < 4; i++) {
        mKk3xPanes[i].pane->show();
        mKk4xPanes[i].pane->hide();
    }
    mKk3xPanes[0].mUserArea = g_mfHIO.field_0x3A;
}

/* 801B24C4-801B2554       .text zoomCursorAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::zoomCursorAnime() {
    /* Nonmatching */
}

/* 801B2554-801B2570       .text playerPointGridAnimeInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::playerPointGridAnimeInit() {
    field_0x510F = g_mfHIO.field_0x28;
    field_0x5110 = 0;
}

/* 801B2570-801B2830       .text playerPointGridAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::playerPointGridAnime() {
    /* Nonmatching */
}

/* 801B2830-801B2A14       .text setDspWindAngle__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::setDspWindAngle() {
    /* Nonmatching */
}

/* 801B2A14-801B3284       .text windArrowColorAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::windArrowColorAnime() {
    /* Nonmatching */
}

/* 801B3284-801B32A0       .text checkMarkAnimeInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkMarkAnimeInit() {
    mFishmanMsgTimer = g_mfHIO.field_0xE0;
    mFishmanMsgToggle = 1;
}

/* 801B32A0-801B3658       .text checkMarkAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkMarkAnime() {
    /* Nonmatching */
}

/* 801B3658-801B3698       .text readFmapTexture__12dMenu_Fmap_cFPCc */
u32 dMenu_Fmap_c::readFmapTexture(const char* i_filename) {
    JKRArchive* archive = dComIfGp_getFmapArchive();
    return JKRArchive::readTypeResource(mpImg, 0x2c00, 'FM  ', i_filename, archive);
}

/* 801B3698-801B36F0       .text aramCmapDatRead__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::aramCmapDatRead() {
    JKRArchive* archive = dComIfGp_getFmapResArchive();
    aramCmapDatPat_t* pat = (aramCmapDatPat_t*)JKRArchive::getGlbResource('DATA', "CmapDat.bin", archive);
    initCmapDatPnt(pat);
}

/* 801B36F0-801B3760       .text initCmapDatPnt__12dMenu_Fmap_cFP16aramCmapDatPat_t */
void dMenu_Fmap_c::initCmapDatPnt(aramCmapDatPat_t* a_pat) {
    if (a_pat != NULL) {
        mCmapDatPnt.m_0x0 = a_pat->m_0x0;
        mCmapDatPnt.m_0x4 = (aramCmapDatPnt_t*)&a_pat->m_0x4;
    } else {
        JUT_ASSERT(0xFC, 0);
    }
}

/* 801B3760-801B37B0       .text getGridNumToCmapDatPnt__12dMenu_Fmap_cFi */
aramCmapDatPnt_t* dMenu_Fmap_c::getGridNumToCmapDatPnt(int i_param) {
    int i;
    aramCmapDatPnt_t* pat = mCmapDatPnt.m_0x4;
    int num;
    for (i = 0, num = mCmapDatPnt.m_0x0; i < num; i++) {
        if (pat->field_0x0 == i_param + 1) {
            break;
        }
        pat++;
    }
    if (i < num) {
        return pat;
    }
    return NULL;
}

/* 801B37B0-801B392C       .text setDispIslandPos__12dMenu_Fmap_cFScSc */
void dMenu_Fmap_c::setDispIslandPos(signed char, signed char) {
    /* Nonmatching */
}

/* 801B392C-801B3984       .text setIslandPos__12dMenu_Fmap_cFP18fopMsgM_pane_classff */
void dMenu_Fmap_c::setIslandPos(fopMsgM_pane_class* i_pane, float i_x, float i_y) {
    float scale = 0.5f;
    f32 newX = mClbPane.mSizeOrig.x * scale;
    i_pane->mPosCenterOrig.x = newX + i_x;
    f32 newY = mClbPane.mSizeOrig.y * scale;
    i_pane->mPosCenterOrig.y = newY + i_y;

    i_pane->mPosCenter = i_pane->mPosCenterOrig;
    fopMsgM_cposMove(i_pane);
}

/* 801B3984-801B3A2C       .text changeFmapTexture__12dMenu_Fmap_cFScSc */
void dMenu_Fmap_c::changeFmapTexture(signed char i_x, signed char i_y) {
    char filename[64];
    sprintf(filename, "R%02X_b.bti", i_x + (i_y + 3) * 7 + 4);
    if (readFmapTexture(filename) == NULL) {
        mR01bPane.pane->hide();
        mR01gPane.pane->hide();
    } else {
        ((J2DPicture*)mR01bPane.pane)->changeTexture(mpImg, 0);
        ((J2DPicture*)mR01gPane.pane)->changeTexture(mpImg, 0);
    }
}

/* 801B3A2C-801B3C4C       .text setDspNormalMapLink__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::setDspNormalMapLink() {
    /* Nonmatching */
}

/* 801B3C4C-801B3DFC       .text setDspLargeMapLink__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::setDspLargeMapLink() {
    /* Nonmatching */
}

/* 801B3DFC-801B3F28       .text checkDspLargeMapLink__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkDspLargeMapLink() {
    /* Nonmatching */
}

/* 801B3F28-801B405C       .text checkDspLargeMapShip__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkDspLargeMapShip() {
    /* Nonmatching */
}

/* 801B405C-801B4264       .text dispEndSalvageLargeMark__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::dispEndSalvageLargeMark() {
    /* Nonmatching */
}

/* 801B4264-801B4640       .text setDspHugeMapLink__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::setDspHugeMapLink() {
    /* Nonmatching */
}

/* 801B4640-801B48C4       .text dispEndSalvageHugeMark__12dMenu_Fmap_cFff */
void dMenu_Fmap_c::dispEndSalvageHugeMark(float, float) {
    /* Nonmatching */
}

/* 801B48C4-801B49F0       .text checkDspHugeMapLink__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkDspHugeMapLink() {
    /* Nonmatching */
}

/* 801B49F0-801B4B44       .text checkDspHugeMapShip__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::checkDspHugeMapShip() {
    /* Nonmatching */
}

/* 801B4B44-801B4C0C       .text _open__12dMenu_Fmap_cFv */
BOOL dMenu_Fmap_c::_open() {
    int ret;
    if (mFrameTimer == 0) {
        mButtonIconMode = FMAP_BTN_ICON_WORLD;
    }
    if (mZoomLocked) {
        ret = 1;
    } else {
        ret = paneTransBase(mFrameTimer - g_mfHIO.field_0x33, g_mfHIO.field_0x34, g_mfHIO.field_0x36, 0.0, NULL, 0);
        mFrameTimer += 1;
    }
    if (ret == TRUE) {
        mFrameTimer = 0;
        return TRUE;
    }
    return FALSE;
}

/* 801B4C0C-801B4C78       .text _close__12dMenu_Fmap_cFv */
BOOL dMenu_Fmap_c::_close() {
    BOOL ret;
    switch (mFmapMode) {
        case FMAP_MODE_NORMAL:
        case FMAP_MODE_WALLPAPER:
            ret = _close_normalMode();
            break;
        case FMAP_MODE_WARP:
            ret = _close_warpMode();
            break;
        case FMAP_MODE_FISHMAN:
            ret = _close_fishManMode();
            break;
    }
    return ret;
}

/* 801B4C78-801B4D78       .text _close_normalMode__12dMenu_Fmap_cFv */
BOOL dMenu_Fmap_c::_close_normalMode() {
    /* Nonmatching */
    return FALSE;
}

/* 801B4D78-801B4E14       .text _move__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::_move() {
    switch (mFmapMode) {
        case FMAP_MODE_NORMAL:
            move_normal();
            break;
        case FMAP_MODE_WARP:
            moveMain_warpMode();
            break;
        case FMAP_MODE_WALLPAPER:
            if (CPad_CHECK_TRIG_LEFT(0) || CPad_CHECK_TRIG_DOWN(0) || CPad_CHECK_TRIG_B(0)) {
                mMapClose = TRUE;
            } else {
                mMapClose = FALSE;
            }
            break;
        case FMAP_MODE_FISHMAN:
            movefishManMode();
            break;
    }
}

/* 801B4E14-801B4E6C       .text _draw__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::_draw() {
    dComIfGd_set2DOpa(&mDlst);
    if (mMainProcIdx == 1) {
        mFmap2._draw();
    }
}

/* 801B4E6C-801B4F40       .text _delete__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::_delete() {
    /* Nonmatching */
}

/* 801B4F40-801B5034       .text FmapProcMain__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::FmapProcMain() {
    /* Nonmatching */
}

/* 801B5034-801B5878       .text SelectGrid__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::SelectGrid() {
    /* Nonmatching */
    if (dComIfGs_isSaveArriveGrid(fmapSv->field_0x4 + (fmapSv->field_0x5 + 3) * 7 + 3)) {
        mButtonIconMode = FMAP_BTN_ICON_LOCKED;
    } else {
        mButtonIconMode = FMAP_BTN_ICON_SECTOR;
    }
    JUT_ASSERT(0x1E9, fmapSv != NULL);
}

/* 801B5878-801B5B58       .text zoom1000x1000Init__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::zoom1000x1000Init() {
    /* Nonmatching */
}

/* 801B5B58-801B5BB4       .text zoomMapAlphaSet__12dMenu_Fmap_cFScScP18fopMsgM_pane_classUc */
void dMenu_Fmap_c::zoomMapAlphaSet(signed char i_gridX, signed char i_gridY, fopMsgM_pane_class* i_pane, unsigned char i_alpha) {
    if ((i_gridX + 3) + (i_gridY + 3) * 7 == 0x19) {
        i_pane->mInitAlpha = i_alpha;
    } else {
        i_pane->mInitAlpha = 0xFF;
    }
    i_pane->mInitAlpha = 0xFF;
    fopMsgM_setAlpha(i_pane);
}

/* 801B5BB4-801B5D6C       .text ZoomGridLv1In__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv1In() {
    /* Nonmatching */
}

/* 801B5D6C-801B5F80       .text ZoomGridLv1Proc__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv1Proc() {
    /* Nonmatching */
    if (CPad_CHECK_TRIG_A(0) != 0 || mWarpScrollGuard != false) {
        if (mButtonIconMode == 1) {
            mDoAud_seStart(JA_SE_CHART_ZOOM_IN);
            mButtonIconMode = FMAP_BTN_ICON_DETAIL;
            JUT_ASSERT(0x1E3, fmapSv != NULL)
            fmapSv->field_0x1 = 0x2;
            zoom200x200Init();
            f32 clgOrigX = mClgPane.mSizeOrig.x;
            paneTranceZoom2Map(0, g_mfHIO.field_0x2F, field_0x5134 * (clgOrigX / 100000.0f),
                field_0x5138 * (mClgPane.mSizeOrig.y / 100000.0f), 0.0, 0.0,
                mTsw1Pane.mSizeOrig.x / clgOrigX, 1.0, 0x2, 0);
            for (int i = 0; i < 8; i++) {
                mKk3xPanes[i].pane->mInheritAlpha = FALSE;
            }
            mR01bPane.pane->mInheritAlpha = FALSE;
            mFrameTimer = 0;
            mFmapProcIdx = 4;
        }
        mWarpScrollGuard = FALSE;
    } else {
        if (CPad_CHECK_TRIG_B(0) || mWarpAnimActive) {
            mDoAud_seStart(JA_SE_CHART_ZOOM_OUT);
            if (field_0x5182 != 0) {
                mLnk2Pane.pane->hide();
            }
            if (field_0x5184) {
                mSpi2Pane.pane->hide();
            }
            mWarpAnimActive = FALSE;
            zoomCursorInit();
            mFmapProcIdx = 3;
        }
    }
    zoomCursorAnime();
}

/* 801B5F80-801B6084       .text zoom200x200Init__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::zoom200x200Init() {
    zoomMapAlphaSet(getCtZoomGridX(), getCtZoomGridY(), &mR01gPane, 0x1E);
    zoomCursorInit();
    setDspHugeMapLink();
    checkDspHugeMapLink();
    checkDspHugeMapShip();
    mClgPane.pane->show();
}

/* 801B6084-801B6270       .text ZoomGridLv1Out__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv1Out() {
    /* Nonmatching */
}

/* 801B6270-801B6388       .text ZoomGridLv2In__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv2In() {
    /* Nonmatching */
}

/* 801B6388-801B6440       .text ZoomGridLv2Proc__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv2Proc() {
    /* Nonmatching */
}

/* 801B6440-801B65D8       .text ZoomGridLv2Out__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::ZoomGridLv2Out() {
    /* Nonmatching */
}

/* 801B65D8-801B6610       .text move_normal__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::move_normal() {
    /* Nonmatching */
}

/* 801B6610-801B66DC       .text FmapProc__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::FmapProc() {
    /* Nonmatching */
}

/* 801B66DC-801B6714       .text HikakuProc__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::HikakuProc() {
    /* Nonmatching */
}

/* 801B6714-801B678C       .text fmap2Open__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmap2Open() {
    /* Nonmatching */
}

/* 801B678C-801B68A0       .text fmap2Move__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmap2Move() {
    /* Nonmatching */
}

/* 801B68A0-801B68EC       .text fmap2Close__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmap2Close() {
    /* Nonmatching */
}

/* 801B68EC-801B6A7C       .text paneTransBase__12dMenu_Fmap_cFsUcffUci */
int dMenu_Fmap_c::paneTransBase(short, unsigned char, float, float, unsigned char, int) {
    /* Nonmatching */
    return false;
}

/* 801B6A7C-801B6F88       .text paneTranceZoomMap__12dMenu_Fmap_cFsUcffffffUci */
void dMenu_Fmap_c::paneTranceZoomMap(short, unsigned char, float, float, float, float, float, float, unsigned char, int) {
    /* Nonmatching */
}

/* 801B6F88-801B7018       .text paneTranceZoomMapAlpah__12dMenu_Fmap_cFsUcUci */
void dMenu_Fmap_c::paneTranceZoomMapAlpah(short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801B7018-801B74EC       .text paneTranceZoom2Map__12dMenu_Fmap_cFsUcffffffUci */
void dMenu_Fmap_c::paneTranceZoom2Map(short, unsigned char, float, float, float, float, float, float, unsigned char, int) {
    /* Nonmatching */
}

/* 801B74EC-801B75B0       .text paneAlphaFmapCursor__12dMenu_Fmap_cFP18fopMsgM_pane_classsUcUci */
void dMenu_Fmap_c::paneAlphaFmapCursor(fopMsgM_pane_class*, short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801B75B0-801B76A0       .text PaneAlphaSelvageItem__12dMenu_Fmap_cFsUc */
void dMenu_Fmap_c::PaneAlphaSelvageItem(short, unsigned char) {
    /* Nonmatching */
}

/* 801B76A0-801B77A8       .text gShipMarkAnimeInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::gShipMarkAnimeInit() {
    /* Nonmatching */
}

/* 801B77A8-801B78B0       .text gShipMarkAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::gShipMarkAnime() {
    /* Nonmatching */
}

/* 801B78B0-801B79E8       .text _open_warpMode__12dMenu_Fmap_cFv */
bool dMenu_Fmap_c::_open_warpMode() {
    /* Nonmatching */
    return false;
}

/* 801B79E8-801B7CD0       .text init_warpMode__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::init_warpMode() {
    /* Nonmatching */
    mDoAud_seStart(JA_SE_SHIPPU_CHART_OPEN);
    mFmapMode = FMAP_MODE_WARP;
    mButtonIconMode = FMAP_BTN_ICON_WARP;

    areaTextChangeAnimeInit();
    mFrameCounter = 0;
    setDspWarpBackCornerColor(0.0);
    warpAreaAnime0();
}

/* 801B7CD0-801B7E30       .text selCursorMoveWarp__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::selCursorMoveWarp() {
    /* Nonmatching */
}

/* 801B7E30-801B7EA8       .text _close_warpMode__12dMenu_Fmap_cFv */
BOOL dMenu_Fmap_c::_close_warpMode() {
    BOOL ret = paneTransBase(mFrameTimer, g_mfHIO.field_0x34, 0.0, 0.0, NULL, 1);
    mFrameTimer += 1;
    if (ret == 1) {
        mFrameTimer = 0;
        mFmapMode = FMAP_MODE_NORMAL;
        return TRUE;
    }
    return FALSE;
}

/* 801B7EA8-801B7EF8       .text moveMain_warpMode__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::moveMain_warpMode() {
    /* Nonmatching */
}

/* 801B7EF8-801B8754       .text wrapMove__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::wrapMove() {
    /* Nonmatching */
}

/* 801B8754-801B8938       .text wrapSelWinFadeIn1__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::wrapSelWinFadeIn1() {
    /* Nonmatching */
}

/* 801B8938-801B8E60       .text wrapSelect__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::wrapSelect() {
    /* Nonmatching */
}

/* 801B8E60-801B9064       .text wrapSelWinFadeOut__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::wrapSelWinFadeOut() {
    /* Nonmatching */
}

/* 801B9064-801B9288       .text wrapSelWarp__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::wrapSelWarp() {
    /* Nonmatching */
}

/* 801B9288-801B940C       .text warpAreaAnime0__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::warpAreaAnime0() {
    /* Nonmatching */
}

/* 801B940C-801B94F4       .text paneTranceWarpMsg__12dMenu_Fmap_cFP18fopMsgM_pane_classsUcffUci */
void dMenu_Fmap_c::paneTranceWarpMsg(fopMsgM_pane_class*, short, unsigned char, float, float, unsigned char, int) {
    /* Nonmatching */
}

/* 801B94F4-801B9584       .text paneAlphaWarpMsgBack__12dMenu_Fmap_cFsUcUci */
void dMenu_Fmap_c::paneAlphaWarpMsgBack(short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801B9584-801B95D4       .text warpSelCursorMove__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::warpSelCursorMove() {
    /* Nonmatching */
}

/* 801B95D4-801B9608       .text warpSelCursorAnimeInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::warpSelCursorAnimeInit() {
    /* Nonmatching */
}

/* 801B9608-801B96D8       .text warpSelCursorAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::warpSelCursorAnime() {
    /* Nonmatching */
}

/* 801B96D8-801B96F0       .text getWarpAreaGridX__12dMenu_Fmap_cFi */
void dMenu_Fmap_c::getWarpAreaGridX(int) {
    /* Nonmatching */
}

/* 801B96F0-801B970C       .text getWarpAreaGridY__12dMenu_Fmap_cFi */
void dMenu_Fmap_c::getWarpAreaGridY(int) {
    /* Nonmatching */
}

/* 801B970C-801B9724       .text getWarpAreaNo__12dMenu_Fmap_cFPC13cursorTable_t */
void dMenu_Fmap_c::getWarpAreaNo(const cursorTable_t*) {
    /* Nonmatching */
}

/* 801B9724-801B973C       .text getWarpAreaNoUp__12dMenu_Fmap_cFPC13cursorTable_t */
void dMenu_Fmap_c::getWarpAreaNoUp(const cursorTable_t*) {
    /* Nonmatching */
}

/* 801B973C-801B9754       .text getWarpAreaNoDown__12dMenu_Fmap_cFPC13cursorTable_t */
void dMenu_Fmap_c::getWarpAreaNoDown(const cursorTable_t*) {
    /* Nonmatching */
}

/* 801B9754-801B976C       .text getWarpAreaNoLeft__12dMenu_Fmap_cFPC13cursorTable_t */
void dMenu_Fmap_c::getWarpAreaNoLeft(const cursorTable_t*) {
    /* Nonmatching */
}

/* 801B976C-801B9784       .text getWarpAreaNoRight__12dMenu_Fmap_cFPC13cursorTable_t */
void dMenu_Fmap_c::getWarpAreaNoRight(const cursorTable_t*) {
    /* Nonmatching */
}

/* 801B9784-801B97DC       .text getWarpAreaTablePtr__12dMenu_Fmap_cFScSc */
void dMenu_Fmap_c::getWarpAreaTablePtr(signed char, signed char) {
    /* Nonmatching */
}

/* 801B97DC-801B9AB0       .text areaTextChangeAnimeInit__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::areaTextChangeAnimeInit() {
    /* Nonmatching */
}

/* 801B9AB0-801B9B40       .text areaTextChangeAnime__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::areaTextChangeAnime() {
    /* Nonmatching */
}

/* 801B9B40-801B9C90       .text PaneAlphaAreaTxt__12dMenu_Fmap_cFsUci */
void dMenu_Fmap_c::PaneAlphaAreaTxt(short, unsigned char, int) {
    /* Nonmatching */
}

/* 801B9C90-801BA01C       .text setDspWarpBackCornerColor__12dMenu_Fmap_cFf */
void dMenu_Fmap_c::setDspWarpBackCornerColor(float) {
    /* Nonmatching */
}

/* 801BA01C-801BA08C       .text setWrapBackEmitter__12dMenu_Fmap_cF4cXyz */
void dMenu_Fmap_c::setWrapBackEmitter(cXyz) {
    /* Nonmatching */
}

/* 801BA08C-801BA110       .text setWrapSpotEmitter__12dMenu_Fmap_cFi4cXyz */
void dMenu_Fmap_c::setWrapSpotEmitter(int, cXyz) {
    /* Nonmatching */
}

/* 801BA110-801BA19C       .text _open_fishManMode__12dMenu_Fmap_cFv */
bool dMenu_Fmap_c::_open_fishManMode() {
    /* Nonmatching */
    return false;
}

/* 801BA19C-801BA214       .text _close_fishManMode__12dMenu_Fmap_cFv */
BOOL dMenu_Fmap_c::_close_fishManMode() {
    BOOL ret = paneTransBase(mFrameTimer, g_mfHIO.field_0x11B, 0.0, 0.0, NULL, 1);
    mFrameTimer += 1;
    if (ret == 1) {
        mFrameTimer = 0;
        mFmapMode = FMAP_MODE_NORMAL;
        return TRUE;
    }
    return FALSE;
}

/* 801BA214-801BA49C       .text init_fishManMode__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::init_fishManMode() {
    /* Nonmatching */
    mFmapMode = FMAP_MODE_FISHMAN;
    mButtonIconMode = FMAP_BTN_ICON_FISHMAN;
}

/* 801BA49C-801BA4D4       .text movefishManMode__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::movefishManMode() {
    /* Nonmatching */
}

/* 801BA4D4-801BA608       .text fmDispArea__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmDispArea() {
    /* Nonmatching */
}

/* 801BA608-801BA768       .text fmZoomGridLv1In__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmZoomGridLv1In() {
    /* Nonmatching */
}

/* 801BA768-801BA88C       .text fmZoomGridLv2In__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmZoomGridLv2In() {
    /* Nonmatching */
}

/* 801BA88C-801BAA50       .text islandNameSet__12dMenu_Fmap_cFUc */
void dMenu_Fmap_c::islandNameSet(unsigned char) {
    /* Nonmatching */
}

/* 801BAA50-801BAB00       .text fmMapWrite__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmMapWrite() {
    /* Nonmatching */
}

/* 801BAB00-801BABCC       .text fmMapWait__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmMapWait() {
    /* Nonmatching */
}

/* 801BABCC-801BAC88       .text paneAlphaZoom2Map__12dMenu_Fmap_cFsUcUci */
void dMenu_Fmap_c::paneAlphaZoom2Map(short, unsigned char, unsigned char, int) {
    /* Nonmatching */
}

/* 801BAC88-801BADB8       .text fmZoomGridLv2Out__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmZoomGridLv2Out() {
    /* Nonmatching */
}

/* 801BADB8-801BAEF4       .text fmZoomGridLv1Out__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmZoomGridLv1Out() {
    /* Nonmatching */
}

/* 801BAEF4-801BAF18       .text fmEndWait__12dMenu_Fmap_cFv */
void dMenu_Fmap_c::fmEndWait() {
    /* Nonmatching */
}

/* 801BAF18-801BAFCC       .text _open_wallPaper__12dMenu_Fmap_cFv */
bool dMenu_Fmap_c::_open_wallPaper() {
    if (mFrameTimer == 0) {
        mButtonIconMode = FMAP_BTN_ICON_WALLPAPER;
        selCursorHide();
    }
    BOOL ret = paneTransBase(mFrameTimer, g_mfHIO.field_0x34, g_mfHIO.field_0x36, 0.0, NULL, 1);
    mFrameTimer += 1;
    if (ret == 1) {
        mFrameTimer = 0;
        mFmapMode = FMAP_MODE_WALLPAPER;
        return TRUE;
    }
    return FALSE;
}

/* 801BAFCC-801BB024       .text getButtonIconMode__12dMenu_Fmap_cFv */
int dMenu_Fmap_c::getButtonIconMode() {
    if (mMainProcIdx == 1) {
        return mFmap2.getButtonIconMode() + 7;
    }
    if (mInputDisabled) {
        return mFmap2.getButtonIconMode() + 7;
    }
    return mButtonIconMode;
}

/* 801BB024-801BB088       .text draw__12dDlst_FMAP_cFv */
void dDlst_FMAP_c::draw() {
    /* Nonmatching */
}
