#ifndef RES_CAMRES_H
#define RES_CAMRES_H

enum dRes_INDEX_CAMRES {
    /* SCRN */
    dRes_INDEX_CAMRES_BLO_WIPE_01_01_e=0x4,
    dRes_INDEX_CAMRES_BLO_WIPE_01_02_e=0x5,
    /* TIMG */
    dRes_INDEX_CAMRES_BTI_FINDER_00_e=0x8,
    dRes_INDEX_CAMRES_BTI_FINDER_01_e=0x9,
    dRes_INDEX_CAMRES_BTI_PHOTO_ICON_00_e=0xA,
    dRes_INDEX_CAMRES_BTI_STRIP00_e=0xB,
    dRes_INDEX_CAMRES_BTI_WIPE_BAIRITU2_e=0xC,
    dRes_INDEX_CAMRES_BTI_WIPE_IN2_e=0xD,
    dRes_INDEX_CAMRES_BTI_WIPE_OUT2_e=0xE,
    dRes_INDEX_CAMRES_BTI_WIPE_SCALE_2_e=0xF,
};

enum dRes_ID_CAMRES {
    /* SCRN */
    dRes_ID_CAMRES_BLO_WIPE_01_01_e=0x4,
    dRes_ID_CAMRES_BLO_WIPE_01_02_e=0x5,
    /* TIMG */
    dRes_ID_CAMRES_BTI_FINDER_00_e=0x8,
    dRes_ID_CAMRES_BTI_FINDER_01_e=0x9,
    dRes_ID_CAMRES_BTI_PHOTO_ICON_00_e=0xA,
    dRes_ID_CAMRES_BTI_STRIP00_e=0xB,
    dRes_ID_CAMRES_BTI_WIPE_BAIRITU2_e=0xC,
    dRes_ID_CAMRES_BTI_WIPE_IN2_e=0xD,
    dRes_ID_CAMRES_BTI_WIPE_OUT2_e=0xE,
    dRes_ID_CAMRES_BTI_WIPE_SCALE_2_e=0xF,
};

#endif /* !RES_CAMRES_H */