#ifndef RES_DMSGRES_H
#define RES_DMSGRES_H

enum dRes_INDEX_DMSGRES {
    /* SCRN */
    dRes_INDEX_DMSGRES_BLO_HUKIDASHI_D00_e=0x4,
    dRes_INDEX_DMSGRES_BLO_HUKIDASHI_D09_e=0x5,
    /* TIMG */
    dRes_INDEX_DMSGRES_BTI_BACK_LIGHT_D_e=0x8,
    dRes_INDEX_DMSGRES_BTI_DOT_02_D_e=0x9,
    dRes_INDEX_DMSGRES_BTI_HUKIDASHI_00_D_e=0xA,
    dRes_INDEX_DMSGRES_BTI_HUKIDASHI_0212_D_e=0xB,
    dRes_INDEX_DMSGRES_BTI_RING_LOGHT_D_e=0xC,
    dRes_INDEX_DMSGRES_BTI_YAZIRUSHI_00_D_e=0xD,
};

enum dRes_ID_DMSGRES {
    /* SCRN */
    dRes_ID_DMSGRES_BLO_HUKIDASHI_D00_e=0x4,
    dRes_ID_DMSGRES_BLO_HUKIDASHI_D09_e=0x5,
    /* TIMG */
    dRes_ID_DMSGRES_BTI_BACK_LIGHT_D_e=0x8,
    dRes_ID_DMSGRES_BTI_DOT_02_D_e=0x9,
    dRes_ID_DMSGRES_BTI_HUKIDASHI_00_D_e=0xA,
    dRes_ID_DMSGRES_BTI_HUKIDASHI_0212_D_e=0xB,
    dRes_ID_DMSGRES_BTI_RING_LOGHT_D_e=0xC,
    dRes_ID_DMSGRES_BTI_YAZIRUSHI_00_D_e=0xD,
};

#endif /* !RES_DMSGRES_H */