#ifndef RES_SCOPERES_H
#define RES_SCOPERES_H

enum dRes_INDEX_SCOPERES {
    /* SCRN */
    dRes_INDEX_SCOPERES_BLO_WIPE_00_e=0x4,
    dRes_INDEX_SCOPERES_BLO_WIPE_00_2_e=0x5,
    /* TIMG */
    dRes_INDEX_SCOPERES_BTI_WIPE_BAIRITU_e=0x8,
    dRes_INDEX_SCOPERES_BTI_WIPE_IN_e=0x9,
    dRes_INDEX_SCOPERES_BTI_WIPE_OUT_e=0xA,
    dRes_INDEX_SCOPERES_BTI_WIPE_SCALE_e=0xB,
};

enum dRes_ID_SCOPERES {
    /* SCRN */
    dRes_ID_SCOPERES_BLO_WIPE_00_e=0x4,
    dRes_ID_SCOPERES_BLO_WIPE_00_2_e=0x5,
    /* TIMG */
    dRes_ID_SCOPERES_BTI_WIPE_BAIRITU_e=0x8,
    dRes_ID_SCOPERES_BTI_WIPE_IN_e=0x9,
    dRes_ID_SCOPERES_BTI_WIPE_OUT_e=0xA,
    dRes_ID_SCOPERES_BTI_WIPE_SCALE_e=0xB,
};

#endif /* !RES_SCOPERES_H */