#ifndef RES_SWIMRES_H
#define RES_SWIMRES_H

enum dRes_INDEX_SWIMRES {
    /* SCRN */
    dRes_INDEX_SWIMRES_BLO_TIME_SWIM_1_e=0x4,
    dRes_INDEX_SWIMRES_BLO_TIME_SWIM_2_e=0x5,
    /* TIMG */
    dRes_INDEX_SWIMRES_BTI_LIGHT_e=0x8,
    dRes_INDEX_SWIMRES_BTI_SWIMTIME_METER_e=0x9,
    dRes_INDEX_SWIMRES_BTI_SWIMTIME_METER_MASK_e=0xA,
    dRes_INDEX_SWIMRES_BTI_SWIMTIME_SOUL_e=0xB,
    dRes_INDEX_SWIMRES_BTI_SWIMTIME_WAKU_e=0xC,
    dRes_INDEX_SWIMRES_BTI_TEKARI_e=0xD,
};

enum dRes_ID_SWIMRES {
    /* SCRN */
    dRes_ID_SWIMRES_BLO_TIME_SWIM_1_e=0x4,
    dRes_ID_SWIMRES_BLO_TIME_SWIM_2_e=0x5,
    /* TIMG */
    dRes_ID_SWIMRES_BTI_LIGHT_e=0x8,
    dRes_ID_SWIMRES_BTI_SWIMTIME_METER_e=0x9,
    dRes_ID_SWIMRES_BTI_SWIMTIME_METER_MASK_e=0xA,
    dRes_ID_SWIMRES_BTI_SWIMTIME_SOUL_e=0xB,
    dRes_ID_SWIMRES_BTI_SWIMTIME_WAKU_e=0xC,
    dRes_ID_SWIMRES_BTI_TEKARI_e=0xD,
};

#endif /* !RES_SWIMRES_H */