#ifndef RES_YSMAPRES_H
#define RES_YSMAPRES_H

enum dRes_INDEX_YSMAPRES {
    /* SCRN */
    dRes_INDEX_YSMAPRES_BLO_YS_MAP_1_e=0x4,
    /* TIMG */
    dRes_INDEX_YSMAPRES_BTI_YS_BLACK_e=0x7,
    dRes_INDEX_YSMAPRES_BTI_YS_CLOTH_PIECE01_e=0x8,
    dRes_INDEX_YSMAPRES_BTI_YS_KAZARI_01_e=0x9,
    dRes_INDEX_YSMAPRES_BTI_YS_KAZARI_02_e=0xA,
    dRes_INDEX_YSMAPRES_BTI_YS_LINE392_e=0xB,
    dRes_INDEX_YSMAPRES_BTI_YS_LINK_e=0xC,
    dRes_INDEX_YSMAPRES_BTI_YS_MENU_NOTE_00_e=0xD,
    dRes_INDEX_YSMAPRES_BTI_YS_MENU_NOTE_01_e=0xE,
    dRes_INDEX_YSMAPRES_BTI_YS_MENU_NOTE_02_e=0xF,
    dRes_INDEX_YSMAPRES_BTI_YS_MENU_NOTE_03_e=0x10,
    dRes_INDEX_YSMAPRES_BTI_YS_NOTE_03_1_e=0x11,
    dRes_INDEX_YSMAPRES_BTI_YS_TITLE_e=0x12,
    dRes_INDEX_YSMAPRES_BTI_YS_YOGORE_01_e=0x13,
    dRes_INDEX_YSMAPRES_BTI_YS_YOGORE_02_e=0x14,
    dRes_INDEX_YSMAPRES_BTI_YS_YOUSEI_e=0x15,
    dRes_INDEX_YSMAPRES_BTI_YS_YOUSEI2_e=0x16,
    dRes_INDEX_YSMAPRES_BTI_YS_YOUSEI_MN_e=0x17,
};

enum dRes_ID_YSMAPRES {
    /* SCRN */
    dRes_ID_YSMAPRES_BLO_YS_MAP_1_e=0x4,
    /* TIMG */
    dRes_ID_YSMAPRES_BTI_YS_BLACK_e=0x7,
    dRes_ID_YSMAPRES_BTI_YS_CLOTH_PIECE01_e=0x8,
    dRes_ID_YSMAPRES_BTI_YS_KAZARI_01_e=0x9,
    dRes_ID_YSMAPRES_BTI_YS_KAZARI_02_e=0xA,
    dRes_ID_YSMAPRES_BTI_YS_LINE392_e=0xB,
    dRes_ID_YSMAPRES_BTI_YS_LINK_e=0xC,
    dRes_ID_YSMAPRES_BTI_YS_MENU_NOTE_00_e=0xD,
    dRes_ID_YSMAPRES_BTI_YS_MENU_NOTE_01_e=0xE,
    dRes_ID_YSMAPRES_BTI_YS_MENU_NOTE_02_e=0xF,
    dRes_ID_YSMAPRES_BTI_YS_MENU_NOTE_03_e=0x10,
    dRes_ID_YSMAPRES_BTI_YS_NOTE_03_1_e=0x11,
    dRes_ID_YSMAPRES_BTI_YS_TITLE_e=0x12,
    dRes_ID_YSMAPRES_BTI_YS_YOGORE_01_e=0x13,
    dRes_ID_YSMAPRES_BTI_YS_YOGORE_02_e=0x14,
    dRes_ID_YSMAPRES_BTI_YS_YOUSEI_e=0x15,
    dRes_ID_YSMAPRES_BTI_YS_YOUSEI2_e=0x16,
    dRes_ID_YSMAPRES_BTI_YS_YOUSEI_MN_e=0x17,
};

#endif /* !RES_YSMAPRES_H */