#ifndef RES_LS_H
#define RES_LS_H

#include "global.h" // IWYU pragma: keep

enum LS_RES_FILE_ID {
    /* BCKS */
    LS_BCK_LS_DEMOLOOK=0x0,
    LS_BCK_LS_DEMOWAIT=0x1,
    LS_BCK_LS_FURIMUKI=0x2,
    LS_BCK_LS_GET=0x3,
    LS_BCK_LS_NOZOKU=0x4,
    LS_BCK_LS_WAIT01=0x5,
    LS_BCK_LS_WAIT02=0x6,
    LS_BCK_LS_WAIT03=0x7,
    LS_BCK_LS_WAIT04=0x8,
    LS_BCK_LS_WAIT05=0x9,
    LS_BCK_LS_WAIT06=0xA,
    LS_BCK_LS_WATASU=0xB,
    LS_BCK_LS_TALK01=0x1E,
    LS_BCK_LS_WAIT07=0x1F,
    
    /* BDL */
    LS_BDL_LSHAND=0xC,
    
    /* BDLM */
    LS_BDL_LS=0xD,
    
    /* BTK */
    LS_BTK_LS=0xE,
    LS_BTK_LS_DEMOLOOK=0xF,
    LS_BTK_LS_DEMOWAIT=0x10,
    
    /* BTP */
    LS_BTP_FUAN=0x11,
    LS_BTP_FUAN02=0x12,
    LS_BTP_KIZUKU=0x13,
    LS_BTP_LS_DEMOLOOK=0x14,
    LS_BTP_LS_DEMOWAIT=0x15,
    LS_BTP_LS_GET=0x16,
    LS_BTP_MABA=0x17,
    LS_BTP_NGWARAI=0x18,
    LS_BTP_NOZOKU=0x19,
    LS_BTP_OKORI=0x1A,
    LS_BTP_WARAI=0x1B,
    
    /* TEX */
    LS_BTI_LSBODY02=0x1D,
};

enum LS_RES_FILE_INDEX {
    /* BCKS */
    LS_INDEX_BCK_LS_DEMOLOOK=0x8,
    LS_INDEX_BCK_LS_DEMOWAIT=0x9,
    LS_INDEX_BCK_LS_FURIMUKI=0xA,
    LS_INDEX_BCK_LS_GET=0xB,
    LS_INDEX_BCK_LS_NOZOKU=0xC,
    LS_INDEX_BCK_LS_WAIT01=0xD,
    LS_INDEX_BCK_LS_WAIT02=0xE,
    LS_INDEX_BCK_LS_WAIT03=0xF,
    LS_INDEX_BCK_LS_WAIT04=0x10,
    LS_INDEX_BCK_LS_WAIT05=0x11,
    LS_INDEX_BCK_LS_WAIT06=0x12,
    LS_INDEX_BCK_LS_WATASU=0x13,
    LS_INDEX_BCK_LS_TALK01=0x14,
    LS_INDEX_BCK_LS_WAIT07=0x15,
    
    /* BDL */
    LS_INDEX_BDL_LSHAND=0x18,
    
    /* BDLM */
    LS_INDEX_BDL_LS=0x1B,
    
    /* BTK */
    LS_INDEX_BTK_LS=0x1E,
    LS_INDEX_BTK_LS_DEMOLOOK=0x1F,
    LS_INDEX_BTK_LS_DEMOWAIT=0x20,
    
    /* BTP */
    LS_INDEX_BTP_FUAN=0x23,
    LS_INDEX_BTP_FUAN02=0x24,
    LS_INDEX_BTP_KIZUKU=0x25,
    LS_INDEX_BTP_LS_DEMOLOOK=0x26,
    LS_INDEX_BTP_LS_DEMOWAIT=0x27,
    LS_INDEX_BTP_LS_GET=0x28,
    LS_INDEX_BTP_MABA=0x29,
    LS_INDEX_BTP_NGWARAI=0x2A,
    LS_INDEX_BTP_NOZOKU=0x2B,
    LS_INDEX_BTP_OKORI=0x2C,
    LS_INDEX_BTP_WARAI=0x2D,
    
    /* TEX */
    LS_INDEX_BTI_LSBODY02=0x30,
};

#endif /* RES_LS_H */
