#ifndef RES_DAIOCTA_H
#define RES_DAIOCTA_H

#include "global.h" // IWYU pragma: keep

enum DAIOCTA_RES_FILE_ID { // IDs and indexes are synced
    /* BCK */
    DAIOCTA_BCK_DAMAGE1=0x6,
    DAIOCTA_BCK_DAMAGE2=0x7,
    DAIOCTA_BCK_DEATH1=0x8,
    DAIOCTA_BCK_DEATH2=0x9,
    DAIOCTA_BCK_GAWA00=0xA,
    DAIOCTA_BCK_HAKIDASU1=0xB,
    DAIOCTA_BCK_SUIKOMU1=0xC,
    DAIOCTA_BCK_WAIT1=0xD,
    
    /* BDLM */
    DAIOCTA_BDL_DO_EYE1=0x10,
    DAIOCTA_BDL_DO_MAIN1=0x11,
    DAIOCTA_BDL_GAWA00=0x12,
    DAIOCTA_BDL_GDO_SUI00=0x13,
    
    /* BRK */
    DAIOCTA_BRK_DAMAGE1=0x16,
    DAIOCTA_BRK_DAMAGE2=0x17,
    DAIOCTA_BRK_DAMAGE_EYE_A1=0x18,
    DAIOCTA_BRK_DAMAGE_EYE_B1=0x19,
    DAIOCTA_BRK_DEATH1=0x1A,
    DAIOCTA_BRK_DEATH2=0x1B,
    DAIOCTA_BRK_GAWA00=0x1C,
    DAIOCTA_BRK_GDO_SUI00=0x1D,
    DAIOCTA_BRK_HAKIDASU1=0x1E,
    DAIOCTA_BRK_SUIKOMU1=0x1F,
    DAIOCTA_BRK_WAIT1=0x20,
    
    /* BTK */
    DAIOCTA_BTK_DAMAGE_EYE_A1=0x23,
    DAIOCTA_BTK_DAMAGE_EYE_B1=0x24,
    DAIOCTA_BTK_GAWA00=0x25,
    DAIOCTA_BTK_GDO_SUI00=0x26,
};

#endif /* RES_DAIOCTA_H */
