#ifndef RES_TLOGOE_H
#define RES_TLOGOE_H

#include "global.h" // IWYU pragma: keep

#if VERSION == VERSION_USA
enum TLOGOE_RES_FILE_ID { // IDs and indexes are synced
    /* BCK */
    TLOGOE_BCK_TITLE_SHIP=0x8,
    
    /* BDLM */
    TLOGOE_BDL_SUBTITLE_KIRARI_E=0xB,
    TLOGOE_BDL_SUBTITLE_START_ANIM_E=0xC,
    TLOGOE_BDL_TITLE_SHIP=0xD,
    
    /* BPK */
    TLOGOE_BPK_TITLE_SHIP=0x10,
    
    /* BTK */
    TLOGOE_BTK_SUBTITLE_KIRARI_E=0x13,
    TLOGOE_BTK_SUBTITLE_START_ANIM_E=0x14,
    
    /* SCRN */
    TLOGOE_BLO_TITLE_LOGO_E=0x17,
    
    /* TIMG */
    TLOGOE_BTI_C_NINTENDO_E=0x1A,
    TLOGOE_BTI_DUMMY=0x1B,
    TLOGOE_BTI_LOGO_ZELDA_JPA=0x1C,
    TLOGOE_BTI_LOGO_ZELDA_MAIN=0x1D,
    TLOGOE_BTI_PRESS_START=0x1E,
};
#endif

#endif /* RES_TLOGOE_H */
