#ifndef RES_BMSW_H
#define RES_BMSW_H

#include "global.h" // IWYU pragma: keep

enum BMSW_RES_FILE_ID {
    /* BCKS */
    BMSW_BCK_BMARM_TALK01=0x0,
    BMSW_BCK_BMARM_SHIWAKE01=0x11,
    BMSW_BCK_BMARM_SHIWAKE02=0x12,
    BMSW_BCK_BMARM_TALK02=0x13,
    BMSW_BCK_BM_SHIWAKE01=0x14,
    BMSW_BCK_BM_SHIWAKE02=0x15,
    BMSW_BCK_BM_TALK01=0x16,
    BMSW_BCK_BM_TALK02=0x17,
    BMSW_BCK_BMARM_WAIT01=0x1A,
    BMSW_BCK_BM_WAIT01=0x1B,
    BMSW_BCK_BMARM_TALK03=0x1D,
    BMSW_BCK_BMARM_WAIT02=0x1E,
    BMSW_BCK_BM_TALK03=0x1F,
    BMSW_BCK_BM_WAIT02=0x20,
    
    /* BDL */
    BMSW_BDL_BM_BAG=0x2,
    BMSW_BDL_BM_LETTER=0x1C,
    
    /* BDLM */
    BMSW_BDL_BM=0x3,
    BMSW_BDL_BMARM=0x4,
    BMSW_BDL_QMAIL=0xF,
    BMSW_BDL_BMHEAD11=0x21,
    
    /* BMT */
    BMSW_BMT_BM02=0x9,
    BMSW_BMT_BMARM02=0xA,
    
    /* BTP */
    BMSW_BTP_QMAIL=0x10,
    BMSW_BTP_BMHEAD11=0x22,
    
    /* BMDM */
    BMSW_BMD_SHOP_CURSOR01=0x18,
    
    /* BRK */
    BMSW_BRK_SHOP_CURSOR01=0x19,
};

enum BMSW_RES_FILE_INDEX {
    /* BCKS */
    BMSW_INDEX_BCK_BMARM_TALK01=0x9,
    BMSW_INDEX_BCK_BMARM_SHIWAKE01=0xA,
    BMSW_INDEX_BCK_BMARM_SHIWAKE02=0xB,
    BMSW_INDEX_BCK_BMARM_TALK02=0xC,
    BMSW_INDEX_BCK_BM_SHIWAKE01=0xD,
    BMSW_INDEX_BCK_BM_SHIWAKE02=0xE,
    BMSW_INDEX_BCK_BM_TALK01=0xF,
    BMSW_INDEX_BCK_BM_TALK02=0x10,
    BMSW_INDEX_BCK_BMARM_WAIT01=0x11,
    BMSW_INDEX_BCK_BM_WAIT01=0x12,
    BMSW_INDEX_BCK_BMARM_TALK03=0x13,
    BMSW_INDEX_BCK_BMARM_WAIT02=0x14,
    BMSW_INDEX_BCK_BM_TALK03=0x15,
    BMSW_INDEX_BCK_BM_WAIT02=0x16,
    
    /* BDL */
    BMSW_INDEX_BDL_BM_BAG=0x19,
    BMSW_INDEX_BDL_BM_LETTER=0x1A,
    
    /* BDLM */
    BMSW_INDEX_BDL_BM=0x1D,
    BMSW_INDEX_BDL_BMARM=0x1E,
    BMSW_INDEX_BDL_QMAIL=0x1F,
    BMSW_INDEX_BDL_BMHEAD11=0x20,
    
    /* BMT */
    BMSW_INDEX_BMT_BM02=0x23,
    BMSW_INDEX_BMT_BMARM02=0x24,
    
    /* BTP */
    BMSW_INDEX_BTP_QMAIL=0x27,
    BMSW_INDEX_BTP_BMHEAD11=0x28,
    
    /* BMDM */
    BMSW_INDEX_BMD_SHOP_CURSOR01=0x2B,
    
    /* BRK */
    BMSW_INDEX_BRK_SHOP_CURSOR01=0x2E,
};

#endif /* RES_BMSW_H */
