#ifndef RES_SV_H
#define RES_SV_H

#include "global.h" // IWYU pragma: keep

enum SV_RES_FILE_ID {
    /* BCKS */
    SV_BCK_SV_BYE=0x3,
    SV_BCK_SV_HARAU=0x4,
    SV_BCK_SV_KYORO=0x5,
    SV_BCK_SV_MAWASI=0x6,
    SV_BCK_SV_SHI=0x7,
    SV_BCK_SV_TALK01=0x8,
    SV_BCK_SV_TALK02=0x9,
    SV_BCK_SV_TALK03=0xA,
    SV_BCK_SV_UNAZUKU=0xB,
    SV_BCK_SV_WAIT01=0xC,
    SV_BCK_SV_WAIT02=0xD,
    SV_BCK_SV_YA=0xE,
    
    /* BDL */
    SV_BDL_SV=0x1,
};

enum SV_RES_FILE_INDEX {
    /* BCKS */
    SV_INDEX_BCK_SV_BYE=0x4,
    SV_INDEX_BCK_SV_HARAU=0x5,
    SV_INDEX_BCK_SV_KYORO=0x6,
    SV_INDEX_BCK_SV_MAWASI=0x7,
    SV_INDEX_BCK_SV_SHI=0x8,
    SV_INDEX_BCK_SV_TALK01=0x9,
    SV_INDEX_BCK_SV_TALK02=0xA,
    SV_INDEX_BCK_SV_TALK03=0xB,
    SV_INDEX_BCK_SV_UNAZUKU=0xC,
    SV_INDEX_BCK_SV_WAIT01=0xD,
    SV_INDEX_BCK_SV_WAIT02=0xE,
    SV_INDEX_BCK_SV_YA=0xF,
    
    /* BDL */
    SV_INDEX_BDL_SV=0x12,
};

#endif /* RES_SV_H */
