#ifndef RES_BJ_H
#define RES_BJ_H

#include "global.h" // IWYU pragma: keep

enum BJ_RES_FILE_ID {
    /* BCKS */
    BJ_BCK_BOW=0x0,
    BJ_BCK_DANCE=0x1,
    BJ_BCK_FLY01=0x2,
    BJ_BCK_HAPPY=0x3,
    BJ_BCK_SHOCK=0x6,
    BJ_BCK_TALK01=0x7,
    BJ_BCK_TALK02=0x8,
    BJ_BCK_THROW=0x9,
    BJ_BCK_WAIT01=0xA,
    BJ_BCK_WALK=0xB,
    BJ_BCK_M_OPEN=0x27,
    BJ_BCK_OPEN=0x28,
    BJ_BCK_FLY02=0x2A,
    
    /* BMT */
    BJ_BMT_BJ2=0x17,
    BJ_BMT_BJ3=0x18,
    
    /* BDL */
    BJ_BDL_PL_AL=0x19,
    BJ_BDL_PL_AR=0x1A,
    BJ_BDL_BJ1_FACE=0x1D,
    BJ_BDL_BJ2_FACE=0x1E,
    BJ_BDL_BJ3_FACE=0x1F,
    BJ_BDL_BJ4_FACE=0x20,
    BJ_BDL_BJ5_FACE=0x21,
    BJ_BDL_BJ6_FACE=0x22,
    BJ_BDL_BJ7_FACE=0x23,
    BJ_BDL_BJ8_FACE=0x24,
    BJ_BDL_BJ9_FACE=0x25,
    BJ_BDL_PP=0x29,
    
    /* BDLM */
    BJ_BDL_BJ=0x26,
};

enum BJ_RES_FILE_INDEX {
    /* BCKS */
    BJ_INDEX_BCK_BOW=0x6,
    BJ_INDEX_BCK_DANCE=0x7,
    BJ_INDEX_BCK_FLY01=0x8,
    BJ_INDEX_BCK_HAPPY=0x9,
    BJ_INDEX_BCK_SHOCK=0xA,
    BJ_INDEX_BCK_TALK01=0xB,
    BJ_INDEX_BCK_TALK02=0xC,
    BJ_INDEX_BCK_THROW=0xD,
    BJ_INDEX_BCK_WAIT01=0xE,
    BJ_INDEX_BCK_WALK=0xF,
    BJ_INDEX_BCK_M_OPEN=0x10,
    BJ_INDEX_BCK_OPEN=0x11,
    BJ_INDEX_BCK_FLY02=0x12,
    
    /* BMT */
    BJ_INDEX_BMT_BJ2=0x15,
    BJ_INDEX_BMT_BJ3=0x16,
    
    /* BDL */
    BJ_INDEX_BDL_PL_AL=0x19,
    BJ_INDEX_BDL_PL_AR=0x1A,
    BJ_INDEX_BDL_BJ1_FACE=0x1B,
    BJ_INDEX_BDL_BJ2_FACE=0x1C,
    BJ_INDEX_BDL_BJ3_FACE=0x1D,
    BJ_INDEX_BDL_BJ4_FACE=0x1E,
    BJ_INDEX_BDL_BJ5_FACE=0x1F,
    BJ_INDEX_BDL_BJ6_FACE=0x20,
    BJ_INDEX_BDL_BJ7_FACE=0x21,
    BJ_INDEX_BDL_BJ8_FACE=0x22,
    BJ_INDEX_BDL_BJ9_FACE=0x23,
    BJ_INDEX_BDL_PP=0x24,
    
    /* BDLM */
    BJ_INDEX_BDL_BJ=0x27,
};

#endif /* RES_BJ_H */
