#ifndef RES_BM2_H
#define RES_BM2_H

#include "global.h" // IWYU pragma: keep

enum BM2_RES_FILE_ID {
    /* BCKS */
    BM2_BCK_BMARM_WAIT01=0x0,
    BM2_BCK_BMHEAD01_DWAIT=0x1,
    BM2_BCK_BMHEAD01_LOOKUP=0x2,
    BM2_BCK_BMHEAD01_OROORO=0x3,
    BM2_BCK_BMWING_DWAIT=0x4,
    BM2_BCK_BMWING_LOOKUP=0x5,
    BM2_BCK_BMWING_OROORO=0x6,
    BM2_BCK_BM_DWAIT=0x7,
    BM2_BCK_BM_LOOKUP=0x8,
    BM2_BCK_BM_OROORO=0x9,
    
    /* BDL */
    BM2_BDL_BMWING=0xA,
    BM2_BDL_BM_BAG=0xB,
    
    /* BDLM */
    BM2_BDL_BM=0xC,
    BM2_BDL_BMARM=0xD,
    BM2_BDL_BMHEAD01=0xE,
    
    /* BTP */
    BM2_BTP_BMHEAD01=0xF,
};

enum BM2_RES_FILE_INDEX {
    /* BCKS */
    BM2_INDEX_BCK_BMARM_WAIT01=0x6,
    BM2_INDEX_BCK_BMHEAD01_DWAIT=0x7,
    BM2_INDEX_BCK_BMHEAD01_LOOKUP=0x8,
    BM2_INDEX_BCK_BMHEAD01_OROORO=0x9,
    BM2_INDEX_BCK_BMWING_DWAIT=0xA,
    BM2_INDEX_BCK_BMWING_LOOKUP=0xB,
    BM2_INDEX_BCK_BMWING_OROORO=0xC,
    BM2_INDEX_BCK_BM_DWAIT=0xD,
    BM2_INDEX_BCK_BM_LOOKUP=0xE,
    BM2_INDEX_BCK_BM_OROORO=0xF,
    
    /* BDL */
    BM2_INDEX_BDL_BMWING=0x12,
    BM2_INDEX_BDL_BM_BAG=0x13,
    
    /* BDLM */
    BM2_INDEX_BDL_BM=0x16,
    BM2_INDEX_BDL_BMARM=0x17,
    BM2_INDEX_BDL_BMHEAD01=0x18,
    
    /* BTP */
    BM2_INDEX_BTP_BMHEAD01=0x1B,
};

#endif /* RES_BM2_H */
