#ifndef RES_KAIZOKUSEN_H
#define RES_KAIZOKUSEN_H

#include "global.h" // IWYU pragma: keep

enum KAIZOKUSEN_RES_FILE_ID {
    /* DZB */
    KAIZOKUSEN_DZB_ROOM1A=0xF,
    KAIZOKUSEN_DZB_ROOM1B=0x10,
    
    /* TEX */
    KAIZOKUSEN_BTI_TXA_KAIZOKU_HATA=0x3,
    KAIZOKUSEN_BTI_TXA_KAIZOKU_HO=0x4,
    
    /* BDL */
    KAIZOKUSEN_BDL_AMAST=0xD,
    KAIZOKUSEN_BDL_OBA_KAIZOKU_A=0xE,
};

enum KAIZOKUSEN_RES_FILE_INDEX {
    /* DZB */
    KAIZOKUSEN_INDEX_DZB_ROOM1A=0x5,
    KAIZOKUSEN_INDEX_DZB_ROOM1B=0x6,
    
    /* TEX */
    KAIZOKUSEN_INDEX_BTI_TXA_KAIZOKU_HATA=0x9,
    KAIZOKUSEN_INDEX_BTI_TXA_KAIZOKU_HO=0xA,
    
    /* BDL */
    KAIZOKUSEN_INDEX_BDL_AMAST=0xD,
    KAIZOKUSEN_INDEX_BDL_OBA_KAIZOKU_A=0xE,
};

#endif /* RES_KAIZOKUSEN_H */
