#ifndef RES_KANBAN_H
#define RES_KANBAN_H

#include "global.h" // IWYU pragma: keep

enum KANBAN_RES_FILE_ID { // IDs and indexes are synced
    /* BDL */
    KANBAN_BDL_KANBAN=0x3,
    KANBAN_BDL_KANBAN_01=0x4,
    KANBAN_BDL_KANBAN_02=0x5,
    KANBAN_BDL_KANBAN_03=0x6,
    KANBAN_BDL_KANBAN_04=0x7,
    KANBAN_BDL_KANBAN_05=0x8,
    KANBAN_BDL_KANBAN_06=0x9,
    KANBAN_BDL_KANBAN_07=0xA,
    KANBAN_BDL_KANBAN_08=0xB,
    KANBAN_BDL_KANBAN_09=0xC,
    KANBAN_BDL_KANBAN_10=0xD,
};

#endif /* RES_KANBAN_H */
