#ifndef RES_FGANON_H
#define RES_FGANON_H

#include "global.h" // IWYU pragma: keep

enum FGANON_RES_FILE_ID { // IDs and indexes are synced
    /* BCK */
    FGANON_BCK_DAMAGE1=0x6,
    FGANON_BCK_DAMAGE2=0x7,
    FGANON_BCK_DOWN1=0x8,
    FGANON_BCK_KAITEN1=0x9,
    FGANON_BCK_KAITEN_S1=0xA,
    FGANON_BCK_LAST_DAMAGE1=0xB,
    FGANON_BCK_MOGAKU1=0xC,
    FGANON_BCK_NAGERU1=0xD,
    FGANON_BCK_NAGERU_S1=0xE,
    FGANON_BCK_SARU1=0xF,
    FGANON_BCK_TAME1=0x10,
    FGANON_BCK_TAME_S1=0x11,
    FGANON_BCK_TAME_S2=0x12,
    FGANON_BCK_TENNISLR1=0x13,
    FGANON_BCK_TENNISRL1=0x14,
    FGANON_BCK_TYAKUTI1=0x15,
    FGANON_BCK_WAIT1=0x16,
    FGANON_BCK_WARAU1=0x17,
    
    /* BDLM */
    FGANON_BDL_BPG=0x1A,
    FGANON_BDL_YDKBL00=0x1B,
    FGANON_BDL_YDKSP00=0x1C,
    
    /* BRK */
    FGANON_BRK_DERU_KEN1=0x1F,
    FGANON_BRK_DERU_KEN2=0x20,
    FGANON_BRK_DERU_MAIN1=0x21,
    FGANON_BRK_DERU_MAIN2=0x22,
    FGANON_BRK_KIERU_KEN2=0x23,
    FGANON_BRK_KIERU_MAIN1=0x24,
    FGANON_BRK_KIERU_MAIN2=0x25,
    FGANON_BRK_YDKBL00=0x26,
    FGANON_BRK_YDKSP00=0x27,
    
    /* BTK */
    FGANON_BTK_YDKBL00=0x2A,
    FGANON_BTK_YDKSP00=0x2B,
};

#endif /* RES_FGANON_H */
