#ifndef RES_LOGO_H
#define RES_LOGO_H

enum LOGO_RES_FILE_ID { // IDs and indexes are synced
    /* DAT */
    LOGO_BTI_NINTENDO_376X104=0x3,
    LOGO_BTI_PROGRESSIVE_CHOICE=0x4,
    LOGO_BTI_PROGRESSIVE_INTER=0x5,
    LOGO_BTI_PROGRESSIVE_NO=0x6,
    LOGO_BTI_PROGRESSIVE_PRO=0x7,
    LOGO_BTI_PROGRESSIVE_YES=0x8,
    LOGO_BTI_TITLE_DOLBY_MARK=0x9,
};

#endif /* RES_LOGO_H */
