#ifndef RES_GTFGLOW_H
#define RES_GTFGLOW_H

#include "global.h" // IWYU pragma: keep

enum GTFGLOW_RES_FILE_ID { // IDs and indexes are synced
    /* BDLM */
    GTFGLOW_BDL_GDEMO29_A00=0x5,
    GTFGLOW_BDL_GDEMO29_B00=0x6,
    GTFGLOW_BDL_GTFGLOW00=0x7,
    
    /* BRK */
    GTFGLOW_BRK_GDEMO29_A00=0xA,
    GTFGLOW_BRK_GDEMO29_A01=0xB,
    GTFGLOW_BRK_GTFGLOW00=0xC,
    GTFGLOW_BRK_GTFGLOW01=0xD,
    GTFGLOW_BRK_GTFGLOW02=0xE,
    
    /* BTK */
    GTFGLOW_BTK_GDEMO29_B00=0x11,
};

#endif /* RES_GTFGLOW_H */
