#ifndef RES_SARACE_H
#define RES_SARACE_H

#include "global.h" // IWYU pragma: keep

enum SARACE_RES_FILE_ID {
    /* BCKS */
    SARACE_BCK_SA01HEAD_TALK01=0x0,
    SARACE_BCK_SA01HEAD_WAIT01=0x1,
    SARACE_BCK_SA_TALK01=0x2,
    SARACE_BCK_SA_WAIT01=0x3,
    SARACE_BCK_SA01HEAD_TALK02=0x7,
    SARACE_BCK_SA_TALK02=0x8,
    
    /* BDL */
    SARACE_BDL_SA=0x4,
    
    /* BDLM */
    SARACE_BDL_SA01_HEAD=0x5,
    
    /* BTP */
    SARACE_BTP_SA01_MABA=0x6,
};

enum SARACE_RES_FILE_INDEX {
    /* BCKS */
    SARACE_INDEX_BCK_SA01HEAD_TALK01=0x6,
    SARACE_INDEX_BCK_SA01HEAD_WAIT01=0x7,
    SARACE_INDEX_BCK_SA_TALK01=0x8,
    SARACE_INDEX_BCK_SA_WAIT01=0x9,
    SARACE_INDEX_BCK_SA01HEAD_TALK02=0xA,
    SARACE_INDEX_BCK_SA_TALK02=0xB,
    
    /* BDL */
    SARACE_INDEX_BDL_SA=0xE,
    
    /* BDLM */
    SARACE_INDEX_BDL_SA01_HEAD=0x11,
    
    /* BTP */
    SARACE_INDEX_BTP_SA01_MABA=0x14,
};

#endif /* RES_SARACE_H */
