#ifndef RES_GOVER_H
#define RES_GOVER_H

#include "global.h" // IWYU pragma: keep

#if VERSION == VERSION_DEMO
enum GOVER_RES_FILE_ID { // IDs and indexes are synced
    /* ROOT */
    GOVER_ARC_GOVER=0x0,
    
    /* SCRN */
    GOVER_BLO_GAMEOVER=0x5,
    
    /* TIMG */
    GOVER_BTI_SHIPFONT_A_BIG=0x8,
    GOVER_BTI_SHIPFONT_E_BIG=0x9,
    GOVER_BTI_SHIPFONT_G_BIG=0xA,
    GOVER_BTI_SHIPFONT_M_BIG=0xB,
    GOVER_BTI_SHIPFONT_O_BIG=0xC,
    GOVER_BTI_SHIPFONT_R_BIG=0xD,
    GOVER_BTI_SHIPFONT_V_BIG=0xE,
    GOVER_BTI_SMOKE=0xF,
};
#elif VERSION == VERSION_PAL
enum GOVER_RES_FILE_ID { // IDs and indexes are synced
    /* SCRN */
    GOVER_BLO_GAMEOVER=0x4,
    GOVER_BLO_GAMEOVER_SP=0x5,
    
    /* TIMG */
    GOVER_BTI_G_SHIPFONT_A_BIG=0x8,
    GOVER_BTI_G_SHIPFONT_D_BIG=0x9,
    GOVER_BTI_G_SHIPFONT_E_BIG=0xA,
    GOVER_BTI_G_SHIPFONT_F_BIG=0xB,
    GOVER_BTI_G_SHIPFONT_G_BIG=0xC,
    GOVER_BTI_G_SHIPFONT_I_BIG=0xD,
    GOVER_BTI_G_SHIPFONT_L_BIG=0xE,
    GOVER_BTI_G_SHIPFONT_M_BIG=0xF,
    GOVER_BTI_G_SHIPFONT_N_BIG=0x10,
    GOVER_BTI_G_SHIPFONT_O_BIG=0x11,
    GOVER_BTI_G_SHIPFONT_P_BIG=0x12,
    GOVER_BTI_G_SHIPFONT_R_BIG=0x13,
    GOVER_BTI_G_SHIPFONT_T_BIG=0x14,
    GOVER_BTI_G_SHIPFONT_V_BIG=0x15,
    GOVER_BTI_G_SMOKE=0x16,
};
#else
enum GOVER_RES_FILE_ID { // IDs and indexes are synced
    /* SCRN */
    GOVER_BLO_GAMEOVER=0x4,
    
    /* TIMG */
    GOVER_BTI_G_SHIPFONT_A_BIG=0x7,
    GOVER_BTI_G_SHIPFONT_E_BIG=0x8,
    GOVER_BTI_G_SHIPFONT_G_BIG=0x9,
    GOVER_BTI_G_SHIPFONT_M_BIG=0xA,
    GOVER_BTI_G_SHIPFONT_O_BIG=0xB,
    GOVER_BTI_G_SHIPFONT_R_BIG=0xC,
    GOVER_BTI_G_SHIPFONT_V_BIG=0xD,
    GOVER_BTI_G_SMOKE=0xE,
};
#endif

#endif /* RES_GOVER_H */
