#ifndef RES_BMS_H
#define RES_BMS_H

#include "global.h" // IWYU pragma: keep

enum BMS_RES_FILE_ID {
    /* BMDM */
    BMS_BMD_SHOP_CURSOR01=0x4,
    
    /* BRK */
    BMS_BRK_SHOP_CURSOR01=0x5,
    
    /* BTP */
    BMS_BTP_BY_T01=0x8,
    BMS_BTP_MABA01=0x9,
    
    /* BCKS */
    BMS_BCK_BY2_WAIT00=0xA,
    BMS_BCK_BY1_WAIT01=0xF,
    BMS_BCK_BY1_WAIT02=0x10,
    BMS_BCK_BY1_BOW=0x15,
    BMS_BCK_BY1_TALK01=0x16,
    BMS_BCK_BY1_TALK02=0x17,
    
    /* BDL */
    BMS_BDL_BY2=0xB,
    BMS_BDL_BY_EYE=0xC,
    BMS_BDL_BY_MASK=0xD,
    BMS_BDL_BY1=0x11,
    BMS_BDL_BY_LOW1=0x12,
    BMS_BDL_BY_LOW2=0x13,
    BMS_BDL_PTARU=0x14,
    
    /* BDLM */
    BMS_BDL_BY_HEAD=0xE,
};

enum BMS_RES_FILE_INDEX {
    /* BMDM */
    BMS_INDEX_BMD_SHOP_CURSOR01=0x8,
    
    /* BRK */
    BMS_INDEX_BRK_SHOP_CURSOR01=0xB,
    
    /* BTP */
    BMS_INDEX_BTP_BY_T01=0xE,
    BMS_INDEX_BTP_MABA01=0xF,
    
    /* BCKS */
    BMS_INDEX_BCK_BY2_WAIT00=0x12,
    BMS_INDEX_BCK_BY1_WAIT01=0x13,
    BMS_INDEX_BCK_BY1_WAIT02=0x14,
    BMS_INDEX_BCK_BY1_BOW=0x15,
    BMS_INDEX_BCK_BY1_TALK01=0x16,
    BMS_INDEX_BCK_BY1_TALK02=0x17,
    
    /* BDL */
    BMS_INDEX_BDL_BY2=0x1A,
    BMS_INDEX_BDL_BY_EYE=0x1B,
    BMS_INDEX_BDL_BY_MASK=0x1C,
    BMS_INDEX_BDL_BY1=0x1D,
    BMS_INDEX_BDL_BY_LOW1=0x1E,
    BMS_INDEX_BDL_BY_LOW2=0x1F,
    BMS_INDEX_BDL_PTARU=0x20,
    
    /* BDLM */
    BMS_INDEX_BDL_BY_HEAD=0x23,
};

#endif /* RES_BMS_H */
