#ifndef RES_TLOGOE5_H
#define RES_TLOGOE5_H

#include "global.h" // IWYU pragma: keep

#if VERSION == VERSION_PAL
enum TLOGOE5_RES_FILE_ID { // IDs and indexes are synced
    /* BCK */
    TLOGOE5_BCK_TITLE_SHIP=0x8,
    
    /* BDLM */
    TLOGOE5_BDL_SUBTITLE_KIRARI_E=0xB,
    TLOGOE5_BDL_SUBTITLE_START_ANIM_E=0xC,
    TLOGOE5_BDL_TITLE_SHIP=0xD,
    
    /* BPK */
    TLOGOE5_BPK_TITLE_SHIP=0x10,
    
    /* BTK */
    TLOGOE5_BTK_SUBTITLE_KIRARI_E=0x13,
    TLOGOE5_BTK_SUBTITLE_START_ANIM_E=0x14,
    
    /* SCRN */
    TLOGOE5_BLO_TITLE_LOGO_E=0x17,
    
    /* TIMG */
    TLOGOE5_BTI_C_NINTENDO_E=0x1A,
    TLOGOE5_BTI_DUMMY=0x1B,
    TLOGOE5_BTI_LOGO_ZELDA_JPA=0x1C,
    TLOGOE5_BTI_LOGO_ZELDA_MAIN=0x1D,
    TLOGOE5_BTI_PRESS_START=0x1E,
};
#endif

#endif /* RES_TLOGOE5_H */
