#ifndef RES_BMD_H
#define RES_BMD_H

#include "global.h" // IWYU pragma: keep

enum BMD_RES_FILE_ID { // IDs and indexes are synced
    /* BCK */
    BMD_BCK_CALL_01=0x8,
    BMD_BCK_CALL_02=0x9,
    BMD_BCK_CALL_03=0xA,
    BMD_BCK_COA_DAMAGE=0xB,
    BMD_BCK_COA_DEAD1=0xC,
    BMD_BCK_COA_DEAD2=0xD,
    BMD_BCK_COA_LDEAD=0xE,
    BMD_BCK_COA_NDEAD1=0xF,
    BMD_BCK_COA_NDEAD2=0x10,
    BMD_BCK_COA_START1=0x11,
    BMD_BCK_COA_START2=0x12,
    BMD_BCK_COA_START3=0x13,
    BMD_BCK_COA_WAIT=0x14,
    BMD_BCK_DROP=0x15,
    BMD_BCK_HANA_ATTACK=0x16,
    BMD_BCK_HANA_DEAD1=0x17,
    BMD_BCK_HANA_DEAD2=0x18,
    BMD_BCK_HANA_DEAD3=0x19,
    BMD_BCK_HANA_EAT=0x1A,
    BMD_BCK_HANA_HAKIDASU=0x1B,
    BMD_BCK_HANA_OTIRU=0x1C,
    BMD_BCK_HANA_START1=0x1D,
    BMD_BCK_HANA_START2=0x1E,
    BMD_BCK_HANA_TOJIRU=0x1F,
    BMD_BCK_HANA_WAIT=0x20,
    BMD_BCK_HIRAKU_WAIT=0x21,
    BMD_BCK_NEW_SDEMO1=0x22,
    BMD_BCK_NEW_SDEMO2=0x23,
    BMD_BCK_NEW_SDEMO3=0x24,
    BMD_BCK_NEW_SDEMO4=0x25,
    
    /* BDLM */
    BMD_BDL_R00_EF=0x28,
    
    /* BMDM */
    BMD_BMD_BKM=0x2B,
    BMD_BMD_BKM_COA=0x2C,
    BMD_BMD_BKM_COA_DEADMODEL=0x2D,
    BMD_BMD_CB=0x2E,
    BMD_BMD_CB_FACE=0x2F,
    BMD_BMD_CB_STICK=0x30,
    
    /* BRK */
    BMD_BRK_BKM=0x33,
    BMD_BRK_R00_EF=0x34,
    
    /* BTK */
    BMD_BTK_BKM=0x37,
    
    /* DZB */
    BMD_DZB_COLL1=0x3A,
    BMD_DZB_COLL2=0x3B,
};

#endif /* RES_BMD_H */
