#ifndef RES_JI_H
#define RES_JI_H

#include "global.h" // IWYU pragma: keep

enum JI_RES_FILE_ID { // IDs and indexes are synced
    /* BAS */
    JI_BAS_JI_AKIRE=0x8,
    JI_BAS_JI_BIBIRI=0x9,
    JI_BAS_JI_BTKAMAE=0xA,
    JI_BAS_JI_BTKAMASI=0xB,
    JI_BAS_JI_DAMAGE=0xC,
    JI_BAS_JI_GUARD=0xD,
    JI_BAS_JI_INASI=0xE,
    JI_BAS_JI_JPGUARD=0xF,
    JI_BAS_JI_KAMAE=0x10,
    JI_BAS_JI_KROT=0x11,
    JI_BAS_JI_NAKU=0x12,
    JI_BAS_JI_NUGUI=0x13,
    JI_BAS_JI_ODOROKU=0x14,
    JI_BAS_JI_REI=0x15,
    JI_BAS_JI_TALK01=0x16,
    JI_BAS_JI_TALK02=0x17,
    JI_BAS_JI_TATEATTACK=0x18,
    JI_BAS_JI_TATEGUARD=0x19,
    JI_BAS_JI_TOKAMAE=0x1A,
    JI_BAS_JI_UDEGUMI=0x1B,
    JI_BAS_JI_WAIT01=0x1C,
    JI_BAS_JI_WAIT02=0x1D,
    JI_BAS_JI_WARAI=0x1E,
    JI_BAS_JI_YKGUARD=0x1F,
    JI_BAS_JI_YOKOATTACK=0x20,
    JI_BAS_WAIT01=0x21,
    
    /* BCK */
    JI_BCK_JI_AKIRE=0x24,
    JI_BCK_JI_BIBIRI=0x25,
    JI_BCK_JI_BTKAMAE=0x26,
    JI_BCK_JI_BTKAMASI=0x27,
    JI_BCK_JI_DAMAGE=0x28,
    JI_BCK_JI_GUARD=0x29,
    JI_BCK_JI_INASI=0x2A,
    JI_BCK_JI_JPGUARD=0x2B,
    JI_BCK_JI_KAMAE=0x2C,
    JI_BCK_JI_KROT=0x2D,
    JI_BCK_JI_NAKU=0x2E,
    JI_BCK_JI_NUGUI=0x2F,
    JI_BCK_JI_ODOROKU=0x30,
    JI_BCK_JI_REI=0x31,
    JI_BCK_JI_TALK01=0x32,
    JI_BCK_JI_TALK02=0x33,
    JI_BCK_JI_TATEATTACK=0x34,
    JI_BCK_JI_TATEGUARD=0x35,
    JI_BCK_JI_TOKAMAE=0x36,
    JI_BCK_JI_UDEGUMI=0x37,
    JI_BCK_JI_WAIT01=0x38,
    JI_BCK_JI_WAIT02=0x39,
    JI_BCK_JI_WARAI=0x3A,
    JI_BCK_JI_YKGUARD=0x3B,
    JI_BCK_JI_YOKOATTACK=0x3C,
    JI_BCK_JIYARI_TATEATTACK=0x3D,
    JI_BCK_JIYARI_YOKOATTACK=0x3E,
    JI_BCK_WAIT01=0x3F,
    
    /* BDLM */
    JI_BDL_JI=0x42,
    JI_BDL_JI_YARI=0x43,
    JI_BDL_YJITR00=0x44,
    
    /* BRK */
    JI_BRK_YJITR00=0x47,
    
    /* BTK */
    JI_BTK_YJITR00=0x4A,
    
    /* BTP */
    JI_BTP_JI=0x4D,
};

#endif /* RES_JI_H */
