#ifndef RES_KAISEN_H
#define RES_KAISEN_H

#include "global.h" // IWYU pragma: keep

enum KAISEN_RES_FILE_ID { // IDs and indexes are synced
    /* BDL */
    KAISEN_BDL_AK2SH=0x4,
    KAISEN_BDL_AK3SH=0x5,
    KAISEN_BDL_AK4SH=0x6,
    KAISEN_BDL_AKATR=0x7,
    KAISEN_BDL_AKBOD=0x8,
    KAISEN_BDL_AKCSR=0x9,
    KAISEN_BDL_AKHZR=0xA,
    KAISEN_BDL_AKKSL=0xB,
    
    /* TEX */
    KAISEN_BTI_GAME_BEST_RECORD=0xE,
    KAISEN_BTI_GAME_BOMB_01=0xF,
    KAISEN_BTI_GAME_BOMB_02=0x10,
    KAISEN_BTI_GAME_HUNE_DAMAGE=0x11,
    KAISEN_BTI_GAME_PAPER=0x12,
    KAISEN_BTI_GAME_SHIP_NODAMAGE=0x13,
};

#endif /* RES_KAISEN_H */
