#ifndef RES_LOGO_H
#define RES_LOGO_H

#include "global.h" // IWYU pragma: keep

#if VERSION == VERSION_PAL
enum LOGO_RES_FILE_ID { // IDs and indexes are synced
    /* DAT */
    LOGO_BTI_NINTENDO_376X104=0x3,
    LOGO_BTI_PROGRESSIVE_CHOICE=0x4,
    LOGO_BTI_PROGRESSIVE_CHOICE_FR=0x5,
    LOGO_BTI_PROGRESSIVE_CHOICE_GM=0x6,
    LOGO_BTI_PROGRESSIVE_CHOICE_IT=0x7,
    LOGO_BTI_PROGRESSIVE_CHOICE_SP=0x8,
    LOGO_BTI_PROGRESSIVE_INTER=0x9,
    LOGO_BTI_PROGRESSIVE_INTER_FR=0xA,
    LOGO_BTI_PROGRESSIVE_INTER_GM=0xB,
    LOGO_BTI_PROGRESSIVE_INTER_IT=0xC,
    LOGO_BTI_PROGRESSIVE_INTER_SP=0xD,
    LOGO_BTI_PROGRESSIVE_NO=0xE,
    LOGO_BTI_PROGRESSIVE_NO_FR=0xF,
    LOGO_BTI_PROGRESSIVE_NO_GM=0x10,
    LOGO_BTI_PROGRESSIVE_NO_IT=0x11,
    LOGO_BTI_PROGRESSIVE_NO_SP=0x12,
    LOGO_BTI_PROGRESSIVE_PRO=0x13,
    LOGO_BTI_PROGRESSIVE_PRO_FR=0x14,
    LOGO_BTI_PROGRESSIVE_PRO_GM=0x15,
    LOGO_BTI_PROGRESSIVE_PRO_IT=0x16,
    LOGO_BTI_PROGRESSIVE_PRO_SP=0x17,
    LOGO_BTI_PROGRESSIVE_YES=0x18,
    LOGO_BTI_PROGRESSIVE_YES_FR=0x19,
    LOGO_BTI_PROGRESSIVE_YES_GM=0x1A,
    LOGO_BTI_PROGRESSIVE_YES_IT=0x1B,
    LOGO_BTI_PROGRESSIVE_YES_SP=0x1C,
    LOGO_BTI_TITLE_DOLBY_MARK=0x1D,
};
#else
enum LOGO_RES_FILE_ID { // IDs and indexes are synced
    /* DAT */
    LOGO_BTI_NINTENDO_376X104=0x3,
    LOGO_BTI_PROGRESSIVE_CHOICE=0x4,
    LOGO_BTI_PROGRESSIVE_INTER=0x5,
    LOGO_BTI_PROGRESSIVE_NO=0x6,
    LOGO_BTI_PROGRESSIVE_PRO=0x7,
    LOGO_BTI_PROGRESSIVE_YES=0x8,
    LOGO_BTI_TITLE_DOLBY_MARK=0x9,
};
#endif

#endif /* RES_LOGO_H */
