#ifndef RES_CO_H
#define RES_CO_H

#include "global.h" // IWYU pragma: keep

enum CO_RES_FILE_ID {
    /* BCKS */
    CO_BCK_COPEAL_MIGAMAE=0x0,
    CO_BCK_COPEAL_OKIRU=0x1,
    CO_BCK_COPEAL_READ=0x2,
    CO_BCK_COPEAL_SWAIT01=0x3,
    CO_BCK_COPEAL_TALK01=0x4,
    CO_BCK_COPEAL_TALK02=0x5,
    CO_BCK_COPEAL_UKETORI=0x6,
    CO_BCK_COPEAL_WAIT01=0x7,
    CO_BCK_COPEAL_WAIT02=0x8,
    CO_BCK_CO_MIGAMAE=0x9,
    CO_BCK_CO_OKIRU=0xA,
    CO_BCK_CO_READ=0xB,
    CO_BCK_CO_SWAIT01=0xC,
    CO_BCK_CO_TALK01=0xD,
    CO_BCK_CO_TALK02=0xE,
    CO_BCK_CO_UKETORI=0xF,
    CO_BCK_CO_WAIT01=0x10,
    CO_BCK_CO_WAIT02=0x11,
    CO_BCK_CO_WAIT00=0x1D,
    
    /* BDL */
    CO_BDL_CO_LETTER=0x12,
    
    /* BDLM */
    CO_BDL_CO=0x13,
    CO_BDL_CO_PEAL=0x14,
    
    /* BTK */
    CO_BTK_CO_PEAL=0x15,
    
    /* BTP */
    CO_BTP_FUAN=0x16,
    CO_BTP_KIRI=0x17,
    CO_BTP_MIGAMAE=0x18,
    CO_BTP_NAGAME=0x19,
    CO_BTP_NIKO=0x1A,
    CO_BTP_OKIRU=0x1B,
    CO_BTP_OKORI=0x1C,
};

enum CO_RES_FILE_INDEX {
    /* BCKS */
    CO_INDEX_BCK_COPEAL_MIGAMAE=0x7,
    CO_INDEX_BCK_COPEAL_OKIRU=0x8,
    CO_INDEX_BCK_COPEAL_READ=0x9,
    CO_INDEX_BCK_COPEAL_SWAIT01=0xA,
    CO_INDEX_BCK_COPEAL_TALK01=0xB,
    CO_INDEX_BCK_COPEAL_TALK02=0xC,
    CO_INDEX_BCK_COPEAL_UKETORI=0xD,
    CO_INDEX_BCK_COPEAL_WAIT01=0xE,
    CO_INDEX_BCK_COPEAL_WAIT02=0xF,
    CO_INDEX_BCK_CO_MIGAMAE=0x10,
    CO_INDEX_BCK_CO_OKIRU=0x11,
    CO_INDEX_BCK_CO_READ=0x12,
    CO_INDEX_BCK_CO_SWAIT01=0x13,
    CO_INDEX_BCK_CO_TALK01=0x14,
    CO_INDEX_BCK_CO_TALK02=0x15,
    CO_INDEX_BCK_CO_UKETORI=0x16,
    CO_INDEX_BCK_CO_WAIT01=0x17,
    CO_INDEX_BCK_CO_WAIT02=0x18,
    CO_INDEX_BCK_CO_WAIT00=0x19,
    
    /* BDL */
    CO_INDEX_BDL_CO_LETTER=0x1C,
    
    /* BDLM */
    CO_INDEX_BDL_CO=0x1F,
    CO_INDEX_BDL_CO_PEAL=0x20,
    
    /* BTK */
    CO_INDEX_BTK_CO_PEAL=0x23,
    
    /* BTP */
    CO_INDEX_BTP_FUAN=0x26,
    CO_INDEX_BTP_KIRI=0x27,
    CO_INDEX_BTP_MIGAMAE=0x28,
    CO_INDEX_BTP_NAGAME=0x29,
    CO_INDEX_BTP_NIKO=0x2A,
    CO_INDEX_BTP_OKIRU=0x2B,
    CO_INDEX_BTP_OKORI=0x2C,
};

#endif /* RES_CO_H */
