#ifndef RES_MGTEM_H
#define RES_MGTEM_H

enum MGTEM_RES_FILE_ID { // IDs and indexes are synced
    /* SCRN */
    MGTEM_BLO_SHIP_RACE2=0x4,
    
    /* TIMG */
    MGTEM_BTI_MT_SHIPFONT_A=0x7,
    MGTEM_BTI_MT_SHIPFONT_APOSTROPHE=0x8,
    MGTEM_BTI_MT_SHIPFONT_C_BIG=0x9,
    MGTEM_BTI_MT_SHIPFONT_D=0xA,
    MGTEM_BTI_MT_SHIPFONT_E=0xB,
    MGTEM_BTI_MT_SHIPFONT_EX=0xC,
    MGTEM_BTI_MT_SHIPFONT_E_BIG=0xD,
    MGTEM_BTI_MT_SHIPFONT_F_BIG=0xE,
    MGTEM_BTI_MT_SHIPFONT_G=0xF,
    MGTEM_BTI_MT_SHIPFONT_G_BIG=0x10,
    MGTEM_BTI_MT_SHIPFONT_I=0x11,
    MGTEM_BTI_MT_SHIPFONT_L=0x12,
    MGTEM_BTI_MT_SHIPFONT_M=0x13,
    MGTEM_BTI_MT_SHIPFONT_N=0x14,
    MGTEM_BTI_MT_SHIPFONT_O=0x15,
    MGTEM_BTI_MT_SHIPFONT_P=0x16,
    MGTEM_BTI_MT_SHIPFONT_P_BIG=0x17,
    MGTEM_BTI_MT_SHIPFONT_R_BIG=0x18,
    MGTEM_BTI_MT_SHIPFONT_S=0x19,
    MGTEM_BTI_MT_SHIPFONT_T=0x1A,
    MGTEM_BTI_MT_SHIPFONT_T_BIG=0x1B,
    MGTEM_BTI_MT_SHIPFONT_U=0x1C,
    MGTEM_BTI_MT_SHIPFONT_Y_BIG=0x1D,
};

#endif /* RES_MGTEM_H */
