/**
 * d_a_player_battle.inc
 *
 * Code relating to (?) (How is this different from the "cut" functions in the sword file?)
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_link.h"

/* 8013E250-8013E384       .text setSpecialBattle__9daPy_lk_cFi */
void daPy_lk_c::setSpecialBattle(int) {
    /* Nonmatching */
}

/* 8013E384-8013E454       .text changeSpecialBattle__9daPy_lk_cFv */
void daPy_lk_c::changeSpecialBattle() {
    /* Nonmatching */
}

/* 8013E454-8013E72C       .text procBtJump_init__9daPy_lk_cFP13fopEn_enemy_c */
void daPy_lk_c::procBtJump_init(fopEn_enemy_c*) {
    /* Nonmatching */
}

/* 8013E72C-8013E860       .text procBtJump__9daPy_lk_cFv */
void daPy_lk_c::procBtJump() {
    /* Nonmatching */
}

/* 8013E860-8013E9D4       .text procBtJumpCut_init__9daPy_lk_cFP4cXyz */
void daPy_lk_c::procBtJumpCut_init(cXyz*) {
    /* Nonmatching */
}

/* 8013E9D4-8013EBD0       .text procBtJumpCut__9daPy_lk_cFv */
void daPy_lk_c::procBtJumpCut() {
    /* Nonmatching */
}

/* 8013EBD0-8013EC50       .text procBtSlide__9daPy_lk_cFv */
void daPy_lk_c::procBtSlide() {
    /* Nonmatching */
}

/* 8013EC50-8013EE64       .text procBtRoll_init__9daPy_lk_cFP13fopEn_enemy_c */
void daPy_lk_c::procBtRoll_init(fopEn_enemy_c*) {
    /* Nonmatching */
}

/* 8013EE64-8013F010       .text procBtRoll__9daPy_lk_cFv */
void daPy_lk_c::procBtRoll() {
    /* Nonmatching */
}

/* 8013F010-8013F200       .text procBtRollCut_init__9daPy_lk_cFP4cXyz */
void daPy_lk_c::procBtRollCut_init(cXyz*) {
    /* Nonmatching */
}

/* 8013F200-8013F3E8       .text procBtRollCut__9daPy_lk_cFv */
void daPy_lk_c::procBtRollCut() {
    /* Nonmatching */
}

/* 8013F3E8-8013F4A8       .text procBtVerticalJump_init__9daPy_lk_cFP13fopEn_enemy_c */
void daPy_lk_c::procBtVerticalJump_init(fopEn_enemy_c*) {
    /* Nonmatching */
}

/* 8013F4A8-8013F520       .text procBtVerticalJump__9daPy_lk_cFv */
void daPy_lk_c::procBtVerticalJump() {
    /* Nonmatching */
}

/* 8013F520-8013F5BC       .text procBtVerticalJumpCut_init__9daPy_lk_cFv */
void daPy_lk_c::procBtVerticalJumpCut_init() {
    /* Nonmatching */
}

/* 8013F5BC-8013F6E4       .text procBtVerticalJumpCut__9daPy_lk_cFv */
void daPy_lk_c::procBtVerticalJumpCut() {
    /* Nonmatching */
}

/* 8013F6E4-8013F7F0       .text procBtVerticalJumpLand_init__9daPy_lk_cFv */
void daPy_lk_c::procBtVerticalJumpLand_init() {
    /* Nonmatching */
}

/* 8013F7F0-8013F848       .text procBtVerticalJumpLand__9daPy_lk_cFv */
void daPy_lk_c::procBtVerticalJumpLand() {
    /* Nonmatching */
}
