/**
 * d_a_player_climb.inc
 *
 * Code relating to climbing on walls (like vines).
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_main.h"

/* 80135B50-80135B74       .text getClimbMoveAnmSpeed__9daPy_lk_cFv */
void daPy_lk_c::getClimbMoveAnmSpeed() {
    /* Nonmatching */
}

/* 80135B74-80135DA0       .text setClimbShapeOffset__9daPy_lk_cFv */
void daPy_lk_c::setClimbShapeOffset() {
    /* Nonmatching */
}

/* 80135DA0-80135E14       .text getClimbDirectionFromAngle__9daPy_lk_cFv */
void daPy_lk_c::getClimbDirectionFromAngle() {
    /* Nonmatching */
}

/* 80135E14-80135E98       .text changeClimbMoveProc__9daPy_lk_cFi */
void daPy_lk_c::changeClimbMoveProc(int) {
    /* Nonmatching */
}

/* 80135E98-80136154       .text setMoveBGCorrectClimb__9daPy_lk_cFv */
void daPy_lk_c::setMoveBGCorrectClimb() {
    /* Nonmatching */
}

/* 80136154-80136200       .text checkBgCorrectClimbMove__9daPy_lk_cFP4cXyzP4cXyz */
BOOL daPy_lk_c::checkBgCorrectClimbMove(cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 80136200-80136588       .text checkBgClimbMove__9daPy_lk_cFv */
BOOL daPy_lk_c::checkBgClimbMove() {
    /* Nonmatching */
}

/* 80136588-801365F4       .text procClimbUpStart_init_sub__9daPy_lk_cFv */
void daPy_lk_c::procClimbUpStart_init_sub() {
    /* Nonmatching */
}

/* 801365F4-80136708       .text procClimbUpStart_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procClimbUpStart_init() {
    /* Nonmatching */
}

/* 80136708-8013680C       .text procClimbUpStart__9daPy_lk_cFv */
BOOL daPy_lk_c::procClimbUpStart() {
    /* Nonmatching */
}

/* 8013680C-8013693C       .text procClimbDownStart_init__9daPy_lk_cFs */
BOOL daPy_lk_c::procClimbDownStart_init(s16) {
    /* Nonmatching */
}

/* 8013693C-80136A34       .text procClimbDownStart__9daPy_lk_cFv */
BOOL daPy_lk_c::procClimbDownStart() {
    /* Nonmatching */
}

/* 80136A34-80136B80       .text procClimbMoveUpDown_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procClimbMoveUpDown_init(int) {
    /* Nonmatching */
}

/* 80136B80-80136C7C       .text procClimbMoveUpDown__9daPy_lk_cFv */
BOOL daPy_lk_c::procClimbMoveUpDown() {
    /* Nonmatching */
}

/* 80136C7C-80136E28       .text procClimbMoveSide_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procClimbMoveSide_init(int) {
    /* Nonmatching */
}

/* 80136E28-8013707C       .text procClimbMoveSide__9daPy_lk_cFv */
BOOL daPy_lk_c::procClimbMoveSide() {
    /* Nonmatching */
}
