/**
 * d_a_player_hang.inc
 *
 * Code relating to hanging and moving on a ledge.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_link.h"

/* 80133F1C-80133F40       .text getHangMoveAnmSpeed__9daPy_lk_cFv */
void daPy_lk_c::getHangMoveAnmSpeed() {
    /* Nonmatching */
}

/* 80133F40-80133FB4       .text getHangDirectionFromAngle__9daPy_lk_cFv */
void daPy_lk_c::getHangDirectionFromAngle() {
    /* Nonmatching */
}

/* 80133FB4-801342D8       .text changeHangMoveProc__9daPy_lk_cFi */
void daPy_lk_c::changeHangMoveProc(int) {
    /* Nonmatching */
}

/* 801342D8-80134440       .text changeHangEndProc__9daPy_lk_cFi */
void daPy_lk_c::changeHangEndProc(int) {
    /* Nonmatching */
}

/* 80134440-80134630       .text setHangShapeOffset__9daPy_lk_cFv */
void daPy_lk_c::setHangShapeOffset() {
    /* Nonmatching */
}

/* 80134630-80134908       .text procHangStart_init__9daPy_lk_cFv */
void daPy_lk_c::procHangStart_init() {
    /* Nonmatching */
}

/* 80134908-801349D8       .text procHangStart__9daPy_lk_cFv */
void daPy_lk_c::procHangStart() {
    /* Nonmatching */
}

/* 801349D8-80134DF8       .text procHangFallStart_init__9daPy_lk_cFP8cM3dGPla */
void daPy_lk_c::procHangFallStart_init(cM3dGPla*) {
    /* Nonmatching */
}

/* 80134DF8-80134EF0       .text procHangFallStart__9daPy_lk_cFv */
void daPy_lk_c::procHangFallStart() {
    /* Nonmatching */
}

/* 80134EF0-80134F74       .text procHangUp_init__9daPy_lk_cFi */
void daPy_lk_c::procHangUp_init(int) {
    /* Nonmatching */
}

/* 80134F74-80135094       .text procHangUp__9daPy_lk_cFv */
void daPy_lk_c::procHangUp() {
    /* Nonmatching */
}

/* 80135094-80135140       .text procHangWait_init__9daPy_lk_cFv */
void daPy_lk_c::procHangWait_init() {
    /* Nonmatching */
}

/* 80135140-801351FC       .text procHangWait__9daPy_lk_cFv */
void daPy_lk_c::procHangWait() {
    /* Nonmatching */
}

/* 801351FC-80135354       .text procHangMove_init__9daPy_lk_cFi */
void daPy_lk_c::procHangMove_init(int) {
    /* Nonmatching */
}

/* 80135354-801357C0       .text procHangMove__9daPy_lk_cFv */
void daPy_lk_c::procHangMove() {
    /* Nonmatching */
}

/* 801357C0-80135874       .text procHangClimb_init__9daPy_lk_cFf */
void daPy_lk_c::procHangClimb_init(float) {
    /* Nonmatching */
}

/* 80135874-801358D0       .text procHangClimb__9daPy_lk_cFv */
void daPy_lk_c::procHangClimb() {
    /* Nonmatching */
}

/* 801358D0-80135AE0       .text procHangWallCatch_init__9daPy_lk_cFv */
void daPy_lk_c::procHangWallCatch_init() {
    /* Nonmatching */
}

/* 80135AE0-80135B50       .text procHangWallCatch__9daPy_lk_cFv */
void daPy_lk_c::procHangWallCatch() {
    /* Nonmatching */
}
