/**
 * d_a_player_food.inc
 *
 * Code relating to the All-Purpose Bait and Hyoi Pear items.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_main.h"

/* 80154334-801543A0       .text setHyoiModel__9daPy_lk_cFv */
void daPy_lk_c::setHyoiModel() {
    /* Nonmatching */
}

/* 801543A0-801546F4       .text procFoodThrow_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procFoodThrow_init() {
    /* Nonmatching */
}

/* 801546F4-80154880       .text procFoodThrow__9daPy_lk_cFv */
BOOL daPy_lk_c::procFoodThrow() {
    /* Nonmatching */
}

/* 80154880-80154A48       .text procFoodSet_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procFoodSet_init() {
    /* Nonmatching */
}

/* 80154A48-80154B80       .text procFoodSet__9daPy_lk_cFv */
BOOL daPy_lk_c::procFoodSet() {
    /* Nonmatching */
}
