//
// Generated by dtk
// Translation Unit: d_a_shutter.cpp
//

#include "d/actor/d_a_shutter.h"
#include "d/d_procname.h"

/* 00000078-00000108       .text _delete__11daShutter_cFv */
BOOL daShutter_c::_delete() {
    /* Nonmatching */
}

/* 00000108-00000128       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00000128-000002B8       .text CreateHeap__11daShutter_cFv */
void daShutter_c::CreateHeap() {
    /* Nonmatching */
}

/* 000002B8-000004B4       .text Create__11daShutter_cFv */
s32 daShutter_c::Create() {
    /* Nonmatching */
}

/* 000004B4-000005A0       .text _create__11daShutter_cFv */
s32 daShutter_c::_create() {
    /* Nonmatching */
}

/* 000005E0-000006F0       .text set_mtx__11daShutter_cFv */
void daShutter_c::set_mtx() {
    /* Nonmatching */
}

/* 000006F0-00000788       .text _execute__11daShutter_cFv */
BOOL daShutter_c::_execute() {
    /* Nonmatching */
}

/* 00000788-00000B14       .text shutter_move__11daShutter_cFv */
void daShutter_c::shutter_move() {
    /* Nonmatching */
}

/* 00000B14-00000CF0       .text demo__11daShutter_cFv */
void daShutter_c::demo() {
    /* Nonmatching */
}

/* 00000CF0-00000DD8       .text _draw__11daShutter_cFv */
BOOL daShutter_c::_draw() {
    /* Nonmatching */
}

/* 00000DD8-00000DF8       .text daShutter_Create__FPv */
static s32 daShutter_Create(void*) {
    /* Nonmatching */
}

/* 00000DF8-00000E18       .text daShutter_Delete__FPv */
static BOOL daShutter_Delete(void*) {
    /* Nonmatching */
}

/* 00000E18-00000E38       .text daShutter_Draw__FPv */
static BOOL daShutter_Draw(void*) {
    /* Nonmatching */
}

/* 00000E38-00000E58       .text daShutter_Execute__FPv */
static BOOL daShutter_Execute(void*) {
    /* Nonmatching */
}

/* 00000E58-00000E60       .text daShutter_IsDelete__FPv */
static BOOL daShutter_IsDelete(void*) {
    /* Nonmatching */
}


static actor_method_class daShutterMethodTable = {
    (process_method_func)daShutter_Create,
    (process_method_func)daShutter_Delete,
    (process_method_func)daShutter_Execute,
    (process_method_func)daShutter_IsDelete,
    (process_method_func)daShutter_Draw,
};

actor_process_profile_definition g_profile_SHUTTER = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 0x0003,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_SHUTTER,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daShutter_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ 0x01BA,
    /* Actor SubMtd */ &daShutterMethodTable,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* CullType     */ fopAc_CULLBOX_CUSTOM_e,
};
