//
// Generated by dtk
// Translation Unit: d_a_npc_kg2.cpp
//

#include "d_a_npc_kg2.h"
#include "dolphin/types.h"

/* 000000EC-00000194       .text __ct__15daNpc_Kg2_HIO_cFv */
daNpc_Kg2_HIO_c::daNpc_Kg2_HIO_c() {
    /* Nonmatching */
}

/* 00000194-00000368       .text nodeCallBack__FP7J3DNodei */
void nodeCallBack(J3DNode*, int) {
    /* Nonmatching */
}

/* 00000368-000003A4       .text __dt__4cXyzFv */
cXyz::~cXyz() {
    /* Nonmatching */
}

/* 000003A4-0000048C       .text set_mtx__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::set_mtx() {
    /* Nonmatching */
}

/* 0000048C-000005A0       .text initTexPatternAnm__11daNpc_Kg2_cFb */
void daNpc_Kg2_c::initTexPatternAnm(bool) {
    /* Nonmatching */
}

/* 000005A0-000006EC       .text playTexPatternAnm__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::playTexPatternAnm() {
    /* Nonmatching */
}

/* 000006EC-00000838       .text setAnm__11daNpc_Kg2_cFScf */
void daNpc_Kg2_c::setAnm(signed char, float) {
    /* Nonmatching */
}

/* 00000838-000009E8       .text subAnm__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::subAnm() {
    /* Nonmatching */
}

/* 000009E8-00000B3C       .text chkAttention__11daNpc_Kg2_cF4cXyzs */
void daNpc_Kg2_c::chkAttention(cXyz, short) {
    /* Nonmatching */
}

/* 00000B3C-00000BC0       .text eventOrder__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::eventOrder() {
    /* Nonmatching */
}

/* 00000BC0-00000CC4       .text checkOrder__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::checkOrder() {
    /* Nonmatching */
}

/* 00000CC4-00000E38       .text getMsg__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::getMsg() {
    /* Nonmatching */
}

/* 00000E38-00001028       .text next_msgStatus__11daNpc_Kg2_cFPUl */
void daNpc_Kg2_c::next_msgStatus(unsigned long*) {
    /* Nonmatching */
}

/* 00001028-000012EC       .text anmAtr__11daNpc_Kg2_cFUs */
void daNpc_Kg2_c::anmAtr(unsigned short) {
    /* Nonmatching */
}

/* 000012EC-00001308       .text setAttention__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::setAttention() {
    /* Nonmatching */
}

/* 00001308-00001448       .text lookBack__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::lookBack() {
    /* Nonmatching */
}

/* 00001448-00001468       .text CallbackCreateHeap__FP10fopAc_ac_c */
void CallbackCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00001468-0000180C       .text CreateHeap__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::CreateHeap() {
    /* Nonmatching */
}

/* 0000180C-00001A9C       .text CreateInit__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::CreateInit() {
    /* Nonmatching */
}

/* 00001A9C-00001BDC       .text wait01__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::wait01() {
    /* Nonmatching */
}

/* 00001BDC-00001CA4       .text talk01__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::talk01() {
    /* Nonmatching */
}

/* 00001CA4-00001D88       .text evn_setAnm_init__11daNpc_Kg2_cFi */
void daNpc_Kg2_c::evn_setAnm_init(int) {
    /* Nonmatching */
}

/* 00001D88-00001E4C       .text evn_setAnm__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::evn_setAnm() {
    /* Nonmatching */
}

/* 00001E4C-00001F14       .text evn_jnt_lock_init__11daNpc_Kg2_cFi */
void daNpc_Kg2_c::evn_jnt_lock_init(int) {
    /* Nonmatching */
}

/* 00001F14-00001F88       .text evn_talk_init__11daNpc_Kg2_cFi */
void daNpc_Kg2_c::evn_talk_init(int) {
    /* Nonmatching */
}

/* 00001F88-00001FBC       .text evn_talk__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::evn_talk() {
    /* Nonmatching */
}

/* 00001FBC-00002070       .text evn_createItem_init__11daNpc_Kg2_cFi */
void daNpc_Kg2_c::evn_createItem_init(int) {
    /* Nonmatching */
}

/* 00002070-000021EC       .text privateCut__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::privateCut() {
    /* Nonmatching */
}

/* 000021EC-00002250       .text processMove__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::processMove() {
    /* Nonmatching */
}

/* 00002250-00002334       .text wait_action__11daNpc_Kg2_cFPv */
void daNpc_Kg2_c::wait_action(void*) {
    /* Nonmatching */
}

/* 00002334-00002590       .text event_wait_action__11daNpc_Kg2_cFPv */
void daNpc_Kg2_c::event_wait_action(void*) {
    /* Nonmatching */
}

/* 00002590-000027BC       .text _create__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::_create() {
    /* Nonmatching */
}

/* 000027BC-00002818       .text __dt__13mDoExt_btpAnmFv */
mDoExt_btpAnm::~mDoExt_btpAnm() {
    /* Nonmatching */
}

/* 00002818-00002860       .text __dt__14mDoExt_baseAnmFv */
mDoExt_baseAnm::~mDoExt_baseAnm() {
    /* Nonmatching */
}

/* 00002860-0000292C       .text __dt__8dCcD_CylFv */
dCcD_Cyl::~dCcD_Cyl() {
    /* Nonmatching */
}

/* 0000292C-00002974       .text __dt__8cM3dGCylFv */
cM3dGCyl::~cM3dGCyl() {
    /* Nonmatching */
}

/* 00002974-000029D0       .text __dt__14cCcD_ShapeAttrFv */
cCcD_ShapeAttr::~cCcD_ShapeAttr() {
    /* Nonmatching */
}

/* 000029D0-00002A18       .text __dt__8cM3dGAabFv */
cM3dGAab::~cM3dGAab() {
    /* Nonmatching */
}

/* 00002A18-00002A74       .text __dt__10dCcD_GSttsFv */
dCcD_GStts::~dCcD_GStts() {
    /* Nonmatching */
}

/* 00002A74-00002AFC       .text __dt__12dBgS_AcchCirFv */
dBgS_AcchCir::~dBgS_AcchCir() {
    /* Nonmatching */
}

/* 00002AFC-00002B6C       .text __dt__12dBgS_ObjAcchFv */
dBgS_ObjAcch::~dBgS_ObjAcch() {
    /* Nonmatching */
}

/* 00002B6C-00002BFC       .text _delete__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::_delete() {
    /* Nonmatching */
}

/* 00002BFC-00002D14       .text _execute__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::_execute() {
    /* Nonmatching */
}

/* 00002D14-00002E74       .text _draw__11daNpc_Kg2_cFv */
void daNpc_Kg2_c::_draw() {
    /* Nonmatching */
}

/* 00002E74-00002E94       .text daNpc_Kg2_Create__FP10fopAc_ac_c */
void daNpc_Kg2_Create(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00002E94-00002EB4       .text daNpc_Kg2_Delete__FP11daNpc_Kg2_c */
void daNpc_Kg2_Delete(daNpc_Kg2_c*) {
    /* Nonmatching */
}

/* 00002EB4-00002ED4       .text daNpc_Kg2_Execute__FP11daNpc_Kg2_c */
void daNpc_Kg2_Execute(daNpc_Kg2_c*) {
    /* Nonmatching */
}

/* 00002ED4-00002EF4       .text daNpc_Kg2_Draw__FP11daNpc_Kg2_c */
void daNpc_Kg2_Draw(daNpc_Kg2_c*) {
    /* Nonmatching */
}

/* 00002EF4-00002EFC       .text daNpc_Kg2_IsDelete__FP11daNpc_Kg2_c */
void daNpc_Kg2_IsDelete(daNpc_Kg2_c*) {
    /* Nonmatching */
}

/* 00002EFC-00002F44       .text __dt__13cBgS_PolyInfoFv */
cBgS_PolyInfo::~cBgS_PolyInfo() {
    /* Nonmatching */
}

/* 00002F44-00002F8C       .text __dt__8cM2dGCirFv */
cM2dGCir::~cM2dGCir() {
    /* Nonmatching */
}

/* 00002F8C-00002FE8       .text __dt__8cM3dGCirFv */
cM3dGCir::~cM3dGCir() {
    /* Nonmatching */
}

/* 00002FE8-00003030       .text __dt__10cCcD_GSttsFv */
cCcD_GStts::~cCcD_GStts() {
    /* Nonmatching */
}

/* 00003030-00003040       .text GetShapeAttr__8dCcD_CylFv */
void dCcD_Cyl::GetShapeAttr() {
    /* Nonmatching */
}

/* 00003040-00003048       .text GetCoCP__12cCcD_CylAttrFv */
void cCcD_CylAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00003048-00003050       .text GetCoCP__12cCcD_CylAttrCFv */
void cCcD_CylAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00003050-00003058       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_AabAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_AabAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00003058-00003060       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_PntAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_PntAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00003060-00003098       .text CrossAtTg__12cCcD_CylAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00003098-000030A0       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_AabAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_AabAttr&, float*) const {
    /* Nonmatching */
}

/* 000030A0-000030A8       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_TriAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_TriAttr&, float*) const {
    /* Nonmatching */
}

/* 000030A8-000030B0       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_PntAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_PntAttr&, float*) const {
    /* Nonmatching */
}

/* 000030B0-000030E8       .text CrossCo__12cCcD_CylAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 000030E8-000030EC       .text GetGObjInf__12cCcD_GObjInfCFv */
void cCcD_GObjInf::GetGObjInf() const {
    /* Nonmatching */
}

/* 000030EC-000030F4       .text GetShapeAttr__8cCcD_ObjCFv */
void cCcD_Obj::GetShapeAttr() const {
    /* Nonmatching */
}

/* 000030F4-000030FC       .text CrossAtTg__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_ShapeAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 000030FC-00003104       .text CrossCo__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_ShapeAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00003104-00003110       .text GetCoCP__14cCcD_ShapeAttrFv */
void cCcD_ShapeAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00003110-0000311C       .text GetCoCP__14cCcD_ShapeAttrCFv */
void cCcD_ShapeAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 0000311C-0000317C       .text __dt__15daNpc_Kg2_HIO_cFv */
daNpc_Kg2_HIO_c::~daNpc_Kg2_HIO_c() {
    /* Nonmatching */
}

/* 0000317C-00003198       .text cLib_calcTimer<s>__FPs */
void cLib_calcTimer<short>(short*) {
    /* Nonmatching */
}

/* 000031D4-000031DC       .text @32@__dt__12dBgS_ObjAcchFv */
void @32@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 000031DC-000031E4       .text @20@__dt__12dBgS_ObjAcchFv */
void @20@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 000031E4-000031EC       .text @280@__dt__8dCcD_CylFv */
void @280@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 000031EC-000031F4       .text @248@__dt__8dCcD_CylFv */
void @248@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 000031F4-0000323C       .text __dt__10dNpc_HIO_cFv */
dNpc_HIO_c::~dNpc_HIO_c() {
    /* Nonmatching */
}

/* 0000323C-00003244       .text next_msgStatus__12fopNpc_npc_cFPUl */
void fopNpc_npc_c::next_msgStatus(unsigned long*) {
    /* Nonmatching */
}

/* 00003244-0000324C       .text getMsg__12fopNpc_npc_cFv */
void fopNpc_npc_c::getMsg() {
    /* Nonmatching */
}

/* 0000324C-00003250       .text anmAtr__12fopNpc_npc_cFUs */
void fopNpc_npc_c::anmAtr(unsigned short) {
    /* Nonmatching */
}

