/**
 * d_a_player_crawl.inc
 *
 * Code relating to crawling.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_link.h"

/* 801387A4-801387EC       .text getCrawlMoveAnmSpeed__9daPy_lk_cFv */
void daPy_lk_c::getCrawlMoveAnmSpeed() {
    /* Nonmatching */
}

/* 801387EC-80138868       .text getCrawlMoveSpeed__9daPy_lk_cFv */
void daPy_lk_c::getCrawlMoveSpeed() {
    /* Nonmatching */
}

/* 80138868-801389D0       .text setCrawlMoveDirectionArrow__9daPy_lk_cFv */
void daPy_lk_c::setCrawlMoveDirectionArrow() {
    /* Nonmatching */
}

/* 801389D0-80138D50       .text changeCrawlAutoMoveProc__9daPy_lk_cFP4cXyz */
void daPy_lk_c::changeCrawlAutoMoveProc(cXyz*) {
    /* Nonmatching */
}

/* 80138D50-80138F28       .text getCrawlMoveVec__9daPy_lk_cFP4cXyzP4cXyzP4cXyz */
void daPy_lk_c::getCrawlMoveVec(cXyz*, cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 80138F28-801390B8       .text crawlBgCheck__9daPy_lk_cFP4cXyzP4cXyz */
void daPy_lk_c::crawlBgCheck(cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 801390B8-801392BC       .text checkCrawlSideWall__9daPy_lk_cFP4cXyzP4cXyzP4cXyzP4cXyzPsPs */
void daPy_lk_c::checkCrawlSideWall(cXyz*, cXyz*, cXyz*, cXyz*, short*, short*) {
    /* Nonmatching */
}

/* 801392BC-80139424       .text setDoStatusCrawl__9daPy_lk_cFv */
void daPy_lk_c::setDoStatusCrawl() {
    /* Nonmatching */
}

/* 80139424-801394F0       .text procCrawlStart_init__9daPy_lk_cFv */
void daPy_lk_c::procCrawlStart_init() {
    /* Nonmatching */
}

/* 801394F0-80139640       .text procCrawlStart__9daPy_lk_cFv */
void daPy_lk_c::procCrawlStart() {
    /* Nonmatching */
}

/* 80139640-801396B0       .text checkNotCrawlStand__9daPy_lk_cFP4cXyz */
void daPy_lk_c::checkNotCrawlStand(cXyz*) {
    /* Nonmatching */
}

/* 801396B0-80139760       .text checkNotCrawlStand__9daPy_lk_cFP4cXyzP4cXyz */
void daPy_lk_c::checkNotCrawlStand(cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 80139760-80139878       .text procCrawlMove_init__9daPy_lk_cFss */
void daPy_lk_c::procCrawlMove_init(short, short) {
    /* Nonmatching */
}

/* 80139878-8013A004       .text procCrawlMove__9daPy_lk_cFv */
void daPy_lk_c::procCrawlMove() {
    /* Nonmatching */
}

/* 8013A004-8013A0F0       .text procCrawlAutoMove_init__9daPy_lk_cFiP4cXyz */
void daPy_lk_c::procCrawlAutoMove_init(int, cXyz*) {
    /* Nonmatching */
}

/* 8013A0F0-8013A630       .text procCrawlAutoMove__9daPy_lk_cFv */
void daPy_lk_c::procCrawlAutoMove() {
    /* Nonmatching */
}

/* 8013A630-8013A7C4       .text procCrawlEnd_init__9daPy_lk_cFiss */
void daPy_lk_c::procCrawlEnd_init(int, short, short) {
    /* Nonmatching */
}

/* 8013A7C4-8013A85C       .text procCrawlEnd__9daPy_lk_cFv */
void daPy_lk_c::procCrawlEnd() {
    /* Nonmatching */
}
