//
// Generated by dtk
// Translation Unit: d_a_bb.cpp
//

#include "d_a_bb.h"
#include "dolphin/types.h"

/* 000000EC-000003C8       .text nodeCallBack__FP7J3DNodei */
void nodeCallBack(J3DNode*, int) {
    /* Nonmatching */
}

/* 000003C8-00000404       .text __dt__4cXyzFv */
cXyz::~cXyz() {
    /* Nonmatching */
}

/* 00000404-000009A4       .text tail_control__FP8bb_class */
void tail_control(bb_class*) {
    /* Nonmatching */
}

/* 000009A4-00000A94       .text tail_draw__FP8bb_class */
void tail_draw(bb_class*) {
    /* Nonmatching */
}

/* 00000A94-00000B90       .text tex_anm_set__FP8bb_classUs */
void tex_anm_set(bb_class*, unsigned short) {
    /* Nonmatching */
}

/* 00000B90-00000C40       .text bb_eye_tex_anm__FP8bb_class */
void bb_eye_tex_anm(bb_class*) {
    /* Nonmatching */
}

/* 00000C40-00000D74       .text anm_init__FP8bb_classifUcfi */
void anm_init(bb_class*, int, float, unsigned char, float, int) {
    /* Nonmatching */
}

/* 00000D74-00001048       .text s_a_d_sub__FPvPv */
void s_a_d_sub(void*, void*) {
    /* Nonmatching */
}

/* 00001048-00001174       .text __dt__11dBgS_LinChkFv */
dBgS_LinChk::~dBgS_LinChk() {
    /* Nonmatching */
}

/* 00001174-00001214       .text __dt__8dBgS_ChkFv */
dBgS_Chk::~dBgS_Chk() {
    /* Nonmatching */
}

/* 00001214-00001270       .text __dt__15dBgS_GrpPassChkFv */
dBgS_GrpPassChk::~dBgS_GrpPassChk() {
    /* Nonmatching */
}

/* 00001270-000012B8       .text __dt__15cBgS_GrpPassChkFv */
cBgS_GrpPassChk::~cBgS_GrpPassChk() {
    /* Nonmatching */
}

/* 000012B8-00001314       .text __dt__16dBgS_PolyPassChkFv */
dBgS_PolyPassChk::~dBgS_PolyPassChk() {
    /* Nonmatching */
}

/* 00001314-0000135C       .text __dt__16cBgS_PolyPassChkFv */
cBgS_PolyPassChk::~cBgS_PolyPassChk() {
    /* Nonmatching */
}

/* 0000135C-000013F0       .text __dt__11cBgS_LinChkFv */
cBgS_LinChk::~cBgS_LinChk() {
    /* Nonmatching */
}

/* 000013F0-00001438       .text __dt__8cM3dGLinFv */
cM3dGLin::~cM3dGLin() {
    /* Nonmatching */
}

/* 00001438-00001480       .text __dt__13cBgS_PolyInfoFv */
cBgS_PolyInfo::~cBgS_PolyInfo() {
    /* Nonmatching */
}

/* 00001480-000015D4       .text search_esa__FP8bb_class */
void search_esa(bb_class*) {
    /* Nonmatching */
}

/* 000015D4-000015F4       .text kuti_open__FP8bb_classsUl */
void kuti_open(bb_class*, short, unsigned long) {
    /* Nonmatching */
}

/* 000015F4-00001928       .text bb_player_bg_check__FP8bb_class */
void bb_player_bg_check(bb_class*) {
    /* Nonmatching */
}

/* 00001928-00001C50       .text bb_setpos_bg_check__FP8bb_class */
void bb_setpos_bg_check(bb_class*) {
    /* Nonmatching */
}

/* 00001C50-00001DF8       .text bb_player_view_check__FP8bb_class */
void bb_player_view_check(bb_class*) {
    /* Nonmatching */
}

/* 00001DF8-00002250       .text path_check__FP8bb_class */
void path_check(bb_class*) {
    /* Nonmatching */
}

/* 00002250-0000234C       .text daBb_shadowDraw__FP8bb_class */
void daBb_shadowDraw(bb_class*) {
    /* Nonmatching */
}

/* 0000234C-00002444       .text daBb_Draw__FP8bb_class */
void daBb_Draw(bb_class*) {
    /* Nonmatching */
}

/* 00002444-00002708       .text bb_pos_move__FP8bb_class */
void bb_pos_move(bb_class*) {
    /* Nonmatching */
}

/* 00002708-00002854       .text bb_ground_pos_move__FP8bb_class */
void bb_ground_pos_move(bb_class*) {
    /* Nonmatching */
}

/* 00002854-00003224       .text bb_path_move__FP8bb_class */
void bb_path_move(bb_class*) {
    /* Nonmatching */
}

/* 00003224-00003F88       .text bb_auto_move__FP8bb_class */
void bb_auto_move(bb_class*) {
    /* Nonmatching */
}

/* 00003F88-00004000       .text bb_water_check__FP8bb_class */
void bb_water_check(bb_class*) {
    /* Nonmatching */
}

/* 00004000-0000404C       .text pl_name_check__FPvPv */
void pl_name_check(void*, void*) {
    /* Nonmatching */
}

/* 0000404C-000044EC       .text bb_kamome_attack__FP8bb_class */
void bb_kamome_attack(bb_class*) {
    /* Nonmatching */
}

/* 000044EC-00005534       .text bb_atack_move__FP8bb_class */
void bb_atack_move(bb_class*) {
    /* Nonmatching */
}

/* 00005534-00005BB4       .text bb_wait_move__FP8bb_class */
void bb_wait_move(bb_class*) {
    /* Nonmatching */
}

/* 00005BB4-00006234       .text bb_su_wait_move__FP8bb_class */
void bb_su_wait_move(bb_class*) {
    /* Nonmatching */
}

/* 00006234-00006278       .text bb_fail_move__FP8bb_class */
void bb_fail_move(bb_class*) {
    /* Nonmatching */
}

/* 00006278-0000696C       .text damage_check__FP8bb_class */
void damage_check(bb_class*) {
    /* Nonmatching */
}

/* 0000696C-000069A8       .text __dt__5csXyzFv */
csXyz::~csXyz() {
    /* Nonmatching */
}

/* 000069A8-00007778       .text daBb_Execute__FP8bb_class */
void daBb_Execute(bb_class*) {
    /* Nonmatching */
}

/* 00007778-00007780       .text daBb_IsDelete__FP8bb_class */
void daBb_IsDelete(bb_class*) {
    /* Nonmatching */
}

/* 00007780-000077EC       .text daBb_Delete__FP8bb_class */
void daBb_Delete(bb_class*) {
    /* Nonmatching */
}

/* 000077EC-00007A68       .text useHeapInit__FP10fopAc_ac_c */
void useHeapInit(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00007A68-00007F58       .text daBb_Create__FP10fopAc_ac_c */
void daBb_Create(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00007F58-00008394       .text __ct__8bb_classFv */
bb_class::bb_class() {
    /* Nonmatching */
}

/* 00008394-00008460       .text __dt__8dCcD_CylFv */
dCcD_Cyl::~dCcD_Cyl() {
    /* Nonmatching */
}

/* 00008460-000084A8       .text __dt__8cM3dGCylFv */
cM3dGCyl::~cM3dGCyl() {
    /* Nonmatching */
}

/* 000084A8-000084AC       .text __ct__5csXyzFv */
csXyz::csXyz() {
    /* Nonmatching */
}

/* 000084AC-000084B0       .text __ct__4cXyzFv */
cXyz::cXyz() {
    /* Nonmatching */
}

/* 000084B0-0000857C       .text __dt__8dCcD_SphFv */
dCcD_Sph::~dCcD_Sph() {
    /* Nonmatching */
}

/* 0000857C-000085C4       .text __dt__8cM3dGSphFv */
cM3dGSph::~cM3dGSph() {
    /* Nonmatching */
}

/* 000085C4-00008620       .text __dt__14cCcD_ShapeAttrFv */
cCcD_ShapeAttr::~cCcD_ShapeAttr() {
    /* Nonmatching */
}

/* 00008620-00008668       .text __dt__8cM3dGAabFv */
cM3dGAab::~cM3dGAab() {
    /* Nonmatching */
}

/* 00008668-000086C4       .text __dt__10dCcD_GSttsFv */
dCcD_GStts::~dCcD_GStts() {
    /* Nonmatching */
}

/* 000086C4-00008734       .text __dt__12dBgS_ObjAcchFv */
dBgS_ObjAcch::~dBgS_ObjAcch() {
    /* Nonmatching */
}

/* 00008734-000087BC       .text __dt__12dBgS_AcchCirFv */
dBgS_AcchCir::~dBgS_AcchCir() {
    /* Nonmatching */
}

/* 000087BC-00008818       .text __dt__13mDoExt_btpAnmFv */
mDoExt_btpAnm::~mDoExt_btpAnm() {
    /* Nonmatching */
}

/* 00008818-00008860       .text __dt__14mDoExt_baseAnmFv */
mDoExt_baseAnm::~mDoExt_baseAnm() {
    /* Nonmatching */
}

/* 00008860-00008864       .text draw__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::draw(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00008864-00008868       .text executeAfter__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::executeAfter(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00008868-0000886C       .text execute__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::execute(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 0000886C-00008870       .text init__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::init(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00008870-000088B8       .text __dt__34JPACallBackBase<P14JPABaseEmitter>Fv */
JPACallBackBase<JPABaseEmitter*>::~JPACallBackBase() {
    /* Nonmatching */
}

/* 000088B8-00008914       .text __dt__18dPa_levelEcallBackFv */
dPa_levelEcallBack::~dPa_levelEcallBack() {
    /* Nonmatching */
}

/* 00008914-0000895C       .text __dt__8cM2dGCirFv */
cM2dGCir::~cM2dGCir() {
    /* Nonmatching */
}

/* 0000895C-000089B8       .text __dt__8cM3dGCirFv */
cM3dGCir::~cM3dGCir() {
    /* Nonmatching */
}

/* 000089B8-00008A00       .text __dt__10cCcD_GSttsFv */
cCcD_GStts::~cCcD_GStts() {
    /* Nonmatching */
}

/* 00008A00-00008A10       .text GetShapeAttr__8dCcD_CylFv */
void dCcD_Cyl::GetShapeAttr() {
    /* Nonmatching */
}

/* 00008A10-00008A18       .text GetCoCP__12cCcD_CylAttrFv */
void cCcD_CylAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00008A18-00008A20       .text GetCoCP__12cCcD_CylAttrCFv */
void cCcD_CylAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00008A20-00008A28       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_AabAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_AabAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008A28-00008A30       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_PntAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_PntAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008A30-00008A68       .text CrossAtTg__12cCcD_CylAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008A68-00008A70       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_AabAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_AabAttr&, float*) const {
    /* Nonmatching */
}

/* 00008A70-00008A78       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_TriAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_TriAttr&, float*) const {
    /* Nonmatching */
}

/* 00008A78-00008A80       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_PntAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_PntAttr&, float*) const {
    /* Nonmatching */
}

/* 00008A80-00008AB8       .text CrossCo__12cCcD_CylAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00008AB8-00008ABC       .text GetGObjInf__12cCcD_GObjInfCFv */
void cCcD_GObjInf::GetGObjInf() const {
    /* Nonmatching */
}

/* 00008ABC-00008AC4       .text GetShapeAttr__8cCcD_ObjCFv */
void cCcD_Obj::GetShapeAttr() const {
    /* Nonmatching */
}

/* 00008AC4-00008AD4       .text GetShapeAttr__8dCcD_SphFv */
void dCcD_Sph::GetShapeAttr() {
    /* Nonmatching */
}

/* 00008AD4-00008ADC       .text GetCoCP__12cCcD_SphAttrFv */
void cCcD_SphAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00008ADC-00008AE4       .text GetCoCP__12cCcD_SphAttrCFv */
void cCcD_SphAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00008AE4-00008AEC       .text CrossAtTg__12cCcD_SphAttrCFRC12cCcD_AabAttrP4cXyz */
void cCcD_SphAttr::CrossAtTg(const cCcD_AabAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008AEC-00008AF4       .text CrossAtTg__12cCcD_SphAttrCFRC12cCcD_PntAttrP4cXyz */
void cCcD_SphAttr::CrossAtTg(const cCcD_PntAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008AF4-00008B2C       .text CrossAtTg__12cCcD_SphAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_SphAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008B2C-00008B34       .text CrossCo__12cCcD_SphAttrCFRC12cCcD_AabAttrPf */
void cCcD_SphAttr::CrossCo(const cCcD_AabAttr&, float*) const {
    /* Nonmatching */
}

/* 00008B34-00008B3C       .text CrossCo__12cCcD_SphAttrCFRC12cCcD_TriAttrPf */
void cCcD_SphAttr::CrossCo(const cCcD_TriAttr&, float*) const {
    /* Nonmatching */
}

/* 00008B3C-00008B44       .text CrossCo__12cCcD_SphAttrCFRC12cCcD_PntAttrPf */
void cCcD_SphAttr::CrossCo(const cCcD_PntAttr&, float*) const {
    /* Nonmatching */
}

/* 00008B44-00008B7C       .text CrossCo__12cCcD_SphAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_SphAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00008B7C-00008B84       .text CrossAtTg__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_ShapeAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00008B84-00008B8C       .text CrossCo__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_ShapeAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00008B8C-00008B98       .text GetCoCP__14cCcD_ShapeAttrFv */
void cCcD_ShapeAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00008B98-00008BA4       .text GetCoCP__14cCcD_ShapeAttrCFv */
void cCcD_ShapeAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00008CFC-00008D58       .text __dt__7bbHIO_cFv */
bbHIO_c::~bbHIO_c() {
    /* Nonmatching */
}

/* 00008D58-00008DA0       .text __dt__14mDoHIO_entry_cFv */
mDoHIO_entry_c::~mDoHIO_entry_c() {
    /* Nonmatching */
}

/* 00008DA0-00008DA8       .text @20@__dt__11cBgS_LinChkFv */
void @20@__dt__11cBgS_LinChkFv {
    /* Nonmatching */
}

/* 00008DA8-00008DB0       .text @12@__dt__8dBgS_ChkFv */
void @12@__dt__8dBgS_ChkFv {
    /* Nonmatching */
}

/* 00008DB0-00008DB8       .text @20@__dt__11dBgS_LinChkFv */
void @20@__dt__11dBgS_LinChkFv {
    /* Nonmatching */
}

/* 00008DB8-00008DC0       .text @100@__dt__11dBgS_LinChkFv */
void @100@__dt__11dBgS_LinChkFv {
    /* Nonmatching */
}

/* 00008DC0-00008DC8       .text @88@__dt__11dBgS_LinChkFv */
void @88@__dt__11dBgS_LinChkFv {
    /* Nonmatching */
}

/* 00008DC8-00008DD0       .text @32@__dt__12dBgS_ObjAcchFv */
void @32@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 00008DD0-00008DD8       .text @20@__dt__12dBgS_ObjAcchFv */
void @20@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 00008DD8-00008DE0       .text @280@__dt__8dCcD_SphFv */
void @280@__dt__8dCcD_SphFv {
    /* Nonmatching */
}

/* 00008DE0-00008DE8       .text @248@__dt__8dCcD_SphFv */
void @248@__dt__8dCcD_SphFv {
    /* Nonmatching */
}

/* 00008DE8-00008DF0       .text @280@__dt__8dCcD_CylFv */
void @280@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 00008DF0-00008DF8       .text @248@__dt__8dCcD_CylFv */
void @248@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

