/**
 * d_a_player_dproc.inc
 *
 * Code relating to "demo processes" (small cutscene-like actions).
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is known because of an assert contained within
 * a function from this file.
*/

#include "d/actor/d_a_player_link.h"

/* 8012CD60-8012CDD4       .text getDemoLookActor__9daPy_lk_cFv */
void daPy_lk_c::getDemoLookActor() {
    /* Nonmatching */
}

/* 8012CDD4-8012CE2C       .text setTinkleCeiverModel__9daPy_lk_cFv */
void daPy_lk_c::setTinkleCeiverModel() {
    /* Nonmatching */
}

/* 8012CE2C-8012CEFC       .text setTalismanModel__9daPy_lk_cFv */
void daPy_lk_c::setTalismanModel() {
    /* Nonmatching */
}

/* 8012CEFC-8012CFE8       .text setLetterModel__9daPy_lk_cFv */
void daPy_lk_c::setLetterModel() {
    /* Nonmatching */
}

/* 8012CFE8-8012D010       .text checkCaughtShapeHide__9daPy_lk_cFv */
void daPy_lk_c::checkCaughtShapeHide() {
    /* Nonmatching */
}

/* 8012D010-8012D08C       .text setShapeAngleToTalkActor__9daPy_lk_cFv */
void daPy_lk_c::setShapeAngleToTalkActor() {
    /* Nonmatching */
}

/* 8012D08C-8012D134       .text checkEndMessage__9daPy_lk_cFUl */
void daPy_lk_c::checkEndMessage(unsigned long) {
    /* Nonmatching */
}

/* 8012D134-8012D300       .text setTalkStartBack__9daPy_lk_cFv */
void daPy_lk_c::setTalkStartBack() {
    /* Nonmatching */
}

/* 8012D300-8012D3C4       .text dProcTool_init__9daPy_lk_cFv */
void daPy_lk_c::dProcTool_init() {
    /* Nonmatching */
}

/* 8012D3C4-8012DA3C       .text dProcTool__9daPy_lk_cFv */
void daPy_lk_c::dProcTool() {
    /* Nonmatching */
}

/* 8012DA3C-8012DBD0       .text dProcTalk_init__9daPy_lk_cFv */
void daPy_lk_c::dProcTalk_init() {
    /* Nonmatching */
}

/* 8012DBD0-8012DDEC       .text dProcTalk__9daPy_lk_cFv */
void daPy_lk_c::dProcTalk() {
    /* Nonmatching */
}

/* 8012DDEC-8012DEA0       .text dProcDamage_init__9daPy_lk_cFv */
void daPy_lk_c::dProcDamage_init() {
    /* Nonmatching */
}

/* 8012DEA0-8012DF24       .text dProcDamage__9daPy_lk_cFv */
void daPy_lk_c::dProcDamage() {
    /* Nonmatching */
}

/* 8012DF24-8012E054       .text dProcHoldup_init__9daPy_lk_cFv */
void daPy_lk_c::dProcHoldup_init() {
    /* Nonmatching */
}

/* 8012E054-8012E09C       .text dProcHoldup__9daPy_lk_cFv */
void daPy_lk_c::dProcHoldup() {
    /* Nonmatching */
}

/* 8012E09C-8012E244       .text dProcOpenTreasure_init__9daPy_lk_cFv */
void daPy_lk_c::dProcOpenTreasure_init() {
    /* Nonmatching */
}

/* 8012E244-8012E28C       .text dProcOpenTreasure__9daPy_lk_cFv */
void daPy_lk_c::dProcOpenTreasure() {
    /* Nonmatching */
}

/* 8012E28C-8012E418       .text setGetItemSound__9daPy_lk_cFUsi */
void daPy_lk_c::setGetItemSound(unsigned short, int) {
    /* Nonmatching */
}

/* 8012E418-8012E6B4       .text setGetDemo__9daPy_lk_cFv */
void daPy_lk_c::setGetDemo() {
    /* Nonmatching */
}

/* 8012E6B4-8012E8B0       .text dProcGetItem_init__9daPy_lk_cFv */
void daPy_lk_c::dProcGetItem_init() {
    /* Nonmatching */
}

/* 8012E8B0-8012ECB0       .text dProcGetItem__9daPy_lk_cFv */
void daPy_lk_c::dProcGetItem() {
    /* Nonmatching */
}

/* 8012ECB0-8012ED30       .text dProcUnequip_init__9daPy_lk_cFv */
void daPy_lk_c::dProcUnequip_init() {
    /* Nonmatching */
}

/* 8012ED30-8012ED74       .text dProcUnequip__9daPy_lk_cFv */
void daPy_lk_c::dProcUnequip() {
    /* Nonmatching */
}

/* 8012ED74-8012EE0C       .text dProcLavaDamage_init_sub__9daPy_lk_cFv */
void daPy_lk_c::dProcLavaDamage_init_sub() {
    /* Nonmatching */
}

/* 8012EE0C-8012EEE4       .text dProcLavaDamage_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLavaDamage_init() {
    /* Nonmatching */
}

/* 8012EEE4-8012EF78       .text dProcLavaDamage__9daPy_lk_cFv */
void daPy_lk_c::dProcLavaDamage() {
    /* Nonmatching */
}

/* 8012EF78-8012F0DC       .text dProcFreezeDamage_init_sub__9daPy_lk_cFi */
void daPy_lk_c::dProcFreezeDamage_init_sub(int) {
    /* Nonmatching */
}

/* 8012F0DC-8012F174       .text dProcFreezeDamage_init__9daPy_lk_cFv */
void daPy_lk_c::dProcFreezeDamage_init() {
    /* Nonmatching */
}

/* 8012F174-8012F210       .text dProcFreezeDamage__9daPy_lk_cFv */
void daPy_lk_c::dProcFreezeDamage() {
    /* Nonmatching */
}

/* 8012F210-8012F288       .text dProcDead_init_sub__9daPy_lk_cFv */
void daPy_lk_c::dProcDead_init_sub() {
    /* Nonmatching */
}

/* 8012F288-8012F38C       .text dProcDead_init_sub2__9daPy_lk_cFv */
void daPy_lk_c::dProcDead_init_sub2() {
    /* Nonmatching */
}

/* 8012F38C-8012F3B8       .text checkGameOverStart__9daPy_lk_cFv */
void daPy_lk_c::checkGameOverStart() {
    /* Nonmatching */
}

/* 8012F3B8-8012F5A8       .text dProcDead_init__9daPy_lk_cFv */
void daPy_lk_c::dProcDead_init() {
    /* Nonmatching */
}

/* 8012F5A8-8012F928       .text dProcDead__9daPy_lk_cFv */
void daPy_lk_c::dProcDead() {
    /* Nonmatching */
}

/* 8012F928-8012F99C       .text dProcLookAround_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLookAround_init() {
    /* Nonmatching */
}

/* 8012F99C-8012F9E4       .text dProcLookAround__9daPy_lk_cFv */
void daPy_lk_c::dProcLookAround() {
    /* Nonmatching */
}

/* 8012F9E4-8012FA50       .text dProcSalute_init__9daPy_lk_cFv */
void daPy_lk_c::dProcSalute_init() {
    /* Nonmatching */
}

/* 8012FA50-8012FA98       .text dProcSalute__9daPy_lk_cFv */
void daPy_lk_c::dProcSalute() {
    /* Nonmatching */
}

/* 8012FA98-8012FB2C       .text dProcLookAround2_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLookAround2_init() {
    /* Nonmatching */
}

/* 8012FB2C-8012FB88       .text dProcLookAround2__9daPy_lk_cFv */
void daPy_lk_c::dProcLookAround2() {
    /* Nonmatching */
}

/* 8012FB88-8012FC24       .text dProcTalismanPickup_init__9daPy_lk_cFv */
void daPy_lk_c::dProcTalismanPickup_init() {
    /* Nonmatching */
}

/* 8012FC24-8012FCC0       .text dProcTalismanPickup__9daPy_lk_cFv */
void daPy_lk_c::dProcTalismanPickup() {
    /* Nonmatching */
}

/* 8012FCC0-8012FE58       .text dProcTalismanWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcTalismanWait_init() {
    /* Nonmatching */
}

/* 8012FE58-8012FFEC       .text dProcTalismanWait__9daPy_lk_cFv */
void daPy_lk_c::dProcTalismanWait() {
    /* Nonmatching */
}

/* 8012FFEC-801300F4       .text dProcSurprised_init__9daPy_lk_cFv */
void daPy_lk_c::dProcSurprised_init() {
    /* Nonmatching */
}

/* 801300F4-801301C0       .text dProcSurprised__9daPy_lk_cFv */
void daPy_lk_c::dProcSurprised() {
    /* Nonmatching */
}

/* 801301C0-80130278       .text dProcTurnBack_init__9daPy_lk_cFv */
void daPy_lk_c::dProcTurnBack_init() {
    /* Nonmatching */
}

/* 80130278-801302CC       .text dProcTurnBack__9daPy_lk_cFv */
void daPy_lk_c::dProcTurnBack() {
    /* Nonmatching */
}

/* 801302CC-80130338       .text dProcLookUp_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLookUp_init() {
    /* Nonmatching */
}

/* 80130338-80130380       .text dProcLookUp__9daPy_lk_cFv */
void daPy_lk_c::dProcLookUp() {
    /* Nonmatching */
}

/* 80130380-801303FC       .text dProcQuakeWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcQuakeWait_init() {
    /* Nonmatching */
}

/* 801303FC-80130434       .text dProcQuakeWait__9daPy_lk_cFv */
void daPy_lk_c::dProcQuakeWait() {
    /* Nonmatching */
}

/* 80130434-801304A0       .text dProcDance_init__9daPy_lk_cFv */
void daPy_lk_c::dProcDance_init() {
    /* Nonmatching */
}

/* 801304A0-801304D8       .text dProcDance__9daPy_lk_cFv */
void daPy_lk_c::dProcDance() {
    /* Nonmatching */
}

/* 801304D8-80130570       .text dProcCaught_init__9daPy_lk_cFv */
void daPy_lk_c::dProcCaught_init() {
    /* Nonmatching */
}

/* 80130570-801305A8       .text dProcCaught__9daPy_lk_cFv */
void daPy_lk_c::dProcCaught() {
    /* Nonmatching */
}

/* 801305A8-8013065C       .text dProcLookWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLookWait_init() {
    /* Nonmatching */
}

/* 8013065C-80130724       .text dProcLookWait__9daPy_lk_cFv */
void daPy_lk_c::dProcLookWait() {
    /* Nonmatching */
}

/* 80130724-801307AC       .text dProcPushPullWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcPushPullWait_init() {
    /* Nonmatching */
}

/* 801307AC-801307E4       .text dProcPushPullWait__9daPy_lk_cFv */
void daPy_lk_c::dProcPushPullWait() {
    /* Nonmatching */
}

/* 801307E4-80130884       .text dProcPushMove_init__9daPy_lk_cFv */
void daPy_lk_c::dProcPushMove_init() {
    /* Nonmatching */
}

/* 80130884-801308BC       .text dProcPushMove__9daPy_lk_cFv */
void daPy_lk_c::dProcPushMove() {
    /* Nonmatching */
}

/* 801308BC-8013098C       .text dProcDoorOpen_init__9daPy_lk_cFv */
void daPy_lk_c::dProcDoorOpen_init() {
    /* Nonmatching */
}

/* 8013098C-80130A54       .text dProcDoorOpen__9daPy_lk_cFv */
void daPy_lk_c::dProcDoorOpen() {
    /* Nonmatching */
}

/* 80130A54-80130ADC       .text dProcNod_init__9daPy_lk_cFv */
void daPy_lk_c::dProcNod_init() {
    /* Nonmatching */
}

/* 80130ADC-80130B38       .text dProcNod__9daPy_lk_cFv */
void daPy_lk_c::dProcNod() {
    /* Nonmatching */
}

/* 80130B38-80130BE8       .text dProcPresent_init_sub__9daPy_lk_cFv */
void daPy_lk_c::dProcPresent_init_sub() {
    /* Nonmatching */
}

/* 80130BE8-80130CA0       .text dProcPresent_init__9daPy_lk_cFv */
void daPy_lk_c::dProcPresent_init() {
    /* Nonmatching */
}

/* 80130CA0-80130E88       .text dProcPresent__9daPy_lk_cFv */
void daPy_lk_c::dProcPresent() {
    /* Nonmatching */
}

/* 80130E88-80130F2C       .text dProcWindChange_init__9daPy_lk_cFv */
void daPy_lk_c::dProcWindChange_init() {
    /* Nonmatching */
}

/* 80130F2C-80130F98       .text dProcWindChange__9daPy_lk_cFv */
void daPy_lk_c::dProcWindChange() {
    /* Nonmatching */
}

/* 80130F98-8013116C       .text dProcStandItemPut_init__9daPy_lk_cFv */
void daPy_lk_c::dProcStandItemPut_init() {
    /* Nonmatching */
}

/* 8013116C-80131274       .text dProcStandItemPut__9daPy_lk_cFv */
void daPy_lk_c::dProcStandItemPut() {
    /* Nonmatching */
}

/* 80131274-80131310       .text dProcVorcanoFail_init__9daPy_lk_cFv */
void daPy_lk_c::dProcVorcanoFail_init() {
    /* Nonmatching */
}

/* 80131310-80131348       .text dProcVorcanoFail__9daPy_lk_cFv */
void daPy_lk_c::dProcVorcanoFail() {
    /* Nonmatching */
}

/* 80131348-80131450       .text dProcSlightSurprised_init__9daPy_lk_cFv */
void daPy_lk_c::dProcSlightSurprised_init() {
    /* Nonmatching */
}

/* 80131450-8013154C       .text dProcSlightSurprised__9daPy_lk_cFv */
void daPy_lk_c::dProcSlightSurprised() {
    /* Nonmatching */
}

/* 8013154C-801315F8       .text dProcSmile_init__9daPy_lk_cFv */
void daPy_lk_c::dProcSmile_init() {
    /* Nonmatching */
}

/* 801315F8-8013168C       .text dProcSmile__9daPy_lk_cFv */
void daPy_lk_c::dProcSmile() {
    /* Nonmatching */
}

/* 8013168C-80131780       .text dProcBossWarp_init__9daPy_lk_cFv */
void daPy_lk_c::dProcBossWarp_init() {
    /* Nonmatching */
}

/* 80131780-8013182C       .text dProcBossWarp__9daPy_lk_cFv */
void daPy_lk_c::dProcBossWarp() {
    /* Nonmatching */
}

/* 8013182C-80131908       .text dProcAgbUse_init__9daPy_lk_cFv */
void daPy_lk_c::dProcAgbUse_init() {
    /* Nonmatching */
}

/* 80131908-8013194C       .text dProcAgbUse__9daPy_lk_cFv */
void daPy_lk_c::dProcAgbUse() {
    /* Nonmatching */
}

/* 8013194C-801319D0       .text dProcLookTurn_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLookTurn_init() {
    /* Nonmatching */
}

/* 801319D0-80131A7C       .text dProcLookTurn__9daPy_lk_cFv */
void daPy_lk_c::dProcLookTurn() {
    /* Nonmatching */
}

/* 80131A7C-80131B18       .text dProcLetterOpen_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLetterOpen_init() {
    /* Nonmatching */
}

/* 80131B18-80131B98       .text dProcLetterOpen__9daPy_lk_cFv */
void daPy_lk_c::dProcLetterOpen() {
    /* Nonmatching */
}

/* 80131B98-80131C54       .text dProcLetterRead_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLetterRead_init() {
    /* Nonmatching */
}

/* 80131C54-80131D6C       .text dProcLetterRead__9daPy_lk_cFv */
void daPy_lk_c::dProcLetterRead() {
    /* Nonmatching */
}

/* 80131D6C-80131DD4       .text dProcRedeadStop_init__9daPy_lk_cFv */
void daPy_lk_c::dProcRedeadStop_init() {
    /* Nonmatching */
}

/* 80131DD4-80131E0C       .text dProcRedeadStop__9daPy_lk_cFv */
void daPy_lk_c::dProcRedeadStop() {
    /* Nonmatching */
}

/* 80131E0C-80131E74       .text dProcRedeadCatch_init__9daPy_lk_cFv */
void daPy_lk_c::dProcRedeadCatch_init() {
    /* Nonmatching */
}

/* 80131E74-80131EAC       .text dProcRedeadCatch__9daPy_lk_cFv */
void daPy_lk_c::dProcRedeadCatch() {
    /* Nonmatching */
}

/* 80131EAC-80131FB0       .text dProcGetDance_init__9daPy_lk_cFv */
void daPy_lk_c::dProcGetDance_init() {
    /* Nonmatching */
}

/* 80131FB0-80132224       .text dProcGetDance__9daPy_lk_cFv */
void daPy_lk_c::dProcGetDance() {
    /* Nonmatching */
}

/* 80132224-801322D0       .text dProcBottleOpenFairy_init__9daPy_lk_cFv */
void daPy_lk_c::dProcBottleOpenFairy_init() {
    /* Nonmatching */
}

/* 801322D0-80132438       .text dProcBottleOpenFairy__9daPy_lk_cFv */
void daPy_lk_c::dProcBottleOpenFairy() {
    /* Nonmatching */
}

/* 80132438-801324D0       .text dProcWarpShort_init__9daPy_lk_cFv */
void daPy_lk_c::dProcWarpShort_init() {
    /* Nonmatching */
}

/* 801324D0-80132534       .text dProcWarpShort__9daPy_lk_cFv */
void daPy_lk_c::dProcWarpShort() {
    /* Nonmatching */
}

/* 80132534-801325F0       .text dProcOpenSalvageTreasure_init__9daPy_lk_cFv */
void daPy_lk_c::dProcOpenSalvageTreasure_init() {
    /* Nonmatching */
}

/* 801325F0-8013265C       .text dProcOpenSalvageTreasure__9daPy_lk_cFv */
void daPy_lk_c::dProcOpenSalvageTreasure() {
    /* Nonmatching */
}

/* 8013265C-80132728       .text dProcSurprisedWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcSurprisedWait_init() {
    /* Nonmatching */
}

/* 80132728-80132784       .text dProcSurprisedWait__9daPy_lk_cFv */
void daPy_lk_c::dProcSurprisedWait() {
    /* Nonmatching */
}

/* 80132784-80132844       .text dProcPowerUpWait_init__9daPy_lk_cFv */
void daPy_lk_c::dProcPowerUpWait_init() {
    /* Nonmatching */
}

/* 80132844-8013294C       .text dProcPowerUp_init__9daPy_lk_cFv */
void daPy_lk_c::dProcPowerUp_init() {
    /* Nonmatching */
}

/* 8013294C-80132A88       .text dProcPowerUp__9daPy_lk_cFv */
void daPy_lk_c::dProcPowerUp() {
    /* Nonmatching */
}

/* 80132A88-80132B68       .text dProcShipSit_init__9daPy_lk_cFv */
void daPy_lk_c::dProcShipSit_init() {
    /* Nonmatching */
}

/* 80132B68-80132BC4       .text dProcShipSit__9daPy_lk_cFv */
void daPy_lk_c::dProcShipSit() {
    /* Nonmatching */
}

/* 80132BC4-80132D00       .text dProcLastCombo_init__9daPy_lk_cFv */
void daPy_lk_c::dProcLastCombo_init() {
    /* Nonmatching */
}

/* 80132D00-80132DDC       .text dProcLastCombo__9daPy_lk_cFv */
void daPy_lk_c::dProcLastCombo() {
    /* Nonmatching */
}

/* 80132DDC-80132E48       .text dProcHandUp_init__9daPy_lk_cFv */
void daPy_lk_c::dProcHandUp_init() {
    /* Nonmatching */
}

/* 80132E48-80132E80       .text dProcHandUp__9daPy_lk_cFv */
void daPy_lk_c::dProcHandUp() {
    /* Nonmatching */
}

/* 80132E80-80132EEC       .text dProcIceSlip_init__9daPy_lk_cFv */
void daPy_lk_c::dProcIceSlip_init() {
    /* Nonmatching */
}

/* 80132EEC-80132F34       .text dProcIceSlip__9daPy_lk_cFv */
void daPy_lk_c::dProcIceSlip() {
    /* Nonmatching */
}
