//
// Generated by dtk
// Translation Unit: d_a_sie_flag.cpp
//

#include "d_a_sie_flag.h"
#include "dolphin/types.h"

/* 000000EC-00000118       .text __ct__16daSie_Flag_HIO_cFv */
daSie_Flag_HIO_c::daSie_Flag_HIO_c() {
    /* Nonmatching */
}

/* 00000118-000001C4       .text set_mtx__12daSie_Flag_cFv */
void daSie_Flag_c::set_mtx() {
    /* Nonmatching */
}

/* 000001C4-000001E4       .text CheckCreateHeap__FP10fopAc_ac_c */
void CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 000001E4-0000030C       .text CreateHeap__12daSie_Flag_cFv */
void daSie_Flag_c::CreateHeap() {
    /* Nonmatching */
}

/* 0000030C-000003D4       .text CreateInit__12daSie_Flag_cFv */
void daSie_Flag_c::CreateInit() {
    /* Nonmatching */
}

/* 000003D4-00000488       .text _create__12daSie_Flag_cFv */
void daSie_Flag_c::_create() {
    /* Nonmatching */
}

/* 00000488-00000620       .text __ct__12daSie_Flag_cFv */
daSie_Flag_c::daSie_Flag_c() {
    /* Nonmatching */
}

/* 00000620-000006EC       .text __dt__8dCcD_CylFv */
dCcD_Cyl::~dCcD_Cyl() {
    /* Nonmatching */
}

/* 000006EC-00000734       .text __dt__8cM3dGCylFv */
cM3dGCyl::~cM3dGCyl() {
    /* Nonmatching */
}

/* 00000734-00000790       .text __dt__14cCcD_ShapeAttrFv */
cCcD_ShapeAttr::~cCcD_ShapeAttr() {
    /* Nonmatching */
}

/* 00000790-000007D8       .text __dt__8cM3dGAabFv */
cM3dGAab::~cM3dGAab() {
    /* Nonmatching */
}

/* 000007D8-00000814       .text __dt__4cXyzFv */
cXyz::~cXyz() {
    /* Nonmatching */
}

/* 00000814-00000864       .text _delete__12daSie_Flag_cFv */
void daSie_Flag_c::_delete() {
    /* Nonmatching */
}

/* 00000864-00000B08       .text _execute__12daSie_Flag_cFv */
void daSie_Flag_c::_execute() {
    /* Nonmatching */
}

/* 00000B08-00000B94       .text _draw__12daSie_Flag_cFv */
void daSie_Flag_c::_draw() {
    /* Nonmatching */
}

/* 00000B94-00000BB4       .text daSie_FlagCreate__FPv */
void daSie_FlagCreate(void*) {
    /* Nonmatching */
}

/* 00000BB4-00000BD8       .text daSie_FlagDelete__FPv */
void daSie_FlagDelete(void*) {
    /* Nonmatching */
}

/* 00000BD8-00000BFC       .text daSie_FlagExecute__FPv */
void daSie_FlagExecute(void*) {
    /* Nonmatching */
}

/* 00000BFC-00000C20       .text daSie_FlagDraw__FPv */
void daSie_FlagDraw(void*) {
    /* Nonmatching */
}

/* 00000C20-00000C28       .text daSie_FlagIsDelete__FPv */
void daSie_FlagIsDelete(void*) {
    /* Nonmatching */
}

/* 00000C28-00000C38       .text GetShapeAttr__8dCcD_CylFv */
void dCcD_Cyl::GetShapeAttr() {
    /* Nonmatching */
}

/* 00000C38-00000C40       .text GetCoCP__12cCcD_CylAttrFv */
void cCcD_CylAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00000C40-00000C48       .text GetCoCP__12cCcD_CylAttrCFv */
void cCcD_CylAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00000C48-00000C50       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_AabAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_AabAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00000C50-00000C58       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_PntAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_PntAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00000C58-00000C90       .text CrossAtTg__12cCcD_CylAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00000C90-00000C98       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_AabAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_AabAttr&, float*) const {
    /* Nonmatching */
}

/* 00000C98-00000CA0       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_TriAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_TriAttr&, float*) const {
    /* Nonmatching */
}

/* 00000CA0-00000CA8       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_PntAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_PntAttr&, float*) const {
    /* Nonmatching */
}

/* 00000CA8-00000CE0       .text CrossCo__12cCcD_CylAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00000CE0-00000CE4       .text GetGObjInf__12cCcD_GObjInfCFv */
void cCcD_GObjInf::GetGObjInf() const {
    /* Nonmatching */
}

/* 00000CE4-00000CEC       .text GetShapeAttr__8cCcD_ObjCFv */
void cCcD_Obj::GetShapeAttr() const {
    /* Nonmatching */
}

/* 00000CEC-00000CF4       .text CrossAtTg__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_ShapeAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00000CF4-00000CFC       .text CrossCo__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_ShapeAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 00000CFC-00000D08       .text GetCoCP__14cCcD_ShapeAttrFv */
void cCcD_ShapeAttr::GetCoCP() {
    /* Nonmatching */
}

/* 00000D08-00000D14       .text GetCoCP__14cCcD_ShapeAttrCFv */
void cCcD_ShapeAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00000D14-00000D5C       .text __dt__16daSie_Flag_HIO_cFv */
daSie_Flag_HIO_c::~daSie_Flag_HIO_c() {
    /* Nonmatching */
}

/* 00000E00-00000E08       .text @280@__dt__8dCcD_CylFv */
void @280@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 00000E08-00000E10       .text @248@__dt__8dCcD_CylFv */
void @248@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

