// The name of this .inc file is known because of an assert contained in it.

#include "d/actor/d_a_npc_tt.h"

/* 00002CD4-00002DEC       .text initTexPatternAnm__10daNpc_Tt_cFb */
void daNpc_Tt_c::initTexPatternAnm(bool) {
    /* Nonmatching */
}

/* 00002DEC-00002E78       .text playTexPatternAnm__10daNpc_Tt_cFv */
void daNpc_Tt_c::playTexPatternAnm() {
    /* Nonmatching */
}

/* 00002E78-00002F94       .text setAnm__10daNpc_Tt_cFi */
void daNpc_Tt_c::setAnm(int) {
    /* Nonmatching */
}

/* 00002F94-00002FFC       .text danceInit__10daNpc_Tt_cFi */
void daNpc_Tt_c::danceInit(int) {
    /* Nonmatching */
}

/* 00002FFC-000030B0       .text danceProc__10daNpc_Tt_cFv */
void daNpc_Tt_c::danceProc() {
    /* Nonmatching */
}

/* 000030B0-00003210       .text danceNext__10daNpc_Tt_cFv */
void daNpc_Tt_c::danceNext() {
    /* Nonmatching */
}
