/**
 * d_a_player_ship.inc
 *
 * Code relating to interacting with and controlling The King of Red Lions.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_main.h"

/* 8013F848-8013F8AC       .text shipSpecialDemoStart__9daPy_lk_cFv */
void daPy_lk_c::shipSpecialDemoStart() {
    /* Nonmatching */
}

/* 8013F8AC-8013F984       .text checkJumpRideShip__9daPy_lk_cFv */
BOOL daPy_lk_c::checkJumpRideShip() {
    /* Nonmatching */
}

/* 8013F984-8013F9B0       .text checkShipNotNormalMode__9daPy_lk_cFv */
BOOL daPy_lk_c::checkShipNotNormalMode() {
    /* Nonmatching */
}

/* 8013F9B0-8013FE78       .text setShipRideArmAngle__9daPy_lk_cFiP16J3DTransformInfo */
void daPy_lk_c::setShipRideArmAngle(int, J3DTransformInfo*) {
    /* Nonmatching */
}

/* 8013FE78-8013FEF4       .text checkShipRideUseItem__9daPy_lk_cFi */
int daPy_lk_c::checkShipRideUseItem(int) {
    /* Nonmatching */
}

/* 8013FEF4-8013FFC0       .text initShipRideUseItem__9daPy_lk_cFii */
void daPy_lk_c::initShipRideUseItem(int, int) {
    /* Nonmatching */
}

/* 8013FFC0-80140018       .text setShipRidePosUseItem__9daPy_lk_cFv */
void daPy_lk_c::setShipRidePosUseItem() {
    /* Nonmatching */
}

/* 80140018-801403E0       .text setShipRidePos__9daPy_lk_cFi */
void daPy_lk_c::setShipRidePos(int) {
    /* Nonmatching */
}

/* 801403E0-80140480       .text setShipAttentionAnmSpeed__9daPy_lk_cFf */
void daPy_lk_c::setShipAttentionAnmSpeed(f32) {
    /* Nonmatching */
}

/* 80140480-801405F0       .text setShipAttnetionBodyAngle__9daPy_lk_cFv */
void daPy_lk_c::setShipAttnetionBodyAngle() {
    /* Nonmatching */
}

/* 801405F0-80140C88       .text changeShipEndProc__9daPy_lk_cFv */
void daPy_lk_c::changeShipEndProc() {
    /* Nonmatching */
}

/* 80140C88-80140D04       .text initShipBaseAnime__9daPy_lk_cFv */
void daPy_lk_c::initShipBaseAnime() {
    /* Nonmatching */
}

/* 80140D04-80140D80       .text initShipCraneAnime__9daPy_lk_cFv */
void daPy_lk_c::initShipCraneAnime() {
    /* Nonmatching */
}

/* 80140D80-80140EF0       .text procShipReady_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipReady_init() {
    /* Nonmatching */
}

/* 80140EF0-8014105C       .text procShipReady__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipReady() {
    /* Nonmatching */
}

/* 8014105C-80141140       .text procShipJumpRide_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipJumpRide_init() {
    /* Nonmatching */
}

/* 80141140-80141180       .text procShipJumpRide__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipJumpRide() {
    /* Nonmatching */
}

/* 80141180-8014123C       .text procShipSteer_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipSteer_init() {
    /* Nonmatching */
}

/* 8014123C-80141288       .text procShipSteer__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipSteer() {
    /* Nonmatching */
}

/* 80141288-801413A4       .text procShipPaddle_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipPaddle_init() {
    /* Nonmatching */
}

/* 801413A4-801416BC       .text procShipPaddle__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipPaddle() {
    /* Nonmatching */
}

/* 801416BC-801417EC       .text procShipScope_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procShipScope_init(int) {
    /* Nonmatching */
}

/* 801417EC-801418B4       .text procShipScope__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipScope() {
    /* Nonmatching */
}

/* 801418B4-801419B4       .text procShipBoomerang_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipBoomerang_init() {
    /* Nonmatching */
}

/* 801419B4-80141BB0       .text procShipBoomerang__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipBoomerang() {
    /* Nonmatching */
}

/* 80141BB0-80141CF8       .text procShipHookshot_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipHookshot_init() {
    /* Nonmatching */
}

/* 80141CF8-80141F2C       .text procShipHookshot__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipHookshot() {
    /* Nonmatching */
}

/* 80141F2C-80142084       .text procShipBow_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipBow_init() {
    /* Nonmatching */
}

/* 80142084-80142250       .text procShipBow__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipBow() {
    /* Nonmatching */
}

/* 80142250-80142300       .text procShipCannon_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipCannon_init() {
    /* Nonmatching */
}

/* 80142300-80142388       .text procShipCannon__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipCannon() {
    /* Nonmatching */
}

/* 80142388-80142458       .text procShipCrane_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipCrane_init() {
    /* Nonmatching */
}

/* 80142458-80142920       .text procShipCrane__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipCrane() {
    /* Nonmatching */
}

/* 80142920-80142A5C       .text procShipGetOff_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipGetOff_init() {
    /* Nonmatching */
}

/* 80142A5C-80142C08       .text procShipGetOff__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipGetOff() {
    /* Nonmatching */
}

/* 80142C08-80142C9C       .text procShipRestart_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipRestart_init() {
    /* Nonmatching */
}

/* 80142C9C-80142D08       .text procShipRestart__9daPy_lk_cFv */
BOOL daPy_lk_c::procShipRestart() {
    /* Nonmatching */
}
