/**
 * d_a_player_HIO.inc
 *
 * Player HostIO interface handling.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the classes it contains.
 * 
 * In the retail version of the game, only a single constructor is present.
 * But the debug version had implementations for all of Link's HIO classes.
 */

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/actor/d_a_player_main.h"

daPy_HIO_c::daPy_HIO_c() {}
