/**
 * d_a_player_sword.inc
 *
 * Code relating using a sword item.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is known because of an assert contained within
 * a function from this file.
*/

#include "d/actor/d_a_player_link.h"

/* 80154B80-80154FBC       .text setSwordModel__9daPy_lk_cFi */
void daPy_lk_c::setSwordModel(int) {
    /* Nonmatching */
}

/* 80154FBC-80155490       .text setLightSaver__9daPy_lk_cFv */
void daPy_lk_c::setLightSaver() {
    /* Nonmatching */
}

/* 80155490-801554C8       .text checkDemoShieldNoDraw__9daPy_lk_cFv */
void daPy_lk_c::checkDemoShieldNoDraw() {
    /* Nonmatching */
}

/* 801554C8-80155544       .text checkDemoSwordNoDraw__9daPy_lk_cFi */
void daPy_lk_c::checkDemoSwordNoDraw(int) {
    /* Nonmatching */
}

/* 80155544-80155574       .text checkChanceMode__9daPy_lk_cFv */
void daPy_lk_c::checkChanceMode() {
    /* Nonmatching */
}

/* 80155574-8015559C       .text checkCutRollChange__9daPy_lk_cCFv */
void daPy_lk_c::checkCutRollChange() const {
    /* Nonmatching */
}

/* 8015559C-801555FC       .text getSwordBlurColor__9daPy_lk_cFv */
void daPy_lk_c::getSwordBlurColor() {
    /* Nonmatching */
}

/* 801555FC-80155694       .text setNormalCutAtParam__9daPy_lk_cFUc */
void daPy_lk_c::setNormalCutAtParam(unsigned char) {
    /* Nonmatching */
}

/* 80155694-8015572C       .text setFinishCutAtParam__9daPy_lk_cFUc */
void daPy_lk_c::setFinishCutAtParam(unsigned char) {
    /* Nonmatching */
}

/* 8015572C-801557C4       .text setExtraCutAtParam__9daPy_lk_cFUc */
void daPy_lk_c::setExtraCutAtParam(unsigned char) {
    /* Nonmatching */
}

/* 801557C4-8015585C       .text setExtraFinishCutAtParam__9daPy_lk_cFUc */
void daPy_lk_c::setExtraFinishCutAtParam(unsigned char) {
    /* Nonmatching */
}

/* 8015585C-80155970       .text setJumpCutAtParam__9daPy_lk_cFv */
void daPy_lk_c::setJumpCutAtParam() {
    /* Nonmatching */
}

/* 80155970-801559F0       .text getCutDirection__9daPy_lk_cFv */
void daPy_lk_c::getCutDirection() {
    /* Nonmatching */
}

/* 801559F0-80155C3C       .text changeCutProc__9daPy_lk_cFv */
void daPy_lk_c::changeCutProc() {
    /* Nonmatching */
}

/* 80155C3C-80156034       .text changeCutReverseProc__9daPy_lk_cFQ29daPy_lk_c8daPy_ANM */
void daPy_lk_c::changeCutReverseProc(daPy_lk_c::daPy_ANM) {
    /* Nonmatching */
}

/* 80156034-80156198       .text procCutA_init__9daPy_lk_cFs */
void daPy_lk_c::procCutA_init(short) {
    /* Nonmatching */
}

/* 80156198-80156424       .text procCutA__9daPy_lk_cFv */
void daPy_lk_c::procCutA() {
    /* Nonmatching */
}

/* 80156424-80156584       .text procCutF_init__9daPy_lk_cFs */
void daPy_lk_c::procCutF_init(short) {
    /* Nonmatching */
}

/* 80156584-80156828       .text procCutF__9daPy_lk_cFv */
void daPy_lk_c::procCutF() {
    /* Nonmatching */
}

/* 80156828-80156984       .text procCutR_init__9daPy_lk_cFs */
void daPy_lk_c::procCutR_init(short) {
    /* Nonmatching */
}

/* 80156984-80156C10       .text procCutR__9daPy_lk_cFv */
void daPy_lk_c::procCutR() {
    /* Nonmatching */
}

/* 80156C10-80156D6C       .text procCutL_init__9daPy_lk_cFs */
void daPy_lk_c::procCutL_init(short) {
    /* Nonmatching */
}

/* 80156D6C-80156FF8       .text procCutL__9daPy_lk_cFv */
void daPy_lk_c::procCutL() {
    /* Nonmatching */
}

/* 80156FF8-80157154       .text procCutEA_init__9daPy_lk_cFv */
void daPy_lk_c::procCutEA_init() {
    /* Nonmatching */
}

/* 80157154-80157348       .text procCutEA__9daPy_lk_cFv */
void daPy_lk_c::procCutEA() {
    /* Nonmatching */
}

/* 80157348-801574A4       .text procCutEB_init__9daPy_lk_cFv */
void daPy_lk_c::procCutEB_init() {
    /* Nonmatching */
}

/* 801574A4-8015768C       .text procCutEB__9daPy_lk_cFv */
void daPy_lk_c::procCutEB() {
    /* Nonmatching */
}

/* 8015768C-801577EC       .text procCutExA_init__9daPy_lk_cFv */
void daPy_lk_c::procCutExA_init() {
    /* Nonmatching */
}

/* 801577EC-80157A18       .text procCutExA__9daPy_lk_cFv */
void daPy_lk_c::procCutExA() {
    /* Nonmatching */
}

/* 80157A18-80157B74       .text procCutExB_init__9daPy_lk_cFv */
void daPy_lk_c::procCutExB_init() {
    /* Nonmatching */
}

/* 80157B74-80157D3C       .text procCutExB__9daPy_lk_cFv */
void daPy_lk_c::procCutExB() {
    /* Nonmatching */
}

/* 80157D3C-80158220       .text procCutTurn_init__9daPy_lk_cFi */
void daPy_lk_c::procCutTurn_init(int) {
    /* Nonmatching */
}

/* 80158220-80158460       .text procCutTurn__9daPy_lk_cFv */
void daPy_lk_c::procCutTurn() {
    /* Nonmatching */
}

/* 80158460-801585D8       .text procCutRoll_init__9daPy_lk_cFv */
void daPy_lk_c::procCutRoll_init() {
    /* Nonmatching */
}

/* 801585D8-801588F0       .text procCutRoll__9daPy_lk_cFv */
void daPy_lk_c::procCutRoll() {
    /* Nonmatching */
}

/* 801588F0-80158A40       .text procCutRollEnd_init__9daPy_lk_cFv */
void daPy_lk_c::procCutRollEnd_init() {
    /* Nonmatching */
}

/* 80158A40-80158A98       .text procCutRollEnd__9daPy_lk_cFv */
void daPy_lk_c::procCutRollEnd() {
    /* Nonmatching */
}

/* 80158A98-80158B00       .text procCutTurnCharge_init__9daPy_lk_cFv */
void daPy_lk_c::procCutTurnCharge_init() {
    /* Nonmatching */
}

/* 80158B00-80158B58       .text procCutTurnCharge__9daPy_lk_cFv */
void daPy_lk_c::procCutTurnCharge() {
    /* Nonmatching */
}

/* 80158B58-80158D40       .text procCutTurnMove_init__9daPy_lk_cFv */
void daPy_lk_c::procCutTurnMove_init() {
    /* Nonmatching */
}

/* 80158D40-80159130       .text procCutTurnMove__9daPy_lk_cFv */
void daPy_lk_c::procCutTurnMove() {
    /* Nonmatching */
}

/* 80159130-801592A4       .text procCutReverse_init__9daPy_lk_cFQ29daPy_lk_c8daPy_ANM */
void daPy_lk_c::procCutReverse_init(daPy_lk_c::daPy_ANM) {
    /* Nonmatching */
}

/* 801592A4-80159390       .text procCutReverse__9daPy_lk_cFv */
void daPy_lk_c::procCutReverse() {
    /* Nonmatching */
}

/* 80159390-80159500       .text procJumpCut_init__9daPy_lk_cFi */
void daPy_lk_c::procJumpCut_init(int) {
    /* Nonmatching */
}

/* 80159500-80159608       .text procJumpCut__9daPy_lk_cFv */
void daPy_lk_c::procJumpCut() {
    /* Nonmatching */
}

/* 80159608-80159864       .text procJumpCutLand_init__9daPy_lk_cFv */
void daPy_lk_c::procJumpCutLand_init() {
    /* Nonmatching */
}

/* 80159864-80159998       .text procJumpCutLand__9daPy_lk_cFv */
void daPy_lk_c::procJumpCutLand() {
    /* Nonmatching */
}

/* 80159998-80159B80       .text procCutExMJ_init__9daPy_lk_cFi */
void daPy_lk_c::procCutExMJ_init(int) {
    /* Nonmatching */
}

/* 80159B80-80159E60       .text procCutExMJ__9daPy_lk_cFv */
void daPy_lk_c::procCutExMJ() {
    /* Nonmatching */
}

/* 80159E60-80159FB0       .text procCutKesa_init__9daPy_lk_cFv */
void daPy_lk_c::procCutKesa_init() {
    /* Nonmatching */
}

/* 80159FB0-8015A1DC       .text procCutKesa__9daPy_lk_cFv */
void daPy_lk_c::procCutKesa() {
    /* Nonmatching */
}
