/**
 * d_a_player_grab.inc
 *
 * Code relating to grabbing, holding, and throwing other actors.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_main.h"

/* 8013A85C-8013A890       .text checkGrabSpecialHeavyState__9daPy_lk_cFv */
BOOL daPy_lk_c::checkGrabSpecialHeavyState() {
    /* Nonmatching */
}

/* 8013A890-8013A8B4       .text getGrabMissActor__9daPy_lk_cFv */
fopAc_ac_c* daPy_lk_c::getGrabMissActor() {
    /* Nonmatching */
}

/* 8013A8B4-8013A904       .text setWeaponBlur__9daPy_lk_cFv */
void daPy_lk_c::setWeaponBlur() {
    /* Nonmatching */
}

/* 8013A904-8013A97C       .text checkGrabBarrelSearch__9daPy_lk_cFi */
BOOL daPy_lk_c::checkGrabBarrelSearch(int) {
    /* Nonmatching */
}

/* 8013A97C-8013AF84       .text setGrabItemPos__9daPy_lk_cFv */
void daPy_lk_c::setGrabItemPos() {
    /* Nonmatching */
}

/* 8013AF84-8013B05C       .text freeGrabItem__9daPy_lk_cFv */
void daPy_lk_c::freeGrabItem() {
    /* Nonmatching */
}

/* 8013B05C-8013B458       .text checkNextActionGrab__9daPy_lk_cFv */
void daPy_lk_c::checkNextActionGrab() {
    /* Nonmatching */
}

/* 8013B458-8013B56C       .text initGrabNextMode__9daPy_lk_cFv */
void daPy_lk_c::initGrabNextMode() {
    /* Nonmatching */
}

/* 8013B56C-8013B6F4       .text procGrabReady_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabReady_init() {
    /* Nonmatching */
}

/* 8013B6F4-8013B8A0       .text procGrabReady__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabReady() {
    /* Nonmatching */
}

/* 8013B8A0-8013BA50       .text procGrabUp_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabUp_init() {
    /* Nonmatching */
}

/* 8013BA50-8013BBBC       .text procGrabUp__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabUp() {
    /* Nonmatching */
}

/* 8013BBBC-8013BC40       .text procGrabMiss_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabMiss_init() {
    /* Nonmatching */
}

/* 8013BC40-8013BD30       .text procGrabMiss__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabMiss() {
    /* Nonmatching */
}

/* 8013BD30-8013BE10       .text procGrabThrow_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procGrabThrow_init(int) {
    /* Nonmatching */
}

/* 8013BE10-8013C020       .text procGrabThrow__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabThrow() {
    /* Nonmatching */
}

/* 8013C020-8013C124       .text procGrabPut_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabPut_init() {
    /* Nonmatching */
}

/* 8013C124-8013C504       .text procGrabPut__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabPut() {
    /* Nonmatching */
}

/* 8013C504-8013C678       .text procGrabWait_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabWait_init() {
    /* Nonmatching */
}

/* 8013C678-8013C914       .text procGrabWait__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabWait() {
    /* Nonmatching */
}

/* 8013C914-8013C9AC       .text procGrabHeavyWait_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabHeavyWait_init() {
    /* Nonmatching */
}

/* 8013C9AC-8013CB78       .text procGrabHeavyWait__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabHeavyWait() {
    /* Nonmatching */
}

/* 8013CB78-8013CBD0       .text procGrabRebound_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabRebound_init() {
    /* Nonmatching */
}

/* 8013CBD0-8013CC64       .text procGrabRebound__9daPy_lk_cFv */
BOOL daPy_lk_c::procGrabRebound() {
    /* Nonmatching */
}
