/**
 * d_a_player_whide.inc
 *
 * Code relating to "wall hiding" (sidling).
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_link.h"

/* 8013707C-801371E0       .text setBlendWHideMoveAnime__9daPy_lk_cFf */
void daPy_lk_c::setBlendWHideMoveAnime(f32) {
    /* Nonmatching */
}

/* 801371E0-80137608       .text getWHideModePolygon__9daPy_lk_cFP4cXyzP4cXyzP4cXyzi */
void daPy_lk_c::getWHideModePolygon(cXyz*, cXyz*, cXyz*, int) {
    /* Nonmatching */
}

/* 80137608-80137640       .text getWHideBasePos__9daPy_lk_cFP4cXyz */
void daPy_lk_c::getWHideBasePos(cXyz*) {
    /* Nonmatching */
}

/* 80137640-8013769C       .text getWHideNextPos__9daPy_lk_cFP4cXyzP4cXyz */
void daPy_lk_c::getWHideNextPos(cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 8013769C-80137754       .text checkWHideBackWall__9daPy_lk_cFP4cXyz */
void daPy_lk_c::checkWHideBackWall(cXyz*) {
    /* Nonmatching */
}

/* 80137754-80137828       .text checkWHideFrontFloor__9daPy_lk_cFP4cXyz */
void daPy_lk_c::checkWHideFrontFloor(cXyz*) {
    /* Nonmatching */
}

/* 80137828-80137914       .text checkWHideModeChange__9daPy_lk_cFP4cXyz */
void daPy_lk_c::checkWHideModeChange(cXyz*) {
    /* Nonmatching */
}

/* 80137914-80137A00       .text changeWHideEndProc__9daPy_lk_cFP4cXyz */
void daPy_lk_c::changeWHideEndProc(cXyz*) {
    /* Nonmatching */
}

/* 80137A00-80137BD8       .text procWHideReady_init__9daPy_lk_cFP8cM3dGPlaP4cXyz */
void daPy_lk_c::procWHideReady_init(cM3dGPla*, cXyz*) {
    /* Nonmatching */
}

/* 80137BD8-80137CD0       .text procWHideReady__9daPy_lk_cFv */
void daPy_lk_c::procWHideReady() {
    /* Nonmatching */
}

/* 80137CD0-80137DF0       .text procWHideWait_init__9daPy_lk_cFv */
void daPy_lk_c::procWHideWait_init() {
    /* Nonmatching */
}

/* 80137DF0-80138074       .text procWHideWait__9daPy_lk_cFv */
void daPy_lk_c::procWHideWait() {
    /* Nonmatching */
}

/* 80138074-801380F0       .text procWHideMove_init__9daPy_lk_cFv */
void daPy_lk_c::procWHideMove_init() {
    /* Nonmatching */
}

/* 801380F0-8013852C       .text procWHideMove__9daPy_lk_cFv */
void daPy_lk_c::procWHideMove() {
    /* Nonmatching */
}

/* 8013852C-801385EC       .text procWHidePeep_init__9daPy_lk_cFv */
void daPy_lk_c::procWHidePeep_init() {
    /* Nonmatching */
}

/* 801385EC-801387A4       .text procWHidePeep__9daPy_lk_cFv */
void daPy_lk_c::procWHidePeep() {
    /* Nonmatching */
}
