//
// Generated by dtk
// Translation Unit: d_a_obj_hami2.cpp
//

#include "d/actor/d_a_obj_hami2.h"
#include "dolphin/types.h"

/* 00000078-0000012C       .text nodeCallBack__FP7J3DNodei */
void nodeCallBack(J3DNode*, int) {
    /* Nonmatching */
}

/* 0000012C-0000032C       .text CreateHeap__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::CreateHeap() {
    /* Nonmatching */
}

/* 0000032C-0000042C       .text Create__Q210daObjHami25Act_cFv */
s32 daObjHami2::Act_c::Create() {
    /* Nonmatching */
}

/* 0000042C-00000540       .text Mthd_Create__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::Mthd_Create() {
    /* Nonmatching */
}

/* 00000540-00000548       .text Delete__Q210daObjHami25Act_cFv */
BOOL daObjHami2::Act_c::Delete() {
    /* Nonmatching */
}

/* 00000548-000005E8       .text Mthd_Delete__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::Mthd_Delete() {
    /* Nonmatching */
}

/* 000005E8-00000678       .text set_mtx__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::set_mtx() {
    /* Nonmatching */
}

/* 00000678-000006B4       .text init_mtx__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::init_mtx() {
    /* Nonmatching */
}

/* 000006B4-00000730       .text daObjHami2_close_stop__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_close_stop() {
    /* Nonmatching */
}

/* 00000730-00000810       .text daObjHami2_open_demo_wait__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_open_demo_wait() {
    /* Nonmatching */
}

/* 00000810-000008A0       .text daObjHami2_open_demo__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_open_demo() {
    /* Nonmatching */
}

/* 000008A0-0000091C       .text daObjHami2_open_stop__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_open_stop() {
    /* Nonmatching */
}

/* 0000091C-0000096C       .text daObjHami2_close_demo_wait__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_close_demo_wait() {
    /* Nonmatching */
}

/* 0000096C-00000A08       .text daObjHami2_close_demo__Q210daObjHami25Act_cFv */
void daObjHami2::Act_c::daObjHami2_close_demo() {
    /* Nonmatching */
}

/* 00000A08-00000AB8       .text Execute__Q210daObjHami25Act_cFPPA3_A4_f */
void daObjHami2::Act_c::Execute(float(**)[3][4]) {
    /* Nonmatching */
}

/* 00000AB8-00000B58       .text Draw__Q210daObjHami25Act_cFv */
BOOL daObjHami2::Act_c::Draw() {
    /* Nonmatching */
}
