//
// Generated by dtk
// Translation Unit: d_a_obj_ojtree.cpp
//

#include "d_a_obj_ojtree.h"
#include "dolphin/types.h"

/* 00000078-0000012C       .text CreateHeap__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::CreateHeap() {
    /* Nonmatching */
}

/* 0000012C-000001EC       .text Create__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::Create() {
    /* Nonmatching */
}

/* 000001EC-000002E4       .text Mthd_Create__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::Mthd_Create() {
    /* Nonmatching */
}

/* 000002E4-000002EC       .text Delete__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::Delete() {
    /* Nonmatching */
}

/* 000002EC-00000338       .text Mthd_Delete__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::Mthd_Delete() {
    /* Nonmatching */
}

/* 00000338-000003B8       .text set_mtx__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::set_mtx() {
    /* Nonmatching */
}

/* 000003B8-000003F4       .text init_mtx__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::init_mtx() {
    /* Nonmatching */
}

/* 000003F4-0000045C       .text Execute__Q211daObjOjtree5Act_cFPPA3_A4_f */
void daObjOjtree::Act_c::Execute(float(**)[3][4]) {
    /* Nonmatching */
}

/* 0000045C-000004FC       .text Draw__Q211daObjOjtree5Act_cFv */
void daObjOjtree::Act_c::Draw() {
    /* Nonmatching */
}

/* 000004FC-0000051C       .text Mthd_Create__Q211daObjOjtree28@unnamed@d_a_obj_ojtree_cpp@FPv */
void daObjOjtree::@unnamed@d_a_obj_ojtree_cpp@::Mthd_Create(void*) {
    /* Nonmatching */
}

/* 0000051C-0000053C       .text Mthd_Delete__Q211daObjOjtree28@unnamed@d_a_obj_ojtree_cpp@FPv */
void daObjOjtree::@unnamed@d_a_obj_ojtree_cpp@::Mthd_Delete(void*) {
    /* Nonmatching */
}

/* 0000053C-0000055C       .text Mthd_Execute__Q211daObjOjtree28@unnamed@d_a_obj_ojtree_cpp@FPv */
void daObjOjtree::@unnamed@d_a_obj_ojtree_cpp@::Mthd_Execute(void*) {
    /* Nonmatching */
}

/* 0000055C-00000588       .text Mthd_Draw__Q211daObjOjtree28@unnamed@d_a_obj_ojtree_cpp@FPv */
void daObjOjtree::@unnamed@d_a_obj_ojtree_cpp@::Mthd_Draw(void*) {
    /* Nonmatching */
}

/* 00000588-000005B4       .text Mthd_IsDelete__Q211daObjOjtree28@unnamed@d_a_obj_ojtree_cpp@FPv */
void daObjOjtree::@unnamed@d_a_obj_ojtree_cpp@::Mthd_IsDelete(void*) {
    /* Nonmatching */
}

/* 000005B4-000005BC       .text IsDelete__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::IsDelete() {
    /* Nonmatching */
}

/* 000005BC-000005C4       .text ToFore__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::ToFore() {
    /* Nonmatching */
}

/* 000005C4-000005CC       .text ToBack__16dBgS_MoveBgActorFv */
void dBgS_MoveBgActor::ToBack() {
    /* Nonmatching */
}

