/**
 * d_a_player_ladder.inc
 *
 * Code relating to getting on, getting off, and climbing ladders.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_link.h"

/* 80132F34-80132F58       .text getLadderMoveAnmSpeed__9daPy_lk_cFv */
void daPy_lk_c::getLadderMoveAnmSpeed() {
    /* Nonmatching */
}

/* 80132F58-80133058       .text setLadderFootSe__9daPy_lk_cFv */
void daPy_lk_c::setLadderFootSe() {
    /* Nonmatching */
}

/* 80133058-80133240       .text changeLadderMoveProc__9daPy_lk_cFi */
void daPy_lk_c::changeLadderMoveProc(int) {
    /* Nonmatching */
}

/* 80133240-801333A8       .text setMoveBGLadderCorrect__9daPy_lk_cFv */
void daPy_lk_c::setMoveBGLadderCorrect() {
    /* Nonmatching */
}

/* 801333A8-80133414       .text procLadderUpStart_init_sub__9daPy_lk_cFv */
void daPy_lk_c::procLadderUpStart_init_sub() {
    /* Nonmatching */
}

/* 80133414-8013356C       .text procLadderUpStart_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderUpStart_init() {
    /* Nonmatching */
}

/* 8013356C-80133670       .text procLadderUpStart__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderUpStart() {
    /* Nonmatching */
}

/* 80133670-80133710       .text procLadderUpEnd_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procLadderUpEnd_init(int) {
    /* Nonmatching */
}

/* 80133710-801337B4       .text procLadderUpEnd__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderUpEnd() {
    /* Nonmatching */
}

/* 801337B4-8013384C       .text procLadderDownStart_init_sub__9daPy_lk_cFv */
void daPy_lk_c::procLadderDownStart_init_sub() {
    /* Nonmatching */
}

/* 8013384C-8013399C       .text procLadderDownStart_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderDownStart_init() {
    /* Nonmatching */
}

/* 8013399C-80133AB8       .text procLadderDownStart__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderDownStart() {
    /* Nonmatching */
}

/* 80133AB8-80133B4C       .text procLadderDownEnd_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procLadderDownEnd_init(int) {
    /* Nonmatching */
}

/* 80133B4C-80133BB4       .text procLadderDownEnd__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderDownEnd() {
    /* Nonmatching */
}

/* 80133BB4-80133E28       .text procLadderMove_init__9daPy_lk_cFiiP4cXyz */
BOOL daPy_lk_c::procLadderMove_init(int, int, cXyz*) {
    /* Nonmatching */
}

/* 80133E28-80133F1C       .text procLadderMove__9daPy_lk_cFv */
BOOL daPy_lk_c::procLadderMove() {
    /* Nonmatching */
}
