//
// Generated by dtk
// Translation Unit: d_a_player_npc.cpp
//

#include "d_a_player_npc.h"
#include "dolphin/types.h"

/* 8015A37C-8015A448       .text check_initialRoom__10daPy_npc_cFv */
void daPy_npc_c::check_initialRoom() {
    /* Nonmatching */
}

/* 8015A448-8015A524       .text check_moveStop__10daPy_npc_cFv */
void daPy_npc_c::check_moveStop() {
    /* Nonmatching */
}

/* 8015A524-8015A590       .text setRestart__10daPy_npc_cFSc */
void daPy_npc_c::setRestart(signed char) {
    /* Nonmatching */
}

/* 8015A590-8015A624       .text unconditionalSetRestart__10daPy_npc_cFSc */
void daPy_npc_c::unconditionalSetRestart(signed char) {
    /* Nonmatching */
}

/* 8015A624-8015A6A4       .text setOffsetHomePos__10daPy_npc_cFv */
void daPy_npc_c::setOffsetHomePos() {
    /* Nonmatching */
}

/* 8015A6A4-8015AA0C       .text setPointRestart__10daPy_npc_cFsSc */
void daPy_npc_c::setPointRestart(short, signed char) {
    /* Nonmatching */
}

/* 8015AA0C-8015AB28       .text checkRestart__10daPy_npc_cFSc */
void daPy_npc_c::checkRestart(signed char) {
    /* Nonmatching */
}

/* 8015AB28-8015ABD8       .text initialRestartOption__10daPy_npc_cFSci */
void daPy_npc_c::initialRestartOption(signed char, int) {
    /* Nonmatching */
}

/* 8015ABD8-8015AC74       .text checkNowPosMove__10daPy_npc_cFPCc */
void daPy_npc_c::checkNowPosMove(const char*) {
    /* Nonmatching */
}

/* 8015AC74-8015AD20       .text drawDamageFog__10daPy_npc_cFv */
void daPy_npc_c::drawDamageFog() {
    /* Nonmatching */
}

/* 8015AD20-8015AEF8       .text chkMoveBlock__10daPy_npc_cFP4cXyz */
void daPy_npc_c::chkMoveBlock(cXyz*) {
    /* Nonmatching */
}

/* 8015AEF8-8015B00C       .text daPy_npc_JudgeForPNameAndDistance__FPvPv */
void daPy_npc_JudgeForPNameAndDistance(void*, void*) {
    /* Nonmatching */
}

/* 8015B00C-8015B0A4       .text daPy_npc_SearchAreaByName__FP10fopAc_ac_csfP4cXyz */
void daPy_npc_SearchAreaByName(fopAc_ac_c*, short, float, cXyz*) {
    /* Nonmatching */
}

