//
// Generated by dtk
// Translation Unit: d_a_npc_de1.cpp
//

#include "d_a_npc_de1.h"
#include "dolphin/types.h"

/* 000000EC-00000144       .text __ct__15daNpc_De1_HIO_cFv */
daNpc_De1_HIO_c::daNpc_De1_HIO_c() {
    /* Nonmatching */
}

/* 00000144-000001BC       .text searchActor_leafLift__FPvPv */
void searchActor_leafLift(void*, void*) {
    /* Nonmatching */
}

/* 000001BC-0000033C       .text createInit__11daNpc_De1_cFv */
void daNpc_De1_c::createInit() {
    /* Nonmatching */
}

/* 0000033C-00000550       .text setMtx__11daNpc_De1_cFv */
void daNpc_De1_c::setMtx() {
    /* Nonmatching */
}

/* 00000550-00000658       .text anmResID__11daNpc_De1_cFiPiPi */
void daNpc_De1_c::anmResID(int, int*, int*) {
    /* Nonmatching */
}

/* 00000658-00000744       .text setAnm_anm__11daNpc_De1_cFPQ211daNpc_De1_c9anm_prm_c */
void daNpc_De1_c::setAnm_anm(daNpc_De1_c::anm_prm_c*) {
    /* Nonmatching */
}

/* 00000744-00000774       .text setAnm_NUM__11daNpc_De1_cFi */
void daNpc_De1_c::setAnm_NUM(int) {
    /* Nonmatching */
}

/* 00000774-000007AC       .text setAnm__11daNpc_De1_cFv */
void daNpc_De1_c::setAnm() {
    /* Nonmatching */
}

/* 000007AC-000007B8       .text chngAnmTag__11daNpc_De1_cFv */
void daNpc_De1_c::chngAnmTag() {
    /* Nonmatching */
}

/* 000007B8-000007C4       .text ctrlAnmTag__11daNpc_De1_cFv */
void daNpc_De1_c::ctrlAnmTag() {
    /* Nonmatching */
}

/* 000007C4-00000800       .text chngAnmAtr__11daNpc_De1_cFUc */
void daNpc_De1_c::chngAnmAtr(unsigned char) {
    /* Nonmatching */
}

/* 00000800-00000848       .text ctrlAnmAtr__11daNpc_De1_cFv */
void daNpc_De1_c::ctrlAnmAtr() {
    /* Nonmatching */
}

/* 00000848-0000087C       .text setAnm_ATR__11daNpc_De1_cFv */
void daNpc_De1_c::setAnm_ATR() {
    /* Nonmatching */
}

/* 0000087C-00000938       .text anmAtr__11daNpc_De1_cFUs */
void daNpc_De1_c::anmAtr(unsigned short) {
    /* Nonmatching */
}

/* 00000938-000009B4       .text setStt__11daNpc_De1_cFSc */
void daNpc_De1_c::setStt(signed char) {
    /* Nonmatching */
}

/* 000009B4-00000C98       .text next_msgStatus__11daNpc_De1_cFPUl */
void daNpc_De1_c::next_msgStatus(unsigned long*) {
    /* Nonmatching */
}

/* 00000C98-00000D6C       .text getMsg__11daNpc_De1_cFv */
void daNpc_De1_c::getMsg() {
    /* Nonmatching */
}

/* 00000D6C-00000E14       .text eventOrder__11daNpc_De1_cFv */
void daNpc_De1_c::eventOrder() {
    /* Nonmatching */
}

/* 00000E14-00000F8C       .text checkOrder__11daNpc_De1_cFv */
void daNpc_De1_c::checkOrder() {
    /* Nonmatching */
}

/* 00000F8C-000010B8       .text chkAttention__11daNpc_De1_cFv */
void daNpc_De1_c::chkAttention() {
    /* Nonmatching */
}

/* 000010B8-00001194       .text setAttention__11daNpc_De1_cFv */
void daNpc_De1_c::setAttention() {
    /* Nonmatching */
}

/* 00001194-000011C8       .text searchByID__11daNpc_De1_cFUi */
void daNpc_De1_c::searchByID(unsigned int) {
    /* Nonmatching */
}

/* 000011C8-0000124C       .text setDemoStartCenter__11daNpc_De1_cFv */
void daNpc_De1_c::setDemoStartCenter() {
    /* Nonmatching */
}

/* 0000124C-00001300       .text partner_srch__11daNpc_De1_cFv */
void daNpc_De1_c::partner_srch() {
    /* Nonmatching */
}

/* 00001300-000013F0       .text ccCreate__11daNpc_De1_cFv */
void daNpc_De1_c::ccCreate() {
    /* Nonmatching */
}

/* 000013F0-000014A0       .text cc_set__11daNpc_De1_cFv */
void daNpc_De1_c::cc_set() {
    /* Nonmatching */
}

/* 000014A0-00001524       .text set_pa_happa__11daNpc_De1_cFv */
void daNpc_De1_c::set_pa_happa() {
    /* Nonmatching */
}

/* 00001524-00001550       .text del_pa_happa__11daNpc_De1_cFv */
void daNpc_De1_c::del_pa_happa() {
    /* Nonmatching */
}

/* 00001550-000015CC       .text followPa_happa__11daNpc_De1_cFv */
void daNpc_De1_c::followPa_happa() {
    /* Nonmatching */
}

/* 000015CC-0000165C       .text decideType__11daNpc_De1_cFi */
void daNpc_De1_c::decideType(int) {
    /* Nonmatching */
}

/* 0000165C-00001858       .text event_actionInit__11daNpc_De1_cFi */
void daNpc_De1_c::event_actionInit(int) {
    /* Nonmatching */
}

/* 00001858-00001938       .text event_action__11daNpc_De1_cFv */
void daNpc_De1_c::event_action() {
    /* Nonmatching */
}

/* 00001938-00001A40       .text privateCut__11daNpc_De1_cFv */
void daNpc_De1_c::privateCut() {
    /* Nonmatching */
}

/* 00001A40-00001A60       .text endEvent__11daNpc_De1_cFv */
void daNpc_De1_c::endEvent() {
    /* Nonmatching */
}

/* 00001A60-00001B90       .text event_proc__11daNpc_De1_cFv */
void daNpc_De1_c::event_proc() {
    /* Nonmatching */
}

/* 00001B90-00001C3C       .text set_action__11daNpc_De1_cFM11daNpc_De1_cFPCvPvPv_iPv */
void daNpc_De1_c::set_action(int (daNpc_De1_c::*)(void*), void*) {
    /* Nonmatching */
}

/* 00001C3C-00001C94       .text wait01__11daNpc_De1_cFv */
void daNpc_De1_c::wait01() {
    /* Nonmatching */
}

/* 00001C94-00001D38       .text wait02__11daNpc_De1_cFv */
void daNpc_De1_c::wait02() {
    /* Nonmatching */
}

/* 00001D38-00001D8C       .text wait03__11daNpc_De1_cFv */
void daNpc_De1_c::wait03() {
    /* Nonmatching */
}

/* 00001D8C-00001EA0       .text wait04__11daNpc_De1_cFv */
void daNpc_De1_c::wait04() {
    /* Nonmatching */
}

/* 00001EA0-00001F38       .text wait05__11daNpc_De1_cFv */
void daNpc_De1_c::wait05() {
    /* Nonmatching */
}

/* 00001F38-00001F90       .text talk01__11daNpc_De1_cFv */
void daNpc_De1_c::talk01() {
    /* Nonmatching */
}

/* 00001F90-00002020       .text talk02__11daNpc_De1_cFv */
void daNpc_De1_c::talk02() {
    /* Nonmatching */
}

/* 00002020-000020C0       .text wait_action1__11daNpc_De1_cFPv */
void daNpc_De1_c::wait_action1(void*) {
    /* Nonmatching */
}

/* 000020C0-000021AC       .text wait_action2__11daNpc_De1_cFPv */
void daNpc_De1_c::wait_action2(void*) {
    /* Nonmatching */
}

/* 000021AC-00002248       .text demo__11daNpc_De1_cFv */
void daNpc_De1_c::demo() {
    /* Nonmatching */
}

/* 00002248-00002358       .text _draw__11daNpc_De1_cFv */
void daNpc_De1_c::_draw() {
    /* Nonmatching */
}

/* 00002358-00002454       .text _execute__11daNpc_De1_cFv */
void daNpc_De1_c::_execute() {
    /* Nonmatching */
}

/* 00002454-00002500       .text _delete__11daNpc_De1_cFv */
void daNpc_De1_c::_delete() {
    /* Nonmatching */
}

/* 00002500-00002520       .text CheckCreateHeap__FP10fopAc_ac_c */
void CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00002520-000027A4       .text _create__11daNpc_De1_cFv */
void daNpc_De1_c::_create() {
    /* Nonmatching */
}

/* 000027A4-00002870       .text __dt__8dCcD_CylFv */
dCcD_Cyl::~dCcD_Cyl() {
    /* Nonmatching */
}

/* 00002870-000028B8       .text __dt__8cM3dGCylFv */
cM3dGCyl::~cM3dGCyl() {
    /* Nonmatching */
}

/* 000028B8-00002914       .text __dt__14cCcD_ShapeAttrFv */
cCcD_ShapeAttr::~cCcD_ShapeAttr() {
    /* Nonmatching */
}

/* 00002914-0000295C       .text __dt__8cM3dGAabFv */
cM3dGAab::~cM3dGAab() {
    /* Nonmatching */
}

/* 0000295C-000029B8       .text __dt__10dCcD_GSttsFv */
dCcD_GStts::~dCcD_GStts() {
    /* Nonmatching */
}

/* 000029B8-00002A40       .text __dt__12dBgS_AcchCirFv */
dBgS_AcchCir::~dBgS_AcchCir() {
    /* Nonmatching */
}

/* 00002A40-00002AB0       .text __dt__12dBgS_ObjAcchFv */
dBgS_ObjAcch::~dBgS_ObjAcch() {
    /* Nonmatching */
}

/* 00002AB0-00002E04       .text CreateHeap__11daNpc_De1_cFv */
void daNpc_De1_c::CreateHeap() {
    /* Nonmatching */
}

/* 00002E04-00002E24       .text daNpc_De1_Create__FP10fopAc_ac_c */
void daNpc_De1_Create(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00002E24-00002E44       .text daNpc_De1_Delete__FP11daNpc_De1_c */
void daNpc_De1_Delete(daNpc_De1_c*) {
    /* Nonmatching */
}

/* 00002E44-00002E64       .text daNpc_De1_Execute__FP11daNpc_De1_c */
void daNpc_De1_Execute(daNpc_De1_c*) {
    /* Nonmatching */
}

/* 00002E64-00002E84       .text daNpc_De1_Draw__FP11daNpc_De1_c */
void daNpc_De1_Draw(daNpc_De1_c*) {
    /* Nonmatching */
}

/* 00002E84-00002E8C       .text daNpc_De1_IsDelete__FP11daNpc_De1_c */
void daNpc_De1_IsDelete(daNpc_De1_c*) {
    /* Nonmatching */
}

/* 00002E8C-00002ED4       .text __dt__15daNpc_De1_HIO_cFv */
daNpc_De1_HIO_c::~daNpc_De1_HIO_c() {
    /* Nonmatching */
}

/* 00002ED4-00002EF0       .text cLib_calcTimer<s>__FPs */
void cLib_calcTimer<short>(short*) {
    /* Nonmatching */
}

/* 00002F2C-00002F34       .text @32@__dt__12dBgS_ObjAcchFv */
void @32@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 00002F34-00002F3C       .text @20@__dt__12dBgS_ObjAcchFv */
void @20@__dt__12dBgS_ObjAcchFv {
    /* Nonmatching */
}

/* 00002F3C-00002F44       .text @280@__dt__8dCcD_CylFv */
void @280@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 00002F44-00002F4C       .text @248@__dt__8dCcD_CylFv */
void @248@__dt__8dCcD_CylFv {
    /* Nonmatching */
}

/* 00002F4C-00002F54       .text @196@__dt__10dBgWDeformFv */
void @196@__dt__10dBgWDeformFv {
    /* Nonmatching */
}

/* 00002F54-00002F58       .text MatrixCrrPos__6dBgWSvFR13cBgS_PolyInfoPvbP4cXyzP5csXyzP5csXyz */
void dBgWSv::MatrixCrrPos(cBgS_PolyInfo&, void*, bool, cXyz*, csXyz*, csXyz*) {
    /* Nonmatching */
}

/* 00002F58-00002FFC       .text __dt__10dBgWDeformFv */
dBgWDeform::~dBgWDeform() {
    /* Nonmatching */
}

/* 00002FFC-00003044       .text __dt__13cBgS_PolyInfoFv */
cBgS_PolyInfo::~cBgS_PolyInfo() {
    /* Nonmatching */
}

/* 00003044-0000308C       .text __dt__8cM2dGCirFv */
cM2dGCir::~cM2dGCir() {
    /* Nonmatching */
}

/* 0000308C-000030E8       .text __dt__8cM3dGCirFv */
cM3dGCir::~cM3dGCir() {
    /* Nonmatching */
}

/* 000030E8-00003130       .text __dt__10cCcD_GSttsFv */
cCcD_GStts::~cCcD_GStts() {
    /* Nonmatching */
}

/* 00003130-00003134       .text draw__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::draw(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00003134-00003138       .text executeAfter__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::executeAfter(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00003138-0000313C       .text execute__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::execute(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 0000313C-00003140       .text init__34JPACallBackBase<P14JPABaseEmitter>FP14JPABaseEmitter */
void JPACallBackBase<JPABaseEmitter*>::init(JPABaseEmitter*) {
    /* Nonmatching */
}

/* 00003140-00003188       .text __dt__34JPACallBackBase<P14JPABaseEmitter>Fv */
JPACallBackBase<JPABaseEmitter*>::~JPACallBackBase() {
    /* Nonmatching */
}

/* 00003188-000031E4       .text __dt__18dPa_levelEcallBackFv */
dPa_levelEcallBack::~dPa_levelEcallBack() {
    /* Nonmatching */
}

/* 000031E4-000031F4       .text GetShapeAttr__8dCcD_CylFv */
void dCcD_Cyl::GetShapeAttr() {
    /* Nonmatching */
}

/* 000031F4-000031FC       .text GetCoCP__12cCcD_CylAttrFv */
void cCcD_CylAttr::GetCoCP() {
    /* Nonmatching */
}

/* 000031FC-00003204       .text GetCoCP__12cCcD_CylAttrCFv */
void cCcD_CylAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 00003204-0000320C       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_AabAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_AabAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 0000320C-00003214       .text CrossAtTg__12cCcD_CylAttrCFRC12cCcD_PntAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_PntAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 00003214-0000324C       .text CrossAtTg__12cCcD_CylAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_CylAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 0000324C-00003254       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_AabAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_AabAttr&, float*) const {
    /* Nonmatching */
}

/* 00003254-0000325C       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_TriAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_TriAttr&, float*) const {
    /* Nonmatching */
}

/* 0000325C-00003264       .text CrossCo__12cCcD_CylAttrCFRC12cCcD_PntAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_PntAttr&, float*) const {
    /* Nonmatching */
}

/* 00003264-0000329C       .text CrossCo__12cCcD_CylAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_CylAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 0000329C-000032A0       .text GetGObjInf__12cCcD_GObjInfCFv */
void cCcD_GObjInf::GetGObjInf() const {
    /* Nonmatching */
}

/* 000032A0-000032A8       .text GetShapeAttr__8cCcD_ObjCFv */
void cCcD_Obj::GetShapeAttr() const {
    /* Nonmatching */
}

/* 000032A8-000032B0       .text CrossAtTg__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrP4cXyz */
void cCcD_ShapeAttr::CrossAtTg(const cCcD_ShapeAttr&, cXyz*) const {
    /* Nonmatching */
}

/* 000032B0-000032B8       .text CrossCo__14cCcD_ShapeAttrCFRC14cCcD_ShapeAttrPf */
void cCcD_ShapeAttr::CrossCo(const cCcD_ShapeAttr&, float*) const {
    /* Nonmatching */
}

/* 000032B8-000032C4       .text GetCoCP__14cCcD_ShapeAttrFv */
void cCcD_ShapeAttr::GetCoCP() {
    /* Nonmatching */
}

/* 000032C4-000032D0       .text GetCoCP__14cCcD_ShapeAttrCFv */
void cCcD_ShapeAttr::GetCoCP() const {
    /* Nonmatching */
}

/* 000032D0-000032D8       .text next_msgStatus__12fopNpc_npc_cFPUl */
void fopNpc_npc_c::next_msgStatus(unsigned long*) {
    /* Nonmatching */
}

/* 000032D8-000032E0       .text getMsg__12fopNpc_npc_cFv */
void fopNpc_npc_c::getMsg() {
    /* Nonmatching */
}

/* 000032E0-000032E4       .text anmAtr__12fopNpc_npc_cFUs */
void fopNpc_npc_c::anmAtr(unsigned short) {
    /* Nonmatching */
}

