//
// Generated by dtk
// Translation Unit: d_a_mtoge.cpp
//

#include "d/actor/d_a_mtoge.h"
#include "d/d_procname.h"

/* 00000078-00000084       .text getSwbit__9daMtoge_cFv */
void daMtoge_c::getSwbit() {
    /* Nonmatching */
}

/* 00000084-000000A4       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 000000A4-000001E8       .text CreateHeap__9daMtoge_cFv */
void daMtoge_c::CreateHeap() {
    /* Nonmatching */
}

/* 000001E8-00000254       .text calcMtx__9daMtoge_cFv */
void daMtoge_c::calcMtx() {
    /* Nonmatching */
}

/* 00000254-00000384       .text CreateInit__9daMtoge_cFv */
void daMtoge_c::CreateInit() {
    /* Nonmatching */
}

/* 00000384-0000041C       .text create__9daMtoge_cFv */
s32 daMtoge_c::create() {
    /* Nonmatching */
}

/* 0000041C-00000424       .text daMtoge_actionWait__FP9daMtoge_c */
void daMtoge_actionWait(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000424-000004D4       .text daMtoge_actionHind__FP9daMtoge_c */
void daMtoge_actionHind(daMtoge_c*) {
    /* Nonmatching */
}

/* 000004D4-00000550       .text daMtoge_actionUp__FP9daMtoge_c */
void daMtoge_actionUp(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000550-00000600       .text daMtoge_actionArrival__FP9daMtoge_c */
void daMtoge_actionArrival(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000600-0000067C       .text daMtoge_actionDown__FP9daMtoge_c */
void daMtoge_actionDown(daMtoge_c*) {
    /* Nonmatching */
}

/* 0000067C-000006DC       .text daMtoge_Draw__FP9daMtoge_c */
static BOOL daMtoge_Draw(daMtoge_c*) {
    /* Nonmatching */
}

/* 000006DC-00000718       .text daMtoge_Execute__FP9daMtoge_c */
static BOOL daMtoge_Execute(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000718-00000720       .text daMtoge_IsDelete__FP9daMtoge_c */
static BOOL daMtoge_IsDelete(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000720-00000790       .text daMtoge_Delete__FP9daMtoge_c */
static BOOL daMtoge_Delete(daMtoge_c*) {
    /* Nonmatching */
}

/* 00000790-000007B0       .text daMtoge_Create__FP10fopAc_ac_c */
static s32 daMtoge_Create(fopAc_ac_c*) {
    /* Nonmatching */
}


static actor_method_class l_daMtoge_Method = {
    (process_method_func)daMtoge_Create,
    (process_method_func)daMtoge_Delete,
    (process_method_func)daMtoge_Execute,
    (process_method_func)daMtoge_IsDelete,
    (process_method_func)daMtoge_Draw,
};

actor_process_profile_definition g_profile_MTOGE = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 0x0007,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_MTOGE,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daMtoge_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ 0x0134,
    /* Actor SubMtd */ &l_daMtoge_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* CullType     */ fopAc_CULLBOX_6_e,
};
