/**
 * d_a_player_pushpull.inc
 *
 * Code relating to pushing and pulling other actors.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
 */

#include "d/actor/d_a_player_main.h"

/* 801514B0-80151644       .text setPushPullKeepData__9daPy_lk_cFQ24dBgW13PushPullLabel */
void daPy_lk_c::setPushPullKeepData(dBgW::PushPullLabel) {
    /* Nonmatching */
}

/* 80151644-801517C0       .text procPushPullWait_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procPushPullWait_init(int) {
    /* Nonmatching */
}

/* 801517C0-8015198C       .text procPushPullWait__9daPy_lk_cFv */
BOOL daPy_lk_c::procPushPullWait() {
    /* Nonmatching */
}

/* 8015198C-80151A1C       .text procPushMove_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procPushMove_init() {
    /* Nonmatching */
}

/* 80151A1C-80151B38       .text procPushMove__9daPy_lk_cFv */
BOOL daPy_lk_c::procPushMove() {
    /* Nonmatching */
}

/* 80151B38-80151BC8       .text procPullMove_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procPullMove_init() {
    /* Nonmatching */
}

/* 80151BC8-80151E40       .text procPullMove__9daPy_lk_cFv */
BOOL daPy_lk_c::procPullMove() {
    /* Nonmatching */
}
