//
// Generated by dtk
// Translation Unit: d_a_sk.cpp
//

#include "d/actor/d_a_sk.h"
#include "m_Do/m_Do_ext.h"
#include "d/d_procname.h"
#include "d/d_priority.h"

/* 00000078-00000240       .text nodeCallBack__FP7J3DNodei */
static BOOL nodeCallBack(J3DNode*, int) {
    /* Nonmatching */
}

/* 0000027C-000002EC       .text daSk_Draw__FP8sk_class */
static BOOL daSk_Draw(sk_class*) {
    /* Nonmatching */
}

/* 000002EC-00000498       .text dousa_move__FP8sk_class */
void dousa_move(sk_class*) {
    /* Nonmatching */
}

/* 00000498-00000758       .text body_atari_check__FP8sk_class */
void body_atari_check(sk_class*) {
    /* Nonmatching */
}

/* 00000758-000008D4       .text daSk_Execute__FP8sk_class */
static BOOL daSk_Execute(sk_class*) {
    /* Nonmatching */
}

/* 000008D4-000008DC       .text daSk_IsDelete__FP8sk_class */
static BOOL daSk_IsDelete(sk_class*) {
    /* Nonmatching */
}

/* 000008DC-0000090C       .text daSk_Delete__FP8sk_class */
static BOOL daSk_Delete(sk_class*) {
    /* Nonmatching */
}

/* 0000090C-00000A6C       .text useHeapInit__FP10fopAc_ac_c */
static BOOL useHeapInit(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00000A6C-00000E30       .text daSk_Create__FP10fopAc_ac_c */
static cPhs_State daSk_Create(fopAc_ac_c*) {
    /* Nonmatching */
}

static actor_method_class l_daSk_Method = {
    (process_method_func)daSk_Create,
    (process_method_func)daSk_Delete,
    (process_method_func)daSk_Execute,
    (process_method_func)daSk_IsDelete,
    (process_method_func)daSk_Draw,
};

actor_process_profile_definition g_profile_SK = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 0x0003,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_SK,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(sk_class),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ PRIO_SK,
    /* Actor SubMtd */ &l_daSk_Method,
    /* Status       */ fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* CullType     */ fopAc_CULLBOX_CUSTOM_e,
};
