/**
 * d_a_player_vomit.inc
 *
 * Code relating to being launched in the air (like from a Boko Bulb).
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is not known, but a best guess was taken 
 * based on the original names of the functions it contains.
*/

#include "d/actor/d_a_player_main.h"

/* 8014F8A0-8014F994       .text checkJumpFlower__9daPy_lk_cFv */
void daPy_lk_c::checkJumpFlower() {
    /* Nonmatching */
}

/* 8014F994-8014FA88       .text procVomitReady_init__9daPy_lk_cFsf */
BOOL daPy_lk_c::procVomitReady_init(s16, f32) {
    /* Nonmatching */
}

/* 8014FA88-8014FB64       .text procVomitReady__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitReady() {
    /* Nonmatching */
}

/* 8014FB64-8014FC20       .text procVomitWait_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitWait_init() {
    /* Nonmatching */
}

/* 8014FC20-8014FD8C       .text procVomitWait__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitWait() {
    /* Nonmatching */
}

/* 8014FD8C-8014FF0C       .text procVomitJump_init__9daPy_lk_cFi */
BOOL daPy_lk_c::procVomitJump_init(int) {
    /* Nonmatching */
}

/* 8014FF0C-801500E4       .text procVomitJump__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitJump() {
    /* Nonmatching */
}

/* 801500E4-80150164       .text procVomitLand_init__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitLand_init() {
    /* Nonmatching */
}

/* 80150164-8015023C       .text procVomitLand__9daPy_lk_cFv */
BOOL daPy_lk_c::procVomitLand() {
    /* Nonmatching */
}