//
// Generated by dtk
// Translation Unit: d_a_obj_xfuta.cpp
//

#include "d/actor/d_a_obj_xfuta.h"
#include "dolphin/types.h"

/* 00000078-0000009C       .text solidHeapCB__Q210daObjXfuta5Act_cFP10fopAc_ac_c */
void daObjXfuta::Act_c::solidHeapCB(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 0000009C-0000015C       .text create_heap__Q210daObjXfuta5Act_cFv */
void daObjXfuta::Act_c::create_heap() {
    /* Nonmatching */
}

/* 0000015C-00000214       .text _create__Q210daObjXfuta5Act_cFv */
s32 daObjXfuta::Act_c::_create() {
    /* Nonmatching */
}

/* 00000214-00000244       .text _delete__Q210daObjXfuta5Act_cFv */
BOOL daObjXfuta::Act_c::_delete() {
    /* Nonmatching */
}

/* 00000244-000002F0       .text set_mtx__Q210daObjXfuta5Act_cFv */
void daObjXfuta::Act_c::set_mtx() {
    /* Nonmatching */
}

/* 000002F0-00000338       .text _execute__Q210daObjXfuta5Act_cFv */
BOOL daObjXfuta::Act_c::_execute() {
    /* Nonmatching */
}

/* 00000338-0000040C       .text _draw__Q210daObjXfuta5Act_cFv */
BOOL daObjXfuta::Act_c::_draw() {
    /* Nonmatching */
}






/* 000004A0-00000500       .text __dt__Q210daObjXfuta5Act_cFv */
daObjXfuta::Act_c::~Act_c() {
    /* Nonmatching */
}

