/**
 * d_a_player_hammer.inc
 *
 * Code relating to the Skull Hammer item.
 * 
 * This file is not a standalone translation unit and is instead directly 
 * included into d_a_player_main.cpp.
 * 
 * The original name of this file is known because of an assert contained within
 * a function from this file.
*/

#include "d/actor/d_a_player_link.h"

/* 8015023C-80150324       .text setHammerModel__9daPy_lk_cFv */
void daPy_lk_c::setHammerModel() {
    /* Nonmatching */
}

/* 80150324-801508FC       .text setHammerQuake__9daPy_lk_cFP13cBgS_PolyInfoPC4cXyzi */
void daPy_lk_c::setHammerQuake(cBgS_PolyInfo*, const cXyz*, int) {
    /* Nonmatching */
}

/* 801508FC-80150B60       .text setHammerWaterSplash__9daPy_lk_cFv */
void daPy_lk_c::setHammerWaterSplash() {
    /* Nonmatching */
}

/* 80150B60-80150C40       .text procHammerSideSwing_init__9daPy_lk_cFv */
void daPy_lk_c::procHammerSideSwing_init() {
    /* Nonmatching */
}

/* 80150C40-80150DDC       .text procHammerSideSwing__9daPy_lk_cFv */
void daPy_lk_c::procHammerSideSwing() {
    /* Nonmatching */
}

/* 80150DDC-80150F08       .text procHammerFrontSwingReady_init__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwingReady_init() {
    /* Nonmatching */
}

/* 80150F08-80150F98       .text procHammerFrontSwingReady__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwingReady() {
    /* Nonmatching */
}

/* 80150F98-801510DC       .text procHammerFrontSwing_init__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwing_init() {
    /* Nonmatching */
}

/* 801510DC-801513D4       .text procHammerFrontSwing__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwing() {
    /* Nonmatching */
}

/* 801513D4-80151450       .text procHammerFrontSwingEnd_init__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwingEnd_init() {
    /* Nonmatching */
}

/* 80151450-801514B0       .text procHammerFrontSwingEnd__9daPy_lk_cFv */
void daPy_lk_c::procHammerFrontSwingEnd() {
    /* Nonmatching */
}
