#ifndef RES_CLCTRES_H
#define RES_CLCTRES_H

enum dRes_INDEX_CLCTRES {
    /* SCRN */
    dRes_INDEX_CLCTRES_BLO_MENU_COLLECT_01_e=0x4,
    /* TIMG */
    dRes_INDEX_CLCTRES_BTI_BATON_INPUT_FRAME2_e=0x7,
    dRes_INDEX_CLCTRES_BTI_BLACK_WHITE_2_e=0x8,
    dRes_INDEX_CLCTRES_BTI_CIRCLE2_e=0x9,
    dRes_INDEX_CLCTRES_BTI_HEART_PIECE_01_e=0xA,
    dRes_INDEX_CLCTRES_BTI_HEART_PIECE_02_e=0xB,
    dRes_INDEX_CLCTRES_BTI_HEART_PIECE_03_e=0xC,
    dRes_INDEX_CLCTRES_BTI_HEART_PIECE_BASE_e=0xD,
    dRes_INDEX_CLCTRES_BTI_MAKORE_VIOLIN_e=0xE,
    dRes_INDEX_CLCTRES_BTI_MEDORI_HARP_e=0xF,
    dRes_INDEX_CLCTRES_BTI_TITLE_COLLECT_e=0x10,
    dRes_INDEX_CLCTRES_BTI_TITLE_COLLECT_1_e=0x11,
    dRes_INDEX_CLCTRES_BTI_TITLE_COLLECT_2_e=0x12,
    dRes_INDEX_CLCTRES_BTI_TITLE_COLLECT_3_e=0x13,
    dRes_INDEX_CLCTRES_BTI_TITLE_COLLECT_4_e=0x14,
    dRes_INDEX_CLCTRES_BTI_TRIFORCE_e=0x15,
    dRes_INDEX_CLCTRES_BTI_TRIFORCE_GROW_e=0x16,
    dRes_INDEX_CLCTRES_BTI_TRI_BASE_e=0x17,
    dRes_INDEX_CLCTRES_BTI_WHITE_BLACK2_e=0x18,
    dRes_INDEX_CLCTRES_BTI_WORD_OPTION_e=0x19,
    dRes_INDEX_CLCTRES_BTI_WORD_OPTION_1_e=0x1A,
    dRes_INDEX_CLCTRES_BTI_WORD_OPTION_2_e=0x1B,
    dRes_INDEX_CLCTRES_BTI_WORD_OPTION_3_e=0x1C,
    dRes_INDEX_CLCTRES_BTI_WORD_OPTION_4_e=0x1D,
    dRes_INDEX_CLCTRES_BTI_WORD_SAVE_e=0x1E,
    dRes_INDEX_CLCTRES_BTI_WORD_SAVE_1_e=0x1F,
    dRes_INDEX_CLCTRES_BTI_WORD_SAVE_2_e=0x20,
    dRes_INDEX_CLCTRES_BTI_WORD_SAVE_3_e=0x21,
    dRes_INDEX_CLCTRES_BTI_WORD_SAVE_4_e=0x22,
};

enum dRes_ID_CLCTRES {
    /* SCRN */
    dRes_ID_CLCTRES_BLO_MENU_COLLECT_01_e=0x4,
    /* TIMG */
    dRes_ID_CLCTRES_BTI_BATON_INPUT_FRAME2_e=0x7,
    dRes_ID_CLCTRES_BTI_BLACK_WHITE_2_e=0x8,
    dRes_ID_CLCTRES_BTI_CIRCLE2_e=0x9,
    dRes_ID_CLCTRES_BTI_HEART_PIECE_01_e=0xA,
    dRes_ID_CLCTRES_BTI_HEART_PIECE_02_e=0xB,
    dRes_ID_CLCTRES_BTI_HEART_PIECE_03_e=0xC,
    dRes_ID_CLCTRES_BTI_HEART_PIECE_BASE_e=0xD,
    dRes_ID_CLCTRES_BTI_MAKORE_VIOLIN_e=0xE,
    dRes_ID_CLCTRES_BTI_MEDORI_HARP_e=0xF,
    dRes_ID_CLCTRES_BTI_TITLE_COLLECT_e=0x10,
    dRes_ID_CLCTRES_BTI_TITLE_COLLECT_1_e=0x11,
    dRes_ID_CLCTRES_BTI_TITLE_COLLECT_2_e=0x12,
    dRes_ID_CLCTRES_BTI_TITLE_COLLECT_3_e=0x13,
    dRes_ID_CLCTRES_BTI_TITLE_COLLECT_4_e=0x14,
    dRes_ID_CLCTRES_BTI_TRIFORCE_e=0x15,
    dRes_ID_CLCTRES_BTI_TRIFORCE_GROW_e=0x16,
    dRes_ID_CLCTRES_BTI_TRI_BASE_e=0x17,
    dRes_ID_CLCTRES_BTI_WHITE_BLACK2_e=0x18,
    dRes_ID_CLCTRES_BTI_WORD_OPTION_e=0x19,
    dRes_ID_CLCTRES_BTI_WORD_OPTION_1_e=0x1A,
    dRes_ID_CLCTRES_BTI_WORD_OPTION_2_e=0x1B,
    dRes_ID_CLCTRES_BTI_WORD_OPTION_3_e=0x1C,
    dRes_ID_CLCTRES_BTI_WORD_OPTION_4_e=0x1D,
    dRes_ID_CLCTRES_BTI_WORD_SAVE_e=0x1E,
    dRes_ID_CLCTRES_BTI_WORD_SAVE_1_e=0x1F,
    dRes_ID_CLCTRES_BTI_WORD_SAVE_2_e=0x20,
    dRes_ID_CLCTRES_BTI_WORD_SAVE_3_e=0x21,
    dRes_ID_CLCTRES_BTI_WORD_SAVE_4_e=0x22,
};

#endif /* !RES_CLCTRES_H */