#ifndef RES_SAVERES_H
#define RES_SAVERES_H

enum dRes_INDEX_SAVERES {
    /* SCRN */
    dRes_INDEX_SAVERES_BLO_MENU_SAVE_e=0x4,
    /* TIMG */
    dRes_INDEX_SAVERES_BTI_TITLE_SAVE_e=0x7,
    dRes_INDEX_SAVERES_BTI_TITLE_SAVE_FR_e=0x8,
    dRes_INDEX_SAVERES_BTI_TITLE_SAVE_GM_e=0x9,
    dRes_INDEX_SAVERES_BTI_TITLE_SAVE_IT_e=0xA,
    dRes_INDEX_SAVERES_BTI_TITLE_SAVE_SP_e=0xB,
};

enum dRes_ID_SAVERES {
    /* SCRN */
    dRes_ID_SAVERES_BLO_MENU_SAVE_e=0x4,
    /* TIMG */
    dRes_ID_SAVERES_BTI_TITLE_SAVE_e=0x7,
    dRes_ID_SAVERES_BTI_TITLE_SAVE_FR_e=0x8,
    dRes_ID_SAVERES_BTI_TITLE_SAVE_GM_e=0x9,
    dRes_ID_SAVERES_BTI_TITLE_SAVE_IT_e=0xA,
    dRes_ID_SAVERES_BTI_TITLE_SAVE_SP_e=0xB,
};

#endif /* !RES_SAVERES_H */