#ifndef RES_WINDRES_H
#define RES_WINDRES_H

enum dRes_INDEX_WINDRES {
    /* SCRN */
    dRes_INDEX_WINDRES_BLO_OPERATE_WIND_e=0x4,
    dRes_INDEX_WINDRES_BLO_OPERATE_WIND_MASK_e=0x5,
    /* TIMG */
    dRes_INDEX_WINDRES_BTI_EAST2_e=0x8,
    dRes_INDEX_WINDRES_BTI_RING_00_e=0x9,
    dRes_INDEX_WINDRES_BTI_SHIPFONT_E_BIG_e=0xA,
    dRes_INDEX_WINDRES_BTI_SHIPFONT_N_BIG_e=0xB,
    dRes_INDEX_WINDRES_BTI_SHIPFONT_O_BIG_e=0xC,
    dRes_INDEX_WINDRES_BTI_SHIPFONT_S_BIG_e=0xD,
    dRes_INDEX_WINDRES_BTI_SHIPFONT_W_BIG_e=0xE,
    dRes_INDEX_WINDRES_BTI_SOUTH2_e=0xF,
    dRes_INDEX_WINDRES_BTI_WEST2_e=0x10,
    dRes_INDEX_WINDRES_BTI_WIND_YAZIRUSHI2_e=0x11,
    dRes_INDEX_WINDRES_BTI_WIND_YAZIRUSHI_0_e=0x12,
    dRes_INDEX_WINDRES_BTI_YAZIRUSHI03_e=0x13,
};

enum dRes_ID_WINDRES {
    /* SCRN */
    dRes_ID_WINDRES_BLO_OPERATE_WIND_e=0x4,
    dRes_ID_WINDRES_BLO_OPERATE_WIND_MASK_e=0x5,
    /* TIMG */
    dRes_ID_WINDRES_BTI_EAST2_e=0x8,
    dRes_ID_WINDRES_BTI_RING_00_e=0x9,
    dRes_ID_WINDRES_BTI_SHIPFONT_E_BIG_e=0xA,
    dRes_ID_WINDRES_BTI_SHIPFONT_N_BIG_e=0xB,
    dRes_ID_WINDRES_BTI_SHIPFONT_O_BIG_e=0xC,
    dRes_ID_WINDRES_BTI_SHIPFONT_S_BIG_e=0xD,
    dRes_ID_WINDRES_BTI_SHIPFONT_W_BIG_e=0xE,
    dRes_ID_WINDRES_BTI_SOUTH2_e=0xF,
    dRes_ID_WINDRES_BTI_WEST2_e=0x10,
    dRes_ID_WINDRES_BTI_WIND_YAZIRUSHI2_e=0x11,
    dRes_ID_WINDRES_BTI_WIND_YAZIRUSHI_0_e=0x12,
    dRes_ID_WINDRES_BTI_YAZIRUSHI03_e=0x13,
};

#endif /* !RES_WINDRES_H */