//
// Generated by dtk
// Translation Unit: control.cpp
//

#include "control.h"
#include "dolphin/types.h"


/* 802797A0-80279800       .text __dt__Q217JStudio_JParticle13TCreateObjectFv */
JStudio_JParticle::TCreateObject::~TCreateObject() {
    /* Nonmatching */
}

/* 80279800-80279878       .text create__Q217JStudio_JParticle13TCreateObjectFPPQ27JStudio7TObjectRCQ47JStudio3stb4data20TParse_TBlock_object */
void JStudio_JParticle::TCreateObject::create(JStudio::TObject**, const JStudio::stb::data::TParse_TBlock_object&) {
    /* Nonmatching */
}

